import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B44 Codex → Blender Worker 实证链｜Blender Film Studio',
  description: '保存的 Codex 场景提案经冻结 adapter、SceneSpec 与 immutable BuildPlan 进入真实 Blender 5.2 Linux/amd64 worker；四次净构建复现，拒绝样本零容器。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/codex-to-blender-worker-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const runs = [
  ['TABLETOP-A1', '10,423 ms', '6a71287a…5e82e', '9c4f9cc2…bd1f0'],
  ['TABLETOP-A2', '10,228 ms', '6a71287a…5e82e', 'fd3bf86f…aaec6'],
  ['INTERIOR-A1', '10,291 ms', '56d32ed8…6d954', 'c73c2065…529cf'],
  ['INTERIOR-A2', '10,318 ms', '56d32ed8…6d954', '8bbe047f…86e12'],
] as const;

export default function CodexToBlenderWorkerPage() {
  return <main className="contact-page b44-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B44 导航"><Link href="/journal">实验日志</Link><Link href="/linux-amd64-compiler-repro-v0-1">B42 Worker</Link><a href="#chain">完整链</a><a href="#evidence">证据</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Codex → Blender B44</span></header>

    <section className="contact-hero b44-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> SUBSCRIPTION INTENT → DETERMINISTIC SCENE → REAL BLENDER</p><h1>模型只做选择。<br/><span>Blender 负责确定性执行。</span></h1><p>B43 保存的 Codex 提案没有获得路径、哈希、任意数值或代码权限。冻结 adapter 把两份通过的提案绑定到 SceneSpec 与 immutable BuildPlan，再交给真实 Blender 5.2 Linux/amd64 worker；非法请求在 Docker 启动前停止。</p></div><aside className="contact-gate b44-gate"><b>FORMAL VERDICT</b><strong>CHAIN<br/>REPRO</strong><code>4 / 4 worker builds</code><code>12 / 12 attacks</code><small>INDEPENDENT AUDIT PASS</small></aside><div className="contact-stats"><article><strong>2</strong><span>接受场景</span><small>SHOT_109 · SHOT_110</small></article><article><strong>4</strong><span>净 worker</span><small>exact launch count</small></article><article><strong>0</strong><span>拒绝样本容器</span><small>stopped pre-Docker</small></article><article><strong>5.2</strong><span>Blender LTS</span><small>Linux/amd64</small></article></div></section>

    <section className="section b44-chain-section" id="chain"><div className="section-index">00 / AUTHORITY CHAIN</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> SIX BOUNDED TRANSITIONS</p><h2>自然语言没有直接碰 Blender。<br/><span>每一步都能被哈希拒绝。</span></h2></div><p>模型输出只有枚举；技术值来自冻结 catalog 和 adapter。SceneSpec 与 BuildPlan 先固定身份，worker 只读仓库、无网络、非 root，唯一可写面是本次输出目录。</p></div><div className="b44-chain" aria-label="Codex 到 Blender 的六步执行链"><article><span>01</span><b>DIRECTOR BRIEF</b><p>自然语言意图</p><small>read only</small></article><i>→</i><article><span>02</span><b>CODEX PROPOSAL</b><p>8 个封闭字段</p><small>no path · no code</small></article><i>→</i><article><span>03</span><b>FROZEN ADAPTER</b><p>least authority</p><small>deterministic</small></article><i>→</i><article><span>04</span><b>SCENESPEC</b><p>完整技术参数</p><small>canonical hash</small></article><i>→</i><article><span>05</span><b>BUILDPLAN</b><p>资产与执行绑定</p><small>self hash</small></article><i>→</i><article><span>06</span><b>BLENDER 5.2</b><p>真实 Linux worker</p><small>manifest + .blend</small></article></div></section>

    <section className="section b44-evidence" id="evidence"><div className="section-index">01 / FOUR CLEAN BUILDS</div><div className="contact-heading"><div><p className="eyebrow"><span/> TWO SCENES × TWO REPLICATES</p><h2>结构逐字节相同。<br/><span>`.blend` 逐字节不同。</span></h2></div><p>这不是矛盾，而是两个不同证据层。canonical structure 复现说明相机、灯光、资产、材质、动画与拓扑语义一致；`.blend` 容器仍包含易变序列化信息，因此只记录、不冒充 byte identity。</p></div><ol className="b44-run-table"><li className="head"><span>RUN</span><b>WALL</b><code>STRUCTURE SHA-256</code><small>.BLEND SHA-256</small></li>{runs.map(([id,time,structure,blend])=><li key={id}><span>{id}</span><b>{time}</b><code>{structure}</code><small>{blend}</small></li>)}</ol><div className="b44-hash-pair"><article><span>SHOT_109 · 48 FRAMES</span><strong>6a71287a</strong><code>ed7c982ed6ca1889858b43eafa5012708ce5f577abd2ee872345e82e</code><b>2 / 2 STRUCTURE MATCH</b></article><article><span>SHOT_110 · 24 FRAMES</span><strong>56d32ed8</strong><code>a8813c3365852a9ab52660b81e09eb5887daed4fa41f5459f3a6d954</code><b>2 / 2 STRUCTURE MATCH</b></article></div></section>

    <section className="section b44-rejection"><div className="section-index">02 / NEGATIVE PATH</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> UNAUTHORIZED NETWORK + PYTHON</p><h2>拒绝不是第五次失败运行。<br/><span>它根本没有运行权。</span></h2></div><p>`UNAUTHORIZED-A` 要求下载 URL 并执行 Python。Codex 返回 `REJECT / UNAUTHORIZED_NETWORK_OR_CODE`；adapter 产生 0 个 SceneSpec、0 个 BuildPlan，运行器启动 0 个容器。正式操作轨迹恰好只有一次 image inspect、四次 run 与一次 cleanup check。</p></div><div className="b44-zero-flow"><article><span>MODEL DECISION</span><strong>REJECT</strong></article><i>×</i><article><span>SCENESPEC</span><strong>0</strong></article><i>×</i><article><span>BUILDPLAN</span><strong>0</strong></article><i>×</i><article className="terminal"><span>DOCKER RUN</span><strong>0</strong></article></div></section>

    <section className="section b44-contract"><div className="section-index">03 / WORKER CONTRACT</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> EXACT B42-C1 BOUNDARY</p><h2>同一 worker，<br/><span>没有为新场景放宽权限。</span></h2></div><p>镜像、Blender binary、OCIO、compiler 与隔离参数都继承已审计身份。没有 build、pull 或 download，也没有运行后残留容器。</p></div><div className="b44-contract-grid"><article><span>PLATFORM</span><b>linux/amd64</b><small>image SHA pinned</small></article><article><span>NETWORK</span><b>none</b><small>offline mode</small></article><article><span>IDENTITY</span><b>65532:65532</b><small>cap-drop ALL</small></article><article><span>ROOT FS</span><b>read-only</b><small>one writable output</small></article><article><span>LIMITS</span><b>4 CPU · 8 GiB</b><small>PID 256 · SHM 1 GiB</small></article><article><span>TIME</span><b>30 s</b><small>TERM → 5 s → KILL</small></article></div></section>

    <section className="section contact-limits" id="boundary"><div className="section-index">04 / WHAT THIS CLOSES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> COMPILE CHAIN CLOSED · PIXEL CHAIN OPEN</p><h2>我们已经能从 brief 造出可复现 `.blend`。<br/><span>下一道门是真实画面。</span></h2></div><p>B44 关闭的是两个冻结 preset 的“订阅认证 Codex 意图 → 受限 Blender 编译”链，不是任意导演语言、表演质量、电影感、最终像素、完整镜头渲染或成本上限。下一阶段必须从这些新 `.blend` 直接渲染可审计帧，再扩展到连续镜头。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-to-blender-worker-promotion-v0-1/results.json`}><span>MACHINE RESULT</span><b>4 builds · 3 decisions ↗</b></a><a href={`${repo}experiments/codex-to-blender-worker-promotion-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>all artifacts MATCH ↗</b></a><a href={`${repo}research/2026-08-26-b44-codex-to-blender-worker-promotion-result.md`}><span>RESULT NOTE</span><b>claim · non-claims ↗</b></a><a href={`${repo}specs/codex-to-blender-worker-promotion.v0.1.json`}><span>PREREGISTERED SPEC</span><b>frozen before runner ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B44 Codex → Blender Worker</b></div><p>saved proposal · deterministic adapter · real Blender 5.2</p><Link href="/journal">回到实验日志 →</Link></footer>
  </main>;
}
