import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B46 Blender 连续镜头与故障恢复｜Blender Film Studio',
  description: '四份 B44 .blend 在真实 Blender 5.2 Linux/amd64 worker 中复现 16/16 帧与 14/14 float32 时间差分；受控中断后以新容器和空目录精确恢复。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/codex-worker-sequence-v0-1/' },
};

const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const runs=[
  ['TABLETOP-A1','15,566 ms','6dcea8c9…496c','20,600 → 21,010'],
  ['TABLETOP-A2','15,374 ms','6dcea8c9…496c','20,600 → 21,010'],
  ['INTERIOR-A1','16,624 ms','334bdd26…e28c5','0 × 7'],
  ['INTERIOR-A2','16,668 ms','334bdd26…e28c5','0 × 7'],
] as const;

export default function CodexWorkerSequencePage(){return <main className="contact-page b46-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B46 导航"><Link href="/journal">实验日志</Link><Link href="/codex-worker-pixels-v0-1">B45-C1 像素</Link><a href="#sequences">连续帧</a><a href="#recovery">恢复</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Sequence B46</span></header>

  <section className="contact-hero b46-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> REAL .BLEND → ORDERED FLOAT FRAMES → TEMPORAL DELTAS</p><h1>不只是一帧。<br/><span>连续变化也完全复现。</span></h1><p>两个语义场景、四份不同字节的 `.blend`、四个真实 Blender 5.2 worker。每份渲染 8 个有序帧；独立审计重解码全部成功 EXR，确认 16/16 跨构建帧像素与 14/14 跨构建时间差分逐字节一致。</p></div><aside className="contact-gate b46-gate"><b>FORMAL VERDICT</b><strong>SEQUENCE<br/>EXACT</strong><code>16 / 16 frame pairs</code><code>14 / 14 delta pairs</code><small>RECOVERY MATCH · AUDIT PASS</small></aside><div className="contact-stats"><article><strong>40</strong><span>成功 EXR 解码</span><small>32 primary + 8 recovery</small></article><article><strong>6</strong><span>隔离容器</span><small>4 + fault + recovery</small></article><article><strong>8 spp</strong><span>冻结采样</span><small>128 × 72 · Cycles CPU</small></article><article><strong>21 / 21</strong><span>攻击通过</span><small>independent audit</small></article></div></section>

  <section className="section b46-chain-section"><div className="section-index">00 / BOUNDED SEQUENCE GATE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> FRAME IDENTITY + TEMPORAL IDENTITY</p><h2>逐帧相同还不够。<br/><span>帧与帧之间的变化也必须相同。</span></h2></div><p>每个 EXR 解码为 little-endian BGRA float32。帧哈希覆盖规范 metadata 与像素 bytes；时间哈希覆盖 `next − previous` 的 float32 差分。MP4 只用于浏览，不进入高比特判决。</p></div><div className="b46-flow"><article><span>01 · SOURCE</span><b>4 × `.BLEND`</b><small>SHA + plan + structure bound</small></article><i>→</i><article><span>02 · RENDER</span><b>8 FRAMES</b><small>strict ascending · 8 spp</small></article><i>→</i><article><span>03 · DECODE</span><b>FLOAT32</b><small>finite BGRA · 36,864 values</small></article><i>→</i><article><span>04 · DELTA</span><b>7 STEPS</b><small>next − previous · float32</small></article><i>→</i><article><span>05 · DECIDE</span><b>EXACT</b><small>frame + transition hashes</small></article></div></section>

  <section className="section b46-sequences" id="sequences"><div className="section-index">01 / REAL EIGHT-FRAME CARRIERS</div><div className="contact-heading"><div><p className="eyebrow"><span/> HUMAN NAVIGATION ONLY · LOSSY H.264</p><h2>一个真实运动镜头，<br/><span>一个严格静态对照。</span></h2></div><p>TABLETOP 的相机在 frame 21–28 线性推进，7 个时间差分都有非零分量；INTERIOR 的 frame 9–16 无动画，7 个差分全部为零。下列 MP4 为 24 fps 导航载体，不承担精确性证明。</p></div><div className="b46-video-grid"><figure><video controls loop muted playsInline poster={`${basePath}/evidence/b46/tabletop-first.png`}><source src={`${basePath}/evidence/b46/tabletop.mp4`} type="video/mp4"/></video><figcaption><span>SHOT_109 · FRAME 21–28</span><b>MOVING CAMERA</b><code>7 / 7 non-zero transitions</code></figcaption></figure><figure><video controls loop muted playsInline poster={`${basePath}/evidence/b46/interior-static.png`}><source src={`${basePath}/evidence/b46/interior.mp4`} type="video/mp4"/></video><figcaption><span>SHOT_110 · FRAME 9–16</span><b>STATIC CONTROL</b><code>7 / 7 zero transitions</code></figcaption></figure></div><div className="b46-frame-strip"><figure><Image src={`${basePath}/evidence/b46/tabletop-first.png`} width={128} height={72} unoptimized alt="TABLETOP frame 21 real Blender render"/><figcaption>FRAME 21 · 2eae7dc6…478b</figcaption></figure><span>CAMERA PUSH →</span><figure><Image src={`${basePath}/evidence/b46/tabletop-last.png`} width={128} height={72} unoptimized alt="TABLETOP frame 28 real Blender render"/><figcaption>FRAME 28 · c8e635cc…ecd7</figcaption></figure></div></section>

  <section className="section b46-evidence"><div className="section-index">02 / FOUR PRIMARY WORKERS</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> TWO SEMANTIC PAIRS · TWO TEMPORAL ROLES</p><h2>不同构建文件，<br/><span>相同有序序列。</span></h2></div><p>两个 TABLETOP 序列哈希一致，且每一步非零分量计数一致；两个 INTERIOR 序列哈希一致，所有时间差分为精确零。A/B 比较从未以 MP4 容器字节作判据。</p></div><ol className="b46-run-table"><li className="head"><span>RUN</span><b>WALL</b><code>SEQUENCE SHA-256</code><small>CHANGED COMPONENTS / TRANSITION</small></li>{runs.map(([id,time,hash,changed])=><li key={id}><span>{id}</span><b>{time}</b><code>{hash}</code><small>{changed}</small></li>)}</ol><div className="b46-pairs"><article><span>MOVING CAMERA</span><strong>8 + 7 EXACT</strong><code>frames + temporal deltas</code></article><article><span>STATIC CONTROL</span><strong>8 + 7 EXACT</strong><code>zero delta is measured, not assumed</code></article></div></section>

  <section className="section b46-recovery" id="recovery"><div className="section-index">03 / PARTIAL FAILURE RECOVERY</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> NO IN-PLACE RESUME · NO PARTIAL PROMOTION</p><h2>故障留下一个帧。<br/><span>恢复必须从新容器与空目录开始。</span></h2></div><p>第五个容器完成 frame 21 后由预注册故障点直接以 86 退出：一个 EXR/PNG、没有最终 report、不可晋级。第六个容器写入全新的空目录并重渲染 8 帧，完整帧哈希、时间差分哈希和序列哈希全部匹配 TABLETOP-A1。</p></div><div className="b46-recovery-flow"><article><span>FAULT ATTEMPT</span><strong>EXIT 86</strong><code>1 completed frame · report absent</code><small>NON-PROMOTABLE</small></article><i>×</i><article><span>BOUNDARY</span><strong>NEW</strong><code>container + empty output root</code><small>NO PARTIAL DIRECTORY REUSE</small></article><i>→</i><article><span>RECOVERY</span><strong>8 / 8</strong><code>frames + deltas + sequence exact</code><small>MATCH PRIMARY</small></article></div></section>

  <section className="section contact-limits" id="boundary"><div className="section-index">04 / WHAT THIS CLOSES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> BOUNDED SEQUENCE CLOSED · CINEMA QUALITY OPEN</p><h2>数据链能稳定生成短序列。<br/><span>电影感仍然是下一组问题。</span></h2></div><p>B46 只覆盖两段 8 帧、128×72、8-spp Cycles CPU 区间，以及一种受控进程退出。它不证明完整镜头、高采样降噪、运动模糊、4K 母版、人物表演、跨主机/GPU 复现、感知无闪烁或生产吞吐。下一道证据门应测试“生产表示与质量阶梯”：多层 EXR/AOV、运动矢量、运动模糊、采样/降噪与成本曲线。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-worker-sequence-promotion-v0-1/results.json`}><span>MACHINE RESULT</span><b>evidence hash · 6 runs ↗</b></a><a href={`${repo}experiments/codex-worker-sequence-promotion-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>40 EXR re-decodes MATCH ↗</b></a><a href={`${repo}research/2026-08-26-b46-codex-worker-sequence-promotion-result.md`}><span>RESULT NOTE</span><b>claims · non-claims ↗</b></a><a href={`${repo}research/2026-08-26-b46-codex-worker-sequence-promotion-protocol.md`}><span>PREREGISTRATION</span><b>frozen before tools ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B46 Worker Sequence</b></div><p>real `.blend` · ordered float frames · bounded recovery</p><Link href="/journal">回到实验日志 →</Link></footer>
</main>}
