import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B45-C1 Blender Worker 浮点像素晋级｜Blender Film Studio',
  description: '四份 B44 .blend 在真实 Blender 5.2 Linux/amd64 Cycles CPU worker 中完成渲染；两组解码 scene-linear float32 像素逐字节一致，失败与修正均保留。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/codex-worker-pixels-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio' : '';
const runs = [
  ['TABLETOP-A1', '10,061 ms', '9c4f9cc2…bd1f0', 'bee41c68…eb5e', 'b45f5424…7dbd'],
  ['TABLETOP-A2', '10,258 ms', 'fd3bf86f…aaec6', 'b5bbba7e…a927', 'b45f5424…7dbd'],
  ['INTERIOR-A1', '9,690 ms', 'c73c2065…529cf', 'dcfdcf74…9b00', '0dd7514f…6544b'],
  ['INTERIOR-A2', '9,693 ms', '8bbe047f…86e12', 'dcfdcf74…9b00', '0dd7514f…6544b'],
] as const;

export default function CodexWorkerPixelsPage() {
  return <main className="contact-page b45-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B45-C1 导航"><Link href="/journal">实验日志</Link><Link href="/codex-to-blender-worker-v0-1">B44 编译链</Link><a href="#frames">真实帧</a><a href="#failure">失败</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Float Pixels B45-C1</span></header>

    <section className="contact-hero b45-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> REAL .BLEND → REAL RENDER RESULT → CANONICAL FLOAT ARRAY</p><h1>文件字节不同。<br/><span>渲染像素完全相同。</span></h1><p>四份 B44 `.blend` 直接进入四个新的 Blender 5.2 Linux/amd64 worker。两个镜头各自的 A/B 构建产生完全一致的 scene-linear float32 像素；独立 audit 重新解码全部 EXR，而不是相信运行器摘要。</p></div><aside className="contact-gate b45-gate"><b>FORMAL VERDICT</b><strong>PIXEL<br/>EXACT</strong><code>4 / 4 real renders</code><code>2 / 2 exact pairs</code><small>INDEPENDENT AUDIT PASS</small></aside><div className="contact-stats"><article><strong>36,864</strong><span>float components / run</span><small>all finite · BGRA</small></article><article><strong>16 / 16</strong><span>攻击通过</span><small>14 base + 2 correction</small></article><article><strong>1 spp</strong><span>诊断采样</span><small>quality deliberately low</small></article><article><strong>9.7–10.3s</strong><span>容器耗时</span><small>Cycles CPU</small></article></div></section>

    <section className="section b45-chain-section"><div className="section-index">00 / PIXEL PROMOTION CHAIN</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> NO RECOMPILE · NO VIDEO MODEL</p><h2>B44 的场景没有被重造。<br/><span>只验证它能否抵达真实像素。</span></h2></div><p>每次运行先校验 `.blend` SHA、BuildPlan、SceneSpec、structure、shot seed 与 OCIO，再执行一次 render。相同 Render Result 保存为 EXR32 和 PNG8；host 端用冻结的 OpenCV/NumPy 解码 EXR，并哈希规范化 float bytes。</p></div><div className="b45-flow"><article><span>01</span><b>B44 `.BLEND`</b><small>different container hashes</small></article><i>→</i><article><span>02</span><b>BLENDER 5.2</b><small>Cycles CPU · 1 spp</small></article><i>→</i><article><span>03</span><b>RENDER RESULT</b><small>one operator call</small></article><i>→</i><article><span>04</span><b>EXR32 + PNG8</b><small>same render result</small></article><i>→</i><article><span>05</span><b>FLOAT32 HASH</b><small>exact pair decision</small></article></div></section>

    <section className="section b45-frames" id="frames"><div className="section-index">01 / REAL CANARY FRAMES</div><div className="contact-heading"><div><p className="eyebrow"><span/> DIAGNOSTIC EVIDENCE · NOT A BEAUTY CLAIM</p><h2>两张真实 Blender 帧。<br/><span>故意只有一个采样。</span></h2></div><p>低分辨率和高噪声是预注册的成本控制，不是渲染器质量上限。这里证明数据链与可复现性；电影感、降噪、高采样和连续运动仍需下一轮实验。</p></div><div className="b45-frame-grid"><figure><Image src={`${basePath}/evidence/b45-c1/tabletop.png`} width={128} height={72} unoptimized alt="SHOT_109 tabletop frame 24, one-sample Cycles CPU diagnostic render"/><figcaption><span>SHOT_109 · FRAME 24</span><b>TABLETOP</b><code>b45f5424…7dbd · A/B exact</code></figcaption></figure><figure><Image src={`${basePath}/evidence/b45-c1/interior.png`} width={128} height={72} unoptimized alt="SHOT_110 interior frame 12, one-sample Cycles CPU diagnostic render"/><figcaption><span>SHOT_110 · FRAME 12</span><b>INTERIOR</b><code>0dd7514f…6544b · A/B exact</code></figcaption></figure></div></section>

    <section className="section b45-evidence"><div className="section-index">02 / FOUR WORKER RUNS</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> SOURCE ≠ CONTAINER ≠ DECODED PIXELS</p><h2>三个哈希层，<br/><span>各自回答不同问题。</span></h2></div><p>TABLETOP 两份 EXR/PNG 文件 SHA 不同，但解码 float bytes 相同；INTERIOR 的容器和像素都相同。因此 promotion gate 只以可规范解码的高比特像素内容作判据。</p></div><ol className="b45-run-table"><li className="head"><span>RUN</span><b>WALL</b><code>SOURCE .BLEND</code><small>EXR CONTAINER</small><strong>FLOAT PIXELS</strong></li>{runs.map(([id,time,source,exr,pixel])=><li key={id}><span>{id}</span><b>{time}</b><code>{source}</code><small>{exr}</small><strong>{pixel}</strong></li>)}</ol><div className="b45-pairs"><article><span>TABLETOP PAIR</span><strong>PIXEL EXACT</strong><code>EXR bytes differ · PNG bytes differ</code></article><article><span>INTERIOR PAIR</span><strong>PIXEL EXACT</strong><code>EXR bytes exact · PNG bytes exact</code></article></div></section>

    <section className="section b45-failure" id="failure"><div className="section-index">03 / FAILURE RETAINED</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> B45 INVALID → C1 PREREGISTERED → PASS</p><h2>第一次没有像素。<br/><span>它没有被从历史里删掉。</span></h2></div><p>首轮四个容器都到达 `RENDER_STARTED`，随后因 `MULTI_LAYER_IMAGE` 状态不接受单层 `OPEN_EXR` 而退出；runner 又在 null report 上崩溃。失败与原始日志先提交，C1 才获准只修这两个接口问题。</p></div><div className="b45-failure-flow"><article className="invalid"><span>B45 · ATTEMPT 01</span><strong>INVALID</strong><code>0 EXR · 0 PNG · 0 report</code><small>NO PIXEL DECISION</small></article><i>→</i><article><span>C1 · FROZEN SCOPE</span><strong>2 fixes</strong><code>media_type + null totality</code><small>threshold unchanged</small></article><i>→</i><article className="passed"><span>B45-C1 · FORMAL</span><strong>PASS</strong><code>4 renders · audit MATCH</code><small>failure remains addressable</small></article></div></section>

    <section className="section contact-limits" id="boundary"><div className="section-index">04 / WHAT THIS CLOSES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> PIXEL HANDOFF CLOSED · CINEMA QUALITY OPEN</p><h2>现在链条抵达高比特像素。<br/><span>还没有抵达电影成片。</span></h2></div><p>B45-C1 关闭的是两个冻结场景的一帧 Cycles CPU 可复现性。它不证明连续镜头、时序稳定、高采样降噪、4K 母版、人物表演、GPU/Eevee、跨主机复现、任意 prompt 或生产成本。下一道门应从同一 B44 场景晋级到短连续镜头，并预先冻结时间域与恢复策略。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-worker-pixel-promotion-c1-v0-1/results.json`}><span>MACHINE RESULT</span><b>evidence hash · 4 runs ↗</b></a><a href={`${repo}experiments/codex-worker-pixel-promotion-c1-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>re-decoded outputs MATCH ↗</b></a><a href={`${repo}research/2026-08-26-b45-c1-codex-worker-pixel-promotion-result.md`}><span>RESULT NOTE</span><b>claims · non-claims ↗</b></a><a href={`${repo}experiments/codex-worker-pixel-promotion-v0-1/failure.json`}><span>FAILED ATTEMPT</span><b>raw failure retained ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B45-C1 Worker Float Pixels</b></div><p>real `.blend` · real Cycles CPU · canonical float evidence</p><Link href="/journal">回到实验日志 →</Link></footer>
  </main>;
}
