import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = { title: 'B12 资源预算｜Blender 编译 Watchdog｜Blender Film Studio', description: '为 Codex/CLI 到 Blender 5.2 的场景编译建立墙钟、RSS、日志和输出预算，并用六类反例验证终止行为。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/resource-budget-v0-1/' } };
const attacks = [
  ['N01', 'wall time', '261 ms > 250 ms', 'WALL_TIME'],
  ['N02', 'log bytes', '65,536 B > 8,192 B', 'LOG_BYTES'],
  ['N03', 'output files', '12 > 4', 'OUTPUT_FILES'],
  ['N04', 'output bytes', '262,144 B > 65,536 B', 'OUTPUT_BYTES'],
  ['N05', 'sampled RSS', '183.2 MB > 50.3 MB', 'RSS_BYTES'],
  ['N06', 'child exit', 'exit 7', 'CHILD_FAILED'],
];

export default function ResourceBudgetV01Page() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B12 导航"><Link href="/asset-security-v0-1">B11 资产</Link><Link href="/security-v0-1">B10 路径</Link><a href="#profile">预算</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Resource Budget 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B12 · RESTRICTED PROCESS WATCHDOG</p><h1>让 Blender 可被停止。<br /><span>不把 watchdog 叫沙箱。</span></h1><p>Codex/CLI 现在通过固定入口启动 Blender 5.2。墙钟、采样 RSS、日志和输出目录任一越界都会产生稳定原因、终止进程并等待退出；完整命令与预算哈希进入证据。</p></div><aside className="contact-gate"><b>CURRENT STATUS</b><strong>FORMAL B12<br />TRUE</strong><code>6 / 6 breaches classified</code><code>B01 structure unchanged</code><small>soft watchdog · not kernel quota</small></aside><div className="contact-stats"><article><strong>568 ms</strong><span>B01 受限编译</span><small>30,000 ms limit</small></article><article><strong>253.8 MB</strong><span>峰值采样 RSS</span><small>2 GiB limit</small></article><article><strong>1,109 B</strong><span>编译日志</span><small>2 MiB limit</small></article><article><strong>3</strong><span>输出文件</span><small>129,032 bytes</small></article></div></section>
    <section className="section contact-verdict" id="profile"><div className="section-index">00 / 固定预算</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> ONE PINNED COMPILE PROFILE</p><h2>预算不是提示词。<br /><span>它是启动条件。</span></h2></div><p>profile SHA-256 为 `9203aba8…eebe`。这组上限只服务于 SceneSpec → BuildPlan → `.blend` 场景编译；最终 Cycles 帧渲染必须按分辨率、采样数和帧数建立另一套 profile。</p></div><div className="contact-flow"><article><span>01</span><b>30 s · 2 GiB</b><p>wall + sampled root RSS</p></article><i>→</i><article><span>02</span><b>2 MiB LOG</b><p>4 KiB preview + full hash</p></article><i>→</i><article><span>03</span><b>32 · 128 MiB</b><p>files + output bytes</p></article></div></section>
    <section className="section contact-diagnostic"><div className="section-index">01 / 预注册反例</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> TERMINATE · THEN AWAIT</p><h2>不是只报错。<br /><span>超限进程真的退出。</span></h2></div><p>五类超预算进程均收到 SIGTERM 且被 supervisor 等待；非零退出不伪装成预算通过。所有 fixture 都是本地无害负载，只写实验 work 目录。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,observed,result]) => <li key={id}><span>{id}</span><b>{item}</b><code>{observed}</code><small>{result}</small></li>)}</ol></section>
    <section className="section contact-contract"><div className="section-index">02 / 正例与路径回归</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> REAL CLI · SAME SEMANTICS</p><h2>守卫改变执行边界。<br /><span>不改变场景结构。</span></h2></div><p>真实 `compile:restricted` CLI 返回 0，B01 仍得到结构哈希 `c699fc…b7f0b`。BuildPlan symlink、仓库外 output 和仓库外 report 三项回归均在 Blender 启动前被拒绝，外部文件没有出现。</p></div><div className="contact-plan"><span>POSITIVE CONTROL</span><code>c699fc27230d…b7f0b</code><b>CLI EXIT 0</b><b>PATH REGRESSION 3 / 3</b></div></section>
    <section className="section contact-limits" id="boundary"><div className="section-index">03 / 未关闭边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> WATCHDOG ≠ SANDBOX</p><h2>能停止一个进程，<br /><span>不等于隔离了一台机器。</span></h2></div><p>100 ms 采样会有超调；RSS 只看根子进程；GPU VRAM、网络、系统调用、解析器漏洞与子进程合计内存均未被隔离。下一层需要 OS/container worker，而不是把 B12 的措辞写大。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/resource-budget-v0-1/results.json`}><span>RESULT</span><b>6/6 + B01 指标 ↗</b></a><a href={`${repo}experiments/resource-budget-v0-1/first-run-baseline.json`}><span>BASELINE</span><b>无预算 B01 ↗</b></a><a href={`${repo}specs/restricted-compile-budget.v0.1.json`}><span>PROFILE</span><b>固定预算 v0.1 ↗</b></a><a href={`${repo}research/2026-08-26-b12-resource-budget-result.md`}><span>RESULT NOTE</span><b>结论与非结论 ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B12 Restricted Process Watchdog</b></div><p>6/6 classified · B01 unchanged · OS sandbox still open</p><Link href="/compile-receipt-v0-1">继续 B13 →</Link></footer>
  </main>;
}
