import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = {
  title: 'B23 同进程重复 Render 实验｜Blender Film Studio',
  description: '真实 Blender 72 PID / 144 EXR 实验：同一进程同一帧连续 render 仍只有 59/108 exact，20/20 攻击通过。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/eevee-repeated-render-boundary-v0-1/' },
};
const frames = [
  ['1','5/9','76','0.0008544921875'],['5','2/9','2,704','0.004638671875'],['20','5/9','96','0.00634765625'],['35','7/9','38','0.0048828125'],['38','7/9','52','0.00390625'],['47','5/9','64','0.00341796875'],['83','7/9','20','0.000732421875'],['93','5/9','60','0.004150390625'],['103','1/9','226','0.00537109375'],['110','3/9','108','0.005615234375'],['114','9/9','0','0'],['144','3/9','186','0.00439453125'],
];

export default function RepeatedRenderBoundaryPage() {
  return <main className="contact-page factorial-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B23 导航"><Link href="/journal">实验日志</Link><Link href="/eevee-thread-count-factorial-v0-1">B22</Link><a href="#gates">三道 gate</a><a href="#frames">逐帧</a><a href="#meaning">边界</a><a href="#next">下一步</a></nav><span className="edition contact-edition">Repeated Render 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B23 · SAME PID · SAME FRAME · THREE RENDERS</p><h1>Blender 没有重启。<br /><span>Float 仍会重新变化。</span></h1><p>PERSIST 进程只加载一次 `.blend`，固定同一帧，连续 render 三次；FRESH 对照 render 一次。72 个唯一 PID 共生成 144 张 scene-linear RGBA32 EXR。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>PER-RENDER<br />VARIATION</strong><code>WITHIN · 59 / 108</code><code>FRESH · 25 / 36</code><small>20 / 20 ATTACKS PASS</small></aside><div className="contact-stats"><article><strong>72/72</strong><span>唯一 PID</span><small>interleaved cells</small></article><article><strong>144</strong><span>render calls</span><small>same EXR contract</small></article><article><strong>252</strong><span>float pairs</span><small>three frozen gates</small></article><article><strong>20/20</strong><span>负向攻击</span><small>stable reasons</small></article></div></section>

    <section className="section contact-verdict" id="gates"><div className="section-index">00 / 三道零容差 gate</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> PROCESS INIT × RENDER INVOCATION</p><h2>初始化不是充分起点。<br /><span>每次 render 都可能复发。</span></h2></div><p>WITHIN_PERSIST 比较同一 PID 的 R1/R2/R3。如果这里 108/108 exact，才可能支持“只在进程初始化时变化”；实际只有 59/108。</p></div><div className="factorial-matrix"><article className="factorial-nonexact"><span>WITHIN PERSIST</span><strong>59/108</strong><b>same PID · same frame</b><small>3,630 failed pixels</small></article><article className="factorial-nonexact"><span>PERSIST CROSS</span><strong>64/108</strong><b>same ordinal · new PID</b><small>974 failed pixels</small></article><article className="factorial-nonexact"><span>FRESH CROSS</span><strong>25/36</strong><b>one render · new PID</b><small>300 failed pixels</small></article><article className="factorial-exact"><span>EXECUTION</span><strong>72/72</strong><b>unique process IDs</b><small>144 calls · 20 attacks</small></article></div><div className="diagnostic-verdict"><b>DECISION</b><code>PER_RENDER_VARIATION_SUPPORT</code><p>“per-render”是观察边界，不是内部机制。它不等于已经证明 race、Metal 调度或 Blender bug。</p></div></section>

    <section className="section contact-evidence" id="frames"><div className="section-index light">01 / WITHIN_PERSIST 逐帧</div><div className="contact-heading"><div><p className="eyebrow"><span /> NINE SAME-PID PAIRS PER SENTINEL</p><h2>有的帧完全稳定。<br /><span>有的帧在同进程内强烈分裂。</span></h2></div><p>frame 114 为 9/9 exact；frame 103 只有 1/9。frame 5 单独贡献 2,704 failed pixels。它们是描述性 stress observations，不是事后新门槛。</p></div><ol className="contact-negative-list">{frames.map(([frame,exact,failed,max],index) => <li key={frame}><span>{String(index + 1).padStart(2,'0')}</span><b>frame {frame}</b><code>{exact} exact</code><small>{failed} px · max {max}</small></li>)}</ol></section>

    <section className="section contact-limits" id="meaning"><div className="section-index">02 / 结论边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> EXACTNESS ≠ CINEMATIC QUALITY</p><h2>严格复现已被证伪。<br /><span>肉眼可见性仍未回答。</span></h2></div><p>B23 证明的是 float 数值不完全相同；它没有证明镜头质量下降，也没有测量观众能否察觉。像素身份属于 provenance，电影感属于另一套生产验收。</p></div><div className="contact-nonclaim"><b>NON-CLAIM</b><p>不能从 0.0063 scene-linear 最大误差直接推出显示 code、曝光后差异或感知显著性。必须在新的 holdout 数据上冻结并验证门槛。</p></div></section>

    <section className="section contact-diagnostic"><div className="section-index">03 / 方法结论</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> STOP OPTIMIZING THE EXACT BENCHMARK</p><h2>结构继续 exact。<br /><span>像素转向独立 holdout。</span></h2></div><p>B15-B23 已系统排除多个显式候选。继续从同一批差异里挑“最好设置”会过拟合。下一合同应把结构/资产/版本哈希保持 exact，再用新数据验证预先冻结的数值与感知门。</p></div></section>

    <section className="section contact-limits" id="next"><div className="section-index">04 / 下一研究协议</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> DERIVATION SET × HOLDOUT SET</p><h2>先定生产容差。<br /><span>再让新镜头判它生死。</span></h2></div><p>B23 只能用于挑选候选指标和 stress frame，不能同时设阈值又证明阈值。下一实验需要独立 holdout、显示域与 scene-linear 双测量，并保留人类盲评边界。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/eevee-repeated-render-boundary-v0-1/results.json`}><span>RESULT</span><b>252 float pairs ↗</b></a><a href={`${repo}experiments/eevee-repeated-render-boundary-v0-1/evidence/comparisons/WITHIN_PERSIST.comparison.json`}><span>WITHIN PID</span><b>108 comparisons ↗</b></a><a href={`${repo}research/2026-08-26-b23-eevee-repeated-render-boundary-result.md`}><span>RESULT NOTE</span><b>interpretation boundary ↗</b></a><a href={`${repo}research/2026-08-26-b23-eevee-repeated-render-boundary-protocol.md`}><span>PROTOCOL</span><b>pre-execution freeze ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B23 Repeated-render Boundary</b></div><p>Strict variation recurs without restarting Blender</p><Link href="/research-agenda">转向生产可接受性 →</Link></footer>
  </main>;
}
