import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: '真实 Blender 实验日志｜Blender Film Studio', description: '持续记录 BlenderFilmStudio 在真实 Blender 5.2 上的假设、命令、观察、失败与下一步。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/journal/' } };
const entries = [
  ['J-001','最小编译器','B01 / B02 两次净构建结构一致，.blend 字节不一致','STRUCTURE PASS · BYTE IDENTITY FALSIFIED'],
  ['J-002','角色与抓握','真实 rig、Shape Keys、接触采样和双指 IK 已进入编译器','AUTOMATION PASS · HUMAN QUALITY OPEN'],
  ['J-003','物理与回放','源刚体精确复现失败；132 帧固定轨迹回放零误差','SOURCE FALSIFIED · REPLAY PASS'],
  ['J-004','资产安全','路径首轮 6 个逃逸；隐藏 Blender 求值行为首轮被编译','B10 8/8 · B11 9/9'],
  ['J-005','资源预算','真实 Blender 超时/日志与本地输出/RSS 反例全部被分类','B12 FORMAL TRUE · 6/6'],
  ['J-006','编译收据','四次真实净构建、19 项验证、三次实现假设被证伪','B13 FORMAL TRUE · 10+2'],
  ['J-007','完整审片样片','真实 Blender 跑完 144 帧；恒真 OCIO 检查被发现后全量重跑','B14 AUTOMATION TRUE · HUMAN PENDING'],
  ['J-008','代理像素复现','同源 A/B 仅 127/144 帧解码 exact；114 像素差异','B15 FORMAL EXACT FALSIFIED'],
  ['J-009','Dither 因果隔离','只把 dither 1→0，仍有 14 帧、69 像素微差','B16 DITHER NOT SUFFICIENT'],
  ['J-010','Eevee 采样因果','1/32 samples × dither 0/1，共 8 次净运行与 1,152 帧','B17 SAMPLING CAUSAL SUPPORT · 12/12'],
  ['J-011','采样剂量响应','1/2/4/8/16/32 samples 共 12 次净运行，exact 向量 F,T,F,F,F,F','B18 NON-MONOTONIC · 13/13'],
  ['J-012','Eevee 控制清单','真实 RNA 显示 Fast GI 与 TAA reprojection 开启；两次无效候选被拒绝','EXPLORATORY · NOT CAUSAL'],
  ['J-013','GI × Reprojection','四个 on/off cells 全部非 exact；同时关闭仍 131/144','B19 NO SUFFICIENT INTERVENTION · 14/14'],
  ['J-014','进程历史隔离','39 个唯一 PID、468 帧；每帧新进程仍只有 26/36 哨兵配对 exact','B20 PROCESS ISOLATION NOT SUFFICIENT · 18/18'],
  ['J-015','Float 输出接口','后台 Render Result.pixels 为空；同一结果可保存 PNG8 与 float EXR32','EXPLORATORY · DIRECT MEMORY CLAIM REJECTED'],
  ['J-016','双输出定位','EXR32 与 PNG8 均 21/36 exact，且 36 个 pair 标签逐一相同','B21 PRE-PNG VARIATION SUPPORT · 21/21'],
  ['J-017','线程数对照冻结','T01 × T08、12 哨兵、三重复；明确 CPU threads 可能不控制 Eevee GPU','B22 PRE-REGISTERED · 72 PROCESSES'],
  ['J-018','线程数对照与下一边界','T01 19/36、T08 22/36；1 thread 不足，转向进程初始化 × repeated render','B22 THREAD COUNT NOT SUFFICIENT · 19/19'],
  ['J-019','重复 render 协议冻结','PERSIST 同 PID 三次 render × FRESH 单次；72 进程、144 EXR、三道 gate','B23 PRE-REGISTERED · NOT EXECUTED'],
  ['J-020','重复 render 结果与研究转向','同 PID 同帧仍只有 59/108 exact；严格 provenance 与感知生产门分离','B23 PER-RENDER VARIATION · 20/20'],
  ['J-021','生产容差与 holdout 冻结','288 EXR + 36 PNG derivation；24 个未见帧、72 新进程验证','B24 PRE-REGISTERED · NO THRESHOLD REVISION'],
  ['J-022','生产容差 holdout 结果','EXR 与 PNG 均 72/72；strict exact 70/72，转向 temporal playback','B24 ENVELOPE SUPPORT · 22/22'],
  ['J-023','连续序列时间残差','三次完整 144 帧；temporal 429/429，static 430/432，frame 38 超门 1 像素','B25 STATIC-ONLY FAIL · 19/19'],
  ['J-024','匿名时间稳定性审片包','三条 lossless carrier 均 144/144 RGB exact；18 个平衡 session，当前 0 response','B26 PACKAGE READY · HUMAN PENDING'],
  ['J-025','frame 38 历史隔离','HISTORY 2/12、DIRECT 3/12 超门；p≈1；24 个输出只出现两个 exact 模式','B27 NO HISTORY ASSOCIATION · 23/23'],
  ['J-026','同 PID 重复 frame 38','12/12 PID 内出现两个冻结模式；144 render，42/132 相邻调用切换','B28 WITHIN-PID SWITCH · 23/23'],
  ['J-027','Pass 域探索定位','单 PID pilot：Combined/Crypto 同步一次；Depth/Normal/Position exact；Vector first-call transient','B29 DERIVATION ONLY'],
  ['J-028','Pass 域正式反证','103 coupled R、38 coupled A、3 Crypto-only 解耦；closest-sample passes 144/144 exact','B29 DECOUPLED PATTERN · 25/25'],
  ['J-029','固定 jitter 探索','NATURAL 单 PID 双模式；CENTER 与 ±QUARTER 各 12/12 exact，但都改变全幅采样','B30 DERIVATION ONLY'],
  ['J-030','固定 jitter 正式干预','CENTER 12/12 PID、144/144 exact；NATURAL 10/12 PID 切换；全幅采样代价保留','B30 STRICT STABILITY · 25/25'],
  ['J-031','采样质量代价探索','三个 frame 的 CENTER/NATURAL edge-reference RMSE 为 2.19–2.26×；双 1024 proxy 自身误差极小','B31 DERIVATION ONLY'],
  ['J-032','采样质量正式 holdout','四个未见 frame 全部 ≥1.5；最小 2.1693×；reference reliability 4/4','B31 EDGE COST SUPPORT · 23/23'],
  ['J-033','四点确定性积分','Q4 A/B exact；edge error 降至 CENTER 的 0.555×，仍为 NATURAL 的 1.238×','B32 DERIVATION · 4.093× COST'],
  ['J-034','八点分层积分','Q8 A/B exact；三个 derivation frame 的 Q8/NATURAL 为 0.926–0.948×','B32.1 PROMOTE TO HOLDOUT'],
  ['J-035','正式 holdout 无效尝试','frame 22 cutoff tie 使 quantile+≥ 选出 25,921 而非 25,920 pixels','B32 V0.1 INVALID · NO QUALITY DECISION'],
  ['J-036','Exact-top-k 正式 holdout','28 个新 PID、112 EXR；Q4 mean 1.2706×，Q8 mean 0.9510×，29/29 attacks','B32 V0.2 COST CURVE SUPPORT'],
  ['J-037','Q4/Q8 连续帧派生','28 PID、224 EXR；motion Q4/N 1.823×，Q8/N 0.948×，Q8/Q4 0.520×','B33 DERIVATION · THRESHOLD FREEZE'],
  ['J-038','Q8 连续帧正式 holdout','新 frame 74–81；Q8 motion mean 0.9497×、max 1.0397×，12/12 attacks','B33 TEMPORAL PROXY SUPPORT'],
  ['J-039','N/Q4/Q8 独立盲评包','13 PID、1,872 EXR；三条 carrier 432/432 RGB exact；首轮 audit bug 被保留','B34 PACKAGE READY · HUMAN 0/18'],
  ['J-040','公开哈希解盲攻击','public method→SHA 与 observer CLIP→SHA join，18/18 session 全恢复','B34 HUMAN COLLECTION STOPPED'],
  ['J-041','延迟披露协议冻结','52 mm 新 realization、3,226 项敏感 registry 与 collection-close 顺序在工具前冻结','B35 PREREGISTERED · HUMAN 0/18'],
  ['J-042','原始缓存清理被拒','唯一 B34 work 删除命令被安全层在执行前拒绝；没有绕过，raw work 保留','NO DELETION · FAILURE RETAINED'],
  ['J-043','新盲评包与零泄露公开面','13 PID、1,872 render、432/432 RGB exact；tool commit 扫描 3,226 项为 0 match','B35 PRIVATE PACKAGE READY · COLLECTION NOT OPEN'],
  ['J-044','真实浏览器观察员界面 pilot','三条匿名 clip 均 2/2、汇总 dropped 0、960×540；response 保持 UNLOCKED','B35 INTERFACE PASS · HUMAN 0/18'],
  ['J-045','B36 首次运行被身份字符串判废','真实 API 返回 5.2.0 LTS；analyzer 错写 5.2.0，七个 attacks 前停止并保留输出','B36 ATTEMPT 1 INVALID · NO RETROACTIVE PASS'],
  ['J-046','Registered Text autoexec 边界','6 个新 PID；ENABLE 2/2 执行、DISABLE/default 4/4 阻断；7/7 attacks','B36 NARROW BOUNDARY SUPPORT · NOT SANDBOX'],
  ['J-047','Deprecated SBPL worker capability canary','6 PID；16/16 capability block；inherited 假 secret 2/2 可见、sanitized 0/2','B37 PARTIAL SUPPORT · ENV COUNTEREXAMPLE'],
  ['J-048','Backend-agnostic worker launch contract','3/3 canonical plan；11-key env allowlist；真实 host admission blocked','B38 LOGIC SUPPORT · 25/25'],
  ['J-049','Linux Worker 首轮架构预检','官方 x64 raw filename 出现 2 次，不是预注册的 1 次；route 未晋级','B39 REJECTED PROTOCOL ASSUMPTION'],
  ['J-050','结构化索引纠错','只改 raw=2 + exact href=1；ARM64 路线拒绝，x64 runtime blocked','B39-C1 SUPPORT · 15/15'],
  ['J-051','B40 binfmt parser','raw flags: POCF 被错误解析为空；容量判决未晋级','INVALID TOOL PARSER'],
  ['J-052','C1 对象别名','in-memory attack 与 JSON audit failure vector 不同','REJECTED ALIASING'],
  ['J-053','C2 failure projection','round-trip PASS，但 wrapper 丢失 14 个具体 failure code','INVALID · 0/14'],
  ['J-054','C3 identity source','读取不存在的 C2 spec 字段，结果写入前 TypeError','NO RESULT TOOL CRASH'],
  ['J-055','C4 result field hash','14/14 + replay PASS；replayPassed 字段却逃出 self-hash','AUDIT REJECTED'],
  ['J-056','C5 replay-stable host admission','四项容量 blocker；14/14 + JSON replay + audit','B40 HOST BLOCKED · PASS'],
  ['J-057','容量干预后的首轮 readmission','清理缓存并扩展 Colima；analyzer 与 audit 的 running-container 投影不一致','B40-R1 REJECTED'],
  ['J-058','Replay-stable host readmission','100 GiB reserve、20 GiB projected write、6 CPU、12 GiB RAM 通过','B40-R2 HOST ADMITTED'],
  ['J-059','Docker architecture alias','aarch64 与冻结 arm64 不同；runtime 前停止','B41 INVALID · NO RUNTIME'],
  ['J-060','Archive 通过，build CLI 失败','官方 archive 验证；宿主 CLI 与 guest receipt 不成立','B41-C1 REJECTED'],
  ['J-061','Legacy builder 架构反例','命令成功但 layer 为 ARM64，不接受表面 amd64 tag','B41-C2 REJECTED'],
  ['J-062','Buildx amd64 transport','真实 amd64 层完成；macOS executable SHA 不能冒充 Linux SHA','B41-C3 REJECTED ID'],
  ['J-063','Linux binary 首轮派生','host 得到 ELF x86-64；guest 缺 xz 且 pipeline 掩盖失败','B41-D1 REJECTED'],
  ['J-064','双路径 Linux executable 身份','host 与 guest 同意 174,666,336 bytes 与 83e826…acf27','B41-D1-C1 PASS'],
  ['J-065','真实 amd64 Blender 启动','Blender 5.2 启动；错误 Eevee enum 被拒绝；timeout canary PASS','B41-C4 REJECTED ENUM'],
  ['J-066','Eevee render 超时','场景与 .blend 写出；EGL_BAD_MATCH；30 s 后 TERM','B41-C5 REJECTED'],
  ['J-067','四种 headless Eevee 组合','4/4 停在 RENDER_STARTED；0 PNG；独立 audit PASS','B41-D2 NO COMPLETION'],
  ['J-068','Cycles CPU 对照确认 worker','32×32 单采样 11,039 ms 成功；Vulkan Eevee 无可用路径','B41-D3 CPU CONFIRMED'],
  ['J-069','B42 失败保留，C1 复现通过','B01/B02 四次净构建结构复现；zeroed planHash 被拒绝','B42-C1 REPRO PASS'],
  ['J-070','冻结确定性意图 adapter','两个 SceneSpec/BuildPlan oracle；非法请求零下游工件','B43-D1 GOLDENS DERIVED'],
  ['J-071','订阅认证 Codex holdout','6/6 提案与预先冻结 oracle canonical exact；零工具事件','B43 HOLDOUT PASS'],
  ['J-072','Codex → Blender worker 晋级链','两场景各两次结构复现；拒绝样本在容器前停止','B44 CHAIN REPRO PASS'],
  ['J-073','B44 `.blend` → 浮点像素','首轮 EXR media type 与 null 分析失败保留；C1 四次真实渲染两组 float pixels exact','B45-C1 PIXEL EXACT · 16/16'],
  ['J-074','连续 float 序列与恢复','两组 8 帧跨构建 exact；故障残留不可晋级，新容器空目录恢复 exact','B46 SEQUENCE EXACT · 21/21'],
  ['J-075','生产通道派生','真实 multipart EXR 暴露 Combined、Depth、Normal、Vector 与三层 CryptoObject；Vector 在关闭 motion blur 时仍非零','B47-D1 LAYOUT DERIVED · NOT PROMOTED'],
  ['J-076','多层 EXR 正式晋级','四个 worker、八个 EXR；28/28 解码 pass pairs exact，容器字节 8/8 不同','B47 PRODUCTION PASSES EXACT · 18/18'],
  ['J-077','采样 × 去噪派生','OIDN 改善 log-luminance，却在 32/128 spp 恶化 linear/edge error，并带来显著固定开销','B48-D1 MULTI-OBJECTIVE · NO GATE'],
  ['J-078','独立高采样参考校准','同 seed 512 spp 跨净 worker exact；三个独立 seed 两两 NRMSE 0.033–0.035','B48-D2 REFERENCE FLOOR MEASURED'],
  ['J-079','质量—成本正式 holdout','14 个 worker、两个未见帧；仅 128 spp raw 在三项指标上同时通过两场景 3× floor','B48 128 RAW SELECTED · 18/18'],
  ['J-080','分辨率缩放派生','1×/4×/9× pixels 的 render time 为 1×/3.890×/8.806×；基线 hash 精确复现','B49-D1 PIXEL EXPONENT 0.980–0.990'],
  ['J-081','跨场景分辨率正式 holdout','两个未见 512×288 点的 render exponent 为 0.985980 / 0.996206','B49-R SUPPORTED · 15/15 · AUDIT EXACT'],
];

export default function JournalPage() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="实验日志导航"><Link href="/research-agenda">研究路线</Link><Link href="/resource-budget-v0-1">B12</Link><a href="#entries">日志</a><a href="#rules">规则</a></nav><span className="edition contact-edition">Real Blender Journal</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> CONTINUOUS REAL-BLENDER LAB RECORD</p><h1>理论先写成假设。<br /><span>让真实 Blender 决定结论。</span></h1><p>实验覆盖本机 Blender 5.2.0 LTS 与已验证 Linux/amd64 worker。日志区分回填证据与现场实验；没有 manifest、哈希、几何测量或反例，就不写“已经解决”。</p></div><aside className="contact-gate"><b>LAB POLICY</b><strong>EVIDENCE<br />BEFORE CLAIM</strong><code>real .blend inputs</code><code>real Blender child processes</code><small>negative results stay published</small></aside><div className="contact-stats"><article><strong>5.2 LTS</strong><span>真实 Blender</span><small>Darwin + Linux/amd64</small></article><article><strong>81</strong><span>日志条目</span><small>retrospective + live</small></article><article><strong>0.986–0.996</strong><span>B49 像素指数</span><small>2 / 2 holdouts pass</small></article><article><strong>ACES 2</strong><span>固定 OCIO</span><small>SHA verified</small></article></div></section>
    <section className="section contact-diagnostic" id="entries"><div className="section-index">00 / 记录</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> HYPOTHESIS · RUN · OBSERVATION</p><h2>保留失败，<br /><span>不重写历史。</span></h2></div><p>每条结论都能回到仓库中的 JSON、manifest、`.blend` 或协议。B06 的失败没有被隐藏，而是直接改变了 B07/B08 的架构：由“每次重算”转为“审核后固定回放”。</p></div><ol className="contact-negative-list">{entries.map(([id,item,observed,result]) => <li key={id}><span>{id}</span><b>{item}</b><code>{observed}</code><small>{result}</small></li>)}</ol></section>
    <section className="section contact-contract" id="rules"><div className="section-index">01 / 日志合同</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> SEVEN REQUIRED FIELDS</p><h2>每次实验必须留下，<br /><span>下一位研究者能复跑的东西。</span></h2></div><p>假设、预注册门槛、真实运行时身份、正反观察、被证伪的假设、机器可读证据路径、下一边界，缺一项就仍是工作笔记而不是晋级结论。</p></div><div className="contact-boundary"><b>REQUIRED</b><span>hypothesis</span><span>frozen gate</span><span>runtime identity</span><span>negative evidence</span><strong>NEXT OPEN BOUNDARY</strong></div></section>
    <section className="section contact-limits"><div className="section-index">02 / 最新结果</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> B48 → B49-D1 → B49-R · OPERATING POINT TO RESOLUTION CURVE</p><h2>先选择数值工作点。<br /><span>再让未见分辨率检验成本曲线。</span></h2></div><p>B49-R 将 B48 选出的 128-spp raw 点放大到 16× pixels。TABLETOP 与 INTERIOR 两个预注册 512×288 cell 的 render-time 指数为 0.985980 与 0.996206，均通过 `[0.95,1.05]` 门；15/15 攻击与独立字节重放通过。</p></div><div className="contact-artifacts"><Link href="/resolution-holdout-v0-1"><span>B49 RESOLUTION</span><b>512×288 · two-scene support →</b></Link><Link href="/quality-cost-holdout-v0-1"><span>B48 QUALITY × COST</span><b>128 raw selected · 2/2 →</b></Link><a href="https://github.com/lovejzzz/BlenderFilmStudio/blob/main/research/RESEARCH_CHARTER.md"><span>CHARTER</span><b>三道门与实验纪律 ↗</b></a><a href="https://github.com/lovejzzz/BlenderFilmStudio/blob/main/research/lab-journal.md"><span>FULL JOURNAL</span><b>失败与修正记录 ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>Real Blender Lab Journal</b></div><p>Blender 5.2 LTS · evidence is append-only in spirit</p><Link href="/">返回研究首页 →</Link></footer>
  </main>;
}
