import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: '真实 Blender 实验日志｜Blender Film Studio', description: '持续记录 BlenderFilmStudio 在真实 Blender 5.2 上的假设、命令、观察、失败与下一步。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/journal/' } };
const entries = [
  ['J-001','最小编译器','B01 / B02 两次净构建结构一致，.blend 字节不一致','STRUCTURE PASS · BYTE IDENTITY FALSIFIED'],
  ['J-002','角色与抓握','真实 rig、Shape Keys、接触采样和双指 IK 已进入编译器','AUTOMATION PASS · HUMAN QUALITY OPEN'],
  ['J-003','物理与回放','源刚体精确复现失败；132 帧固定轨迹回放零误差','SOURCE FALSIFIED · REPLAY PASS'],
  ['J-004','资产安全','路径首轮 6 个逃逸；隐藏 Blender 求值行为首轮被编译','B10 8/8 · B11 9/9'],
  ['J-005','资源预算','真实 Blender 超时/日志与本地输出/RSS 反例全部被分类','B12 FORMAL TRUE · 6/6'],
  ['J-006','编译收据','四次真实净构建、19 项验证、三次实现假设被证伪','B13 FORMAL TRUE · 10+2'],
  ['J-007','完整审片样片','真实 Blender 跑完 144 帧；恒真 OCIO 检查被发现后全量重跑','B14 AUTOMATION TRUE · HUMAN PENDING'],
  ['J-008','代理像素复现','同源 A/B 仅 127/144 帧解码 exact；114 像素差异','B15 FORMAL EXACT FALSIFIED'],
  ['J-009','Dither 因果隔离','只把 dither 1→0，仍有 14 帧、69 像素微差','B16 DITHER NOT SUFFICIENT'],
  ['J-010','Eevee 采样因果','1/32 samples × dither 0/1，共 8 次净运行与 1,152 帧','B17 SAMPLING CAUSAL SUPPORT · 12/12'],
  ['J-011','采样剂量响应','1/2/4/8/16/32 samples 共 12 次净运行，exact 向量 F,T,F,F,F,F','B18 NON-MONOTONIC · 13/13'],
  ['J-012','Eevee 控制清单','真实 RNA 显示 Fast GI 与 TAA reprojection 开启；两次无效候选被拒绝','EXPLORATORY · NOT CAUSAL'],
  ['J-013','GI × Reprojection','四个 on/off cells 全部非 exact；同时关闭仍 131/144','B19 NO SUFFICIENT INTERVENTION · 14/14'],
  ['J-014','进程历史隔离','39 个唯一 PID、468 帧；每帧新进程仍只有 26/36 哨兵配对 exact','B20 PROCESS ISOLATION NOT SUFFICIENT · 18/18'],
  ['J-015','Float 输出接口','后台 Render Result.pixels 为空；同一结果可保存 PNG8 与 float EXR32','EXPLORATORY · DIRECT MEMORY CLAIM REJECTED'],
  ['J-016','双输出定位','EXR32 与 PNG8 均 21/36 exact，且 36 个 pair 标签逐一相同','B21 PRE-PNG VARIATION SUPPORT · 21/21'],
  ['J-017','线程数对照冻结','T01 × T08、12 哨兵、三重复；明确 CPU threads 可能不控制 Eevee GPU','B22 PRE-REGISTERED · 72 PROCESSES'],
  ['J-018','线程数对照与下一边界','T01 19/36、T08 22/36；1 thread 不足，转向进程初始化 × repeated render','B22 THREAD COUNT NOT SUFFICIENT · 19/19'],
  ['J-019','重复 render 协议冻结','PERSIST 同 PID 三次 render × FRESH 单次；72 进程、144 EXR、三道 gate','B23 PRE-REGISTERED · NOT EXECUTED'],
  ['J-020','重复 render 结果与研究转向','同 PID 同帧仍只有 59/108 exact；严格 provenance 与感知生产门分离','B23 PER-RENDER VARIATION · 20/20'],
  ['J-021','生产容差与 holdout 冻结','288 EXR + 36 PNG derivation；24 个未见帧、72 新进程验证','B24 PRE-REGISTERED · NO THRESHOLD REVISION'],
  ['J-022','生产容差 holdout 结果','EXR 与 PNG 均 72/72；strict exact 70/72，转向 temporal playback','B24 ENVELOPE SUPPORT · 22/22'],
  ['J-023','连续序列时间残差','三次完整 144 帧；temporal 429/429，static 430/432，frame 38 超门 1 像素','B25 STATIC-ONLY FAIL · 19/19'],
  ['J-024','匿名时间稳定性审片包','三条 lossless carrier 均 144/144 RGB exact；18 个平衡 session，当前 0 response','B26 PACKAGE READY · HUMAN PENDING'],
  ['J-025','frame 38 历史隔离','HISTORY 2/12、DIRECT 3/12 超门；p≈1；24 个输出只出现两个 exact 模式','B27 NO HISTORY ASSOCIATION · 23/23'],
  ['J-026','同 PID 重复 frame 38','12/12 PID 内出现两个冻结模式；144 render，42/132 相邻调用切换','B28 WITHIN-PID SWITCH · 23/23'],
  ['J-027','Pass 域探索定位','单 PID pilot：Combined/Crypto 同步一次；Depth/Normal/Position exact；Vector first-call transient','B29 DERIVATION ONLY'],
  ['J-028','Pass 域正式反证','103 coupled R、38 coupled A、3 Crypto-only 解耦；closest-sample passes 144/144 exact','B29 DECOUPLED PATTERN · 25/25'],
  ['J-029','固定 jitter 探索','NATURAL 单 PID 双模式；CENTER 与 ±QUARTER 各 12/12 exact，但都改变全幅采样','B30 DERIVATION ONLY'],
  ['J-030','固定 jitter 正式干预','CENTER 12/12 PID、144/144 exact；NATURAL 10/12 PID 切换；全幅采样代价保留','B30 STRICT STABILITY · 25/25'],
  ['J-031','采样质量代价探索','三个 frame 的 CENTER/NATURAL edge-reference RMSE 为 2.19–2.26×；双 1024 proxy 自身误差极小','B31 DERIVATION ONLY'],
  ['J-032','采样质量正式 holdout','四个未见 frame 全部 ≥1.5；最小 2.1693×；reference reliability 4/4','B31 EDGE COST SUPPORT · 23/23'],
  ['J-033','四点确定性积分','Q4 A/B exact；edge error 降至 CENTER 的 0.555×，仍为 NATURAL 的 1.238×','B32 DERIVATION · 4.093× COST'],
  ['J-034','八点分层积分','Q8 A/B exact；三个 derivation frame 的 Q8/NATURAL 为 0.926–0.948×','B32.1 PROMOTE TO HOLDOUT'],
  ['J-035','正式 holdout 无效尝试','frame 22 cutoff tie 使 quantile+≥ 选出 25,921 而非 25,920 pixels','B32 V0.1 INVALID · NO QUALITY DECISION'],
  ['J-036','Exact-top-k 正式 holdout','28 个新 PID、112 EXR；Q4 mean 1.2706×，Q8 mean 0.9510×，29/29 attacks','B32 V0.2 COST CURVE SUPPORT'],
  ['J-037','Q4/Q8 连续帧派生','28 PID、224 EXR；motion Q4/N 1.823×，Q8/N 0.948×，Q8/Q4 0.520×','B33 DERIVATION · THRESHOLD FREEZE'],
  ['J-038','Q8 连续帧正式 holdout','新 frame 74–81；Q8 motion mean 0.9497×、max 1.0397×，12/12 attacks','B33 TEMPORAL PROXY SUPPORT'],
  ['J-039','N/Q4/Q8 独立盲评包','13 PID、1,872 EXR；三条 carrier 432/432 RGB exact；首轮 audit bug 被保留','B34 PACKAGE READY · HUMAN 0/18'],
  ['J-040','公开哈希解盲攻击','public method→SHA 与 observer CLIP→SHA join，18/18 session 全恢复','B34 HUMAN COLLECTION STOPPED'],
  ['J-041','延迟披露协议冻结','52 mm 新 realization、3,226 项敏感 registry 与 collection-close 顺序在工具前冻结','B35 PREREGISTERED · HUMAN 0/18'],
  ['J-042','原始缓存清理被拒','唯一 B34 work 删除命令被安全层在执行前拒绝；没有绕过，raw work 保留','NO DELETION · FAILURE RETAINED'],
  ['J-043','新盲评包与零泄露公开面','13 PID、1,872 render、432/432 RGB exact；tool commit 扫描 3,226 项为 0 match','B35 PRIVATE PACKAGE READY · COLLECTION NOT OPEN'],
  ['J-044','真实浏览器观察员界面 pilot','三条匿名 clip 均 2/2、汇总 dropped 0、960×540；response 保持 UNLOCKED','B35 INTERFACE PASS · HUMAN 0/18'],
  ['J-045','B36 首次运行被身份字符串判废','真实 API 返回 5.2.0 LTS；analyzer 错写 5.2.0，七个 attacks 前停止并保留输出','B36 ATTEMPT 1 INVALID · NO RETROACTIVE PASS'],
  ['J-046','Registered Text autoexec 边界','6 个新 PID；ENABLE 2/2 执行、DISABLE/default 4/4 阻断；7/7 attacks','B36 NARROW BOUNDARY SUPPORT · NOT SANDBOX'],
  ['J-047','Deprecated SBPL worker capability canary','6 PID；16/16 capability block；inherited 假 secret 2/2 可见、sanitized 0/2','B37 PARTIAL SUPPORT · ENV COUNTEREXAMPLE'],
  ['J-048','Backend-agnostic worker launch contract','3/3 canonical plan；11-key env allowlist；真实 host admission blocked','B38 LOGIC SUPPORT · 25/25'],
  ['J-049','Linux Worker 首轮架构预检','官方 x64 raw filename 出现 2 次，不是预注册的 1 次；route 未晋级','B39 REJECTED PROTOCOL ASSUMPTION'],
  ['J-050','结构化索引纠错','只改 raw=2 + exact href=1；ARM64 路线拒绝，x64 runtime blocked','B39-C1 SUPPORT · 15/15'],
  ['J-051','B40 binfmt parser','raw flags: POCF 被错误解析为空；容量判决未晋级','INVALID TOOL PARSER'],
  ['J-052','C1 对象别名','in-memory attack 与 JSON audit failure vector 不同','REJECTED ALIASING'],
  ['J-053','C2 failure projection','round-trip PASS，但 wrapper 丢失 14 个具体 failure code','INVALID · 0/14'],
  ['J-054','C3 identity source','读取不存在的 C2 spec 字段，结果写入前 TypeError','NO RESULT TOOL CRASH'],
  ['J-055','C4 result field hash','14/14 + replay PASS；replayPassed 字段却逃出 self-hash','AUDIT REJECTED'],
  ['J-056','C5 replay-stable host admission','四项容量 blocker；14/14 + JSON replay + audit','B40 HOST BLOCKED · PASS'],
  ['J-057','容量干预后的首轮 readmission','清理缓存并扩展 Colima；analyzer 与 audit 的 running-container 投影不一致','B40-R1 REJECTED'],
  ['J-058','Replay-stable host readmission','100 GiB reserve、20 GiB projected write、6 CPU、12 GiB RAM 通过','B40-R2 HOST ADMITTED'],
  ['J-059','Docker architecture alias','aarch64 与冻结 arm64 不同；runtime 前停止','B41 INVALID · NO RUNTIME'],
  ['J-060','Archive 通过，build CLI 失败','官方 archive 验证；宿主 CLI 与 guest receipt 不成立','B41-C1 REJECTED'],
  ['J-061','Legacy builder 架构反例','命令成功但 layer 为 ARM64，不接受表面 amd64 tag','B41-C2 REJECTED'],
  ['J-062','Buildx amd64 transport','真实 amd64 层完成；macOS executable SHA 不能冒充 Linux SHA','B41-C3 REJECTED ID'],
  ['J-063','Linux binary 首轮派生','host 得到 ELF x86-64；guest 缺 xz 且 pipeline 掩盖失败','B41-D1 REJECTED'],
  ['J-064','双路径 Linux executable 身份','host 与 guest 同意 174,666,336 bytes 与 83e826…acf27','B41-D1-C1 PASS'],
  ['J-065','真实 amd64 Blender 启动','Blender 5.2 启动；错误 Eevee enum 被拒绝；timeout canary PASS','B41-C4 REJECTED ENUM'],
  ['J-066','Eevee render 超时','场景与 .blend 写出；EGL_BAD_MATCH；30 s 后 TERM','B41-C5 REJECTED'],
  ['J-067','四种 headless Eevee 组合','4/4 停在 RENDER_STARTED；0 PNG；独立 audit PASS','B41-D2 NO COMPLETION'],
  ['J-068','Cycles CPU 对照确认 worker','32×32 单采样 11,039 ms 成功；Vulkan Eevee 无可用路径','B41-D3 CPU CONFIRMED'],
  ['J-069','B42 失败保留，C1 复现通过','B01/B02 四次净构建结构复现；zeroed planHash 被拒绝','B42-C1 REPRO PASS'],
  ['J-070','冻结确定性意图 adapter','两个 SceneSpec/BuildPlan oracle；非法请求零下游工件','B43-D1 GOLDENS DERIVED'],
  ['J-071','订阅认证 Codex holdout','6/6 提案与预先冻结 oracle canonical exact；零工具事件','B43 HOLDOUT PASS'],
  ['J-072','Codex → Blender worker 晋级链','两场景各两次结构复现；拒绝样本在容器前停止','B44 CHAIN REPRO PASS'],
  ['J-073','B44 `.blend` → 浮点像素','首轮 EXR media type 与 null 分析失败保留；C1 四次真实渲染两组 float pixels exact','B45-C1 PIXEL EXACT · 16/16'],
  ['J-074','连续 float 序列与恢复','两组 8 帧跨构建 exact；故障残留不可晋级，新容器空目录恢复 exact','B46 SEQUENCE EXACT · 21/21'],
  ['J-075','生产通道派生','真实 multipart EXR 暴露 Combined、Depth、Normal、Vector 与三层 CryptoObject；Vector 在关闭 motion blur 时仍非零','B47-D1 LAYOUT DERIVED · NOT PROMOTED'],
  ['J-076','多层 EXR 正式晋级','四个 worker、八个 EXR；28/28 解码 pass pairs exact，容器字节 8/8 不同','B47 PRODUCTION PASSES EXACT · 18/18'],
  ['J-077','采样 × 去噪派生','OIDN 改善 log-luminance，却在 32/128 spp 恶化 linear/edge error，并带来显著固定开销','B48-D1 MULTI-OBJECTIVE · NO GATE'],
  ['J-078','独立高采样参考校准','同 seed 512 spp 跨净 worker exact；三个独立 seed 两两 NRMSE 0.033–0.035','B48-D2 REFERENCE FLOOR MEASURED'],
  ['J-079','质量—成本正式 holdout','14 个 worker、两个未见帧；仅 128 spp raw 在三项指标上同时通过两场景 3× floor','B48 128 RAW SELECTED · 18/18'],
  ['J-080','分辨率缩放派生','1×/4×/9× pixels 的 render time 为 1×/3.890×/8.806×；基线 hash 精确复现','B49-D1 PIXEL EXPONENT 0.980–0.990'],
  ['J-081','跨场景分辨率正式 holdout','两个未见 512×288 点的 render exponent 为 0.985980 / 0.996206','B49-R SUPPORTED · 15/15 · AUDIT EXACT'],
  ['J-082','运动模糊语义派生','零快门隔离曝光窗口；静态 Combined exact；START/END 等价窗口七通道 exact','B49-MB-D1 USABLE · GLOBAL EDGE PROXY FALSIFIED'],
  ['J-083','运动模糊正式 holdout','八个 worker、三参考重复；CENTER 0.5 在三项指标通过且均略优于 OFF','B49-MB SUPPORTED · 19/19 · SMALL EFFECT'],
  ['J-084','景深语义派生','3/5/8 m 焦点 3/3 跟随；focus object 覆盖 exact；DOF 改变辅助 pass','B49-DOF-D1 USABLE · 15/15'],
  ['J-085','双场景景深正式 holdout','十个 worker、两场景六项指标通过；DOF-on 全部比 OFF 接近参考','B49-DOF SUPPORTED · 21/21 · HUMAN INTENT OPEN'],
  ['J-086','可观看焦点意图盲评包','两次 960×540 worker；18 个 9/9 session；真实浏览器 pilot 不计人类','B50 PACKAGE READY · HUMAN 0/18'],
  ['J-087','原生 CPU × Metal 后端派生','native CPU 约快于 qemu 37×；warm Metal 再快约 7.17×；首个 Metal 同步 108.31 s','B51-D1 USABLE · COLD CACHE OPEN'],
  ['J-088','可逆 Cycles cache 干预','原 cache tree 精确恢复；cache 缺失只增加约 0.21 s，不能解释 108.31 s','B51-D2 USABLE · SUFFICIENT CAUSE FALSIFIED'],
  ['J-089','原生 Metal 正式 holdout','canary 与 warm timing 通过；4/4 跨后端 data contract 失败，chair beauty 超 3 项门槛','B51-H1 NOT SUPPORTED · AUDIT PASS'],
  ['J-090','CPU–Metal pass 空间定位','Crypto 100% 边界化；Depth 仅 3.75–80.24%；chair beauty error energy 100% 空间关联','B51-D3 USABLE · SPLIT CONTRACT NEXT'],
  ['J-091','split-backend EXR 首次合并','像素与 routing exact；OpenImageIO capDate 跨秒导致七字节容器差异','B51-D4 INVALID · AUDIT FAIL RETAINED'],
  ['J-092','capDate 单点修正','Metal Date → 七层 DateTime；两组 merge 与 6/6 独立重放 byte-exact','B51-D4-C3 USABLE · 19/19'],
  ['J-093','CPU data sample–cost 曲线','32 个真实 Blender 进程；1–64 spp 均未 exact 复现两场景 data parent','B51-D5 NO EXACT DISCOUNT · FLOOR 128'],
  ['J-094','解码后的 data-pass 语义门','32 份既有 EXR；64 spp matte / dominant ID / stable Depth 均失败','B51-D6 NO SEMANTIC DISCOUNT · FLOOR 128'],
  ['J-095','CPU adaptive parent-control 反证','30/30 renders 完成；真正 fixed control 未复现 D5 parent，0.01/min0 才 7/7 exact','B52-D1 INVALID · UPSTREAM CONTROL FOUND'],
  ['J-096','B52 双站精确发布与泄漏复核','Pages 与 owner-only Sites v46 同源 c044d3a；4,098 文件零敏感命中','PUBLISHED · B50 HUMAN 0/18'],
  ['J-097','真实 adaptive baseline 正式冻结','0.01/min0/max128 对八个更松阈值；新 seed、54 个 fresh Blender 进程','B52-D2 PREREGISTERED · 0 RENDER'],
  ['J-098','D2 工具冻结与零渲染预检','7 个 tool blobs、54-cell matrix、真实 M4 Max CPU/RNA；合成合同 4/4、攻击 22/22','B52-D2 PREFLIGHT PASS · 0 RENDER'],
  ['J-099','显式 adaptive production holdout','54 个新 PID；5/8 profile 成本过门，但 INTERIOR beauty 与 Crypto/aux 阻断全部候选','B52-D2 NOT SUPPORTED · AUDIT PASS'],
  ['J-100','payload task-semantics 派生冻结','复用 54 个已核验 EXR；16 对 measurement、18 张 map、13 项攻击；禁止重渲染与追认 D2','B52-D3 PREREGISTERED · 0 RENDER'],
  ['J-101','payload task-semantics 派生结果','54 个既有 EXR、16 对 task probe、18 张固定标尺诊断图；Crypto 仅 2/16，Normal/Vector 0/16','B52-D3 USABLE · 0 CANDIDATES · AUDIT PASS'],
  ['J-102','Vector Blur 任务预注册','冻结 baseline Combined/Depth，只改变 Vector；2 scenes × 9 profiles × 2 fresh processes','B52-D4 PREREGISTERED · 0 OUTPUT'],
  ['J-103','D4 工具冻结与真实 API 反例','Group Output 的 name=Image、identifier=Socket_0；两进程 EXR 容器不同而 decoded pixels exact','B52-D4 PREFLIGHT PASS · FAILURE RETAINED'],
  ['J-104','Vector Blur task-validity 失败','36/36 Blender processes、18/18 decoded repeats；两个 baseline 场景均 0 effect pixels','B52-D4 INVALID · BASELINE_EFFECT · AUDIT FAIL'],
  ['J-105','受控运动探索','真实 Cycles fixture 的 Vector max 51.200 px；三档 shutter maximum 与 RMSE 严格递增','B52-D5 EXPLORATORY · NODE RESPONSIVE'],
  ['J-106','受控运动校准预注册','物体/相机运动加静态负控；30 个 fresh Blender 进程、36 个 decoded repeat gates','B52-D5 PREREGISTERED · 0 FORMAL OUTPUT'],
  ['J-107','D5 工具冻结与零输出预检','6 个 tool blobs、7 个 parent；20 attacks 使用独立 synthetic-valid base，磁盘窄裕量通过','B52-D5 PREFLIGHT PASS · 0 RENDER'],
  ['J-108','静态负控使 oracle 退役','两种运动全部通过；静态 Vector p99 1.907e−5 超 1/65536，证据审计独立 PASS','B52-D5 INVALID · STATIC CONTROL · AUDIT PASS'],
  ['J-109','独立像素 warp 预注册','冻结 top-left 坐标、destination-sampled displacement、七个 analytic fixture 与 14 个 fresh Blender 进程','B52-D6 PREREGISTERED · 0 FORMAL OUTPUT'],
  ['J-110','D6 工具冻结与 Bilinear smoke 反例','六个 primitive float32 exact；subpixel maximum 1.758e−6；20 attacks 独立路由','B52-D6 PREFLIGHT PASS · COUNTEREXAMPLE RETAINED'],
  ['J-111','独立 Displace 正式校准','14/14 unique Blender processes、7/7 decoded repeats；六项 exact，Bilinear 稳定但不逐位相同','B52-D6 NOT SUPPORTED · REFERENCE_MATCH · AUDIT PASS'],
  ['J-112','双参考 Bilinear holdout 预注册','六个 unseen fixture、Python + Node reference、24 个 fresh child process 与 23 项攻击','B52-D7 PREREGISTERED · 0 FORMAL OUTPUT'],
  ['J-113','D7 工具冻结与尾部失败预测','18 个 development-smoke process；四组 p99、一个 RMSE 预见失败；正式门未改','B52-D7 PREFLIGHT PASS · TOLERANCE_DISTRIBUTION PREDICTED'],
  ['J-114','Bilinear fresh holdout','24/24 unique PID；双参考与 Blender repeats exact；4/6 p99 超冻结门','B52-D7 NOT SUPPORTED · DISTRIBUTION · AUDIT PASS'],
  ['J-115','外部 canonical bridge 预注册','开发探针 3,404 scalars exact；冻结双 producer、Raw EXR 与 12 个 fresh Blender process','B52-D8 PREREGISTERED · 0 FORMAL OUTPUT'],
  ['J-116','D8 机械字段预正式修订','在工具实现前补入 output path、disk reserve、projection 与 verdict labels；科学合同未变','B52-D8 AMENDED BEFORE TOOL WORK'],
  ['J-117','D8 工具冻结与零输出预检','8 个 frozen blobs；双 producer/encoder exact；真实 Blender graph probe 零 render','B52-D8 PREFLIGHT PASS · 0 FORMAL OUTPUT'],
  ['J-118','外部 canonical warp 精确桥','24/24 unique PID；6/6 encoder、12/12 Blender output exact；最大误差与 changed scalar 均为 0','B52-D8 SUPPORTED · 24/24 · AUDIT PASS'],
  ['J-119','Layer/depth 时序合同','冻结 ownership、depth、bounds、alpha validity 与 current→previous motion','B52-D9 PREREGISTERED · 0 OUTPUT'],
  ['J-120','不可能门槛的预正式修订','camera pan 没有 ownership/depth rejection；删除逻辑上不可能的 naive attack','B52-D9 AMENDED BEFORE TOOL WORK'],
  ['J-121','常量表面反例','双实现 exact，但两组 wrong-sign 最大仅 0.0625，正式输出前停止','B52-D9 DESIGN INVALID · RETAINED'],
  ['J-122','Fresh texture holdout','保持 0.25 失败门，冻结全新分辨率、轨迹与 surface-local texture','B52-D9.1 PREREGISTERED · 0 OUTPUT'],
  ['J-123','D9.1 开发验证','Python/Node 十类 arrays exact；错误 sign 在三组移动 fixture 均 ≥1.125','B52-D9.1 DEVELOPMENT PASS'],
  ['J-124','D9.1 冻结预检','八个 frozen blobs、真实 Blender 零 render graph probe；磁盘准入通过','B52-D9.1 PREFLIGHT PASS · 0 RENDER'],
  ['J-125','Layer/depth temporal holdout','32 unique PID、16 Blender renders；resolved float32 zero error，30/30 attacks','B52-D9.1 SUPPORTED · AUDIT PASS'],
  ['J-126','真实 multipart mapping 派生','Vector XY=previous−current、ZW=current−next；Depth/Object Index 对齐解析真值','B52-D10 DERIVATION · NOT PROMOTED'],
  ['J-127','Pass adapter fresh holdout','冻结 173×97、新轨迹、IDs 与 19-process real-Blender matrix','B52-D10 PREREGISTERED · 0 OUTPUT'],
  ['J-128','D10 冻结预检','七个 tool blobs、独立投影 oracle、真实 Blender API 零 render probe','B52-D10 PREFLIGHT PASS · 0 RENDER'],
  ['J-129','D10 verifier-contract 失败','payload 全部过门；JSON double ≠ Blender RNA float32，attacks 0/34','B52-D10 NOT SUPPORTED · AUDIT FAIL'],
  ['J-130','Typed float32 recovery','全新 181×103 fixtures；只对声明的 RNA float 做 binary32 round-trip','B52-D10.1 PREREGISTERED · 0 OUTPUT'],
  ['J-131','D10.1 开发 smoke','六次 Blender + 三次 adapter；raw-double、one-ULP、pass-index attacks 均拒绝','B52-D10.1 DEVELOPMENT PASS'],
  ['J-132','D10.1 冻结预检','七个 frozen blobs、九个 parents、7/7 tests、真实 API 零 render','B52-D10.1 PREFLIGHT PASS · 0 RENDER'],
  ['J-133','真实 Blender pass adapter','19 unique PID、12 Cycles renders、42/42 arrays、37/37 attacks','B52-D10.1 SUPPORTED · AUDIT PASS'],
  ['J-134','真实 textured 组合预注册','冻结 near-integer float32 → toward-zero 一像素风险与 65-process matrix','B52-D11 PREREGISTERED · 0 OUTPUT'],
  ['J-135','D11 开发反例信号','Python/Node 七类输出 byte-exact；round-nearest 改变 87 个 resolved scalars','DEVELOPMENT ONLY · INTEGERIZATION SIGNAL'],
  ['J-136','Raw EXR bridge smoke','OIDN encoder 与 Blender compositor 三段 decoded float32 hash exact','DEVELOPMENT BRIDGE PASS'],
  ['J-137','D11 冻结预检','11 个 frozen blobs、8/8 tests、真实 Blender graph probe 零 render','B52-D11 PREFLIGHT PASS · 0 RENDER'],
  ['J-138','真实 textured composition','65 unique PID；三类运动 1,492 owner-interior integerization misses','B52-D11 NOT SUPPORTED · AUDIT PASS'],
  ['J-139','D11.1 有界量化器预注册','冻结 1/1024 px whole-array domain、双实现与 81-process fresh holdout','B52-D11.1 PREREGISTERED · 0 OUTPUT'],
  ['J-140','D11.1 真实 Blender smoke','9 个进程跨越 source→adapter→quantizer→accumulator→Raw EXR→bridge','DEVELOPMENT PASS · FORMAL 0'],
  ['J-141','冻结预检与磁盘拒绝','首轮只被 100 GiB reserve 拒绝；授权清理可重建缓存后原门通过','B52-D11.1 PREFLIGHT PASS'],
  ['J-142','有界恢复正式矩阵','81 unique PID；14/14 gates、71/71 attacks；原 audit bool_ 序列化失败','FORMAL SUPPORTED · AUDIT PENDING'],
  ['J-143','C1 身份 guard 拒绝','native bool 修正保留；65 字符 receipt hash 在 replay 前被拒','C1 REJECTED · FORMAL UNCHANGED'],
  ['J-144','C2 独立重放通过','8/8 cells、14 gates、71 attacks 全部重建；零正式 rerender','B52-D11.1 SUPPORTED · AUDIT PASS'],
  ['J-145','透视亚像素开发探针','真实 pinhole oracle 验证 Vector endpoint；direct depth identity 反例','D12 DEVELOPMENT · FORMAL 0'],
  ['J-146','D12 fresh holdout 预注册','四个 107×67 透视 fixtures、transform-aware depth、65-process matrix','B52-D12 PREREGISTERED · 0 OUTPUT'],
  ['J-147','D12 冻结预检','11 tools、11 contracts、双语言 synthetic 与两次 Blender 零 render probe','B52-D12 PREFLIGHT PASS'],
  ['J-148','D12 首次执行无效','Node 无法创建缺失父目录；18 PID 后停止，无科学 verdict','INVALID · FAILURE RETAINED'],
  ['J-149','D12-C1 基础设施修正','只允许 recursive directory materialization；科学合同不变','C1 PREREGISTERED'],
  ['J-150','D12-C1 冻结预检','单行 delta、12 contracts、两次 Blender 零 render probe','C1 PREFLIGHT PASS'],
  ['J-151','D12-C1 完整矩阵','65 PID；运动数值通过，Node report identity 与 static exact gate 失败','D12 NOT SUPPORTED'],
  ['J-152','D12-C2 审计修正','只修 absolute-root replay 与 negative-result attack totality','AUDIT-ONLY PREREGISTRATION'],
  ['J-153','D12-C2 独立确认','10/10 replay checks；47/57 negative attack state 忠实重建','D12 NOT SUPPORTED · AUDIT PASS'],
  ['J-154','Typed evidence envelope 预注册','binary64 network-order normalization；不声称 RFC 8785/JCS','D12.1 DEVELOPMENT · 0 OUTPUT'],
  ['J-155','Reduction identity 反例','16/16 documents exact；producer metrics 仅 4/8 exact','THREE EVIDENCE LAYERS REQUIRED'],
  ['J-156','核心编译器再核验','八份 canonical structure 字节流重算；B01/B02 hashes 全部匹配','CORE COMPILER REVALIDATED'],
  ['J-157','静态底噪 holdout 预注册','三组 fresh optics；容差与 exact-zero 分离；55-process matrix','D12.2 PREREGISTERED · 0 OUTPUT'],
  ['J-158','D12.2 冻结预检','13/13；synthetic dual consumer + 真实 Blender 零 render','D12.2 PREFLIGHT PASS'],
  ['J-159','静态 Vector 浮点底噪','55 PID、24/24 attacks；容差通过，六单元 exact zero 均失败','D12.2 TOLERANCE SUPPORTED'],
  ['J-160','非平面多主体 holdout 预注册','球面、圆环、遮挡平面、薄深度堆栈；沿用 D12.2 门','D12.3 PREREGISTERED · 0 OUTPUT'],
  ['J-161','D12.3 冻结预检','13/13；owner-boundary synthetic、真实球面与圆环零 render probe','D12.3 PREFLIGHT PASS'],
  ['J-162','非平面多主体正式矩阵','55 PID、27/27 attacks；interior 通过，遮挡场景精确撞线','D12.3 PASS · ZERO HEADROOM'],
  ['J-163','零余量像素定位预注册','冻结 D12.3 输入身份、极值总量性与独立重放；禁止修订正式结论','D12.4 PREREGISTERED · 0 RENDER'],
  ['J-164','D12.4 冻结工具预检','12/12 contracts；15/15 audit checks 与 15/15 mutation attacks','D12.4 PREFLIGHT PASS'],
  ['J-165','唯一撞线像素算术重放','前景遮挡体 x56 y38 blue；3px、−2⁻¹⁷ Vector、float32 精确撞线','D12.4 PIXEL LOCALIZED'],
  ['J-166','D12.5 半径干预预注册','radius 2 control × radius 3 intervention；两倍余量与覆盖防作弊','D12.5 PREREGISTERED'],
  ['J-167','D12.5-C1 证据绑定','在工具出现前补齐 frozen typed-envelope parent identities','PREREG CORRECTION · 0 OUTPUT'],
  ['J-168','D12.5 冻结预检','14/14；双语言双半径 synthetic + 三场景 zero-render probe','D12.5 PREFLIGHT PASS'],
  ['J-169','第一次 formal 运行无效','54 child 成功；analyzer NumPy bool 序列化失败，无 results','INVALID · NO VERDICT'],
  ['J-170','D12.5-C2 单行修正预注册','仅 bool cast + fresh identities/root；完整矩阵必须重跑','C2 PREREGISTERED'],
  ['J-171','C2 冻结预检','exact delta；14/14；fresh root admitted','C2 PREFLIGHT PASS'],
  ['J-172','半径 3 fresh holdout','55 PID、30/30 attacks；容差通过，两倍余量与 owner 覆盖失败','BOUNDED · NOT SUPPORTED'],
  ['J-173','内部风险定位预注册','逐像素绑定 owner、距离、Vector bits、taps、weights、贡献与 float32 cast','D12.6 PREREGISTERED'],
  ['J-174','D12.6 冻结预检','10/10 checks；259 synthetic bounds；4 MiB 磁盘投影通过','PREFLIGHT PASS'],
  ['J-175','第一次 D12.6 formal 无效','边界坐标在拒绝前读取 tap；无 results、无测量暴露','INVALID · RETAINED'],
  ['J-176','D12.6-C2 唯一修正','只把坐标拒绝移动到 tap 读取之前；新 ID 与 fresh roots','C2 PREREGISTERED'],
  ['J-177','C2 冻结预检','10/10 checks；无效父运行身份纳入；259 synthetic bounds','C2 PREFLIGHT PASS'],
  ['J-178','局部算术风险界','92,763 RGB 零低估；Spearman 0.894–0.928；18/18 attacks','D12.6-C2 CONSERVATIVE'],
  ['J-179','自适应风险门 fresh holdout 预注册','三组未见几何、双重复；radius 2 + 冻结 risk gate 对照 radius 3','D12.7 PREREGISTERED · 0 OUTPUT'],
  ['J-180','D12.7 冻结工具预检','17/17 checks；259 risk cases；双语言 11 payload exact；三次真实 Blender 零 render probe','D12.7 PREFLIGHT PASS'],
  ['J-181','候选通过、正式标签有界','12 fresh renders；adaptive 保留 99.60–99.86% radius 2；唯一 false 为 radius-3 production','20 / 21 · BOUNDED'],
  ['J-182','审计逃逸与 C1 修正','原 audit 28/30；C1 只保护 roster + analyzerPid，零科学重跑后 30/30','CORRECTED AUDIT PASS'],
  ['J-183','真实运动 / 反遮挡预注册','四组全新透视 fixtures；先做 transform-aware validity，再执行冻结 adaptive risk gate','B52-D12.8 PREREGISTERED · 0 OUTPUT'],
  ['J-184','D12.8 source 零渲染探针','四个真实 Blender 进程构建 2-owner 场景；same-index [13505,13505] 保持','TOOL DEVELOPMENT · 0 FORMAL RENDER'],
  ['J-185','双 consumer 合成对照','首轮 11/12 exact 定位非规范 projection bytes；删去后 9/9 canonical payload exact','COUNTEREXAMPLE RETAINED · FORMAL 0'],
];

export default function JournalPage() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="实验日志导航"><Link href="/research-agenda">研究路线</Link><Link href="/blender-static-radius-intervention-v0-1">D12.5 干预</Link><Link href="/blender-static-interior-risk-localization-v0-1">D12.6 风险</Link><Link href="/blender-static-adaptive-risk-gate-v0-1">D12.7 Holdout</Link><a href="#entries">日志</a><a href="#rules">规则</a></nav><span className="edition contact-edition">Real Blender Journal</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> CONTINUOUS REAL-BLENDER LAB RECORD</p><h1>理论先写成假设。<br /><span>让真实 Blender 决定结论。</span></h1><p>实验覆盖本机 Blender 5.2.0 LTS 与已验证 Linux/amd64 worker。日志区分回填证据与现场实验；没有 manifest、哈希、几何测量或反例，就不写“已经解决”。</p></div><aside className="contact-gate"><b>LAB POLICY</b><strong>EVIDENCE<br />BEFORE CLAIM</strong><code>real .blend inputs</code><code>real Blender child processes</code><small>negative results stay published</small></aside><div className="contact-stats"><article><strong>5.2 LTS</strong><span>真实 Blender</span><small>Darwin + Linux/amd64</small></article><article><strong>185</strong><span>日志条目</span><small>retrospective + live</small></article><article><strong>0 / 18</strong><span>B50 人类证据</span><small>package ready · pending</small></article><article><strong>DUAL 9 / 9 EXACT</strong><span>D12.8 当前阶段</span><small>synthetic only · formal 0</small></article></div></section>
    <section className="section contact-diagnostic" id="entries"><div className="section-index">00 / 记录</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> HYPOTHESIS · RUN · OBSERVATION</p><h2>保留失败，<br /><span>不重写历史。</span></h2></div><p>每条结论都能回到仓库中的 JSON、manifest、`.blend` 或协议。B06 的失败没有被隐藏，而是直接改变了 B07/B08 的架构：由“每次重算”转为“审核后固定回放”。</p></div><ol className="contact-negative-list">{entries.map(([id,item,observed,result]) => <li key={id}><span>{id}</span><b>{item}</b><code>{observed}</code><small>{result}</small></li>)}</ol></section>
    <section className="section contact-contract" id="rules"><div className="section-index">01 / 日志合同</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> SEVEN REQUIRED FIELDS</p><h2>每次实验必须留下，<br /><span>下一位研究者能复跑的东西。</span></h2></div><p>假设、预注册门槛、真实运行时身份、正反观察、被证伪的假设、机器可读证据路径、下一边界，缺一项就仍是工作笔记而不是晋级结论。</p></div><div className="contact-boundary"><b>REQUIRED</b><span>hypothesis</span><span>frozen gate</span><span>runtime identity</span><span>negative evidence</span><strong>NEXT OPEN BOUNDARY</strong></div></section>
    <section className="section contact-limits"><div className="section-index">02 / 最新结果</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> B52-D12.7 · ADAPTIVE RISK HOLDOUT</p><h2>候选规则通过。<br /><span>正式标签没有被追改。</span></h2></div><p>三组未见静态几何中，adaptive 保留 99.60–99.86% 的 radius-2 域、拒绝 44 个高风险像素，并把最大 RGB 误差保持在冻结半门之下。21 项 checks 中唯一失败是 radius-3 comparator 自身越过 production max，因此 verdict 仍为 bounded；C1 独立审计 30/30。</p></div><div className="contact-artifacts"><Link href="/blender-static-adaptive-risk-gate-v0-1"><span>B52-D12.7 RESULT</span><b>fresh holdout →</b></Link><a href="https://github.com/lovejzzz/BlenderFilmStudio/blob/main/experiments/blender-static-adaptive-risk-gate-holdout-v0-1/results.json"><span>MACHINE RESULT</span><b>20 / 21 checks ↗</b></a><a href="https://github.com/lovejzzz/BlenderFilmStudio/blob/main/experiments/blender-static-adaptive-risk-gate-holdout-v0-1/audit.c1.json"><span>CORRECTED AUDIT</span><b>30 / 30 attacks ↗</b></a><a href="https://github.com/lovejzzz/BlenderFilmStudio/blob/main/research/lab-journal.md"><span>FULL JOURNAL</span><b>motion + occlusion next ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>Real Blender Lab Journal</b></div><p>Blender 5.2 LTS · evidence is append-only in spirit</p><Link href="/">返回研究首页 →</Link></footer>
  </main>;
}
