import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B51 原生 CPU × Metal 后端｜Blender Film Studio',
  description: '真实 Blender 5.2 原生 Cycles 后端研究：Metal warm 吞吐、跨后端负结果、确定性 EXR assembly，以及被 D5/D6 双重拒绝的低 sample split-production 成本假设。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/native-backend-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const d3Media = 'https://raw.githubusercontent.com/lovejzzz/BlenderFilmStudio/6ef7d04/experiments/native-metal-pass-localization-v0-1';

const rows = [
  { scene: 'TABLETOP', qemu: '151.992 s', cpu: '4.112 / 4.122 s', metal: '109.534 / 0.574 s', warm: '7.17×', note: 'first Metal is cold' },
  { scene: 'INTERIOR', qemu: '191.877 s', cpu: '5.090 / 5.029 s', metal: '0.717 / 0.695 s', warm: '7.17×', note: 'cache already warm' },
];

export default function NativeBackendPage() {
  return <main className="contact-page b51-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B51 导航"><Link href="/cost-model">成本</Link><Link href="/journal">实验日志</Link><a href="#holdout">正式门</a><a href="#localization">差异定位</a><a href="#assembly">EXR 合并</a><a href="#sample-cost">sample 成本</a><a href="#semantic">语义门</a><Link href="/adaptive-cpu-v0-1">B52 adaptive</Link></nav><span className="edition contact-edition">Native Backend B51</span></header>

    <section className="contact-hero b51-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> REAL BLENDER 5.2 · APPLE M4 MAX · CYCLES</p><h1><em>0.57 s</em> 很快。<br/>生产门仍然 <span>拒绝。</span></h1><p>D1/D2 找到热态速度并排除用户 cache 充分因果；H1 的 13 个新进程随后证明：快，不等于 beauty 与 data passes 已经共享一个可靠的跨后端合同。</p></div><aside className="contact-gate b51-gate"><b>FORMAL HOLDOUT</b><strong>NOT<br/>SUPPORTED</strong><code>13 / 13 real renders</code><code>21 / 21 attacks</code><small>audit PASS · replay exact</small></aside><div className="contact-stats"><article><strong>0.14 s</strong><span>canary synchronization</span><small>readiness pass</small></article><article><strong>0.525–0.751 s</strong><span>warm Metal</span><small>eight holdout cells</small></article><article><strong>4 / 4</strong><span>exact data-pass fail</span><small>CPU ↔ Metal</small></article><article><strong>0.01260</strong><span>chair beauty NRMSE</span><small>limit 0.0065</small></article></div></section>

    <section className="section b51-timing" id="timing"><div className="section-index">00 / COLD ≠ WARM</div><div className="contact-heading"><div><p className="eyebrow"><span/> ONE GPU · TWO COST REGIMES</p><h2>吞吐很快。<br/><span>启动状态决定账单。</span></h2></div><p>首次 TABLETOP Metal 的总 render operator 为 109.534 秒；EXR header 把其中 108.31 秒记为 Cycles synchronization。相同场景后续 Metal 只用 0.574 秒，其中 synchronization 为 0.13 秒。</p></div><div className="b51-timeline"><article className="cold"><header><span>METAL · FIRST OBSERVATION</span><b>109.534 s</b></header><div className="b51-bar"><i/><strong>108.31 s SYNC</strong><small>1.17 s render</small></div></article><article className="warm"><header><span>METAL · LATER PROCESS</span><b>0.574 s</b></header><div className="b51-bar"><i/><strong>0.13 s SYNC</strong><small>0.40 s render</small></div></article></div><div className="contact-nonclaim"><b>D1 OBSERVATION, NOT CAUSE</b><p>D1 只观察到首格极慢。B51-D2 随后对精确用户 Cycles cache 做了可逆干预，并否证该目录是 108.31 秒的充分原因。</p></div></section>

    <section className="section b51-cache" id="cache"><div className="section-index">01 / CACHE INTERVENTION</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> EXACT CACHE ABSENCE · ATOMIC RESTORE</p><h2>移走 74 MiB cache。<br/><span>108 秒没有回来。</span></h2></div><p>原 79-file tree 先做内容哈希，再原子移到同卷 quarantine。三个新 Blender 进程结束后，新 cache 被保留，原 cache 回到完全相同的 tree hash；没有删除或覆盖。</p></div><div className="b51-cache-cells"><article className="cold"><span>CACHE PATH ABSENT</span><strong>0.790 s</strong><b>0.34 s synchronization</b><small>75 files generated</small></article><article><span>GENERATED CACHE · R1</span><strong>0.578 s</strong><b>0.13 s synchronization</b><small>fresh Blender process</small></article><article><span>SAME CACHE · R2</span><strong>0.569 s</strong><b>0.13 s synchronization</b><small>fresh Blender process</small></article></div><div className="b51-cache-verdict"><span>FALSIFIED SUFFICIENT CAUSE</span><strong>≈ 0.21 s penalty ≠ 108.31 s event</strong><p>精确 `~/.cache/cycles` 缺失只带来 1.366× render 与 2.615× synchronization，比 D1 反例小两个数量级以上。剩余候选位于 OS / Metal / driver / host-session 层，目前没有被命名。</p></div><div className="b51-restore"><article><span>ORIGINAL</span><b>79 files · 77,737,584 B</b><code>fc6bc6f949f6…</code></article><i>→</i><article><span>RESTORED</span><b>CONTENT TREE EXACT</b><code>fc6bc6f949f6…</code></article><strong>PASS</strong></div></section>

    <section className="section b51-bench"><div className="section-index">02 / SAME FROZEN WORKLOAD</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> 512×288 · 128 RAW SPP · SEVEN PASSES</p><h2>三个后端，<br/><span>同一组场景数据。</span></h2></div><p>qemu 数字复用已审计的 B49-R 父结果；native CPU 与 Metal 各有两个新的进程。速度比只描述这两个简单场景，不外推到 2K、4K 或角色镜头。</p></div><div className="b51-table" role="table" aria-label="B51 后端时间表"><div className="head" role="row"><span>SCENE</span><span>QEMU CPU</span><span>NATIVE CPU ×2</span><span>METAL ×2</span><span>WARM GAIN</span></div>{rows.map(row=><div className="row" role="row" key={row.scene}><b>{row.scene}<small>{row.note}</small></b><code>{row.qemu}</code><code>{row.cpu}</code><code>{row.metal}</code><strong>{row.warm}</strong></div>)}</div><div className="b51-speed-chain"><article><span>EVIDENCE WORKER</span><b>qemu CPU</b><strong>152–192 s</strong></article><i>≈ 37×</i><article><span>NATIVE CONTROL</span><b>4-thread CPU</b><strong>4.1–5.1 s</strong></article><i>≈ 7.17×</i><article className="active"><span>WARM CANDIDATE</span><b>40-core Metal</b><strong>0.57–0.72 s</strong></article></div></section>

    <section className="section b51-holdout" id="holdout"><div className="section-index">03 / FORMAL HOLDOUT</div><div className="contact-heading"><div><p className="eyebrow"><span/> CANARY PASS · IMAGE CONTRACT FAIL</p><h2>速度门通过。<br/><span>图像门拒绝。</span></h2></div><p>四个先验冻结、从未渲染过的构图分别接受一次 CPU 与两次 Metal。所有 warm 时间和 Metal 重复门通过，但跨后端 exact data passes 与一个 beauty 构图没有通过。</p></div><div className="b51-domain-grid"><article className="exact"><span>PRE-JOB CANARY</span><strong>0.14 s</strong><b>synchronization</b><p>0.396 s render · PASS</p></article><article><span>WARM METAL ×8</span><strong>0.53–0.75</strong><b>seconds / cell</b><p>all below 2.5 s</p></article><article className="mixed"><span>CPU ↔ METAL DATA</span><strong>4 / 4</strong><b>compositions fail exact</b><p>Depth + active Crypto</p></article><article className="mixed"><span>INTERIOR_CHAIR</span><strong>0.01260</strong><b>beauty NRMSE</b><p>frozen limit 0.0065</p></article></div><div className="contact-nonclaim"><b>NEGATIVE EVIDENCE IS THE RESULT</b><p>H1 的审计是 PASS，但 promotion 是 NOT SUPPORTED。审计只证明负结果可从冻结 EXR 与 receipt 精确重放，不会把失败变成成功。</p></div></section>

    <section className="section b51-pixels" id="pixels"><div className="section-index">04 / SAME-BACKEND ≠ CROSS-BACKEND</div><div className="contact-heading"><div><p className="eyebrow"><span/> REPEATABILITY BY PASS DOMAIN</p><h2>同后端可以全等。<br/><span>跨后端不能外推。</span></h2></div><p>D1/D2 证明 Metal 重复中的 Depth 与 Cryptomatte exact；H1 却证明 CPU–Metal 的这些 data passes 在四个未见构图中都不能满足同一个 exact 合同。两类命题必须分开。</p></div><div className="b51-domain-grid"><article className="exact"><span>NATIVE CPU ×2 · D1</span><strong>7 / 7</strong><b>decoded passes exact</b><p>same backend</p></article><article className="exact"><span>METAL ×2 · H1</span><strong>≈1e−7</strong><b>Combined repeat NRMSE</b><p>same backend tolerance pass</p></article><article className="mixed"><span>CPU ↔ METAL · H1</span><strong>0 / 4</strong><b>exact data contracts</b><p>all four compositions rejected</p></article><article><span>BEAUTY HOLDOUT</span><strong>3 / 4</strong><b>compositions pass</b><p>chair variant exceeds 3 limits</p></article></div><div className="contact-nonclaim"><b>PERCEPTION IS STILL OPEN</b><p>数值门失败不自动等于肉眼明显；但在空间定位和 data-pass 语义验证前，也不能把差异降格为“看不见所以没关系”。</p></div></section>

    <section className="section b51-localization" id="localization"><div className="section-index">05 / ZERO-RERENDER LOCALIZATION</div><div className="contact-heading"><div><p className="eyebrow"><span/> 12 RETAINED EXR · FIVE DIAGNOSTIC MAPS</p><h2>Crypto 差异贴着边界。<br/><span>Depth 漂移铺满内部。</span></h2></div><p>D3 没有启动 Blender，而是重新验明 H1 的 12 份 EXR 后按预冻结规则定位。所有 Cryptomatte changed pixels 都在一像素边界邻域；Depth 只有 3.75%–80.24% 在边界，不能用一个“edge noise”解释全部失败。</p></div><div className="b51-localization-grid"><article className="exact"><span>CRYPTOMATTE</span><strong>100%</strong><b>changed pixels near boundary</b><p>4–136 sparse pixels / composition</p></article><article className="mixed"><span>DEPTH</span><strong>3.75–80.24%</strong><b>near-boundary fraction</b><p>33.51–80.19% of frame non-exact</p></article><article><span>DEPTH INTERIOR Δ</span><strong>3.34–4.77e−6</strong><b>maximum absolute difference</b><p>small amplitude · broad support</p></article><article className="exact"><span>CHAIR BEAUTY</span><strong>100%</strong><b>squared error associated</b><p>within 2 px data neighborhood</p></article></div><div className="b51-localization-gallery"><figure><Image src={`${d3Media}/interior_chair-data-map.png`} width={512} height={288} unoptimized alt="INTERIOR_CHAIR CPU 与 Metal data-pass 差异图：红色为 Depth，绿色为 Cryptomatte，蓝色为一像素膨胀 union"/><figcaption><span>ACTUAL D3 DATA MAP</span><b>INTERIOR_CHAIR · CPU ↔ METAL</b><p>R = Depth disagreement · G = Crypto disagreement · B = 1 px dilated union。大面积洋红来自广域 Depth 非 exact，不是画面风格化。</p></figcaption></figure><figure><Image src={`${d3Media}/interior-chair-beauty-heatmap.png`} width={512} height={288} unoptimized alt="INTERIOR_CHAIR CPU 与 Metal Combined 绝对误差对数热图及 data disagreement 关联区域"/><figcaption><span>ACTUAL D3 BEAUTY HEATMAP</span><b>1,971 pixels above 1e−3</b><p>红通道编码 log absolute error；青色标出 data disagreement 的两像素邻域。全部 squared-error energy 位于关联 mask，但这仍是相关而非因果。</p></figcaption></figure></div><div className="contact-nonclaim"><b>LOCALIZED ≠ SAFE</b><p>Crypto 的 100% 边界定位不证明 matte 语义等价；Depth 的微小绝对差也不证明合成安全。D3 的 `METAL_PASS_LOCALIZATION_USABLE` 是诊断结论，不是生产晋级。</p></div></section>

    <section className="section b51-cache" id="assembly"><div className="section-index">06 / DETERMINISTIC MULTIPART ASSEMBLY</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> D4 INVALID → C3 CORRECTED · ZERO RERENDER</p><h2>像素第一次就对。<br/><span>时间戳让文件不一样。</span></h2></div><p>D4 把 Metal beauty 与 CPU data 正确路由进七层 EXR，但 TABLETOP 两次输出因 OpenImageIO 自动生成的 `capDate` 跨了一秒，七层各差一个字节。我们保留无效结果，再预注册单点修正：从冻结 Metal `Date` 派生七层共同 `DateTime`。</p></div><div className="b51-domain-grid"><article className="mixed"><span>D4 FIRST RESULT</span><strong>7 bytes</strong><b>container difference</b><p>pixels exact · audit FAIL</p></article><article className="exact"><span>C3 BASE + ATTACKS</span><strong>19 / 19</strong><b>all intended reasons</b><p>no Blender · no rerender</p></article><article className="exact"><span>MERGE REPLICATES</span><strong>2 / 2</strong><b>pair files byte-exact</b><p>seven subimages each</p></article><article className="exact"><span>INDEPENDENT REPLAY</span><strong>6 / 6</strong><b>artifacts byte-exact</b><p>receipt · result · four EXRs</p></article></div><div className="contact-nonclaim"><b>KNOWN INPUTS ONLY</b><p>C3 关闭的是两组已知 H1 输入的 deterministic assembly 工程门。它没有生成未见画面，也没有证明 split-backend 比全 CPU 更快或更可靠；这些属于 H2。</p></div></section>

    <section className="section b51-holdout" id="sample-cost"><div className="section-index">07 / CPU DATA SAMPLE–COST</div><div className="contact-heading"><div><p className="eyebrow"><span/> 32 REAL BLENDER PROCESSES · 1 → 128 SPP</p><h2>低 sample 很快。<br/><span>但 exact data 不降档。</span></h2></div><p>D5 用两个 H1 构图、八个 sample dose、每格两个 fresh-process repeat 测试 CPU Depth + Cryptomatte。剂量内重复全部 exact；只有 128 spp 同时逐 float 复现两个冻结 parent。</p></div><div className="b51-domain-grid"><article className="exact"><span>RUNTIME MATRIX</span><strong>32 / 32</strong><b>real Blender renders</b><p>2 variants · 8 doses · 2 repeats</p></article><article className="mixed"><span>EXACT SAMPLE FLOOR</span><strong>128</strong><b>samples per pixel</b><p>no 1–64 spp discount</p></article><article><span>TABLETOP 64 SPP</span><strong>63.26%</strong><b>Depth pixels changed</b><p>Crypto00: 2.95%</p></article><article><span>INTERIOR 64 SPP</span><strong>100%</strong><b>Depth pixels changed</b><p>Crypto00: 2.81%</p></article></div><div className="contact-nonclaim"><b>EXACT CONTRACT HAS NO COST ADVANTAGE</b><p>128-spp CPU data 已接近一份完整 CPU production render；再添加 Metal beauty 与 merge 只会增加工作。D5 没有把 raw ID float 或 `1e10` Depth sentinel 的数值差直接解释成合成失败，因此下一门必须先定义任务相关语义。</p></div></section>

    <section className="section b51-localization" id="semantic"><div className="section-index">08 / DECODED PRODUCTION SEMANTICS</div><div className="contact-heading"><div><p className="eyebrow"><span/> D6 · 32 RETAINED EXR · ZERO RERENDER</p><h2>ID float 不再当误差。<br/><span>解码后仍然不降档。</span></h2></div><p>D6 按 Cryptomatte 1.2.0 把三层 RGBA 解成六组 ranked ID/coverage，再由 manifest 重建每个对象 matte；Depth 分离前景拓扑与 coverage ≥ 0.999 的稳定表面。阈值在 analyzer 实现前冻结。</p></div><div className="b51-domain-grid"><article className="exact"><span>INPUT INTEGRITY</span><strong>32 / 32</strong><b>EXR identities match</b><p>metadata + manifests valid</p></article><article className="mixed"><span>SEMANTIC SAMPLE FLOOR</span><strong>128</strong><b>samples per pixel</b><p>both variants · both repeats</p></article><article><span>64 SPP · TABLETOP</span><strong>53</strong><b>hard-matte mismatches</b><p>Depth p99: 2.802 mm</p></article><article><span>64 SPP · INTERIOR</span><strong>205</strong><b>hard-matte mismatches</b><p>Depth p99: 73.200 mm</p></article></div><div className="contact-nonclaim"><b>SPLIT COST HYPOTHESIS CLOSED</b><p>64 spp 还出现 10 / 102 个 confident dominant-ID mismatch，worst matte alpha error 为 0.09375 / 0.15625。D6 audit PASS、16/16 attacks、analyzer replay byte-exact；exact 与 production-semantic 两个合同都只支持 128 spp。</p></div></section>

    <section className="section contact-limits b51-next" id="next"><div className="section-index">09 / B52 FOLLOW-UP</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> INHERITED ADAPTIVE CONTROL FOUND</p><h2>CPU 优化已经开始。<br/><span>第一件事是修正 baseline。</span></h2></div><p>B52-D1 的 30 个进程发现 D5/D6 parent 实际继承 adaptive 0.01/min0。真正 fixed control 未复现 parent，因此实验保持 INVALID；这修订了 baseline，而不是提供一个可晋级 profile。</p></div><div className="b51-next-flow"><article><span>01</span><b>D1 INVALID</b><p>fixed parent mismatch</p></article><i>→</i><article><span>02</span><b>ROOT CAUSE</b><p>D5 inherited 0.01/min0</p></article><i>→</i><article><span>03</span><b>D2 FRESH SEED</b><p>explicit production baseline</p></article><i>→</i><article><span>04</span><b>≥ 20%</b><p>promote or reject</p></article></div><div className="contact-artifacts"><Link href="/adaptive-cpu-v0-1"><span>B52 PAGE</span><b>30 renders · control falsification →</b></Link><a href={`${repo}experiments/native-cpu-adaptive-quality-cost-derivation-v0-1/results.json`}><span>D1 RESULT</span><b>INVALID · replay exact ↗</b></a><a href={`${repo}experiments/native-cpu-adaptive-quality-cost-derivation-v0-1/upstream-adaptive-control-diagnosis.json`}><span>ROOT CAUSE</span><b>two Blender probes ↗</b></a><a href={`${repo}research/2026-08-27-b52-d1-native-cpu-adaptive-quality-cost-derivation-result.md`}><span>RESULT NOTE</span><b>limits · next experiment ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B51 Native Backend Research</b></div><p>assembly reproducible · exact + semantic floor 128 · split cost route closed</p><Link href="/cost-model">回到成本模型 →</Link></footer>
  </main>;
}
