import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B51 原生 CPU × Metal 后端｜Blender Film Studio',
  description: '24 次真实 Blender 5.2 原生 Cycles 渲染：Metal warm 吞吐、可逆缓存反证，以及被正式 holdout 拒绝的跨后端图像契约。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/native-backend-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';

const rows = [
  { scene: 'TABLETOP', qemu: '151.992 s', cpu: '4.112 / 4.122 s', metal: '109.534 / 0.574 s', warm: '7.17×', note: 'first Metal is cold' },
  { scene: 'INTERIOR', qemu: '191.877 s', cpu: '5.090 / 5.029 s', metal: '0.717 / 0.695 s', warm: '7.17×', note: 'cache already warm' },
];

export default function NativeBackendPage() {
  return <main className="contact-page b51-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B51 导航"><Link href="/cost-model">成本</Link><Link href="/journal">实验日志</Link><a href="#timing">时间</a><a href="#cache">Cache 反证</a><a href="#holdout">正式门</a><a href="#next">下一门</a></nav><span className="edition contact-edition">Native Backend B51</span></header>

    <section className="contact-hero b51-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> REAL BLENDER 5.2 · APPLE M4 MAX · CYCLES</p><h1><em>0.57 s</em> 很快。<br/>生产门仍然 <span>拒绝。</span></h1><p>D1/D2 找到热态速度并排除用户 cache 充分因果；H1 的 13 个新进程随后证明：快，不等于 beauty 与 data passes 已经共享一个可靠的跨后端合同。</p></div><aside className="contact-gate b51-gate"><b>FORMAL HOLDOUT</b><strong>NOT<br/>SUPPORTED</strong><code>13 / 13 real renders</code><code>21 / 21 attacks</code><small>audit PASS · replay exact</small></aside><div className="contact-stats"><article><strong>0.14 s</strong><span>canary synchronization</span><small>readiness pass</small></article><article><strong>0.525–0.751 s</strong><span>warm Metal</span><small>eight holdout cells</small></article><article><strong>4 / 4</strong><span>exact data-pass fail</span><small>CPU ↔ Metal</small></article><article><strong>0.01260</strong><span>chair beauty NRMSE</span><small>limit 0.0065</small></article></div></section>

    <section className="section b51-timing" id="timing"><div className="section-index">00 / COLD ≠ WARM</div><div className="contact-heading"><div><p className="eyebrow"><span/> ONE GPU · TWO COST REGIMES</p><h2>吞吐很快。<br/><span>启动状态决定账单。</span></h2></div><p>首次 TABLETOP Metal 的总 render operator 为 109.534 秒；EXR header 把其中 108.31 秒记为 Cycles synchronization。相同场景后续 Metal 只用 0.574 秒，其中 synchronization 为 0.13 秒。</p></div><div className="b51-timeline"><article className="cold"><header><span>METAL · FIRST OBSERVATION</span><b>109.534 s</b></header><div className="b51-bar"><i/><strong>108.31 s SYNC</strong><small>1.17 s render</small></div></article><article className="warm"><header><span>METAL · LATER PROCESS</span><b>0.574 s</b></header><div className="b51-bar"><i/><strong>0.13 s SYNC</strong><small>0.40 s render</small></div></article></div><div className="contact-nonclaim"><b>D1 OBSERVATION, NOT CAUSE</b><p>D1 只观察到首格极慢。B51-D2 随后对精确用户 Cycles cache 做了可逆干预，并否证该目录是 108.31 秒的充分原因。</p></div></section>

    <section className="section b51-cache" id="cache"><div className="section-index">01 / CACHE INTERVENTION</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> EXACT CACHE ABSENCE · ATOMIC RESTORE</p><h2>移走 74 MiB cache。<br/><span>108 秒没有回来。</span></h2></div><p>原 79-file tree 先做内容哈希，再原子移到同卷 quarantine。三个新 Blender 进程结束后，新 cache 被保留，原 cache 回到完全相同的 tree hash；没有删除或覆盖。</p></div><div className="b51-cache-cells"><article className="cold"><span>CACHE PATH ABSENT</span><strong>0.790 s</strong><b>0.34 s synchronization</b><small>75 files generated</small></article><article><span>GENERATED CACHE · R1</span><strong>0.578 s</strong><b>0.13 s synchronization</b><small>fresh Blender process</small></article><article><span>SAME CACHE · R2</span><strong>0.569 s</strong><b>0.13 s synchronization</b><small>fresh Blender process</small></article></div><div className="b51-cache-verdict"><span>FALSIFIED SUFFICIENT CAUSE</span><strong>≈ 0.21 s penalty ≠ 108.31 s event</strong><p>精确 `~/.cache/cycles` 缺失只带来 1.366× render 与 2.615× synchronization，比 D1 反例小两个数量级以上。剩余候选位于 OS / Metal / driver / host-session 层，目前没有被命名。</p></div><div className="b51-restore"><article><span>ORIGINAL</span><b>79 files · 77,737,584 B</b><code>fc6bc6f949f6…</code></article><i>→</i><article><span>RESTORED</span><b>CONTENT TREE EXACT</b><code>fc6bc6f949f6…</code></article><strong>PASS</strong></div></section>

    <section className="section b51-bench"><div className="section-index">02 / SAME FROZEN WORKLOAD</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> 512×288 · 128 RAW SPP · SEVEN PASSES</p><h2>三个后端，<br/><span>同一组场景数据。</span></h2></div><p>qemu 数字复用已审计的 B49-R 父结果；native CPU 与 Metal 各有两个新的进程。速度比只描述这两个简单场景，不外推到 2K、4K 或角色镜头。</p></div><div className="b51-table" role="table" aria-label="B51 后端时间表"><div className="head" role="row"><span>SCENE</span><span>QEMU CPU</span><span>NATIVE CPU ×2</span><span>METAL ×2</span><span>WARM GAIN</span></div>{rows.map(row=><div className="row" role="row" key={row.scene}><b>{row.scene}<small>{row.note}</small></b><code>{row.qemu}</code><code>{row.cpu}</code><code>{row.metal}</code><strong>{row.warm}</strong></div>)}</div><div className="b51-speed-chain"><article><span>EVIDENCE WORKER</span><b>qemu CPU</b><strong>152–192 s</strong></article><i>≈ 37×</i><article><span>NATIVE CONTROL</span><b>4-thread CPU</b><strong>4.1–5.1 s</strong></article><i>≈ 7.17×</i><article className="active"><span>WARM CANDIDATE</span><b>40-core Metal</b><strong>0.57–0.72 s</strong></article></div></section>

    <section className="section b51-holdout" id="holdout"><div className="section-index">03 / FORMAL HOLDOUT</div><div className="contact-heading"><div><p className="eyebrow"><span/> CANARY PASS · IMAGE CONTRACT FAIL</p><h2>速度门通过。<br/><span>图像门拒绝。</span></h2></div><p>四个先验冻结、从未渲染过的构图分别接受一次 CPU 与两次 Metal。所有 warm 时间和 Metal 重复门通过，但跨后端 exact data passes 与一个 beauty 构图没有通过。</p></div><div className="b51-domain-grid"><article className="exact"><span>PRE-JOB CANARY</span><strong>0.14 s</strong><b>synchronization</b><p>0.396 s render · PASS</p></article><article><span>WARM METAL ×8</span><strong>0.53–0.75</strong><b>seconds / cell</b><p>all below 2.5 s</p></article><article className="mixed"><span>CPU ↔ METAL DATA</span><strong>4 / 4</strong><b>compositions fail exact</b><p>Depth + active Crypto</p></article><article className="mixed"><span>INTERIOR_CHAIR</span><strong>0.01260</strong><b>beauty NRMSE</b><p>frozen limit 0.0065</p></article></div><div className="contact-nonclaim"><b>NEGATIVE EVIDENCE IS THE RESULT</b><p>H1 的审计是 PASS，但 promotion 是 NOT SUPPORTED。审计只证明负结果可从冻结 EXR 与 receipt 精确重放，不会把失败变成成功。</p></div></section>

    <section className="section b51-pixels" id="pixels"><div className="section-index">04 / SAME-BACKEND ≠ CROSS-BACKEND</div><div className="contact-heading"><div><p className="eyebrow"><span/> REPEATABILITY BY PASS DOMAIN</p><h2>同后端可以全等。<br/><span>跨后端不能外推。</span></h2></div><p>D1/D2 证明 Metal 重复中的 Depth 与 Cryptomatte exact；H1 却证明 CPU–Metal 的这些 data passes 在四个未见构图中都不能满足同一个 exact 合同。两类命题必须分开。</p></div><div className="b51-domain-grid"><article className="exact"><span>NATIVE CPU ×2 · D1</span><strong>7 / 7</strong><b>decoded passes exact</b><p>same backend</p></article><article className="exact"><span>METAL ×2 · H1</span><strong>≈1e−7</strong><b>Combined repeat NRMSE</b><p>same backend tolerance pass</p></article><article className="mixed"><span>CPU ↔ METAL · H1</span><strong>0 / 4</strong><b>exact data contracts</b><p>all four compositions rejected</p></article><article><span>BEAUTY HOLDOUT</span><strong>3 / 4</strong><b>compositions pass</b><p>chair variant exceeds 3 limits</p></article></div><div className="contact-nonclaim"><b>PERCEPTION IS STILL OPEN</b><p>数值门失败不自动等于肉眼明显；但在空间定位和 data-pass 语义验证前，也不能把差异降格为“看不见所以没关系”。</p></div></section>

    <section className="section contact-limits b51-next" id="next"><div className="section-index">05 / NEXT FALSIFIABLE GATE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> LOCALIZE → SPLIT CONTRACT → RETEST</p><h2>不放宽失败门槛。<br/><span>先找到差异在哪里。</span></h2></div><p>B51-D3 将直接读取 H1 已保留的 EXR，不重渲染：定位 Depth/Crypto changed components 与 `INTERIOR_CHAIR` beauty outlier，再决定 beauty 与 data passes 是否必须分后端生产。</p></div><div className="b51-next-flow"><article><span>01</span><b>PASS LOCALIZATION</b><p>count · magnitude · edges</p></article><i>→</i><article><span>02</span><b>SPATIAL OUTLIER</b><p>chair beauty heatmap</p></article><i>→</i><article><span>03</span><b>SPLIT CONTRACT</b><p>beauty Metal · data CPU?</p></article><i>→</i><article><span>04</span><b>RE-HOLDOUT</b><p>stress remains blocked</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/native-metal-production-holdout-v0-1/results.json`}><span>H1 NEGATIVE RESULT</span><b>13 renders · 21 attacks ↗</b></a><a href={`${repo}experiments/native-metal-production-holdout-v0-1/audit.correction-v0.2.json`}><span>H1 AUDIT</span><b>negative evidence · replay exact ↗</b></a><a href={`${repo}specs/native-metal-production-holdout.v0.1.json`}><span>H1 FROZEN SPEC</span><b>canary · variants · thresholds ↗</b></a><a href={`${repo}research/2026-08-27-b51-h1-native-metal-production-holdout-result.md`}><span>RESULT NOTE</span><b>claims · failures · next fork ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B51 Native Backend Research</b></div><p>warm speed passed · image contract rejected · production blocked</p><Link href="/cost-model">回到成本模型 →</Link></footer>
  </main>;
}
