import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B51 原生 CPU × Metal 后端｜Blender Film Studio',
  description: '八次真实 Blender 5.2 原生 Cycles 渲染：约 37× qemu→native CPU、约 7.17× CPU→warm Metal，以及 108.31 秒冷同步反例。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/native-backend-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';

const rows = [
  { scene: 'TABLETOP', qemu: '151.992 s', cpu: '4.112 / 4.122 s', metal: '109.534 / 0.574 s', warm: '7.17×', note: 'first Metal is cold' },
  { scene: 'INTERIOR', qemu: '191.877 s', cpu: '5.090 / 5.029 s', metal: '0.717 / 0.695 s', warm: '7.17×', note: 'cache already warm' },
];

export default function NativeBackendPage() {
  return <main className="contact-page b51-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B51 导航"><Link href="/cost-model">成本</Link><Link href="/journal">实验日志</Link><a href="#timing">时间</a><a href="#cache">Cache 反证</a><a href="#pixels">像素</a><a href="#next">下一门</a></nav><span className="edition contact-edition">Native Backend B51</span></header>

    <section className="contact-hero b51-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> REAL BLENDER 5.2 · APPLE M4 MAX · CYCLES</p><h1><em>0.57 s</em> 之前，<br/>先发生了 <span>108.31 s。</span></h1><p>八个新的原生 Blender 进程证明 Metal 的热态吞吐非常快，也同时证明“第一次 GPU 渲染”和“后续 GPU 渲染”不是同一个成本问题。</p></div><aside className="contact-gate b51-gate"><b>DERIVATION VERDICT</b><strong>USABLE<br/>NOT PROMOTED</strong><code>8 / 8 real renders</code><code>14 / 14 attacks</code><small>audit replay · byte exact</small></aside><div className="contact-stats"><article><strong>≈37×</strong><span>qemu → native CPU</span><small>two scenes</small></article><article><strong>≈7.17×</strong><span>CPU → warm Metal</span><small>render operator</small></article><article><strong>108.31 s</strong><span>cold synchronization</span><small>first Metal cell</small></article><article><strong>74 MiB</strong><span>observed kernel cache</span><small>posthoc · 79 files</small></article></div></section>

    <section className="section b51-timing" id="timing"><div className="section-index">00 / COLD ≠ WARM</div><div className="contact-heading"><div><p className="eyebrow"><span/> ONE GPU · TWO COST REGIMES</p><h2>吞吐很快。<br/><span>启动状态决定账单。</span></h2></div><p>首次 TABLETOP Metal 的总 render operator 为 109.534 秒；EXR header 把其中 108.31 秒记为 Cycles synchronization。相同场景后续 Metal 只用 0.574 秒，其中 synchronization 为 0.13 秒。</p></div><div className="b51-timeline"><article className="cold"><header><span>METAL · FIRST OBSERVATION</span><b>109.534 s</b></header><div className="b51-bar"><i/><strong>108.31 s SYNC</strong><small>1.17 s render</small></div></article><article className="warm"><header><span>METAL · LATER PROCESS</span><b>0.574 s</b></header><div className="b51-bar"><i/><strong>0.13 s SYNC</strong><small>0.40 s render</small></div></article></div><div className="contact-nonclaim"><b>D1 OBSERVATION, NOT CAUSE</b><p>D1 只观察到首格极慢。B51-D2 随后对精确用户 Cycles cache 做了可逆干预，并否证该目录是 108.31 秒的充分原因。</p></div></section>

    <section className="section b51-cache" id="cache"><div className="section-index">01 / CACHE INTERVENTION</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> EXACT CACHE ABSENCE · ATOMIC RESTORE</p><h2>移走 74 MiB cache。<br/><span>108 秒没有回来。</span></h2></div><p>原 79-file tree 先做内容哈希，再原子移到同卷 quarantine。三个新 Blender 进程结束后，新 cache 被保留，原 cache 回到完全相同的 tree hash；没有删除或覆盖。</p></div><div className="b51-cache-cells"><article className="cold"><span>CACHE PATH ABSENT</span><strong>0.790 s</strong><b>0.34 s synchronization</b><small>75 files generated</small></article><article><span>GENERATED CACHE · R1</span><strong>0.578 s</strong><b>0.13 s synchronization</b><small>fresh Blender process</small></article><article><span>SAME CACHE · R2</span><strong>0.569 s</strong><b>0.13 s synchronization</b><small>fresh Blender process</small></article></div><div className="b51-cache-verdict"><span>FALSIFIED SUFFICIENT CAUSE</span><strong>≈ 0.21 s penalty ≠ 108.31 s event</strong><p>精确 `~/.cache/cycles` 缺失只带来 1.366× render 与 2.615× synchronization，比 D1 反例小两个数量级以上。剩余候选位于 OS / Metal / driver / host-session 层，目前没有被命名。</p></div><div className="b51-restore"><article><span>ORIGINAL</span><b>79 files · 77,737,584 B</b><code>fc6bc6f949f6…</code></article><i>→</i><article><span>RESTORED</span><b>CONTENT TREE EXACT</b><code>fc6bc6f949f6…</code></article><strong>PASS</strong></div></section>

    <section className="section b51-bench"><div className="section-index">02 / SAME FROZEN WORKLOAD</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> 512×288 · 128 RAW SPP · SEVEN PASSES</p><h2>三个后端，<br/><span>同一组场景数据。</span></h2></div><p>qemu 数字复用已审计的 B49-R 父结果；native CPU 与 Metal 各有两个新的进程。速度比只描述这两个简单场景，不外推到 2K、4K 或角色镜头。</p></div><div className="b51-table" role="table" aria-label="B51 后端时间表"><div className="head" role="row"><span>SCENE</span><span>QEMU CPU</span><span>NATIVE CPU ×2</span><span>METAL ×2</span><span>WARM GAIN</span></div>{rows.map(row=><div className="row" role="row" key={row.scene}><b>{row.scene}<small>{row.note}</small></b><code>{row.qemu}</code><code>{row.cpu}</code><code>{row.metal}</code><strong>{row.warm}</strong></div>)}</div><div className="b51-speed-chain"><article><span>EVIDENCE WORKER</span><b>qemu CPU</b><strong>152–192 s</strong></article><i>≈ 37×</i><article><span>NATIVE CONTROL</span><b>4-thread CPU</b><strong>4.1–5.1 s</strong></article><i>≈ 7.17×</i><article className="active"><span>WARM CANDIDATE</span><b>40-core Metal</b><strong>0.57–0.72 s</strong></article></div></section>

    <section className="section b51-pixels" id="pixels"><div className="section-index">03 / CONTAINER ≠ FLOATS</div><div className="contact-heading"><div><p className="eyebrow"><span/> REPEATABILITY BY PASS DOMAIN</p><h2>CPU 像素全等。<br/><span>Metal 有微小浮点漂移。</span></h2></div><p>CPU 两次的七个 decoded pass 都严格一致，但 EXR header 的日期与耗时使容器字节不同。Metal 在 Combined / Normal / Vector 上非 exact；Depth 与三个 Cryptomatte 层保持 exact。D2 的 cold/warm cache 干预没有改变这个域结构。</p></div><div className="b51-domain-grid"><article className="exact"><span>NATIVE CPU ×2</span><strong>7 / 7</strong><b>decoded passes exact</b><p>EXR bytes differ · timing metadata only</p></article><article className="mixed"><span>METAL ×2</span><strong>4 / 7</strong><b>pass domains exact</b><p>Depth + Crypto ×3 exact</p></article><article><span>TABLETOP METAL</span><strong>1.14e−5</strong><b>max Combined delta</b><p>95,039 changed components</p></article><article><span>INTERIOR METAL</span><strong>4.77e−7</strong><b>max Combined delta</b><p>109,410 changed components</p></article></div><div className="b51-domain-list"><div><span>PASS</span><b>CPU REPEAT</b><b>METAL REPEAT</b></div>{[['Combined','EXACT','NON-EXACT'],['Depth','EXACT','EXACT'],['Normal','EXACT','NON-EXACT'],['Vector','EXACT','NON-EXACT'],['Crypto ×3','EXACT','EXACT']].map(([pass,cpu,metal])=><div key={pass}><span>{pass}</span><b className="yes">{cpu}</b><b className={metal==='EXACT'?'yes':'no'}>{metal}</b></div>)}</div><div className="contact-nonclaim"><b>PERCEPTION IS STILL OPEN</b><p>CPU–Metal NRMSE 为 0.000238 / 0.003220，但没有为跨后端差异冻结人眼阈值。这里能说“数值很小且稀疏边界有较大单点”，不能说“肉眼绝对看不见”。</p></div></section>

    <section className="section contact-limits b51-next" id="next"><div className="section-index">04 / NEXT FALSIFIABLE GATE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> CANARY → HOLDOUT → STRESS</p><h2>不破坏 OS cache 追凶。<br/><span>把 readiness 变成合同。</span></h2></div><p>下一正式门先运行一个 Metal canary；只有 synchronization 进入 D2 warm 区间才开始计生产吞吐。未见帧负责验证数值容差，连续序列、热/功耗、角色毛发纹理内存和 macOS containment 分别立门。</p></div><div className="b51-next-flow"><article><span>01</span><b>PRE-JOB CANARY</b><p>sync readiness · fail closed</p></article><i>→</i><article><span>02</span><b>UNSEEN FRAMES</b><p>warm throughput · tolerance</p></article><i>→</i><article><span>03</span><b>LONG SEQUENCE</b><p>thermal · power · memory</p></article><i>→</i><article><span>04</span><b>WORKER HOST</b><p>containment · recovery</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/native-cycles-cache-state-derivation-v0-1/results.json`}><span>D2 RESULT</span><b>cold/warm · restore · 18 attacks ↗</b></a><a href={`${repo}experiments/native-cycles-cache-state-derivation-v0-1/audit.correction-v0.2.json`}><span>D2 AUDIT</span><b>cache safety · replay exact ↗</b></a><a href={`${repo}experiments/native-cycles-backend-derivation-v0-1/results.json`}><span>D1 RESULT</span><b>CPU × Metal × qemu ↗</b></a><a href={`${repo}research/2026-08-27-b51-d2-cycles-cache-state-derivation-result.md`}><span>RESULT NOTE</span><b>falsified cause · next gate ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B51 Native Backend Derivation</b></div><p>native Metal candidate · cold cache unresolved · not production promoted</p><Link href="/cost-model">回到成本模型 →</Link></footer>
  </main>;
}
