import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = {title:'B48 Blender 质量 × 成本 Holdout｜Blender Film Studio',description:'14 个真实 Blender 5.2 worker、两个未见帧、每帧三个独立 512-spp reference；选择唯一通过三指标 3× reference-floor 门的 128-spp raw 数值工作点。',alternates:{canonical:'https://lovejzzz.github.io/BlenderFilmStudio/quality-cost-holdout-v0-1/'}};
const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const cells=[
  ['32 RAW','NO','3.067 s','12.3 min','57.5 MB'],
  ['32 OIDN','NO','20.018 s','80.1 min','84.2 MB'],
  ['128 RAW','YES','10.998 s','44.0 min','61.9 MB'],
  ['128 OIDN','NO','27.948 s','111.8 min','88.6 MB'],
] as const;
const shots=[
  {id:'TABLETOP',frame:'37',ratios:[2.342,2.438,2.206],note:'128 RAW · PASS',files:['tabletop-c032-raw.png','tabletop-c032-oidn.png','tabletop-c128-raw.png','tabletop-c128-oidn.png','tabletop-ref-a.png']},
  {id:'INTERIOR',frame:'19',ratios:[1.767,1.771,2.066],note:'128 RAW · PASS',files:['interior-c032-raw.png','interior-c032-oidn.png','interior-c128-raw.png','interior-c128-oidn.png','interior-ref-a.png']},
] as const;
const labels=['32 RAW','32 OIDN','128 RAW · SELECTED','128 OIDN','512 RAW · REFERENCE'] as const;

export default function QualityCostHoldoutPage(){return <main className="contact-page b48-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B48 导航"><Link href="/journal">实验日志</Link><Link href="/codex-worker-production-passes-v0-1">B47 通道</Link><a href="#method">方法</a><a href="#holdouts">Holdout</a><a href="#cost">成本</a></nav><span className="edition contact-edition">Quality × Cost B48</span></header>
  <section className="contact-hero b48-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> THREE INDEPENDENT REFERENCES × TWO UNSEEN FRAMES</p><h1>我们没有猜最佳参数。<br/><span>证据选择了 128 RAW。</span></h1><p>14 个真实 Blender 5.2 Linux/amd64 worker。每个未见帧先用三个独立 512-spp realization 测出本地 Monte Carlo floor，再让 32/128 spp raw 与 OIDN 同时接受 linear、log-luminance、edge 三道数值门。</p></div><aside className="contact-gate b48-gate"><b>SELECTED OPERATING POINT</b><strong>128 SPP<br/>RAW</strong><code>2 / 2 holdouts passed</code><code>3 / 3 metrics each</code><small>18/18 ATTACKS · AUDIT MATCH</small></aside><div className="contact-stats"><article><strong>14</strong><span>全新 worker</span><small>14 real multipart EXRs</small></article><article><strong>3 × 2</strong><span>独立 reference</span><small>512 spp · new seeds</small></article><article><strong>10.998 s</strong><span>均值 render / frame</span><small>128 × 72 · CPU</small></article><article><strong>44.0 min</strong><span>240 帧机械投影</span><small>not a rendered shot</small></article></div></section>

  <section className="section b48-method" id="method"><div className="section-index">00 / FROZEN DECISION RULE</div><div className="contact-heading"><div><p className="eyebrow"><span/> REFERENCE FLOOR, NOT AN IMAGINARY GROUND TRUTH</p><h2>512 spp 也有噪声。<br/><span>先测地板，再测候选。</span></h2></div><p>D2 已证明三个独立 512-spp realization 彼此不同。正式 B48 因此不膜拜某一张“参考图”：每个 holdout 都从三张 reference 求 float64 均值，并把单张 reference 到均值的最大偏差定义为本地 floor。</p></div><div className="b48-method-flow"><article><span>01 · REFERENCE</span><strong>3 × 512</strong><code>three new seeds</code></article><i>→</i><article><span>02 · CALIBRATE</span><strong>MEAN + FLOOR</strong><code>linear · logY · edge</code></article><i>→</i><article><span>03 · TEST</span><strong>4 CELLS</strong><code>32/128 × raw/OIDN</code></article><i>→</i><article><span>04 · GATE</span><strong>≤ 3×</strong><code>every metric · every shot</code></article><i>→</i><article><span>05 · SELECT</span><strong>CHEAPEST</strong><code>measured render seconds</code></article></div></section>

  <section className="section b48-holdouts" id="holdouts"><div className="section-index">01 / REAL HOLDOUT FRAMES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ACES 2 DISPLAY PROXIES · NOT THE DECISION SURFACE</p><h2>一个高反差材质台。<br/><span>一个低噪室内场景。</span></h2></div><p>下列 PNG 从真实 multipart EXR 的 Combined 通道经固定 ACES 2 SDR view 导出，只供浏览。正式判决始终发生在 scene-linear float32 数据上。两场景的 reference floor 差异很大，因此必须各自校准。</p></div>{shots.map(shot=><article className="b48-shot" key={shot.id}><header><div><span>{shot.id} · FRAME {shot.frame}</span><b>{shot.note}</b></div><div className="b48-ratios"><code>LINEAR {shot.ratios[0]}×</code><code>LOGY {shot.ratios[1]}×</code><code>EDGE {shot.ratios[2]}×</code><small>LIMIT 3.000×</small></div></header><div className="b48-image-row">{shot.files.map((file,index)=><figure key={file} className={index===2?'selected':''}><Image src={`${basePath}/evidence/b48/${file}`} width={128} height={72} unoptimized alt={`${shot.id} ${labels[index]} real Blender render`}/><figcaption>{labels[index]}</figcaption></figure>)}</div></article>)}</section>

  <section className="section b48-matrix"><div className="section-index">02 / TWO-SHOT DECISION MATRIX</div><div className="contact-heading"><div><p className="eyebrow"><span/> NO METRIC COMPENSATION · NO SINGLE-SCENE PROMOTION</p><h2>OIDN 在室内通过。<br/><span>在材质台却被边缘与线性误差拒绝。</span></h2></div><p>去噪降低 log-luminance 误差，却可能用平滑偏差交换高光与边缘误差。32 OIDN 和 128 OIDN 都在 INTERIOR 通过，但 TABLETOP 的 linear/edge 超门；只有 128 RAW 跨过全部六个 shot×metric 关口。</p></div><div className="b48-candidate-grid"><article><span>C032 RAW</span><strong>0 / 2</strong><b>REJECT</b><small>fastest · outside floor</small></article><article><span>C032 OIDN</span><strong>1 / 2</strong><b>REJECT</b><small>TABLETOP bias</small></article><article className="selected"><span>C128 RAW</span><strong>2 / 2</strong><b>SELECTED</b><small>all six metric gates</small></article><article><span>C128 OIDN</span><strong>1 / 2</strong><b>REJECT</b><small>lowest logY · edge fail</small></article></div></section>

  <section className="section b48-cost" id="cost"><div className="section-index">03 / OBSERVED COST, LABELED PROJECTION</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> RENDER OPERATOR ≠ FRESH CONTAINER WALL</p><h2>最便宜不是采样最低。<br/><span>而是通过证据门的最低成本。</span></h2></div><p>OIDN 在当前 ARM64 macOS → Colima/qemu → Linux/amd64 worker 上有约 17 秒固定开销。240 帧数字只把两个 still-frame 的均值乘以 240；它不包含完整镜头的时间连续性、一次启动多帧的摊销，也不是 2K/4K 或云端报价。</p></div><ol className="b48-cost-table"><li className="head"><span>CELL</span><b>ELIGIBLE</b><code>MEAN RENDER / FRAME</code><small>240-FRAME RENDER</small><i>EXR PROJECTION</i></li>{cells.map(([id,eligible,frame,shot,size])=><li key={id} className={eligible==='YES'?'selected':''}><span>{id}</span><b>{eligible}</b><code>{frame}</code><small>{shot}</small><i>{size}</i></li>)}</ol><div className="b48-cost-callout"><span>SELECTED · 128 RAW</span><strong>2,639 s</strong><b>≈ 44.0 MINUTES / 240 FRAMES</b><small>128 × 72 · render-operator-only projection · 61.9 MB EXR</small></div></section>

  <section className="section contact-limits"><div className="section-index">04 / CLAIM BOUNDARY</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> NUMERICAL OPERATING POINT ≠ CINEMATIC QUALITY</p><h2>现在知道从哪里起跑。<br/><span>还没有抵达电影成片。</span></h2></div><p>B48 只选择了两个 128×72 still holdout 上的 bounded numerical point。B49 必须分别扩大空间分辨率，并介入 motion blur、depth of field 等电影特性，测时间、内存、输出与质量缩放；最后仍需匿名人类审片，才能讨论“电影感”。</p></div><div className="b48-next"><span>NEXT EVIDENCE GAP</span><strong>B49</strong><div><b>RESOLUTION</b><i>+</i><b>MOTION BLUR</b><i>+</i><b>DOF</b><i>→</i><b>HUMAN REVIEW</b></div></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-worker-quality-cost-holdout-v0-1/results.json`}><span>MACHINE RESULT</span><b>14 workers · selected 128 raw ↗</b></a><a href={`${repo}experiments/codex-worker-quality-cost-holdout-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>byte-exact replay · 18/18 ↗</b></a><a href={`${repo}research/2026-08-26-b48-codex-worker-quality-cost-holdout-result.md`}><span>RESULT NOTE</span><b>claims · projections · limits ↗</b></a><a href={`${repo}research/2026-08-26-b48-codex-worker-quality-cost-holdout-protocol.md`}><span>PREREGISTRATION</span><b>frozen before formal tools ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B48 Quality × Cost Holdout</b></div><p>three-reference floor · two unseen frames · measured worker cost</p><Link href="/journal">回到实验日志 →</Link></footer>
</main>}
