import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const transitions = [
  { id: '74→75', q4: 1.437742, q8: 0.849566, q8q4: 0.590903 },
  { id: '75→76', q4: 1.439159, q8: 1.039666, q8q4: 0.722412 },
  { id: '76→77', q4: 1.545165, q8: 0.954210, q8q4: 0.617546 },
  { id: '77→78', q4: 1.610238, q8: 0.947158, q8q4: 0.588210 },
  { id: '78→79', q4: 1.678874, q8: 0.957199, q8q4: 0.570144 },
  { id: '79→80', q4: 1.755794, q8: 0.957653, q8q4: 0.545424 },
  { id: '80→81', q4: 1.775566, q8: 0.942129, q8q4: 0.530608 },
];
const domains = [
  { id: 'GLOBAL', q4: 1.314448, q8: 0.823073, q8Max: 0.885587, gate: 1.0, q8q4: 0.628862 },
  { id: 'SPATIAL EDGE', q4: 1.512700, q8: 0.902252, q8Max: 0.983237, gate: 1.1, q8q4: 0.599985 },
  { id: 'REFERENCE MOTION', q4: 1.606077, q8: 0.949654, q8Max: 1.039666, gate: 1.1, q8q4: 0.595035 },
];
const chartX = (index: number) => 64 + index * 104;
const chartY = (value: number) => 244 - ((value - 0.7) / 1.2) * 204;
const line = (key: 'q4' | 'q8') => transitions.map((item, index) => `${chartX(index)},${chartY(item[key]).toFixed(2)}`).join(' ');

export const metadata: Metadata = {
  title: 'B33 Q8 连续帧时间代理验证｜Blender Film Studio',
  description: '用 28 个新 Blender PID、224 个 EXR 和预注册三域 temporal-error 协议，验证 Q8 的连续帧 near-natural proxy 与 Q4 dominance。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/quadrature-temporal-holdout-v0-1/' },
};

export default function QuadratureTemporalHoldoutPage() {
  return <main className="contact-page factorial-page quadrature-page temporal-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B33 导航"><Link href="/journal">实验日志</Link><Link href="/quadrature-cost-holdout-v0-2">B32 静态</Link><a href="#metric">定义</a><a href="#holdout">正式结果</a><a href="#margin">边界</a><a href="#claims">结论</a></nav><span className="edition contact-edition">Temporal 0.1</span></header>

    <section className="contact-hero temporal-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B33 · CONSECUTIVE-FRAME HOLDOUT</p><h1>静态稳定还不够。<br/><span>Q8 连续帧也过门。</span></h1><p>我们没有直接比较相邻画面，而是比较候选方法相对 dual-1024 reference proxy 的误差如何随帧改变。Q8 在八个新连续 frame 上通过 near-natural 与 Q4-dominance 门；一个 transition 明确逼近边界。</p></div><aside className="contact-gate temporal-gate"><b>PRE-REGISTERED DECISION</b><strong>Q8 TEMPORAL<br/>PROXY SUPPORT</strong><code>28 PIDs · 224 EXR</code><code>12 / 12 ATTACKS</code><small>VISIBLE FLICKER · NOT CLAIMED</small></aside><div className="contact-stats"><article><strong>0.9497×</strong><span>Q8 / NATURAL motion mean</span><small>maximum · 1.0397×</small></article><article><strong>1.6061×</strong><span>Q4 / NATURAL motion mean</span><small>maximum · 1.7756×</small></article><article><strong>7.996×</strong><span>Q8 render-time ratio</span><small>Q4 · 4.009×</small></article><article><strong>0</strong><span>Q4/Q8 A/B RMSE</span><small>frame + transition exact</small></article></div></section>

    <section className="section temporal-metric" id="metric"><div className="section-index">00 / 先把“闪烁”问题写对</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> SHARED MOTION MUST CANCEL</p><h2>画面在动，<br/><span>不等于误差在闪。</span></h2></div><p>真实摄影机与物体运动会让相邻帧天然不同。因此先计算每种方法相对参考的误差，再观察这个误差的 frame-to-frame delta。它是可证伪数值代理，仍不是人眼可见性判断。</p></div><div className="temporal-equation-flow"><article><span>01 · REFERENCE</span><strong>R<sub>t</sub></strong><p>REFERENCE1024 A/B<br/>pixelwise mean</p></article><i>→</i><article><span>02 · ERROR</span><strong>E<sub>m,t</sub></strong><p>I<sub>m,t</sub> − R<sub>t</sub></p></article><i>→</i><article className="focus"><span>03 · TEMPORAL DELTA</span><strong>D<sub>m,t</sub></strong><p>E<sub>m,t</sub> − E<sub>m,t−1</sub></p></article></div><div className="temporal-domains"><article><b>GLOBAL</b><span>518,400 pixels</span><p>不允许局部选择掩盖全画面偏差。</p></article><article><b>SPATIAL EDGE UNION</b><span>two exact top-k masks</span><p>追踪相邻两帧高梯度区域的并集。</p></article><article><b>REFERENCE MOTION TOP-K</b><span>exactly 25,920 pixels</span><p>聚焦参考画面变化最大的 5% 像素。</p></article></div></section>

    <section className="section temporal-result" id="holdout"><div className="section-index light">01 / 七个 transition，逐一过门</div><div className="contact-heading"><div><p className="eyebrow"><span/> REFERENCE-MOTION TOP-K</p><h2>Q4 仍在上方。<br/><span>Q8 围绕 NATURAL。</span></h2></div><p>下图只展示最接近“运动中边缘变化”的 reference-motion 域。黑线是 NATURAL32 基准 1.0；虚线是 Q8 的预注册 1.10 门。正式判定同时要求 global 与 spatial-edge 域全部通过。</p></div><div className="temporal-line-wrap"><svg viewBox="0 0 760 300" role="img" aria-label="Frame 74 to 81 reference-motion temporal error ratios: Q4 above natural, Q8 near natural and below its 1.10 gate"><g className="grid">{[0.8,1.0,1.2,1.4,1.6,1.8].map(value=><g key={value}><line x1="48" y1={chartY(value)} x2="712" y2={chartY(value)}/><text x="8" y={chartY(value)+4}>{value.toFixed(1)}</text></g>)}</g><line className="natural-line" x1="48" y1={chartY(1)} x2="712" y2={chartY(1)}/><line className="gate-line" x1="48" y1={chartY(1.1)} x2="712" y2={chartY(1.1)}/><polyline className="q4-line" points={line('q4')}/><polyline className="q8-line" points={line('q8')}/>{transitions.map((item,index)=><g key={item.id}><circle className="q4-dot" cx={chartX(index)} cy={chartY(item.q4)} r="5"/><circle className="q8-dot" cx={chartX(index)} cy={chartY(item.q8)} r="5"/><text className="x-label" x={chartX(index)} y="282" textAnchor="middle">{item.id}</text></g>)}</svg><div className="temporal-legend"><span><i className="q4"/> Q4 / NATURAL</span><span><i className="q8"/> Q8 / NATURAL</span><span><i className="natural"/> NATURAL = 1.0</span><span><i className="gate"/> Q8 GATE = 1.10</span></div></div><div className="temporal-domain-cards">{domains.map(item=><article key={item.id}><header><span>{item.id}</span><b>Q8 MAX {item.q8Max.toFixed(3)} / {item.gate.toFixed(2)}</b></header><div><small>N</small><i style={{width:'55.56%'}}/><strong>1.000</strong></div><div><small>Q4</small><i className="q4" style={{width:`${item.q4/1.8*100}%`}}/><strong>{item.q4.toFixed(3)}</strong></div><div><small>Q8</small><i className="q8" style={{width:`${item.q8/1.8*100}%`}}/><strong>{item.q8.toFixed(3)}</strong></div><footer>Q8 / Q4 MEAN · {item.q8q4.toFixed(3)} ≤ 0.65</footer></article>)}</div></section>

    <section className="section temporal-margin" id="margin"><div className="section-index">02 / PASS 也要报告离失败有多近</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> HOLDOUT CONSUMED THE MARGIN</p><h2>75→76 没有失败。<br/><span>但它差一点。</span></h2></div><p>新区间没有复制派生区间的漂亮数字。最弱 transition 同时抬高 motion Q8/NATURAL 和 global Q8/Q4。它是支持结论的一部分，也是下一次跨镜头复制最值得攻击的边界。</p></div><div className="temporal-margin-grid"><article><span>MOTION · Q8 / NATURAL</span><strong>1.03967</strong><div><i style={{width:`${1.039666/1.1*100}%`}}/></div><footer><b>GATE 1.10</b><small>margin · 0.06033</small></footer></article><article className="near"><span>GLOBAL · Q8 / Q4</span><strong>0.73856</strong><div><i style={{width:`${0.738561/0.75*100}%`}}/></div><footer><b>GATE 0.75</b><small>margin · 0.01144</small></footer></article><article><span>GLOBAL · Q8 / Q4 MEAN</span><strong>0.62886</strong><div><i style={{width:`${0.628862/0.65*100}%`}}/></div><footer><b>GATE 0.65</b><small>margin · 0.02114</small></footer></article></div><div className="contact-nonclaim"><b>COUNTEREXAMPLE VALUE</b><p>Q4 是本轮最有用的负向观察：约四倍 render 并没有自动改善 temporal proxy，三个域的 mean 都高于 NATURAL。更多确定性 component 只有覆盖设计足够时才可能换来更好的时间误差。</p></div></section>

    <section className="section temporal-cost"><div className="section-index light">03 / 时间质量也有明确价格</div><div className="contact-heading"><div><p className="eyebrow"><span/> SAME MACHINE · BLENDER TIMERS</p><h2>Q8 接近 NATURAL proxy。<br/><span>成本仍是八次 render。</span></h2></div><p>这里的秒数只含 Blender 自报 render timer，不含进程启动、磁盘 I/O、scene-linear 合成与编码。它说明工程 trade-off，不是普遍价格。</p></div><div className="temporal-cost-grid"><article><span>NATURAL32</span><strong>2.671 s</strong><i style={{width:'12.5%'}}/><b>1.000× TIME</b><small>active control · non-exact A/B possible</small></article><article className="q4"><span>Q4</span><strong>10.708 s</strong><i style={{width:'50.16%'}}/><b>4.009× TIME</b><small>exact · temporal proxy worse than NATURAL</small></article><article className="q8"><span>Q8</span><strong>21.354 s</strong><i style={{width:'100%'}}/><b>7.996× TIME</b><small>exact · formal near-natural proxy support</small></article></div></section>

    <section className="section contact-limits temporal-claims" id="claims"><div className="section-index">04 / 能说与不能说</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> TEMPORAL PROXY ≠ HUMAN CINEMA</p><h2>数值时间门成立。<br/><span>观众结论仍未成立。</span></h2></div><p>B33 把 B32 的静态曲线推进到连续帧，但 motion blur 关闭，REFERENCE1024 不是 ground truth，也没有独立观察者。下一步必须把匿名片段交给人，而不是继续让 analyzer 冒充观众。</p></div><div className="contact-checks"><article><span>SUPPORTED</span><h3>Exact ensemble</h3><p>Q4/Q8 frame 与 temporal delta A/B float exact。</p><b>FORMAL</b></article><article><span>SUPPORTED</span><h3>Q8 temporal proxy</h3><p>八帧新区间、三域、全部预写门通过。</p><b>FORMAL</b></article><article><span>CAUTION</span><h3>Near boundary</h3><p>75→76 的 global dominance 距失败只剩 0.01144。</p><b>REPLICATE</b></article><article><span>OPEN</span><h3>Human cinema gate</h3><p>可见 flicker、偏好与电影感尚无独立观察者数据。</p><b>NEXT</b></article></div><div className="contact-artifacts"><a href={`${repo}experiments/quadrature-temporal-holdout-v0-1/results.json`}><span>FORMAL RESULT</span><b>224 renders · 12 attacks ↗</b></a><a href={`${repo}experiments/quadrature-temporal-holdout-v0-1/evidence/temporal-analysis.json`}><span>FULL ANALYSIS</span><b>7 transitions · 3 domains ↗</b></a><a href={`${repo}specs/quadrature-temporal-holdout-spec.v0.1.json`}><span>FROZEN SPEC</span><b>frames · equations · gates ↗</b></a><a href={`${repo}experiments/quadrature-temporal-derivation-v0-1/results.json`}><span>DERIVATION</span><b>threshold evidence basis ↗</b></a><a href={`${repo}research/2026-08-26-b33-quadrature-temporal-holdout-result.md`}><span>RESULT NOTE</span><b>margins · costs · nonclaims ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B33 Consecutive-frame Holdout</b></div><p>static + temporal proxy supported · human cinema gate pending</p><Link href="/human-quadrature-review-v0-1">查看 B34 正式盲评包 →</Link></footer>
  </main>;
}
