import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const frames = [
  {frame:10,natural:.00890651,center:.02550486,edge:2.863620,global:1.558080,nonEdge:1.088556,reliability:0},
  {frame:44,natural:.01195950,center:.02836478,edge:2.371738,global:1.513320,nonEdge:1.076749,reliability:.00045276},
  {frame:86,natural:.01321538,center:.02866781,edge:2.169276,global:1.400454,nonEdge:1.084944,reliability:0},
  {frame:120,natural:.01451588,center:.03591649,edge:2.474289,global:1.459338,nonEdge:1.090715,reliability:.00055488},
];

export const metadata: Metadata = {
  title: 'B31 固定抖动采样质量代价｜Blender Film Studio',
  description: '四个未见 frame、六个真实 Blender PID、24 个 EXR：CENTER32 的 edge-reference RMSE 是 NATURAL32 的 2.17–2.86 倍；reference reliability 4/4 通过。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/sampling-quality-holdout-v0-1/' },
};

export default function SamplingQualityHoldoutPage(){return <main className="contact-page factorial-page quality-cost-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B31 导航"><Link href="/journal">实验日志</Link><Link href="/fixed-jitter-intervention-v0-1">B30</Link><a href="#design">设计</a><a href="#result">结果</a><a href="#tradeoff">权衡</a><a href="#next">下一步</a></nav><span className="edition contact-edition">Quality Cost 0.1</span></header>

  <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B31 · SCENE-LINEAR QUALITY-PROXY HOLDOUT</p><h1>稳定是真的。<br/><span>边缘代价也是真的。</span></h1><p>B30 的 CENTER 单点能锁住输出；B31 在四个未见 frame 上验证它离双 1024-sample reference proxy 更远。每帧 edge RMSE 都超过 NATURAL32 的 2.16×，而 reference A/B 自身差异远低于冻结可靠性门。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>EDGE COST<br/>SUPPORT</strong><code>HOLDOUT · 4 / 4 ≥ 1.5×</code><code>MINIMUM · 2.1693×</code><small>PERCEPTUAL CLAIM · NOT TESTED</small></aside><div className="contact-stats"><article><strong>4/4</strong><span>未见 frame 通过</span><small>10 · 44 · 86 · 120</small></article><article><strong>24</strong><span>真实 EXR renders</span><small>6 unique Blender PID</small></article><article><strong>23/23</strong><span>攻击测试</span><small>all intended reasons</small></article><article><strong>2.4697×</strong><span>edge ratio 均值</span><small>not a visibility multiplier</small></article></div></section>

  <section className="section contact-verdict" id="design"><div className="section-index">00 / 参考先证明可靠</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> DUAL NATURAL1024 PROXY</p><h2>不是把高 sample，<br/><span>偷偷叫作 ground truth。</span></h2></div><p>两个独立 NATURAL1024 PID 的逐像素平均只被称为 reference proxy。每帧先验证 A/B edge RMSE 不超过 NATURAL32 error 的 5%，再允许比较 CENTER。它没有空间超采样，也不是视觉系统。</p></div><div className="blind-flow quality-flow"><article><span>REFERENCE A</span><b>NATURAL1024</b><small>fresh Blender PID</small></article><i>+</i><article><span>REFERENCE B</span><b>NATURAL1024</b><small>fresh Blender PID</small></article><i>→</i><article><span>EDGE MASK</span><b>top 5%</b><small>RGB gradient · 25,920 px</small></article><i>→</i><article><span>COMPARE</span><b>N32 × C32</b><small>two PID each</small></article></div><div className="quality-reference-grid">{frames.map(item=><article key={item.frame}><span>FRAME {item.frame}</span><strong>{item.reliability===0?'0':item.reliability.toFixed(6)}</strong><b>reference reliability ratio</b><i style={{width:`${Math.max(item.reliability/.05*100,.4)}%`}}/><small>frozen ceiling · 0.05</small></article>)}</div></section>

  <section className="section contact-evidence" id="result"><div className="section-index light">01 / 四帧逐一门禁</div><div className="contact-heading"><div><p className="eyebrow"><span/> NO AVERAGE CAN HIDE A FRAME</p><h2>最小值 2.1693×。<br/><span>仍高于冻结门 1.5×。</span></h2></div><p>支持要求四个 holdout frame 全部 ≥1.5；任一 frame &lt;1.0 会优先判方向反转。观察值 2.8636、2.3717、2.1693、2.4743，没有 mixed 或 reversed frame。</p></div><div className="quality-ratio-chart">{frames.map(item=><article key={item.frame}><header><span>FRAME {item.frame}</span><strong>{item.edge.toFixed(4)}×</strong></header><div className="quality-threshold"><i style={{width:`${1.5/3*100}%`}}/><small>1.5× gate</small></div><div className="quality-observed"><i style={{width:`${item.edge/3*100}%`}}/></div><footer><code>N · {item.natural.toFixed(6)}</code><code>C · {item.center.toFixed(6)}</code></footer></article>)}</div><div className="diagnostic-verdict"><b>FROZEN DECISION</b><code>EDGE_REFERENCE_COST_SUPPORT</code><p>独立 factory-startup analyzer 重跑与正式 analysis 字节一致。结论对象是 scene-linear、top-5% gradient ROI 相对稳定 proxy 的 RMSE，不是肉眼质量倍率。</p></div></section>

  <section className="section contact-diagnostic" id="tradeoff"><div className="section-index">02 / 两个结论必须共存</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> REPEATABILITY × REFERENCE ERROR</p><h2>更确定，<br/><span>不等于更接近高采样结果。</span></h2></div><p>CENTER32 A/B 在四帧全部 float exact；同一组输出的 edge-reference error 又显著更大。用“可复现”替代“高质量”，或用“误差更大”否定它的稳定性，都是对数据的删减。</p></div><div className="quality-tradeoff"><article><span>B30 · REPEATABILITY</span><strong>144 / 144</strong><b>CENTER decoded identity</b><p>12 个独立 PID 严格一致</p><small>SUPPORTED</small></article><article><span>B31 · EDGE PROXY</span><strong>2.17–2.86×</strong><b>CENTER / NATURAL RMSE</b><p>四个未见 frame 逐一通过</p><small>COST SUPPORTED</small></article><article><span>HUMAN / TEMPORAL</span><strong>PENDING</strong><b>visibility · aliasing · cinema</b><p>机器数值不能替代观察者</p><small>NO CLAIM</small></article></div><div className="quality-domain-table"><header><span>DOMAIN</span><span>MIN RATIO</span><span>MAX RATIO</span><span>INTERPRETATION</span></header><article><b>edge top 5%</b><span>2.1693×</span><span>2.8636×</span><small>largest relative cost</small></article><article><b>global</b><span>1.4005×</span><span>1.5581×</span><small>whole-frame numeric error</small></article><article><b>non-edge</b><span>1.0767×</span><span>1.0907×</span><small>smaller relative cost</small></article></div></section>

  <section className="section contact-limits" id="next"><div className="section-index">03 / 下一工程候选</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> DETERMINISTIC MULTI-JITTER ENSEMBLE</p><h2>不再锁一个点。<br/><span>用多个稳定点重建覆盖。</span></h2></div><p>B32 将探索 4-point / 8-point fixed-offset renders，在 scene-linear 域按预注册权重合成。目标是同时保留 exact repeatability、降低 edge-reference error，并显式记录 4×/8× render cost；候选点先 derivation，未见帧再 holdout。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/sampling-quality-holdout-v0-1/results.json`}><span>RESULT</span><b>24 EXR · 23 attacks ↗</b></a><a href={`${repo}experiments/sampling-quality-holdout-v0-1/evidence/quality-analysis.json`}><span>ANALYSIS</span><b>four frames · all metrics ↗</b></a><a href={`${repo}specs/sampling-quality-holdout-spec.v0.1.json`}><span>FROZEN SPEC</span><b>proxy · ROI · precedence ↗</b></a><a href={`${repo}research/2026-08-26-b31-sampling-quality-holdout-protocol.md`}><span>PROTOCOL</span><b>unseen-frame holdout ↗</b></a><a href={`${repo}research/2026-08-26-b31-sampling-quality-holdout-result.md`}><span>RESULT NOTE</span><b>claims · boundaries ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B31 Sampling-Quality Cost</b></div><p>Repeatability supported · edge-reference cost supported · perception open</p><Link href="/research-agenda">进入 B32 multi-jitter ensemble →</Link></footer>
</main>}
