import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const mediaBase = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio/eevee-gi-reprojection-factorial-v0-1' : '/eevee-gi-reprojection-factorial-v0-1';
export const metadata: Metadata = {
  title: 'B19 Fast GI × TAA Reprojection｜Blender Film Studio',
  description: '真实 Blender 2×2 实验：Fast GI 与 TAA temporal reprojection 单独或同时关闭都未恢复严格像素复现；14/14 攻击通过。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/eevee-gi-reprojection-factorial-v0-1/' },
};
const attacks = [
  ['N01','factorial spec','FACTORIAL_SPEC_SHA'],['N02','ReviewRenderSpec','REVIEW_SPEC_SHA'],['N03','renderer','RENDERER_SHA'],['N04','comparator','COMPARATOR_SHA'],
  ['N05','configurator','CONFIGURATOR_SHA'],['N06','fixed dither','FIXED_DITHER'],['N07','Fast GI observation','FAST_GI'],['N08','reprojection observation','TAA_REPROJECTION'],
  ['N09','render samples','RENDER_SAMPLES'],['N10','run alias','ALIAS_RUNS'],['N11','missing frame','MISSING_FRAME'],['N12','extra frame','EXTRA_FRAME'],
  ['N13','frame bytes','FRAME_SHA'],['N14','comparison binding','COMPARISON_SEQUENCE_BINDING'],
];

export default function GiReprojectionFactorialPage() {
  return <main className="contact-page gi-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B19 导航"><Link href="/journal">实验日志</Link><Link href="/eevee-sampling-dose-response-v0-1">B18</Link><a href="#matrix">因子矩阵</a><a href="#evidence">画面</a><a href="#next">下一变量</a></nav><span className="edition contact-edition">GI × Reprojection 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B19 · REAL-BLENDER 2×2 ISOLATION</p><h1>关 GI，也关 temporal。<br /><span>漂移仍然存在。</span></h1><p>Fast GI on/off × TAA reprojection on/off，四个 cell 各 A/B 两条完整 144 帧序列；固定 32 samples、dither 0。所有组合都没有达到零容差 exact。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>NO SUFFICIENT<br />INTERVENTION</strong><code>all 4 cells · non-exact</code><code>max error · ≈ 1/255</code><small>14 / 14 ATTACKS PASS</small></aside><div className="contact-stats"><article><strong>2×2</strong><span>完整因子</span><small>GI × reprojection</small></article><article><strong>8</strong><span>净运行</span><small>1,152 real frames</small></article><article><strong>0/4</strong><span>exact cells</span><small>no favorable switch</small></article><article><strong>14/14</strong><span>负向攻击</span><small>stable reasons</small></article></div></section>
    <section className="section contact-verdict" id="matrix"><div className="section-index">00 / 因子矩阵</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> 32 SAMPLES · DITHER 0 · ZERO TOLERANCE</p><h2>两个合理候选，<br /><span>都不是充分答案。</span></h2></div><p>控制清单证明它们实际启用，但只有干预实验能谈因果。四个 cell 全失败，因此不能把 Blender RNA 的“GI ray”或“temporal denoise”描述当成根因。</p></div><div className="factorial-matrix"><article className="factorial-nonexact"><span>G1-R1</span><strong>131/144</strong><b>GI on · temporal on</b><small>97 failed pixels</small></article><article className="factorial-nonexact"><span>G0-R1</span><strong>135/144</strong><b>GI off · temporal on</b><small>50 failed pixels</small></article><article className="factorial-nonexact"><span>G1-R0</span><strong>133/144</strong><b>GI on · temporal off</b><small>96 failed pixels</small></article><article className="factorial-nonexact"><span>G0-R0</span><strong>131/144</strong><b>GI off · temporal off</b><small>73 failed pixels</small></article></div><div className="diagnostic-verdict"><b>DECISION</b><code>NO_SUFFICIENT_INTERVENTION</code><p>一个 cell 的差异像素更少并不是预注册的通过门，也不是可靠效果估计。两次随机序列不足以比较概率或均值。</p></div></section>
    <section className="section contact-evidence" id="evidence"><div className="section-index light">01 / 视觉 witness</div><div className="contact-heading"><div><p className="eyebrow"><span /> SAME FRAME 72 · ON/ON VS OFF/OFF</p><h2>肉眼几乎相同。<br /><span>像素门仍然失败。</span></h2></div><p>同一帧的 on/on 与 off/off witness 没有显著肉眼差别，但两组完整 A/B 都非 exact。页面不把一张代表帧冒充全序列证据。</p></div><div className="factorial-gallery"><figure><Image src={`${mediaBase}/G1-R1-frame-0072.png`} alt="B02 第72帧，Fast GI 与 TAA reprojection 均开启" width={960} height={540} sizes="(max-width: 700px) 100vw, 50vw" /><figcaption><span>G1-R1 · FRAME 0072</span><b>Fast GI on · temporal on</b><small>131/144 exact</small></figcaption></figure><figure><Image src={`${mediaBase}/G0-R0-frame-0072.png`} alt="B02 第72帧，Fast GI 与 TAA reprojection 均关闭" width={960} height={540} sizes="(max-width: 700px) 100vw, 50vw" /><figcaption><span>G0-R0 · FRAME 0072</span><b>Fast GI off · temporal off</b><small>131/144 exact</small></figcaption></figure></div><div className="contact-nonclaim"><b>NON-CLAIM</b><p>B19 只证明这两个公开开关不是充分修复；它没有证明它们对差异概率毫无影响，也没有证明隐藏 seed、GPU 调度或帧历史中的任何一个机制。</p></div></section>
    <section className="section contact-diagnostic"><div className="section-index">02 / 对抗验证</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> FOURTEEN STABLE REASONS</p><h2>源状态、两个开关与比较，<br /><span>全部反向绑定。</span></h2></div><p>每次运行先验证源值，再显式设置 dither、GI 与 reprojection；攻击覆盖工具、变量观察、采样数、目录、帧与比较绑定。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,result]) => <li key={id}><span>{id}</span><b>{item}</b><small>{result}</small></li>)}</ol></section>
    <section className="section contact-limits" id="next"><div className="section-index">03 / 下一可证伪边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> PROCESS HISTORY · FRESH FRAME PROCESS</p><h2>下一步重置进程历史，<br /><span>而不是继续关画质功能。</span></h2></div><p>B15–B19 都在一个 Blender 进程里顺序渲染 144 帧。下一实验应预注册高复发 sentinel frames，对比同进程重复与每帧新进程，隔离帧历史/renderer state 与跨进程 GPU 求值。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/eevee-gi-reprojection-factorial-v0-1/results.json`}><span>RESULT</span><b>4 cells · 14 attacks ↗</b></a><a href={`${repo}experiments/eevee-gi-reprojection-factorial-v0-1/evidence/G0-R0.sequence.comparison.json`}><span>DOUBLE OFF</span><b>144 OIIO pairs ↗</b></a><a href={`${repo}research/2026-08-26-b19-gi-reprojection-factorial-result.md`}><span>RESULT NOTE</span><b>falsified candidates ↗</b></a><a href={`${repo}research/2026-08-26-eevee-control-inventory.md`}><span>RNA INVENTORY</span><b>candidate basis ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B19 GI × Reprojection Factorial</b></div><p>Two enabled candidates · neither sufficient</p><Link href="/research-agenda">继续隔离 →</Link></footer>
  </main>;
}
