import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = { title: 'B10 路径安全｜Restricted compiler｜Blender Film Studio', description: '对 SceneSpec 与 BuildPlan 执行符号链接逃逸攻击，公开首轮失败、修复和回归证据。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/security-v0-1/' } };
const attacks = [
  ['N01','asset symlink','BUILD PLAN READ','REJECTED'],['N02','SceneSpec symlink','INPUT READ','REJECTED'],['N03','provenance symlink','SOURCE READ','REJECTED'],['N04','TrajectorySpec symlink','DATA READ','REJECTED'],
  ['N05','output-root symlink','PLANNED WRITE','REJECTED'],['N06','CLI output outside','DIRECT WRITE','REJECTED'],['N07','lexical traversal','SCHEMA','REJECTED'],['N08','network access','SCHEMA','REJECTED'],
];

export default function SecurityV01Page() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B10 导航"><Link href="/trajectory-v0-2">B08 编译</Link><Link href="/research-agenda">研究路线</Link><a href="#attack">攻击</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Security 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B10 · ADVERSARIAL PATH AUDIT</p><h1>字符串在 repo 内，<br /><span>文件不一定在。</span></h1><p>首轮攻击证明：allowed path 下的符号链接可以让 JavaScript 编译阶段读取外部文件，或把输出指向外部目录。我们保留这次失败，再把真实路径检查移到任何读取与写入之前。</p></div><aside className="contact-gate"><b>CURRENT STATUS</b><strong>FORMAL B10<br />TRUE</strong><code>first run: 6 vulnerabilities</code><code>after fix: 0 / 8 escaped</code><small>harmless temporary fixtures only</small></aside><div className="contact-stats"><article><strong>6</strong><span>首轮逃逸成功</span><small>failure evidence retained</small></article><article><strong>8 / 8</strong><span>修复后拒绝</span><small>read + planned write</small></article><article><strong>0</strong><span>剩余已知逃逸</span><small>in frozen corpus</small></article><article><strong>2 / 2</strong><span>关键回归保持</span><small>B05 + B08</small></article></div></section>
    <section className="section contact-verdict"><div className="section-index">00 / 威胁模型</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> LEXICAL PATH ≠ REAL PATH</p><h2>权限检查必须发生在<br /><span>真实文件身份上。</span></h2></div><p>Schema 能识别 `..`、绝对路径和联网请求，却不能看见文件系统里的 symlink。摘要计算会跟随链接，因此只检查字符串并不足以建立数据边界。</p></div><div className="contact-flow"><article><span>01</span><b>DECLARED PATH</b><p>library/props/input.blend</p></article><i>→</i><article><span>02</span><b>REALPATH</b><p>/tmp/external.blend</p></article><i>→</i><article><span>03</span><b>STOP BEFORE READ</b><p>outside repository</p></article></div></section>
    <section className="section contact-diagnostic" id="attack"><div className="section-index">01 / 攻击矩阵</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> SAME CORPUS · BEFORE AND AFTER</p><h2>不是“应该安全”，<br /><span>而是逐条攻击。</span></h2></div><p>N01–N06 首轮都发出了 BuildPlan 或外部写入；修复后同一语料在读取/写入之前被拒绝。N07–N08 从一开始就由 Schema 拦截。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,layer,result]) => <li key={id}><span>{id}</span><b>{item}</b><code>{layer}</code><small>{result}</small></li>)}</ol></section>
    <section className="section contact-contract"><div className="section-index">02 / 修复合同</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> RESOLVE BEFORE ACCESS</p><h2>输入看真实文件，<br /><span>输出看最近真实祖先。</span></h2></div><p>所有现存输入先 realpath；输出路径若尚不存在，则向上找到最近存在的目录再 realpath。真实路径越界或路径身份因 symlink 改变，均停止。</p></div><div className="contact-boundary"><b>CHECKED</b><span>SceneSpec</span><span>assets</span><span>provenance</span><span>trajectory</span><span>OCIO</span><strong>OUTPUT ANCESTORS</strong></div><div className="contact-plan"><span>POSITIVE CONTROL</span><code>7a4bccb64013…2d544dd9</code><b>B08 PLAN UNCHANGED</b><b>B05 STRUCTURE UNCHANGED</b></div></section>
    <section className="section contact-limits" id="boundary"><div className="section-index">03 / 未关闭边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> PATH SAFETY IS ONE LAYER</p><h2>这不是完整沙箱，<br /><span>只是关闭一个真实漏洞类。</span></h2></div><p>B10 尚未覆盖恶意 `.blend` 内容、资源耗尽、包供应链、OS 级进程隔离、签名审批或 MCP 工具越权。下一层安全结论必须继续用攻击样例，而不是由“arbitraryPython: false”推断。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/security-v0-1/first-run-falsified.json`}><span>FIRST RUN</span><b>6 个漏洞证据 ↗</b></a><a href={`${repo}experiments/security-v0-1/results.json`}><span>RESULT</span><b>修复后 8/8 ↗</b></a><a href={`${repo}research/2026-08-26-b10-path-security-result.md`}><span>RESULT NOTE</span><b>结论与边界 ↗</b></a><a href={`${repo}research/2026-08-26-b10-path-security-protocol.md`}><span>PROTOCOL</span><b>预注册威胁 ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B10 Restricted Path Security</b></div><p>First run falsified · remediation pass · broader sandbox still open</p><Link href="/trajectory-v0-2">返回 B08 →</Link></footer>
  </main>;
}
