import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const mediaBase = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio/frame-history-isolation-v0-1' : '/frame-history-isolation-v0-1';
const outcomes = [
  ['HISTORY','2 / 12','10 exact','frames 1→38 first'],
  ['DIRECT','3 / 12','9 exact','frame 38 only'],
];
const modes = [
  ['REFERENCE MODE','19 / 24','c1363822…bf308','H 10 · D 9'],
  ['ALTERNATE MODE','5 / 24','6e9685c1…0feaf','H 2 · D 3'],
];

export const metadata: Metadata = {
  title: 'B27 第 38 帧渲染历史隔离｜Blender Film Studio',
  description: '24 个真实 Blender 进程、468 次 render：HISTORY 2/12 与 DIRECT 3/12 超门，p≈1；连续历史假设未获支持，发现两个稳定像素模式。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/frame-history-isolation-v0-1/' },
};

export default function FrameHistoryIsolationPage(){return <main className="contact-page factorial-page frame-history-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B27 导航"><Link href="/journal">实验日志</Link><Link href="/temporal-residual-holdout-v0-1">B25</Link><a href="#design">设计</a><a href="#result">主结果</a><a href="#modes">双模式</a><a href="#next">下一边界</a></nav><span className="edition contact-edition">Frame History 0.1</span></header>

  <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B27 · REAL BLENDER HISTORY INTERVENTION</p><h1>异常复现。<br/><span>连续历史不是解释。</span></h1><p>12 个进程先渲染 1→38，另 12 个进程只渲染 frame 38。两组都出现同一 17 像素模式；DIRECT 甚至更多一例。预注册主检验 p≈1，不能把 B25 的失败归因于前 37 帧。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>NO HISTORY<br/>ASSOCIATION</strong><code>HISTORY FAIL · 2 / 12</code><code>DIRECT FAIL · 3 / 12</code><small>FISHER TWO-SIDED · P ≈ 1</small></aside><div className="contact-stats"><article><strong>24/24</strong><span>唯一 Blender PID</span><small>fixed interleaved order</small></article><article><strong>468</strong><span>真实 render calls</span><small>456 history + 12 direct</small></article><article><strong>23/23</strong><span>攻击测试</span><small>all intended reasons</small></article><article><strong>2</strong><span>decoded RGB 模式</span><small>no third variant</small></article></div></section>

  <section className="section contact-verdict" id="design"><div className="section-index">00 / 只改变一件事</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> FROZEN BEFORE OUTPUT</p><h2>同一场景，同一 frame。<br/><span>只改变之前有没有 render。</span></h2></div><p>固定 `.blend`、BuildPlan、structure、OCIO、32 samples、dither 0、Fast GI、TAA reprojection、FIXED/8 threads 与 PNG8 接口。每个 replicate 都是新进程，H/D 次序由预先哈希种子交错。</p></div><div className="blind-flow history-flow"><article><span>HISTORY · 12 PID</span><b>1 → 37</b><small>each frame write + hash</small></article><i>→</i><article><span>TARGET</span><b>frame 38</b><small>compare to frozen B25-B</small></article><i>×</i><article><span>DIRECT · 12 PID</span><b>frame 38 only</b><small>zero earlier render calls</small></article><i>→</i><article><span>PRIMARY</span><b>envelope fail?</b><small>Fisher exact · α .05</small></article></div><div className="contact-nonclaim"><b>NO OPTIONAL STOPPING</b><p>样本数、执行次序、≤16 像素门、双侧 Fisher 和五种判定在任何 B27 render 前提交。结果出现后没有扩大门槛，也没有把 132 个相关的组内 pair 伪装成独立样本。</p></div></section>

  <section className="section contact-evidence" id="result"><div className="section-index light">01 / 主终点</div><div className="contact-heading"><div><p className="eyebrow"><span/> FIXED-REFERENCE FAILURES</p><h2>两组都失败。<br/><span>方向还与历史假设相反。</span></h2></div><p>主终点是每个新进程的 frame 38 是否超过冻结静态门。HISTORY 风险 16.7%，DIRECT 25.0%，风险差 −8.3 个百分点；p≈1 不是“严格等价”，但明确不给历史因果假设支持。</p></div><div className="history-outcomes">{outcomes.map(([cell,fail,exact,note])=><article key={cell}><span>{cell}</span><strong>{fail}</strong><b>fixed-reference failures</b><code>{exact}</code><small>{note}</small></article>)}<article className="history-pvalue"><span>TWO-SIDED FISHER</span><strong>≈ 1.000</strong><b>α = 0.05</b><code>risk Δ H−D = −0.0833</code><small>not an equivalence test</small></article></div><div className="diagnostic-verdict"><b>FROZEN DECISION</b><code>FAILURE_REPRODUCED_NO_SIGNIFICANT_HISTORY_ASSOCIATION</code><p>最关键的反例是 D02、D10、D11：三个 DIRECT 进程在没有更早 render 调用的情况下仍进入完全相同的 17 像素模式。</p></div></section>

  <section className="section contact-diagnostic" id="modes"><div className="section-index">02 / 事后空间定位</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> TWO EXACT MODES · NOT FIVE RANDOM ERRORS</p><h2>24 个输出只有两个状态。<br/><span>失败状态就是 B25-A。</span></h2></div><p>5 个失败目标彼此 decoded-pixel exact，并与 B25-A frame 38 完全相同；19 个通过目标都匹配 B25-B/C。模式比例在 H/D 两组都出现，进一步削弱连续历史解释。</p></div><div className="history-mode-grid">{modes.map(([label,count,sha,split],index)=><article key={label} className={index===1?'alternate':''}><span>{label}</span><strong>{count}</strong><b>{split}</b><code>{sha}</code><i style={{width:index===0?'79.17%':'20.83%'}}/></article>)}</div><div className="history-crops"><figure><Image src={`${mediaBase}/frame-0038-reference-crop-16x.png`} width={352} height={352} alt="参考模式在差异区域的 16 倍最近邻放大"/><figcaption><span>REFERENCE</span><b>B25-B/C · 19 observations</b></figcaption></figure><figure><Image src={`${mediaBase}/frame-0038-alternate-crop-16x.png`} width={352} height={352} alt="第二模式在差异区域的 16 倍最近邻放大"/><figcaption><span>ALTERNATE</span><b>B25-A · B27 5 observations</b></figcaption></figure><figure><Image src={`${mediaBase}/frame-0038-difference-mask-16x.png`} width={352} height={352} alt="红色显示 17 个变化像素的差分掩码"/><figcaption><span>DIFFERENCE MASK</span><b>17 px · x267–272 · y112–117</b></figcaption></figure></div><div className="contact-nonclaim"><b>POST-HOC · EXPLORATORY</b><p>放大图和“双稳定模式”是在冻结主判定之后做的定位，只用于下一实验。17 个像素都在同一边界簇，RGB 变化均为 +1 code，alpha 不变；这不证明具体是 rasterization、TAA、Metal 或 GPU 调度。</p></div></section>

  <section className="section contact-limits" id="next"><div className="section-index">03 / 下一可证伪边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> SAME PID · REPEATED FRAME 38</p><h2>进程初始化，还是每次 render？<br/><span>让一个 PID 自己暴露答案。</span></h2></div><p>下一实验将在多个持久 Blender 进程内反复渲染固定 frame 38，并在 render 前冻结两个已知 mode SHA。单个 PID 内切换支持 per-render 边界；PID 内锁定而 PID 间不同才支持初始化状态。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/frame-history-isolation-v0-1/results.json`}><span>RESULT</span><b>primary · 23 attacks ↗</b></a><a href={`${repo}experiments/frame-history-isolation-v0-1/evidence/frame-0038.comparison.json`}><span>COMPARISON</span><b>24 targets · 276 pairs ↗</b></a><a href={`${repo}experiments/frame-history-isolation-v0-1/variant-analysis.json`}><span>POST-HOC MAP</span><b>17 coordinates · two modes ↗</b></a><a href={`${repo}research/2026-08-26-b27-frame-history-isolation-protocol.md`}><span>PREREGISTRATION</span><b>frozen before output ↗</b></a><a href={`${repo}research/2026-08-26-b27-frame-history-isolation-result.md`}><span>RESULT NOTE</span><b>claims · boundaries ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B27 Frame-History Isolation</b></div><p>Failure reproduced · history hypothesis unsupported · two modes localized</p><Link href="/research-agenda">进入同 PID 重复 render →</Link></footer>
</main>}
