import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const mediaBase = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio/frame-history-isolation-v0-1' : '/frame-history-isolation-v0-1';
const naturalSequences = [
  ['N01','RRRRRRRRRRRR'],['N02','RARRARRARRRR'],['N03','RRRRARRRRRAR'],['N04','RRRRRARRRRRR'],
  ['N05','ARRRRRARRRRR'],['N06','RRRRRARARRRR'],['N07','ARRRRRRRRRRR'],['N08','RRRRRRRRRRAA'],
  ['N09','RRRRRRRRRRRR'],['N10','RRRRRRARARRR'],['N11','RRRRRRRRRRAR'],['N12','RARRRRRRRRAA'],
];

export const metadata: Metadata = {
  title: 'B30 固定像素抖动干预｜Blender Film Studio',
  description: '24 个真实 Blender 5.2 PID、288 次 render：CENTER 144/144 严格一致；NATURAL 10/12 PID 复现双模式切换。稳定性支持不等于画质支持。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/fixed-jitter-intervention-v0-1/' },
};

export default function FixedJitterInterventionPage(){return <main className="contact-page factorial-page jitter-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B30 导航"><Link href="/journal">实验日志</Link><Link href="/pass-domain-localization-v0-1">B29</Link><a href="#design">设计</a><a href="#result">结果</a><a href="#sequences">序列</a><a href="#cost">代价</a></nav><span className="edition contact-edition">Fixed Jitter 0.1</span></header>

  <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B30 · REAL BLENDER JITTER INTERVENTION</p><h1>像素稳定了。<br/><span>画质还没有被证明。</span></h1><p>24 个全新 Blender 进程按 NATURAL / CENTER 交错执行 288 次 frame-38 render。固定 hidden jitter `[0,0]` 的 144 张输出全部命中预注册 hash；自然对照仍在 10/12 PID 内切换。它是一项稳定性干预，不是电影感结论。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>STRICT STABILITY<br/>SUPPORT</strong><code>CENTER EXACT · 144 / 144</code><code>NATURAL SWITCH · 10 / 12 PID</code><small>QUALITY CLAIM · NOT TESTED</small></aside><div className="contact-stats"><article><strong>24/24</strong><span>唯一 Blender PID</span><small>fixed interleaved schedule</small></article><article><strong>288</strong><span>真实 render calls</span><small>144 natural + 144 center</small></article><article><strong>12/12</strong><span>CENTER exact PID</span><small>one frozen decoded SHA</small></article><article><strong>25/25</strong><span>攻击测试</span><small>all intended reasons</small></article></div></section>

  <section className="section contact-verdict" id="design"><div className="section-index">00 / derivation 先于 confirmation</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ONE VARIABLE SET · EVERYTHING ELSE FROZEN</p><h2>自然 Halton，<br/><span>对固定 CENTER。</span></h2></div><p>derivation 先比较 NATURAL、CENTER、±QUARTER，再按预写规则提名 CENTER。正式 B30 随后冻结 24 PID、288 render、三个 mode hash、反例优先级和 25 个攻击；正式工具在预注册提交后才出现。</p></div><div className="blind-flow jitter-flow"><article><span>FRESH PID × 12</span><b>NATURAL</b><small>property absent</small></article><i>×</i><article><span>FRESH PID × 12</span><b>CENTER</b><small>[0.0, 0.0]</small></article><i>→</i><article><span>EACH PID</span><b>render × 12</b><small>frame set once</small></article><i>→</i><article><span>STRICT CLASSIFY</span><b>SHA only</b><small>no tolerance rescue</small></article></div><div className="contact-nonclaim"><b>反例优先</b><p>CENTER 只要一张不等于冻结 hash，就必须判 `CENTER_VARIATION`；NATURAL 出现第三 hash 也优先失败。自然对照至少两个 PID 内切换，否则不能确认干预面对的是活跃现象。</p></div></section>

  <section className="section contact-evidence" id="result"><div className="section-index light">01 / 正式结果</div><div className="contact-heading"><div><p className="eyebrow"><span/> ACTIVE CONTROL + STRICT INTERVENTION</p><h2>自然输出继续切换。<br/><span>固定输出没有一次偏离。</span></h2></div><p>NATURAL 得到 125 REFERENCE、19 ALTERNATE 和 30 次相邻转换；CENTER 得到 144 次同一 expected hash、零转换。没有 novel hash，独立 factory-startup classifier 复跑与正式 classification 字节一致。</p></div><div className="history-outcomes jitter-outcomes"><article><span>NATURAL REFERENCE</span><strong>125</strong><b>of 144 renders</b><code>86.81%</code><small>10 switching PID</small></article><article><span>NATURAL ALTERNATE</span><strong>19</strong><b>of 144 renders</b><code>13.19%</code><small>30 adjacent transitions</small></article><article className="jitter-center"><span>CENTER EXPECTED</span><strong>144</strong><b>of 144 renders</b><code>ba0591ae…ff8aca</code><small>12 exact PID · zero transition</small></article></div><div className="diagnostic-verdict"><b>FROZEN DECISION</b><code>FIXED_JITTER_STRICT_STABILITY_SUPPORT</code><p>支持范围仅限本机器、Blender 5.2 build、scene、frame 与 profile。hidden property 还联动其他 sample dimensions，因此不是“只证明 filter U/V 根因”。</p></div></section>

  <section className="section contact-diagnostic" id="sequences"><div className="section-index">02 / NATURAL 原始序列</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> R = REFERENCE · A = ALTERNATE</p><h2>十行发生切换。<br/><span>两行保持 REFERENCE。</span></h2></div><p>每行是一个独立 Blender PID，每格是一次真实 render。CENTER 的十二行都是 `CCCCCCCCCCCC`，所以只展开更有信息量的自然对照。</p></div><div className="mode-sequences jitter-sequences">{naturalSequences.map(([pid,sequence])=><article key={pid}><b>{pid}</b><div>{[...sequence].map((mode,index)=><span className={mode==='A'?'alternate':''} key={`${pid}-${index}`} title={`call ${index+1}: ${mode==='A'?'ALTERNATE':'REFERENCE'}`}>{mode}</span>)}</div><small>{[...sequence].filter(mode=>mode==='A').length} alternate</small></article>)}</div><div className="jitter-center-strip"><span>C01 … C12</span><div>{Array.from({length:12},(_,index)=><i key={index}>C</i>)}</div><b>144 / 144 exact</b></div></section>

  <section className="section contact-limits" id="cost"><div className="section-index">03 / 稳定性的采样代价</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> STABILITY ≠ IMAGE QUALITY</p><h2>不是修补 17 个像素。<br/><span>而是换了一套全幅采样。</span></h2></div><p>冻结 derivation 显示 CENTER 相对 NATURAL REFERENCE 改变 131,779 / 518,400 个 decoded pixels，覆盖全幅 bbox；最大差 46 个 PNG code values。下一实验必须用高采样/空间参考与独立人类审片衡量 aliasing 和感知代价。</p></div><div className="jitter-cost-meter"><header><span>CHANGED PIXELS</span><b>131,779 / 518,400</b><strong>25.42%</strong></header><div><i/></div><footer><code>MAX Δ · 46 code values</code><code>RMS · 0.0036968892</code><code>BBOX · FULL FRAME</code></footer></div><div className="history-crops jitter-crops"><figure><Image src={`${mediaBase}/frame-0038-reference-crop-16x.png`} width={352} height={352} alt="自然参考模式差异区域 16 倍放大"/><figcaption><span>NATURAL REFERENCE</span><b>original frozen mode</b></figcaption></figure><figure><Image src={`${mediaBase}/frame-0038-alternate-crop-16x.png`} width={352} height={352} alt="自然第二模式差异区域 16 倍放大"/><figcaption><span>NATURAL ALTERNATE</span><b>17-pixel local event</b></figcaption></figure><figure><Image src={`${mediaBase}/frame-0038-difference-mask-16x.png`} width={352} height={352} alt="自然双模式 17 像素差异掩码"/><figcaption><span>NATURAL MODE MASK</span><b>not the CENTER cost map</b></figcaption></figure></div><div className="contact-artifacts"><a href={`${repo}experiments/fixed-jitter-intervention-v0-1/results.json`}><span>RESULT</span><b>288 renders · 25 attacks ↗</b></a><a href={`${repo}experiments/fixed-jitter-intervention-v0-1/evidence/mode-classification.json`}><span>CLASSIFICATION</span><b>all calls · all hashes ↗</b></a><a href={`${repo}specs/fixed-jitter-intervention-spec.v0.1.json`}><span>FROZEN SPEC</span><b>cells · precedence ↗</b></a><a href={`${repo}research/2026-08-26-b30-fixed-jitter-intervention-protocol.md`}><span>PROTOCOL</span><b>pre-registered ↗</b></a><a href={`${repo}research/2026-08-26-b30-fixed-jitter-intervention-result.md`}><span>RESULT NOTE</span><b>claims · boundaries ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B30 Fixed-Jitter Intervention</b></div><p>Strict stability supported · sampling quality remains open</p><Link href="/research-agenda">进入 B31 采样质量边界 →</Link></footer>
</main>}
