import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const mediaBase = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio/dual-output-localization-v0-1' : '/dual-output-localization-v0-1';
export const metadata: Metadata = { title: 'B21 EXR32 × PNG8 定位｜Blender Film Studio', description: '真实 Blender 同一 Render Result 双输出实验：float EXR32 与 PNG8 均 21/36 exact，变化在 PNG 之前已存在；21/21 攻击通过。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/dual-output-localization-v0-1/' } };
const attacks = [
  ['N01','B21 spec'],['N02','B20 result'],['N03','float inventory'],['N04','ReviewRenderSpec'],['N05','Blender'],['N06','OCIO'],['N07','source .blend'],['N08','renderer'],['N09','configurator'],['N10','samples'],['N11','dither'],['N12','Fast GI'],['N13','reprojection'],['N14','render call count'],['N15','save count'],['N16','EXR layout'],['N17','PNG layout'],['N18','missing partner'],['N19','mutated output'],['N20','comparison binding'],['N21','comparator'],
];
const frameRows = [
  ['001','1','1/3','1/3'],['002','5','3/3','3/3'],['003','20','1/3','1/3'],['004','35','1/3','1/3'],['005','38','3/3','3/3'],['006','47','3/3','3/3'],['007','83','1/3','1/3'],['008','93','1/3','1/3'],['009','103','0/3','0/3'],['010','110','3/3','3/3'],['011','114','3/3','3/3'],['012','144','1/3','1/3'],
];

export default function DualOutputLocalizationPage() {
  return <main className="contact-page factorial-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B21 导航"><Link href="/journal">实验日志</Link><Link href="/eevee-process-history-isolation-v0-1">B20</Link><a href="#formats">格式</a><a href="#pairs">配对</a><a href="#evidence">画面</a><a href="#next">下一变量</a></nav><span className="edition contact-edition">Dual Output 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B21 · ONE RENDER · TWO SAVES</p><h1>Float EXR 已经变化。<br /><span>PNG 不是起点。</span></h1><p>36 个新 Blender 进程，各 render 一次；同一个 Render Result 先保存 ACES 2 PNG8，再保存 scene-linear ACEScg float EXR32。两种格式逐 pair 得到完全相同的 exact 标签。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>PRE-PNG<br />VARIATION</strong><code>EXR32 · 21 / 36</code><code>PNG8 · 21 / 36</code><small>21 / 21 ATTACKS PASS</small></aside><div className="contact-stats"><article><strong>36/36</strong><span>唯一 PID</span><small>fresh process</small></article><article><strong>36</strong><span>render calls</span><small>exactly one each</small></article><article><strong>72</strong><span>文件保存</span><small>same Render Result</small></article><article><strong>21/21</strong><span>负向攻击</span><small>stable reasons</small></article></div></section>
    <section className="section contact-verdict" id="formats"><div className="section-index">00 / 双格式定位</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> ZERO TOLERANCE · DECODED OIIO</p><h2>高比特保留更多差异，<br /><span>不自动带来确定性。</span></h2></div><p>OpenEXR 是 32-bit float scene-linear ACEScg；PNG 是 8-bit display-referred。两个格式都没有达到 36/36 strict exact，因此显示变换/量化不能解释变化的起点。</p></div><div className="factorial-matrix"><article className="factorial-nonexact"><span>EXR32 · ACEScg</span><strong>21/36</strong><b>328 failed pixels</b><small>max 0.00634765625 linear</small></article><article className="factorial-nonexact"><span>PNG8 · ACES SDR</span><strong>21/36</strong><b>94 failed pixels</b><small>max ≈ 1/255</small></article><article className="factorial-exact"><span>PAIR LABEL MATCH</span><strong>36/36</strong><b>same exact / fail state</b><small>EXR ↔ PNG</small></article><article className="factorial-exact"><span>EXECUTION</span><strong>36/36</strong><b>one render · two saves</b><small>unique PIDs</small></article></div><div className="diagnostic-verdict"><b>DECISION</b><code>PRE_PNG_VARIATION_SUPPORT</code><p>EXR 的线性数值误差不能直接当成显示 code 或肉眼差异。这里定位的是严格复现边界，不是感知质量门槛。</p></div></section>
    <section className="section contact-evidence" id="pairs"><div className="section-index light">01 / 逐帧 paired pattern</div><div className="contact-heading"><div><p className="eyebrow"><span /> THREE PAIRS PER SENTINEL</p><h2>不是两个总数碰巧相同。<br /><span>36 个标签逐一相同。</span></h2></div><p>frame 103 在两种格式都 0/3 exact；frame 5、38、47、110、114 都是 3/3。其余六帧在 EXR 和 PNG 中都以相同 pair 分裂。</p></div><ol className="contact-negative-list">{frameRows.map(([id,frame,exr,png]) => <li key={id}><span>{id}</span><b>frame {frame}</b><code>EXR {exr}</code><small>PNG {png}</small></li>)}</ol></section>
    <section className="section contact-limits" id="evidence"><div className="section-index">02 / 真实 PNG witness</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> FRAME 103 · A VS C</p><h2>显示图几乎一样。<br /><span>Float 与 PNG 都拒绝。</span></h2></div><p>A/C 的 EXR 最大差异 0.00537109375，46 个 failed pixels；PNG 为 11 个 failed pixels、最大约 1/255。页面显示 PNG，原始 EXR 比较留在仓库。</p></div><div className="factorial-gallery"><figure><Image src={`${mediaBase}/A-frame-0103.png`} alt="B21 A 进程第103帧 PNG witness" width={960} height={540} sizes="(max-width: 700px) 100vw, 50vw" /><figcaption><span>A · FRAME 0103</span><b>one render · dual save</b><small>fresh PID 64504</small></figcaption></figure><figure><Image src={`${mediaBase}/C-frame-0103.png`} alt="B21 C 进程第103帧 PNG witness" width={960} height={540} sizes="(max-width: 700px) 100vw, 50vw" /><figcaption><span>C · FRAME 0103</span><b>11 PNG failed pixels</b><small>46 EXR failed pixels</small></figcaption></figure></div><div className="contact-nonclaim"><b>NON-CLAIM</b><p>B21 没有直接读 Blender 内部内存像素，也没有证明 GPU race。它只把变化定位到“scene-linear EXR 保存边界或更早”。</p></div></section>
    <section className="section contact-diagnostic"><div className="section-index">03 / 对抗验证</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> TWENTY-ONE STABLE REASONS</p><h2>一次 render、两次 save，<br /><span>也必须可被攻击。</span></h2></div><p>攻击覆盖历史结果身份、运行时、四个固定控制、调用/保存次数、两种格式布局、伙伴文件、字节变异与比较绑定。</p></div><ol className="contact-negative-list">{attacks.map(([id,item]) => <li key={id}><span>{id}</span><b>{item}</b><small>PASS</small></li>)}</ol></section>
    <section className="section contact-limits" id="next"><div className="section-index">04 / 下一可证伪边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> FIXED THREADS · 1 × 8</p><h2>文件格式已排除。<br /><span>下一步看求值并发。</span></h2></div><p>真实 RNA 清单显示 render threads 固定为 8。下一实验应在 EXR32 上预注册 1-thread 与 8-thread 对照；若都失败，继续向 Eevee GPU 采样/归约边界推进。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/dual-output-localization-v0-1/results.json`}><span>RESULT</span><b>36 PIDs · 21 attacks ↗</b></a><a href={`${repo}experiments/dual-output-localization-v0-1/evidence/comparisons/EXR32_SCENE_LINEAR-A-C.comparison.json`}><span>EXR COMPARISON</span><b>12 float frames ↗</b></a><a href={`${repo}research/2026-08-26-b21-dual-output-localization-result.md`}><span>RESULT NOTE</span><b>candidate failures included ↗</b></a><a href={`${repo}research/2026-08-26-render-result-float-inventory.md`}><span>INTERFACE PROBE</span><b>memory claim rejected ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B21 Dual Output Localization</b></div><p>Float variation exists before PNG output</p><Link href="/research-agenda">继续隔离并发 →</Link></footer>
  </main>;
}
