import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical = 'https://lovejzzz.github.io/BlenderFilmStudio/blender-static-radius-intervention-v0-1/';
const socialImage = 'https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-5/crossing-rods-beauty.png';
export const metadata: Metadata = {title:'B52-D12.5 半径干预 Holdout｜Blender Film Studio',description:'12 次 fresh Blender render：radius 3 守住生产容差，却未获得预注册的两倍余量，并让薄环主体覆盖率跌破门槛。',alternates:{canonical},openGraph:{title:'B52-D12.5 半径干预 Holdout',description:'安全不等于答案：21/23 gates，30/30 attacks。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'B52-D12.5 半径干预 Holdout',description:'安全不等于答案：21/23 gates，30/30 attacks。',images:[socialImage]}};
const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const fixtures=[
  {id:'WEDGE / PANEL',name:'wedge-panel',raster:'109×67',r2:'5,986',r3:'5,350',retention:'89.375%',r2max:'1.2517e−6',r3max:'1.2517e−6',location:'rear panel · d17',status:'UNCHANGED'},
  {id:'NESTED CURVES',name:'nested-curves',raster:'137×89',r2:'3,760',r3:'3,133',retention:'83.324%',r2max:'4.7684e−7',r3max:'3.5763e−7',location:'front ring · d4',status:'−25%'},
  {id:'CROSSING RODS',name:'crossing-rods',raster:'149×97',r2:'6,682',r3:'6,010',retention:'89.943%',r2max:'1.1325e−6',r3max:'1.1325e−6',location:'descending rod · d4',status:'UNCHANGED'},
] as const;
export default function BlenderStaticRadiusInterventionPage(){return <main className="contact-page d125-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.5 导航"><Link href="/blender-static-zero-headroom-localization-v0-1">D12.4</Link><a href="#verdict">结论</a><a href="#fixtures">配对场景</a><a href="#failure">失败机制</a><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Intervention D12.5</span></header>
  <section className="contact-hero d125-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.5-C2 · REAL BLENDER PAIRED HOLDOUT</p><h1>半径 3 很安全。<br/><span>但它不是答案。</span></h1><p>同一批 fresh Blender 数组同时进入 radius 2 control 与 radius 3 intervention。生产容差全部守住；更强的两倍余量与主体公平覆盖却被真实几何否决。</p></div><aside className="contact-gate d125-gate"><b>FORMAL VERDICT</b><strong>BOUNDED<br/>NOT SUPPORTED</strong><code>production tolerance · pass</code><code>headroom + owner coverage · fail</code><small>negative result retained</small></aside><div className="contact-stats"><article><strong>55 / 55</strong><span>unique child PIDs</span><small>12 fresh renders</small></article><article><strong>21 / 23</strong><span>decision gates</span><small>two preregistered failures</small></article><article><strong>30 / 30</strong><span>mutation attacks</span><small>all rejected</small></article><article><strong>83–90%</strong><span>total coverage retained</span><small>owner fairness still failed</small></article></div></section>
  <section className="section d125-verdict" id="verdict"><div className="section-index">00 / THREE DIFFERENT CLAIMS</div><div className="contact-heading"><div><p className="eyebrow"><span/> SAFE · MARGIN · FAIRNESS</p><h2>“没有越界”是真的。<br/><span>“干预成功”是假的。</span></h2></div><p>生产最大误差门仍是 1/524288；确认性干预要求更严格的 1/1048576，并要求每个足够大的 owner 保留至少 60% 像素。三种说法被分开判决，不能拿较弱的通过替代较强的失败。</p></div><div className="d12p-failures d125-claims"><article className="safe"><span>PRODUCTION TOLERANCE</span><strong>PASS</strong><b>6 / 6 fresh cells</b><p>Vector、RGB max 与 RMSE 均未越过原门。</p></article><article className="margin"><span>2× MAX HEADROOM</span><strong>FAIL</strong><b>2 / 3 fixtures</b><p>wedge 与 rods 仍为门槛的 65.625% / 59.375%。</p></article><article className="fairness"><span>PER-OWNER RETENTION</span><strong>FAIL</strong><b>tilted ring · 50.249%</b><p>整体覆盖通过，薄环主体却低于冻结的 60%。</p></article></div></section>
  <section className="section d125-fixtures" id="fixtures"><div className="section-index">01 / SAME SOURCE · PAIRED MASKS</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> BEAUTY · RADIUS 2 · RADIUS 3</p><h2>渲染没有变。<br/><span>只改变哪些像素有资格。</span></h2></div><p>每组左侧是正式 EXR 的 ACES display proxy，中间与右侧分别显示 radius 2/3 的 owner-interior。青/绿为可复用域，橙色为 fail-closed boundary；PNG 不参与正式判决。</p></div><div className="d125-gallery">{fixtures.map(f=><article key={f.id}><header><div><span>{f.id}</span><b>{f.raster}</b></div><code>{f.retention} RETAINED</code></header><div>{[['beauty','BEAUTY'],['radius2','RADIUS 2'],['radius3','RADIUS 3']].map(([suffix,label])=><figure key={suffix}><Image src={`${basePath}/evidence/b52-d12-5/${f.name}-${suffix}.png`} width={298} height={194} unoptimized alt={`${f.id} ${label} display proxy`}/><figcaption>{label}</figcaption></figure>)}</div></article>)}</div><div className="contact-nonclaim"><b>DISPLAY PROXY ≠ DECISION SURFACE</b><p>正式 verdict 来自 scene-linear float32 数组。九份代理在实验结束后导出，并由 manifest 绑定源 EXR、mask 与结果哈希。</p></div></section>
  <section className="section d125-matrix"><div className="section-index">02 / PAIRED EFFECT</div><div className="contact-heading"><div><p className="eyebrow"><span/> REMOVE RING 3 · MEASURE WHAT REMAINS</p><h2>只在一个场景降低极值。<br/><span>另外两个完全不动。</span></h2></div><p>所有被 radius 3 移除的像素都精确位于 distance ring 3，subset 合同成立。但 fresh 极值可以位于 d4 甚至 d17；全局加大 erosion 无法触及它们。</p></div><div className="d125-table"><div className="head"><b>FIXTURE</b><b>R2 PIXELS</b><b>R3 PIXELS</b><b>RETENTION</b><b>R2 MAX</b><b>R3 MAX</b><b>EFFECT</b></div>{fixtures.map(f=><div className="row" key={f.id}><strong>{f.id}<small>{f.location}</small></strong><code>{f.r2}</code><code>{f.r3}</code><code>{f.retention}</code><code>{f.r2max}</code><code>{f.r3max}</code><b>{f.status}</b></div>)}</div></section>
  <section className="section d125-failure" id="failure"><div className="section-index">03 / WHAT THE NEGATIVE RESULT CHANGES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> GLOBAL RADIUS IS TOO COARSE</p><h2>D12.4 找到一种机制。<br/><span>D12.5 证明它不是唯一机制。</span></h2></div><p>D12.4 的撞线像素确实在第一 eligible ring；radius 3 也确实删除了全部 ring-3 像素。但 wedge 的最大值在 rear panel d17，rods 的最大值在 descending rod d4，说明内部 Vector 残差 × 同主体颜色梯度也能主导尾部。</p></div><div className="d125-distance"><article><span>WEDGE / PANEL</span><strong>d17</strong><i/><p>半径 3 不可能触及；max 完全不变。</p></article><article><span>NESTED CURVES</span><strong>d3 → d4</strong><i/><p>旧极值被移除；max 降低 25%。</p></article><article><span>CROSSING RODS</span><strong>d4</strong><i/><p>已在新边界内侧；max 完全不变。</p></article></div><div className="d123-next"><span>NEXT · ZERO-RENDER RISK LOCALIZATION</span><strong>从“几像素远”转向“这个像素有多危险”。</strong><div>{['Vector magnitude','same-owner RGB gradient','bilinear weights','owner topology','coverage cost'].map(item=><code key={item}>{item}</code>)}</div><p>下一步先对 d17 与 d4 极值做 D12.4 式算术分解，推导局部 risk gate；在 fresh adaptive holdout 之前，不把它升级成生产规则。</p></div><div className="d125-invalid"><b>FAILURE RETAINED</b><p>第一次 formal root 的 54 个前置进程成功、analyzer 因 NumPy `bool_` 序列化失败；没有 results，也没有科学 verdict。C2 仅注册一个 bool cast，并从新 root 重跑全部 55 个进程。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-static-radius-intervention-holdout-c2-v0-1/results.json`}><span>MACHINE RESULT</span><b>21 / 23 gates ↗</b></a><a href={`${repo}experiments/blender-static-radius-intervention-holdout-c2-v0-1/receipt.json`}><span>FORMAL RECEIPT</span><b>55 unique PIDs ↗</b></a><a href={`${repo}research/2026-08-27-b52-d12-5-c2-radius-intervention-holdout-result.md`}><span>RESULT NOTE</span><b>bounded, not supported ↗</b></a><a href={`${repo}public/evidence/b52-d12-5/manifest.json`}><span>PROXY MANIFEST</span><b>source-bound ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.5 Radius Intervention</b></div><p>production-safe on this holdout · stronger intervention claim falsified</p><Link href="/journal">继续看实验日志 →</Link></footer>
</main>}
