import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = { title: 'B13 编译收据｜可验证 Blender 产物｜Blender Film Studio', description: '把 BuildPlan、编译器、Blender 5.2 binary、预算、OCIO、manifest 与 .blend 绑定为可独立验证的 CompileReceipt。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/compile-receipt-v0-1/' } };
const attacks = [
  ['N01','receipt body','RECEIPT_SELF_HASH'],['N02','BuildPlan file','PLAN_FILE_SHA'],['N03','plan binding','PLAN_HASH_BINDING'],['N04','compiler source','COMPILER_SHA'],['N05','budget profile','BUDGET_PROFILE_SHA'],['N06','OCIO config','OCIO_SHA'],['N07','Blender binary','BLENDER_BINARY_SHA'],['N08','manifest file','MANIFEST_SHA'],['N09','.blend file','BLEND_SHA'],['N10','manifest ↔ plan','MANIFEST_PLAN_BINDING'],
];

export default function CompileReceiptPage() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B13 导航"><Link href="/journal">实验日志</Link><Link href="/resource-budget-v0-1">B12 预算</Link><a href="#identity">身份</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">CompileReceipt 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B13 · VERIFIABLE COMPILE RECEIPT</p><h1>不只证明场景一样。<br /><span>还要说清是谁编译的。</span></h1><p>每个 receipt 把 BuildPlan、五个工具源文件、预算 profile、ACES 2 OCIO、Blender/Node binary、预算报告、manifest、规范结构字节和 `.blend` 绑定为一张完整哈希图。</p></div><aside className="contact-gate"><b>CURRENT STATUS</b><strong>FORMAL B13<br />TRUE</strong><code>4 / 4 receipts verified</code><code>10 / 10 + 2 / 2 attacks</code><small>exact local identity · unsigned</small></aside><div className="contact-stats"><article><strong>19</strong><span>独立验证检查</span><small>each receipt</small></article><article><strong>4 / 4</strong><span>真实净构建</span><small>B01 ×2 · B02 ×2</small></article><article><strong>183.2 MB</strong><span>Blender binary</span><small>exact SHA-256</small></article><article><strong>0</strong><span>结构哈希回退</span><small>B01 / B02 frozen</small></article></div></section>
    <section className="section contact-verdict" id="identity"><div className="section-index">00 / 两种哈希</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> STABLE IDENTITY · RUN-SPECIFIC RECEIPT</p><h2>工具链身份稳定。<br /><span>每次产物仍然独立。</span></h2></div><p>B01 A/B 都是 `798a9006…563b8`，B02 A/B 都是 `a85a7280…036a4`；不同 benchmark 因 plan 不同而分离。receiptHash 和 `.blend` hash 每次不同，精确记录那一次构建。</p></div><div className="contact-flow"><article><span>01</span><b>PLAN + TOOLS</b><p>execution identity</p></article><i>→</i><article><span>02</span><b>REAL BLENDER</b><p>binary + build hash</p></article><i>→</i><article><span>03</span><b>ARTIFACT GRAPH</b><p>manifest + blend + report</p></article></div></section>
    <section className="section contact-contract"><div className="section-index">01 / Blender 内部回读</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> REOPEN THE ACTUAL .BLEND</p><h2>receipt 不只看旁边的 JSON。<br /><span>Blender 重新打开产物。</span></h2></div><p>四个 `.blend` 都由 Blender 5.2 以禁用 autoexec 的方式重新载入，scene 内嵌的 planHash、SceneSpec hash、structureHash、manifestVersion 与 receipt/manifest 一致。</p></div><div className="contact-plan"><span>FROZEN STRUCTURE</span><code>B01 c699fc27…b7f0b</code><code>B02 025c6fa5…fa856</code><b>4 / 4 REOPEN AUDITS PASS</b></div></section>
    <section className="section contact-diagnostic"><div className="section-index">02 / 预注册攻击</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> REHASHED TAMPER CASES</p><h2>不是只改 JSON 等解析失败。<br /><span>攻击会重新计算 receiptHash。</span></h2></div><p>除 self-hash 反例外，其它 fixture 都重新规范化并重哈希，让 verifier 必须走到目标绑定层。现场另加 canonical-structure 与脏输出目录两项，保持独立 supplementary 标签。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,result]) => <li key={id}><span>{id}</span><b>{item}</b><small>{result}</small></li>)}</ol></section>
    <section className="section contact-limits" id="boundary"><div className="section-index">03 / 三次实现证伪</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> THE JOURNAL CHANGED THE DESIGN</p><h2>`localeCompare`、`0.0`、`.blend1`。<br /><span>三个小细节都足以破坏证据。</span></h2></div><p>键排序规则不一致、跨语言数字词法丢失、复用目录产生未绑定备份，三次都让候选结果停止。最终设计使用明确代码点排序、Blender 写出的规范结构字节和强制空输出目录。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/compile-receipt-v0-1/results.json`}><span>RESULT</span><b>4 runs · 12 attacks ↗</b></a><a href={`${repo}experiments/compile-receipt-v0-1/evidence/B01-A/compile.receipt.json`}><span>SAMPLE RECEIPT</span><b>B01-A 完整收据 ↗</b></a><a href={`${repo}research/2026-08-26-b13-compile-receipt-result.md`}><span>RESULT NOTE</span><b>结论与非结论 ↗</b></a><a href={`${repo}research/lab-journal.md`}><span>JOURNAL</span><b>失败过程 ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B13 Verifiable CompileReceipt</b></div><p>Exact local identity · unsigned · remote attestation still open</p><Link href="/journal">返回实验日志 →</Link></footer>
  </main>;
}
