import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const sequences = [
  ['P01','RARDRRRRRRRA'],['P02','RARRRARRRRRR'],['P03','ARRRRARDARRA'],['P04','RRRRDRRRRRRR'],
  ['P05','RRARRRRRRAAA'],['P06','RRRAARRRRARR'],['P07','RRRRRRAAARRA'],['P08','ARAARARRRAAA'],
  ['P09','RRRRRRRRRRRR'],['P10','ARRRARRRRRRA'],['P11','ARARRRRRRRRR'],['P12','AARRRRRAAAAA'],
];
const passRows = [
  ['PNG decoded RGB','103 R · 38 A · 3 R','REFERENCE','ALTERNATE','display output'],
  ['Combined EXR32','103 R · 38 A · 3 R','REFERENCE','ALTERNATE','scene-linear radiance'],
  ['CryptoObject00','103 R · 38 A · 3 A','REFERENCE','ALTERNATE','wall/floor coverage'],
  ['Depth · Normal · Position','144 stable','STABLE','STABLE','closest-sample data'],
];

export const metadata: Metadata = {
  title: 'B29 Pass 域定位｜Blender Film Studio',
  description: '144 次真实 Blender multilayer render：103 coupled reference、38 coupled alternate、3 个 Crypto-only 解耦反例；Depth/Normal/Position 144/144 exact。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/pass-domain-localization-v0-1/' },
};

export default function PassDomainLocalizationPage(){return <main className="contact-page factorial-page pass-domain-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B29 导航"><Link href="/journal">实验日志</Link><Link href="/repeated-frame-mode-switch-v0-1">B28</Link><a href="#design">设计</a><a href="#result">反例</a><a href="#passes">Pass</a><a href="#next">下一步</a></nav><span className="edition contact-edition">Pass Domain 0.1</span></header>

  <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B29 · REAL BLENDER MULTILAYER HOLDOUT</p><h1>覆盖变化，<br/><span>不总会改变画面。</span></h1><p>144 次同帧 render 同时保存 PNG8 与 EXR32 multilayer。38 次完整 R→A 耦合之外，出现 3 次 Crypto coverage 已切换、Combined/PNG 却仍是 REFERENCE 的反例。按预注册优先级，定位假设被否证。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>DECOUPLED<br/>PASS PATTERN</strong><code>COUPLED · 141 / 144</code><code>COUNTEREXAMPLES · 3</code><small>CLOSEST-SAMPLE VARIANT · ZERO</small></aside><div className="contact-stats"><article><strong>144</strong><span>真实 render calls</span><small>12 calls × 12 PID</small></article><article><strong>288</strong><span>同结果 saves</span><small>PNG8 + EXR32</small></article><article><strong>25/25</strong><span>攻击测试</span><small>all intended reasons</small></article><article><strong>3</strong><span>解耦反例</span><small>crypto-only alternate</small></article></div></section>

  <section className="section contact-verdict" id="design"><div className="section-index">00 / derivation ≠ confirmation</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> PILOT SELECTED · HOLDOUT TESTED</p><h2>同一次 render，<br/><span>读取四个证据层。</span></h2></div><p>pilot 只负责冻结 mode hash 与 wall/floor coverage 假设。正式 B29 使用 12 个全新 PID；每次 operator 只调用一次，然后从同一 Render Result 保存 PNG 与 multilayer EXR，避免跨 render 混配 pass。</p></div><div className="blind-flow pass-flow"><article><span>ONE RENDER</span><b>frame 38</b><small>new Eevee Instance</small></article><i>→</i><article><span>DISPLAY</span><b>PNG8</b><small>decoded RGB mode</small></article><i>+</i><article><span>RADIANCE</span><b>Combined</b><small>scene-linear float</small></article><i>+</i><article><span>COVERAGE</span><b>Crypto</b><small>BACK_WALL · FLOOR</small></article><i>+</i><article><span>DATA</span><b>Z · N · P</b><small>closest sample</small></article></div><div className="contact-nonclaim"><b>INVALID CANDIDATE PRESERVED</b><p>第一批完整输出因 validator 把 9 个 pass-state 字段误写为 8 而未晋级。修正只改字段计数，随后 12 个新 PID 全量重跑；没有复用已看过的 output，也没有修改 frozen tuple。</p></div></section>

  <section className="section contact-evidence" id="result"><div className="section-index light">01 / 预注册反例优先</div><div className="contact-heading"><div><p className="eyebrow"><span/> THREE KNOWN-HASH RECOMBINATIONS</p><h2>大多数符合假设。<br/><span>三个反例足以拒绝它。</span></h2></div><p>10/12 PID 达到 coupled-switch 阈值，但 P01/04、P03/08、P04/05 把已知 hash 重组为 PNG R + Combined R + Crypto A。规则预先规定 decoupling 优先，不能用 141 个符合掩盖 3 个反例。</p></div><div className="history-outcomes"><article><span>COUPLED REFERENCE</span><strong>103</strong><b>of 144</b><code>PNG R · Combined R · Crypto R</code><small>Depth / Normal / Position stable</small></article><article><span>COUPLED ALTERNATE</span><strong>38</strong><b>of 144</b><code>PNG A · Combined A · Crypto A</code><small>10 switching PID</small></article><article className="pass-counterexample"><span>DECOUPLED</span><strong>3</strong><b>of 144</b><code>PNG R · Combined R · Crypto A</code><small>P01/04 · P03/08 · P04/05</small></article></div><div className="diagnostic-verdict"><b>FROZEN DECISION</b><code>DECOUPLED_PASS_PATTERN</code><p>Crypto ALTERNATE 覆盖了全部 38 个 Combined ALTERNATE，却额外出现 3 次。因此它在本数据中与视觉 mode 强关联，但不是充分条件，更不是已证明的原因。</p></div></section>

  <section className="section contact-diagnostic" id="passes"><div className="section-index">02 / Pass 域证据</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> PRE-PNG · COVERAGE SUPERSET · DATA STABLE</p><h2>画面 mode 在编码前。<br/><span>几何 data pass 没切换。</span></h2></div><p>PNG 与 Combined 标签 144/144 一致；Depth、Normal、Position 144/144 strict float exact。Crypto 的变化对象始终是 BACK_WALL 与 FLOOR，只有 coverage weights 变化。</p></div><div className="pass-domain-table"><header><span>DOMAIN</span><span>OBSERVED</span><span>REFERENCE</span><span>ALTERNATE</span><span>MEANING</span></header>{passRows.map(row=><article key={row[0]}>{row.map((item,index)=>index===0?<b key={item}>{item}</b>:<span key={`${item}-${index}`}>{item}</span>)}</article>)}</div><div className="mode-sequences pass-sequences">{sequences.map(([pid,sequence])=><article key={pid}><b>{pid}</b><div>{[...sequence].map((mode,index)=><span className={mode==='A'?'alternate':mode==='D'?'decoupled':''} key={`${pid}-${index}`} title={`call ${index+1}: ${mode}`}>{mode}</span>)}</div><small>{[...sequence].filter(mode=>mode==='D').length} decoupled</small></article>)}</div><div className="contact-nonclaim"><b>SEPARATE VECTOR TRANSIENT</b><p>Vector call 1 的 full-frame 第二状态在 12/12 PID 复现，call 2–12 稳定，但它不伴随 Combined/PNG 切换。它是独立次终点，不能被拿来解释 wall/floor cluster。</p></div></section>

  <section className="section contact-limits" id="next"><div className="section-index">03 / 下一机制 probe</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> NATURAL HALTON × FIXED FILTER JITTER</p><h2>下一步干预采样位置。<br/><span>不是先宣布修复。</span></h2></div><p>Blender 5.2 源码暴露 hidden scene property `override_pixel_jitter_sample`。下一轮先用 derivation 选择固定值，再冻结 natural/fixed 对照，观察 Combined/Crypto repeatability。固定一点会改变抗锯齿目标，只能作为机制探针。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/pass-domain-localization-v0-1/results.json`}><span>RESULT</span><b>144 renders · 25 attacks ↗</b></a><a href={`${repo}experiments/pass-domain-localization-v0-1/evidence/pass-classification.json`}><span>CLASSIFICATION</span><b>8 passes × 144 ↗</b></a><a href={`${repo}specs/pass-domain-localization-spec.v0.1.json`}><span>FROZEN SPEC</span><b>tuples · precedence ↗</b></a><a href={`${repo}research/2026-08-26-b29-pass-domain-localization-protocol.md`}><span>PROTOCOL</span><b>pilot separated ↗</b></a><a href={`${repo}research/2026-08-26-b29-pass-domain-localization-result.md`}><span>RESULT NOTE</span><b>counterexamples ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B29 Pass-Domain Localization</b></div><p>141 coupled · 3 counterexamples · hypothesis rejected as frozen</p><Link href="/fixed-jitter-intervention-v0-1">查看 B30 固定抖动干预 →</Link></footer>
</main>}
