import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const changed = new Set(['0-1','1-1','1-2','2-0','2-1','2-3','2-4','2-5','3-0','3-1','3-2','3-3','3-5','4-2','4-3','4-5','5-3']);

export const metadata: Metadata = {
  title: 'B25 连续序列时间残差 Holdout｜Blender Film Studio',
  description: '三次真实 Blender 完整序列：429/429 时间 transition 通过，静态门 430/432，预注册结论 STATIC_ONLY_ENVELOPE_FAIL。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/temporal-residual-holdout-v0-1/' },
};

export default function TemporalResidualHoldoutPage() {
  return <main className="contact-page factorial-page temporal-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B25 导航"><Link href="/journal">实验日志</Link><Link href="/production-tolerance-holdout-v0-1">B24</Link><a href="#metric">指标</a><a href="#result">结果</a><a href="#frame38">frame 38</a><a href="#human">盲评边界</a></nav><span className="edition contact-edition">Temporal Holdout 0.1</span></header>

    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B25 · COMPLETE-SEQUENCE HOLDOUT</p><h1>时间门 429/429。<br /><span>总门仍然失败。</span></h1><p>三次全新的 144 帧连续渲染把共享运动消去，只测跨运行残差随时间的变化。429/429 transition 在预冻结 envelope 内，但 frame 38 有两个静态 pair 超过空间像素门，因此不能宣告整体支持。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>STATIC-ONLY<br />FAIL</strong><code>TEMPORAL · 429 / 429</code><code>STATIC · 430 / 432</code><small>19 / 19 ATTACKS PASS</small></aside><div className="contact-stats"><article><strong>3</strong><span>独立 Blender PID</span><small>A · B · C</small></article><article><strong>432</strong><span>真实 render calls</span><small>144 frames × 3</small></article><article><strong>429/429</strong><span>时间 transition</span><small>numeric envelope</small></article><article><strong>PENDING</strong><span>人类盲评</span><small>automation cannot pass</small></article></div></section>

    <section className="section contact-verdict" id="metric"><div className="section-index">00 / 先消去共享运动</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> TEMPORAL CROSS-RUN RESIDUAL</p><h2>不是比较“动了多少”。<br /><span>而是比较两次运行动得有何不同。</span></h2></div><p>对 A/B 两次渲染先求 `R_t = A_t − B_t`，再求 `T_t = R_t − R_(t−1)`。镜头和物体共同的运动被抵消，留下跨运行不一致随帧变化的数值代理。</p></div><div className="temporal-formula"><span>SHARED MOTION</span><code>(Aₜ − Aₜ₋₁)</code><b>−</b><code>(Bₜ − Bₜ₋₁)</code><strong>= Tₜ</strong></div><div className="contact-nonclaim"><b>DERIVATION ≠ VALIDATION</b><p>B16–B19 的 4 组旧序列、572 个 transition 只负责选门：max ≤ 2/255、RMS ≤ 1/32768、changed pixels ≤ 64。B25 的 A/B/C 是 432 个全新输出；阈值在任何 B25 render 前提交。</p></div></section>

    <section className="section contact-evidence" id="result"><div className="section-index light">01 / 冻结门结果</div><div className="contact-heading"><div><p className="eyebrow"><span /> ALL OBSERVATIONS · NO AVERAGING</p><h2>时间残差 bounded。<br /><span>静态稀疏度差一票。</span></h2></div><p>每个 frame / transition 必须单独通过全部 ceiling，平均值不能掩盖失败。时间最坏仅 17 个像素、约一个 PNG8 code；静态 frame 38 出现 17 个像素，超过 B24 的 ≤16 门。</p></div><div className="factorial-matrix"><article className="factorial-exact"><span>TEMPORAL ENVELOPE</span><strong>429/429</strong><b>354 exact transitions</b><small>max Δ ≈ 1/255</small></article><article className="factorial-nonexact"><span>STATIC ENVELOPE</span><strong>430/432</strong><b>394 exact frames</b><small>two failures by 1 px</small></article><article className="factorial-exact"><span>PROVENANCE</span><strong>3/3</strong><b>unique Blender PID</b><small>source · plan · structure exact</small></article><article className="factorial-exact"><span>ATTACKS</span><strong>19/19</strong><b>stable rejection reasons</b><small>human-result fabrication included</small></article></div><div className="diagnostic-verdict"><b>FROZEN DECISION</b><code>STATIC_ONLY_ENVELOPE_FAIL</code><p>“时间门通过”是一个有效的子观察，但预注册总门要求 static 与 temporal 同时全通过；所以整体不能写成 support。</p></div></section>

    <section className="section contact-diagnostic" id="frame38"><div className="section-index">02 / 失败定位</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> FRAME 0038 · A-ASSOCIATED CLUSTER</p><h2>B 与 C 在这一帧 exact。<br /><span>A 多出同一簇 17 像素差异。</span></h2></div><p>A–B 与 A–C 的 changed-pixel 坐标完全相同，位于 rows 112–117、columns 267–272；B–C 在 frame 38 解码像素完全一致。它定位了一次 A-associated 事件，但尚不能说明 GPU 底层原因。</p></div><div className="temporal-failure-visual"><figure><div className="temporal-frame"><Image src="/temporal-residual-holdout-v0-1/frame-0038-A.png" width={960} height={540} alt="B25 replicate A frame 38，红框标出 17 像素差异区域" priority /><i aria-hidden="true" /></div><figcaption><span>ACTUAL HOLDOUT FRAME</span><b>A · frame-0038.png</b><code>SHA 0c4e10b…273ad</code></figcaption></figure><aside><header><span>6 × 6 LOCAL GRID</span><b>17 changed pixels</b></header><div className="temporal-pixel-grid" aria-label="rows 112 to 117 and columns 267 to 272; colored cells are changed pixels">{Array.from({length: 36},(_,index)=>{const row=Math.floor(index/6),column=index%6;return <i key={index} className={changed.has(`${row}-${column}`)?'active':''} title={`row ${112+row}, column ${267+column}`} />;})}</div><p>A–B = 17<br />A–C = 17<br />B–C = 0</p></aside></div><div className="contact-nonclaim"><b>NO POST-HOC WIDENING</b><p>把 ≤16 改成 ≤17 会让这次结果“好看”，但会破坏预注册。正确做法是保留失败，并在新实验里研究门槛校准与这个孤立事件的生成机制。</p></div></section>

    <section className="section contact-limits" id="human"><div className="section-index">03 / 自动化到此为止</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> NUMERIC PROXY ≠ VISIBLE FLICKER</p><h2>机器可以定位残差。<br /><span>不能替审片者说“看不见”。</span></h2></div><p>当前输出是 960×540、PNG8、24 fps、无 motion blur 的 review proxy。下一步需要匿名化播放材料，并记录 player、display、观看距离/环境和审片者响应；在此之前 human gate 保持 PENDING。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/temporal-residual-holdout-v0-1/results.json`}><span>RESULT</span><b>decision · 19 attacks ↗</b></a><a href={`${repo}experiments/temporal-residual-holdout-v0-1/evidence/A-B.comparison.json`}><span>COMPARISON</span><b>144 frames · 143 transitions ↗</b></a><a href={`${repo}research/2026-08-26-b25-temporal-residual-holdout-protocol.md`}><span>PREREGISTRATION</span><b>frozen before render ↗</b></a><a href={`${repo}research/2026-08-26-b25-temporal-residual-holdout-result.md`}><span>RESULT NOTE</span><b>failure localization ↗</b></a><a href="https://www.itu.int/rec/R-REC-BT.500-15-202305-I/en"><span>ITU-R BT.500-15</span><b>subjective-method boundary ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B25 Temporal Residual Holdout</b></div><p>Temporal sub-gate passed · combined gate falsified · human review pending</p><Link href="/research-agenda">进入下一可证伪问题 →</Link></footer>
  </main>;
}
