import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical='https://lovejzzz.github.io/BlenderFilmStudio/blender-motion-aware-curvature-risk-holdout-v0-1/';
const socialImage='https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-9-h1/rotated-sweep-high-frequency-beauty.png';
export const metadata:Metadata={title:'B52-D12.9-H1 新鲜曲率风险留出｜Blender Film Studio',description:'16 次真实 Blender 5.2 render：Q30 曲率候选保持零风险低估与 exact fallback，但在两个未见运动场景未达到冻结的 97% 覆盖门。',alternates:{canonical},openGraph:{title:'B52-D12.9-H1 新鲜曲率风险留出',description:'安全门成立，覆盖门未成立；简单放宽阈值不能同时保住质量。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'B52-D12.9-H1 新鲜曲率风险留出',description:'13/14 scientific checks · 9/9 audit · bounded result',images:[socialImage]}};

const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const fixtures=[
  {id:'ROTATED SWEEP / HIGH FREQUENCY',name:'rotated-sweep-high-frequency',raster:'157×103',r2:'10,327',accepted:'9,765',retention:'94.558%',support:'146',risk:'416',rgb:'3.030896e−5',vector:'1.0926e−4',status:'COVERAGE FAIL'},
  {id:'CAMERA TRUCK / PITCH / PARALLAX',name:'camera-truck-pitch-parallax',raster:'167×109',r2:'15,366',accepted:'15,018',retention:'97.735%',support:'152',risk:'196',rgb:'3.024936e−5',vector:'5.4255e−5',status:'PASS'},
  {id:'SAME INDEX / DEPTH CROSSING',name:'same-index-depth-crossing',raster:'179×113',r2:'14,159',accepted:'13,717',retention:'96.878%',support:'192',risk:'250',rgb:'2.887845e−5',vector:'8.9213e−5',status:'COVERAGE FAIL'},
  {id:'STATIC / FREQUENCY CONTROL',name:'static-frequency-control',raster:'131×89',r2:'10,065',accepted:'10,065',retention:'100%',support:'0',risk:'0',rgb:'1.490116e−7',vector:'2.2888e−5',status:'CONTROL PASS'},
] as const;

export default function MotionAwareCurvatureRiskHoldoutPage(){return <main className="contact-page d128-page d129-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.9-H1 导航"><Link href="/blender-motion-aware-curvature-risk-v0-1">D12.9-D1</Link><Link href="/blender-owner-token-pass-v0-1">D12.10 Owner Token</Link><a href="#verdict">结论</a><a href="#evidence">真实像素</a><a href="#matrix">测量</a><a href="#threshold">阈值反证</a><a href="#next">下一干预</a><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Fresh Holdout D12.9-H1</span></header>

  <section className="contact-hero d128-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.9-H1 · FRESH BLENDER 5.2 HOLDOUT</p><h1>安全门成立。<br/><span>覆盖门没有成立。</span></h1><p>冻结 Q30 曲率候选在四组未见场景中保持零 measured risk underbound、零 false invalid accept 与 exact fallback；但 rotated sweep 和 same-index crossing 没有达到预登记的 97% cell coverage。</p></div><aside className="contact-gate d128-gate"><b>FROZEN VERDICT</b><strong>SAFE<br/>BUT BOUNDED</strong><code>scientific checks · 13 / 14</code><code>audit · 9 / 9</code><small>coverage not supported</small></aside><div className="contact-stats"><article><strong>16</strong><span>fresh Cycles renders</span><small>4 fixtures × 2 frames × 2 repeats</small></article><article><strong>0</strong><span>risk underbound</span><small>all support-eligible RGB</small></article><article><strong>80 / 80</strong><span>dual payload checks</span><small>Python ↔ Node byte exact</small></article><article><strong>74 / 74</strong><span>unique processes</span><small>every child exit zero</small></article></div></section>

  <section className="section d128-verdict" id="verdict"><div className="section-index">00 / THREE CLAIMS · ONE FAILURE</div><div className="contact-heading"><div><p className="eyebrow"><span/> VALIDITY PASS · QUALITY PASS · COVERAGE FAIL</p><h2>这不是算法崩溃。<br/><span>是适用边界被量出来了。</span></h2></div><p>与 D12.8 相比，运动 history 从 0–16.98% 恢复到 94.56–97.74%；但冻结门要求每个 cell 至少 97%。安全与覆盖是两个独立问题，不能用“误差低”掩盖 coverage failure。</p></div><div className="d128-logic"><article className="pass"><span>01 · STRUCTURAL</span><strong>PASS</strong><code>owner · bounds · alpha · typed depth</code><p>same-index 场景正确拒绝 4,169 个 depth-invalid history；valid-history depth 单独统计。</p></article><i>→</i><article className="pass"><span>02 · Q30 SAFETY</span><strong>PASS</strong><code>risk underbound · 0</code><p>accepted maximum 与 RMSE 全部低于 2⁻¹⁵；所有 fallback 逐字节等于 current RGBA。</p></article><i>→</i><article className="fail"><span>03 · COVERAGE</span><strong>FAIL</strong><code>94.558% · 96.878%</code><p>两个新鲜运动场景没有跨过 97%；正式 verdict 只能进入 bounded 档。</p></article></div><div className="d128-contrast"><article><span>SWEEP</span><strong>94.558%</strong><p>foreground owner · 94.151%</p></article><article><span>CAMERA</span><strong>97.735%</strong><p>both owners pass</p></article><article><span>SAME INDEX</span><strong>96.878%</strong><p>18 pixels below target</p></article><article><span>STATIC</span><strong>100%</strong><p>control exact</p></article></div></section>

  <section className="section d128-fixtures" id="evidence"><div className="section-index">01 / FORMAL EXR · FORMAL MASKS</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> BEAUTY · STRUCTURAL REASON · Q30 DOMAIN</p><h2>黄色是 support 边界。<br/><span>洋红是曲率风险。</span></h2></div><p>Beauty 来自正式 current-frame ACEScg EXR。结构图显示 valid / bounds / owner / depth；candidate 图中绿色为 accepted、黄色为 4×4 support 不完整、洋红为 Q30 risk rejection、蓝色为其余 radius-2 domain。PNG 不参与判定。</p></div><div className="d128-gallery">{fixtures.map(f=><article key={f.id}><header><div><span>{f.id}</span><b>{f.raster}</b></div><code>{f.status} · {f.retention}</code></header><div>{[['beauty','BEAUTY · ACES DISPLAY'],['structural','STRUCTURE · REASON MAP'],['candidate','Q30 · GREEN ACCEPT / YELLOW SUPPORT / MAGENTA RISK']].map(([suffix,label])=><figure key={suffix}><Image src={`${basePath}/evidence/b52-d12-9-h1/${f.name}-${suffix}.png`} width={537} height={339} alt={`${f.id} ${label}`} unoptimized/><figcaption>{label}</figcaption></figure>)}</div><footer><span>{f.support} SUPPORT REJECT</span><code>{f.risk} RISK REJECT</code></footer></article>)}</div></section>

  <section className="section d128-matrix" id="matrix"><div className="section-index">02 / PRIMARY CELL MEASUREMENTS</div><div className="contact-heading"><div><p className="eyebrow"><span/> REPEAT 1 · REPEAT 2 BYTE EXACT</p><h2>质量贴近上限。<br/><span>覆盖不能靠口头四舍五入。</span></h2></div><p>所有数值来自冻结 analyzer；repeat 2 与 repeat 1 的 source、adapter、consumer identity 完全一致。accepted sample count 以像素列出，RGB metric 则对三个通道计数。</p></div><div className="d128-table"><div className="head"><b>FIXTURE</b><b>VECTOR MAX</b><b>RADIUS 2</b><b>ACCEPTED</b><b>RETENTION</b><b>SUPPORT ↓</b><b>RISK ↓</b><b>RGB MAX</b><b>STATE</b></div>{fixtures.map(f=><div className="row" key={f.id}><strong>{f.id}<small>{f.raster}</small></strong><code>{f.vector}</code><code>{f.r2}</code><code>{f.accepted}</code><code>{f.retention}</code><code>{f.support}</code><code>{f.risk}</code><code>{f.rgb}</code><b className={f.status.includes('PASS')?'pass':'fail'}>{f.status}</b></div>)}</div></section>

  <section className="section d129-rewrite" id="threshold"><div className="section-index">03 / POST-HOC THRESHOLD COUNTERFACTUAL</div><div className="contact-heading"><div><p className="eyebrow"><span/> RELAXATION DOES NOT REPAIR BOTH GATES</p><h2>不是把 131,072<br/><span>改大一点就结束。</span></h2></div><p>下面只解释失败，不改变正式 verdict。对每个 support-eligible pixel 重算 bilinear error，并寻找刚好达到 97% 的最小风险阈值；两个失败 fixture 都立即越过冻结质量门。</p></div><div className="d129-equation"><article className="old"><span>ROTATED SWEEP</span><strong>131,072 → 140,559</strong><code>retention · 94.558% → 97.008%</code><p>需要再接纳 253 个 risk rejects；RGB max 变为 3.260374e−5，高于 2⁻¹⁵。</p></article><i>×</i><article className="old"><span>SAME INDEX</span><strong>131,072 → 31,569,966</strong><code>retention · 96.878% → 97.005%</code><p>只差 18 像素，却需要约 241× 阈值；RGB max 变为 1.230001e−3。</p></article></div><div className="d129-thresholds"><article><span>FROZEN QUALITY</span><strong>3.051758e−5</strong><p>2⁻¹⁵ scene-linear</p></article><article><span>SWEEP COUNTERFACTUAL</span><strong>FAIL</strong><p>3.260374e−5</p></article><article><span>SAME-INDEX COUNTERFACTUAL</span><strong>FAIL ×40</strong><p>1.230001e−3</p></article></div></section>

  <section className="section d128-audit"><div className="section-index">04 / IDENTITY · AUDIT</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> BOUNDED DOES NOT MEAN BROKEN</p><h2>负结论本身，<br/><span>通过了完整审计。</span></h2></div><p>结果、execution、audit 与 receipt 自哈希全部复算一致；48 个注册攻击全部被检测；独立 audit 从 raw arrays 重建 64 项 measurement checks，并确认 verdict mapping 没有把 coverage failure 偷换成 pass。</p></div><div className="d128-byte-grid"><article><span>SCIENTIFIC CHECKS</span><strong>13 / 14</strong><code>COVERAGE · FALSE</code><p>其余 parent、process、identity、Vector、depth、structure、risk、quality、stress 与 static 全 true。</p></article><article><span>AUDIT</span><strong>9 / 9</strong><code>RAW REPLAY</code><p>80 个 dual payload comparisons、64 个 measurement replay checks。</p></article><article><span>MUTATIONS</span><strong>48 / 48</strong><code>REJECTED</code><p>风险公式、typed domains、subsets、process 与 verdict tamper 均纳入 roster。</p></article><article><span>RECEIPT</span><strong>c794…3fe8</strong><code>IMMUTABLE RUN</code><p>16 renders、8 adapters、16 consumers、32 envelopes、analyzer 与 audit。</p></article></div></section>

  <section className="section d128-next" id="next"><div className="section-index">05 / NEXT FALSIFIABLE INTERVENTION</div><div className="contact-heading"><div><p className="eyebrow"><span/> D12.10 · TEMPORAL IDENTITY BEFORE RETUNING</p><h2>先知道 support 属于谁。<br/><span>再谈如何插值。</span></h2></div><p>same-index fixture 证明 Object Index 不是 analytic owner identity。下一步应由 compiler 写入稳定的 temporal owner token，把 target validity、true-owner support availability、interior curvature acceptance 分成三个 typed domains，同时保留 registered-history 总覆盖，避免通过缩小 denominator 制造成功。</p></div><div className="d128-next-grid"><article><span>01</span><strong>TEMPORAL OWNER TOKEN</strong><p>compiler-controlled、跨帧稳定、不同 analytic owner 不允许共享的整数身份。</p></article><article><span>02</span><strong>THREE TYPED DOMAINS</strong><p>target valid、support available、curvature accepted 分层记录，不互相污染。</p></article><article><span>03</span><strong>DUAL COVERAGE</strong><p>同时报告 accepted / registered 与 accepted / true-owner interior，防止 denominator gaming。</p></article><article><span>04</span><strong>FRESH HOLDOUT AGAIN</strong><p>新候选只能在当前数据上派生；验证必须再次更换场景与正式 root。</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-motion-aware-curvature-risk-holdout-v0-1/results.json`}><span>FORMAL RESULT</span><b>13 / 14 checks ↗</b></a><a href={`${repo}experiments/blender-motion-aware-curvature-risk-holdout-v0-1/audit.json`}><span>RAW AUDIT</span><b>9 / 9 checks ↗</b></a><a href={`${repo}experiments/blender-motion-aware-curvature-risk-holdout-coverage-analysis-v0-1/results.json`}><span>POST-HOC DIAGNOSTIC</span><b>threshold counterfactual ↗</b></a><a href={`${repo}research/2026-08-28-b52-d12-9-h1-motion-aware-curvature-risk-holdout-result.md`}><span>RESEARCH NOTE</span><b>claims + limits ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.9-H1 Fresh Holdout</b></div><p>safe accepted domain · frozen coverage not supported</p><Link href="/blender-owner-token-pass-v0-1">继续：D12.10 Owner Token →</Link></footer>
</main>}
