import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B50 焦点意图盲评｜Blender Film Studio',
  description: '两次真实 Blender 5.2 可观看分辨率渲染、18 个延迟披露匿名会话与零人类响应：机器包已就绪，电影感结论仍待真实观察者。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/focus-intent-review-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';

export default function FocusIntentReviewPage() {
  return <main className="contact-page b50-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B50 导航"><Link href="/journal">实验日志</Link><Link href="/depth-of-field-holdout-v0-1">B49 景深</Link><a href="#conflict">焦点冲突</a><a href="#blind">延迟披露</a><a href="#status">人类门</a></nav><span className="edition contact-edition">Focus Intent B50</span></header>

    <section className="contact-hero b50-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> VIEWABLE RESOLUTION · DELAYED DISCLOSURE</p><h1>机器包已经就绪。<br/><span>人类结论仍是零。</span></h1><p>两次新的 Blender 5.2 worker 渲染把“窗区焦点”和“椅子语义焦点”变成 18 个平衡匿名会话。公开页故意不展示候选图：盲法本身就是实验的一部分。</p></div><aside className="contact-gate b50-gate"><b>CURRENT STATUS</b><strong>PACKAGE READY<br/>HUMAN PENDING</strong><code>21 / 21 attacks</code><code>29-check independent audit</code><small>0 / 18 VALID OBSERVERS</small></aside><div className="contact-stats"><article><strong>960×540</strong><span>真实 review 像素</span><small>not a thumbnail</small></article><article><strong>2</strong><span>fresh workers</span><small>670.34 s · 667.68 s</small></article><article><strong>9 / 9</strong><span>匿名顺序平衡</span><small>A/B · B/A</small></article><article><strong>0</strong><span>公开敏感命中</span><small>3,616 files scanned</small></article></div></section>

    <section className="section b50-conflict" id="conflict"><div className="section-index">00 / SEMANTIC CONTRADICTION</div><div className="contact-heading"><div><p className="eyebrow"><span/> THE BRIEF SAYS CHAIR PORTRAIT</p><h2>设置执行正确。<br/><span>意图可能设置错了。</span></h2></div><p>真实 depsgraph 测量把焦点冲突变成米：原编译值 3.2 m 落在窗框范围，而椅子根和椅背中心都约 6.45 m。B49 证明 Blender 忠实执行；B50 问人类它是否忠实表达 brief。</p></div><div className="focus-depth-rail"><div className="focus-camera"><span>CAMERA</span><b>0 m</b></div><div className="focus-window"><span>WINDOW GEOMETRY</span><b>2.74—4.89 m</b><i>compiled focus · 3.20 m</i></div><div className="focus-chair"><span>CHAIR SUBJECT</span><b>5.71—6.98 m</b><i>semantic root · 6.452 m</i></div></div><blockquote className="b50-brief">“A restrained 24-frame locked-off portrait of a chair in an interior.”</blockquote></section>

    <section className="section b50-pair"><div className="section-index">01 / ONE-VARIABLE PAIR</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> EVERYTHING EXCEPT FOCUS OBJECT HELD FIXED</p><h2>不是重做镜头。<br/><span>只改变焦点的语义绑定。</span></h2></div><p>场景、frame 23、70 mm、f/4、128 spp、seed、四线程、ACES 2、CENTER 0.5 快门和七层 EXR 合同完全固定。候选仅把 `camera.data.dof.focus_object` 从 null 绑定到 `PROP_CHAIR`。</p></div><div className="b50-condition-grid"><article><span>PRIVATE CONDITION 01</span><strong>ORIGINAL BINDING</strong><p>numeric 3.2 m · focus object null</p><b>670.342 s</b></article><article><span>PRIVATE CONDITION 02</span><strong>SEMANTIC BINDING</strong><p>numeric retained · focus object chair</p><b>667.678 s</b></article></div><div className="contact-nonclaim"><b>DISCLOSURE NOTE</b><p>这里公开条件定义，但不公开哪个匿名 IMAGE、PNG 哈希或 session 对应哪个条件。真实图片也保持私有，直到采集关闭。</p></div></section>

    <section className="section b50-blind" id="blind"><div className="section-index">02 / DELAYED DISCLOSURE</div><div className="contact-heading"><div><p className="eyebrow"><span/> PUBLIC COMMITMENT · PRIVATE IDENTITIES</p><h2>先承诺整个包。<br/><span>最后才打开映射。</span></h2></div><p>每位观察者只看到 IMAGE-A / IMAGE-B 和独立 salted commitment。条件图、可见图哈希、映射与答案留在 ignored 私有存储；公开面只保存不可 join 的整体承诺。</p></div><div className="b50-disclosure-flow"><article><span>PUBLIC NOW</span><b>SPEC + TOOLS</b><p>问题、阈值、21 attacks、salted commitments</p></article><i>≠</i><article className="sealed"><span>SEALED UNTIL CLOSE</span><b>IMAGE ↔ CONDITION</b><p>output identities · mappings · responses</p></article><i>→</i><article><span>AFTER 18 / 18</span><b>CLOSE + UNBLIND</b><p>分析一次，不能重开采集</p></article></div><div className="b50-audit-grid"><article><strong>21 / 21</strong><span>frozen attacks</span></article><article><strong>29</strong><span>independent checks</span></article><article><strong>3,616</strong><span>public files scanned</span></article><article><strong>0</strong><span>sensitive matches</span></article></div></section>

    <section className="section b50-questions"><div className="section-index">03 / HUMAN QUESTIONS</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> PRIMARY ≠ SECONDARY</p><h2>先问是否完成 brief。<br/><span>再记录电影感。</span></h2></div><p>主要判定是哪个焦点更符合“椅子肖像”；电影感只是描述性副问题，不能推翻主判定。每张图还记录注意力首先落在椅子、窗、房间结构、其他或无明确主体。</p></div><ol className="b50-question-list"><li><span>01 · PRIMARY</span><b>哪张更符合冻结 brief？</b><small>≥14 / 18 才允许方向性支持</small></li><li><span>02 · ATTENTION</span><b>注意力首先落在哪里？</b><small>支持条件还需 ≥14 / 18 选择 CHAIR</small></li><li><span>03 · SECONDARY</span><b>哪张作为静帧更有电影感？</b><small>只描述，不能更改主结果</small></li><li><span>04 · VALIDITY</span><b>显示器、距离、环境、100% zoom</b><small>开发者与 synthetic 均不计数</small></li></ol></section>

    <section className="section contact-limits b50-status" id="status"><div className="section-index">04 / HUMAN GATE IS REAL</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> INTERFACE PASS ≠ OBSERVER EVIDENCE</p><h2>浏览器 pilot 通过。<br/><span>正式人类仍是 0 / 18。</span></h2></div><p>真实浏览器已确认两张图原生与 CSS 均为 960×540、A/B 切换正确、无条件或仓库泄露、无 console error；没有提交表单或下载 response。发布后还需对精确公开状态做最终零泄露扫描，之后采集才可开放。</p></div><div className="delayed-gates"><article className="done"><span>PASS</span><b>RENDER PACKAGE</b><p>2 real workers · seven-pass EXR</p></article><article className="done"><span>PASS</span><b>INTERFACE PILOT</b><p>960×540 · switch · zero errors</p></article><article><span>NEXT</span><b>FINAL PUBLIC AUDIT</b><p>exact published source + site build</p></article><article className="locked"><span>LOCKED</span><b>HUMAN COLLECTION</b><p>18 independent observers · currently 0</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/focus-intent-human-review-v0-1/precollection-commitment.json`}><span>PUBLIC COMMITMENT</span><b>salted · non-joinable ↗</b></a><a href={`${repo}specs/focus-intent-human-review-spec.v0.1.json`}><span>FROZEN SPEC</span><b>people · gates · attacks ↗</b></a><a href={`${repo}research/2026-08-27-b50-focus-intent-human-review-protocol.md`}><span>PROTOCOL</span><b>delayed disclosure v0.1 ↗</b></a><a href={`${repo}research/2026-08-27-b50-focus-intent-package-result.md`}><span>PACKAGE RESULT</span><b>facts · limits · next ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B50 Focus Intent Review</b></div><p>machine package ready · collection not open · human 0/18</p><Link href="/journal">继续看实验日志 →</Link></footer>
  </main>;
}
