import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const frames = [
  { frame: 31, reliability: 0.0001866703, q4: 1.253379, q8: 0.944829, q8q4: 0.753826, tie: '1 / 1' },
  { frame: 67, reliability: 0, q4: 1.245624, q8: 0.952203, q8q4: 0.764439, tie: '1 / 1' },
  { frame: 109, reliability: 0, q4: 1.282386, q8: 0.949626, q8q4: 0.740514, tie: '1 / 2' },
  { frame: 143, reliability: 0.0005276818, q4: 1.300966, q8: 0.957435, q8q4: 0.735941, tie: '2 / 2' },
];
const costs = [
  { label: 'NATURAL32', time: 1.4915, ratio: 1, error: 1, tone: 'natural' },
  { label: 'Q4', time: 6.0630, ratio: 4.065, error: 1.2706, tone: 'q4' },
  { label: 'Q8', time: 12.1443, ratio: 8.142, error: 0.9510, tone: 'q8' },
];

export const metadata: Metadata = {
  title: 'B32 确定性多抖动成本—质量曲线｜Blender Film Studio',
  description: '保留一次 mask-tie 无效尝试后，以 28 个新 Blender PID、112 个 EXR 和 exact-top-k 协议验证 Q4/Q8 的 scene-linear 成本—质量曲线。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/quadrature-cost-holdout-v0-2/' },
};

export default function QuadratureCostHoldoutPage() {
  return <main className="contact-page factorial-page quality-cost-page quadrature-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B32 导航"><Link href="/journal">实验日志</Link><Link href="/sampling-quality-holdout-v0-1">B31</Link><a href="#failure">失败</a><a href="#holdout">正式结果</a><a href="#cost">成本曲线</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Quadrature 0.2</span></header>

    <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B32 · DETERMINISTIC MULTI-JITTER HOLDOUT</p><h1>稳定可以购买。<br/><span>价格是 4× 或 8× render。</span></h1><p>把多个固定 subpixel jitter 分别渲染，再在 scene-linear RGB 中等权合成。Q4 与 Q8 都 A/B float exact；Q8 在四个新 frame 上通过 near-natural reference-proxy 门，并以明确的 8.142× render-time 代价换取覆盖。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>COST–QUALITY<br/>CURVE SUPPORT</strong><code>28 PIDs · 112 EXR</code><code>29 / 29 ATTACKS</code><small>VISIBLE QUALITY · NOT CLAIMED</small></aside><div className="contact-stats"><article><strong>0.9510×</strong><span>Q8 / NATURAL edge mean</span><small>maximum · 0.9574×</small></article><article><strong>1.2706×</strong><span>Q4 / NATURAL edge mean</span><small>maximum · 1.3010×</small></article><article><strong>8.142×</strong><span>Q8 render-time ratio</span><small>Q4 · 4.065×</small></article><article><strong>0</strong><span>Q4/Q8 A/B RMSE</span><small>4 / 4 holdout frames</small></article></div></section>

    <section className="section quadrature-failure" id="failure"><div className="section-index">00 / 失败没有被覆盖</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> V0.1 INVALID · V0.2 CLEAN RESTART</p><h2>25,920 的目标，<br/><span>第一次选出了 25,921。</span></h2></div><p>v0.1 的 quantile + ≥ 在 frame 22 的 cutoff 遇到两个相等梯度值。28 个 PID 和 112 个 render 已完成，analyzer 仍按合约停止；没有偷偷改一行继续算，也没有给 Q4/Q8 质量结论。</p></div><div className="quadrature-failure-flow"><article className="invalid"><span>V0.1 · INVALID</span><strong>25,921</strong><b>pixels selected</b><code>25,919 greater + 2 equal</code><small>IDENTITY_OR_DESIGN_INVALID</small></article><i>→</i><article><span>NEW CONTRACT</span><strong>TOP-K</strong><b>complete total order</b><code>magnitude ↓ · pixel index ↑</code><small>exactly 25,920</small></article><i>→</i><article className="clean"><span>V0.2 · CLEAN</span><strong>112</strong><b>new EXR renders</b><code>frames 31 · 67 · 109 · 143</code><small>no v0.1 output reused</small></article></div><div className="contact-nonclaim"><b>WHY THIS MATTERS</b><p>这次失败证伪了“quantile threshold + ≥ 天然等于 exact top 5%”的隐藏假设。v0.2 换用新帧、全新 PID 和预注册 tie-break；v0.1 的 ledger、diagnostic 与 invalid result 继续公开。</p></div></section>

    <section className="section contact-evidence" id="holdout"><div className="section-index light">01 / 新帧逐一过门</div><div className="contact-heading"><div><p className="eyebrow"><span/> NO AVERAGE MAY HIDE A FRAME</p><h2>Q8 四帧都 ≤ 0.9575×。<br/><span>Q4 四帧都 ≤ 1.3010×。</span></h2></div><p>每帧先验证 dual-NATURAL1024 proxy reliability，再分别检查 Q4≤1.40、Q8≤1.10、Q8≤Q4；Q8/Q4 mean 还必须 ≤0.90。所有 component gate 都通过。</p></div><div className="quadrature-frame-chart">{frames.map(item=><article key={item.frame}><header><span>FRAME {item.frame}</span><strong>{item.q8.toFixed(4)}×</strong></header><div className="quadrature-bars" aria-label={`Frame ${item.frame} error ratios`}><div><small>N</small><i style={{width:'66.67%'}}/><b>1.000</b></div><div><small>Q4</small><i className="q4" style={{width:`${item.q4/1.5*100}%`}}/><b>{item.q4.toFixed(3)}</b></div><div><small>Q8</small><i className="q8" style={{width:`${item.q8/1.5*100}%`}}/><b>{item.q8.toFixed(3)}</b></div></div><footer><code>REF · {item.reliability===0?'0':item.reliability.toFixed(6)}</code><code>Q8/Q4 · {item.q8q4.toFixed(3)}</code><code>boundary tie · {item.tie}</code></footer></article>)}</div><div className="quadrature-gates"><article><span>REFERENCE</span><strong>4 / 4</strong><b>≤ 0.05 reliability</b></article><article><span>REPEATABILITY</span><strong>8 / 8</strong><b>Q4 + Q8 frame composites exact</b></article><article><span>QUALITY PROXY</span><strong>12 / 12</strong><b>Q4 · Q8 · dominance frame gates</b></article><article><span>VALIDITY</span><strong>29 / 29</strong><b>negative attacks</b></article></div></section>

    <section className="section contact-diagnostic" id="cost"><div className="section-index">02 / 成本—误差必须一起看</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> SAME MACHINE · BLENDER TIMERS</p><h2>误差下降不是免费。<br/><span>Q8 是八次 component render。</span></h2></div><p>Q4 把 CENTER 单点的大部分 edge cost 拉回，却仍高于 NATURAL proxy；Q8 再把 Q4 mean error 降约 25.1%。代价几乎精确翻倍。秒数不含调度、I/O 或合成，也不是货币报价。</p></div><div className="quadrature-cost-curve">{costs.map(item=><article className={item.tone} key={item.label}><header><span>{item.label}</span><b>{item.ratio.toFixed(3)}× TIME</b></header><div className="quadrature-cost-meter"><i style={{height:`${item.ratio/8.5*100}%`}}/><strong>{item.time.toFixed(3)}s</strong></div><footer><small>EDGE PROXY</small><strong>{item.error.toFixed(4)}×</strong></footer></article>)}</div><div className="quality-domain-table"><header><span>CELL</span><span>TIME RATIO</span><span>EDGE MEAN</span><span>INTERPRETATION</span></header><article><b>NATURAL32</b><span>1.000×</span><span>1.0000×</span><small>active control · not deterministic</small></article><article><b>Q4 fixed ensemble</b><span>4.065×</span><span>1.2706×</span><small>exact A/B · partial coverage recovery</small></article><article><b>Q8 fixed ensemble</b><span>8.142×</span><span>0.9510×</span><small>exact A/B · near-natural proxy gate</small></article></div></section>

    <section className="section contact-limits" id="boundary"><div className="section-index">03 / 能说与不能说</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> NUMERIC PROXY ≠ CINEMA</p><h2>静态帧曲线成立。<br/><span>电影生产结论还没成立。</span></h2></div><p>ratio 低于 1 只表示相对 dual-1024 proxy 的 scene-linear RMSE 更低，不等于肉眼优于 NATURAL。仍缺连续序列、edge flicker、motion blur、完整镜头摊销、跨 GPU 与独立盲评。</p></div><div className="contact-checks"><article><span>SUPPORTED</span><h3>Exact A/B</h3><p>Q4/Q8 在四个新 frame 的 composite float exact。</p><b>FORMAL</b></article><article><span>SUPPORTED</span><h3>Static proxy curve</h3><p>Q4/Q8 全部通过预写 edge-reference 与 dominance 门。</p><b>FORMAL</b></article><article><span>OPEN</span><h3>Temporal sequence</h3><p>相邻帧残差、flicker 与 motion blur 尚未验证。</p><b>NEXT</b></article><article><span>OPEN</span><h3>Human cinema gate</h3><p>没有观察者数据，不能把数值写成电影感。</p><b>PENDING</b></article></div><div className="contact-artifacts"><a href={`${repo}experiments/quadrature-cost-holdout-v0-2/results.json`}><span>FORMAL RESULT</span><b>112 renders · 29 attacks ↗</b></a><a href={`${repo}experiments/quadrature-cost-holdout-v0-2/evidence/quality-analysis.json`}><span>ANALYSIS</span><b>four frames · exact top-k ↗</b></a><a href={`${repo}specs/quadrature-cost-holdout-spec.v0.2.json`}><span>FROZEN SPEC</span><b>frames · points · gates ↗</b></a><a href={`${repo}experiments/quadrature-cost-holdout-v0-1/results.json`}><span>INVALID V0.1</span><b>25,921-pixel counterexample ↗</b></a><a href={`${repo}research/2026-08-26-b32-quadrature-cost-holdout-v02-result.md`}><span>RESULT NOTE</span><b>claims · costs · boundaries ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B32 Deterministic Quadrature</b></div><p>v0.1 invalid preserved · v0.2 static proxy curve supported · temporal/human open</p><Link href="/research-agenda">进入连续帧验证 →</Link></footer>
  </main>;
}
