import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B52-D9.1 Layer / Depth Temporal Accumulation｜Blender Film Studio',
  description: '32 个独立进程与真实 Blender 5.2 render：外部 layer/depth history validity 与 temporal accumulation fresh holdout exact 通过；30/30 attacks，独立 audit PASS。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/temporal-accumulation-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const evidence = 'https://raw.githubusercontent.com/lovejzzz/BlenderFilmStudio/9210e00/experiments/layer-depth-temporal-accumulation-holdout-v0-1/diagnostics';
const fixtures = [
  { slug: 'textured-foreground-crossing-103x63', name: 'FOREGROUND CROSSING', size: '103 × 63', valid: '6,183 / 6,489', naive: '306 px · 1.015625', wrong: '816 px · 1.125' },
  { slug: 'textured-camera-pan-107x61', name: 'CAMERA PAN', size: '107 × 61', valid: '5,700 / 6,527', naive: 'N/A', wrong: '4,453 px · 1.125' },
  { slug: 'textured-depth-swap-same-id-89x49', name: 'SAME-ID DEPTH SWAP', size: '89 × 49', valid: '3,632 / 4,361', naive: '729 px · 1.140625', wrong: '270 px · 1.140625' },
  { slug: 'textured-static-control-71x43', name: 'STATIC CONTROL', size: '71 × 43', valid: '3,053 / 3,053', naive: '0 px · 0', wrong: '0 px · 0' },
];

export default function TemporalAccumulationPage() {
  return <main className="contact-page b51-page b52-page d91-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D9.1 导航"><Link href="/adaptive-cpu-v0-1">B52 前序</Link><a href="#counterexample">D9 反例</a><a href="#holdout">D9.1 Holdout</a><a href="#evidence">诊断图</a><a href="#boundary">下一门</a><Link href="/journal">实验日志</Link></nav><span className="edition contact-edition">Temporal D9.1</span></header>

    <section className="contact-hero b51-hero b52-hero d91-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D9.1 · LAYER / DEPTH TEMPORAL ACCUMULATION</p><h1>历史不是盲目平均。<br/><span>先证明哪一帧可以相信。</span></h1><p>四个 fresh textured sequences 由 Python 与 Node 独立求解；ownership、depth、bounds 与 alpha 共同决定 history validity。canonical resolved float32 再经 16 个真实 Blender 5.2 compositor renders，所有标量保持 exact。</p></div><aside className="contact-gate b51-gate b52-gate"><b>SCIENTIFIC VERDICT</b><strong>SUPPORTED<br/>EXACT HOLDOUT</strong><code>0 changed scalars · max error 0</code><code>30 / 30 attacks</code><small>independent audit PASS</small></aside><div className="contact-stats"><article><strong>32 / 32</strong><span>formal child processes</span><small>all PID unique</small></article><article><strong>10 / 10</strong><span>canonical arrays</span><small>Python = Node byte-exact</small></article><article><strong>16 / 16</strong><span>Blender outputs</span><small>decoded float32 exact</small></article><article><strong>40 / 40</strong><span>diagnostic artifacts</span><small>byte-exact replay</small></article></div></section>

    <section className="section d91-counterexample" id="counterexample"><div className="section-index">00 / RETAINED COUNTEREXAMPLE</div><div className="contact-heading"><div><p className="eyebrow"><span/> D9 · DESIGN INVALID BEFORE FORMAL OUTPUT</p><h2>旧实验失败了。<br/><span>门槛没有因此降低。</span></h2></div><p>D9 的 constant-color surfaces 让错误 motion sign 在同一层内部只看到 ±1/16 noise：前景与 camera fixture 最大误差都只有 0.0625，未达到冻结的 0.25。我们停止在正式输出前，保留反例，再用全新 resolution、box、motion 与 surface-local texture 预注册 D9.1。</p></div><div className="d91-contrast"><article className="failed"><span>D9 · CONSTANT SURFACE</span><strong>0.0625</strong><b>wrong-sign maximum</b><p>two fixtures fail the frozen 0.25 gate</p></article><i>≠</i><article><span>禁止的做法</span><strong>0</strong><b>retroactive threshold edits</b><p>no output deletion · no silent retuning</p></article><i>→</i><article className="passed"><span>D9.1 · FRESH TEXTURE</span><strong>≥ 1.125</strong><b>wrong-sign maximum</b><p>all three moving fixtures pass</p></article></div><div className="contact-nonclaim"><b>A FAILED DESIGN IS EVIDENCE</b><p>D9 没有被包装成“差一点通过”。它证明 constant-color task 对方向错误的材料敏感度不足；D9.1 改的是新任务的可识别性，而不是旧结果的判定。</p></div></section>

    <section className="section b51-localization" id="holdout"><div className="section-index">01 / FROZEN TEMPORAL CONTRACT</div><div className="contact-heading"><div><p className="eyebrow"><span/> INTEGER MOTION · NEAREST HISTORY · ANALYTIC TRUTH</p><h2>正确历史恢复干净目标。<br/><span>遮挡历史必须被拒绝。</span></h2></div><p>每个 current pixel 用 `q=(x−dx,y+dy)` 回到 previous。只有 q 在 bounds 内、layer ID 相同、depth 在 `max(1,z)/1024` 内一致且两端 alpha 大于 0，history 才有效。有效点精确平均；无效点逐位保留 current。</p></div><div className="d91-formula"><article><span>HISTORY VALIDITY</span><code>bounds(q) ∧ layerₜ(x)=layerₜ₋₁(q)<br/>∧ |zₜ(x)−zₜ₋₁(q)| ≤ max(1,zₜ)/1024<br/>∧ αₜ(x)&gt;0 ∧ αₜ₋₁(q)&gt;0</code></article><article><span>ACCUMULATION</span><code>valid → float32(0.5·current + 0.5·previous(q))<br/>invalid → current exact</code></article></div><div className="d91-process"><article><span>01</span><strong>4 + 4</strong><b>Python / Node</b><p>independent scalar producers</p></article><i>→</i><article><span>02</span><strong>8</strong><b>Raw EXR encoders</b><p>RGBA · FLOAT · ZIP</p></article><i>→</i><article><span>03</span><strong>16</strong><b>Blender 5.2 renders</b><p>two clean repeats per path</p></article><i>→</i><article><span>04</span><strong>PASS</strong><b>independent replay</b><p>results + diagnostics exact</p></article></div>
      <div className="d91-table"><div className="head"><b>FIXTURE</b><b>VALID HISTORY</b><b>NAIVE CONTROL</b><b>WRONG SIGN</b></div>{fixtures.map((f)=><div className="row" key={f.slug}><span><b>{f.name}</b><small>{f.size}</small></span><code>{f.valid}</code><code>{f.naive}</code><code>{f.wrong}</code></div>)}</div>
      <div className="b51-localization-grid"><article className="exact"><span>DUAL IMPLEMENTATION</span><strong>4 / 4</strong><b>all ten arrays exact</b><p>independent ground-truth rebuild</p></article><article className="exact"><span>SENSITIVITY</span><strong>5 / 5</strong><b>applicable controls pass</b><p>thresholds never changed</p></article><article className="exact"><span>BLENDER TRANSPORT</span><strong>16 / 16</strong><b>maximum error 0</b><p>all repeats and paths converge</p></article><article className="exact"><span>INTEGRITY</span><strong>30 / 30</strong><b>attacks pass</b><p>audit has zero failures</p></article></div>
    </section>

    <section className="section d91-evidence" id="evidence"><div className="section-index">02 / FIXED DIAGNOSTICS</div><div className="contact-heading"><div><p className="eyebrow"><span/> CURRENT · VALIDITY · WRONG-SIGN ERROR</p><h2>不是只给绿色数字。<br/><span>把错误发生在哪里画出来。</span></h2></div><p>RGB8 图仅用于定位，正式判定来自 canonical float32。白色 validity 表示可用历史；wrong-sign error 使用冻结标尺。静态负控应为全白 validity 与全黑 error，而运动 fixtures 必须显示结构性错误。</p></div><div className="d91-gallery">{fixtures.map((f)=><article key={f.slug}><header><b>{f.name}</b><span>{f.size}</span></header><div><figure><img src={`${evidence}/${f.slug}-current.png`} width="512" height="320" alt={`${f.name} current textured frame`}/><figcaption>CURRENT</figcaption></figure><figure><img src={`${evidence}/${f.slug}-history-validity.png`} width="512" height="320" alt={`${f.name} analytic history validity mask`}/><figcaption>HISTORY VALIDITY</figcaption></figure><figure><img src={`${evidence}/${f.slug}-wrong-sign-error.png`} width="512" height="320" alt={`${f.name} wrong motion sign error map`}/><figcaption>WRONG-SIGN ERROR</figcaption></figure></div></article>)}</div><div className="contact-nonclaim"><b>PNG ≠ MEASUREMENT INPUT</b><p>20 PNG 与 20 sidecars 都可重建，但它们不参与判定。任何缩放、浏览器色彩管理或肉眼“看起来全黑”都不能替代 float32 wrong-pixel、maximum-error 与 hash gates。</p></div></section>

    <section className="section contact-limits b51-next" id="boundary"><div className="section-index">03 / NEXT FALSIFIABLE GATE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> REAL BLENDER MULTIPART ADAPTER HOLDOUT</p><h2>算法与输出桥已经成立。<br/><span>下一门是生产 pass 的语义。</span></h2></div><p>D9.1 输入是 analytic layer/depth/motion arrays，因此不能证明 Blender Vector 的四分量顺序、符号或 previous/current pair，也不能证明 production Depth/ownership extraction。下一实验必须直接从真实 Blender multipart EXR 取 pass，与独立轨迹真值对齐。</p></div><div className="b51-next-flow"><article><span>01</span><b>VECTOR COMPONENTS</b><p>pair order · sign · pixel units</p></article><i>→</i><article><span>02</span><b>DEPTH EXTRACTION</b><p>camera Z · background semantics</p></article><i>→</i><article><span>03</span><b>OWNERSHIP</b><p>Cryptomatte / stable layer ID</p></article><i>→</i><article><span>04</span><b>D9.1 ADAPTER</b><p>fresh real-pass holdout</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/layer-depth-temporal-accumulation-holdout-v0-1/results.json`}><span>MACHINE RESULT</span><b>SUPPORTED · 30 / 30 ↗</b></a><a href={`${repo}experiments/layer-depth-temporal-accumulation-holdout-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>PASS · exact replay ↗</b></a><a href={`${repo}research/2026-08-27-b52-d9-1-layer-depth-temporal-accumulation-holdout-result.md`}><span>RESULT NOTE</span><b>metrics · non-claims · next ↗</b></a><a href={`${repo}specs/layer-depth-temporal-accumulation-holdout.v0.1.json`}><span>FROZEN SPEC</span><b>fresh fixtures · 30 attacks ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B52-D9.1 Temporal Research</b></div><p>D9 counterexample retained · D9.1 exact holdout supported · real Blender pass adapter next</p><Link href="/journal">继续看实验日志 →</Link></footer>
  </main>;
}
