import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const methods = [
  { id: 'NATURAL32', renders: 144, seconds: 24.378508, ratio: 1, carrier: '27.49 MB', color: 'natural' },
  { id: 'Q4', renders: 576, seconds: 96.557780, ratio: 3.961, carrier: '25.42 MB', color: 'q4' },
  { id: 'Q8', renders: 1152, seconds: 194.590571, ratio: 7.982, carrier: '24.46 MB', color: 'q8' },
];
const permutations = ['N · Q4 · Q8','N · Q8 · Q4','Q4 · N · Q8','Q4 · Q8 · N','Q8 · N · Q4','Q8 · Q4 · N'];
const chain = [
  ['01','FRESH SOURCE','13 unique Blender PIDs','1,872 float32 EXR'],
  ['02','SCENE-LINEAR','equal-weight ACEScg','432 composite EXR'],
  ['03','DISPLAY','pinned ACES 2 SDR','432 RGBA PNG8'],
  ['04','CARRIER','lossless VP9 gbrp','432/432 RGB exact'],
  ['05','HUMAN','salted blind sessions','0/18 responses'],
];

export const metadata: Metadata = {
  title: 'B34 NATURAL / Q4 / Q8 独立盲评包｜Blender Film Studio',
  description: '13 个真实 Blender PID、1,872 次渲染与三条 RGB-exact carrier 已完成；public carrier-hash join 可解盲 18/18 session，因此不得从 B34 收集正式人类结果。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/human-quadrature-review-v0-1/' },
};

export default function HumanQuadratureReviewPage() {
  return <main className="contact-page factorial-page human-q-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B34 导航"><Link href="/journal">实验日志</Link><Link href="/quadrature-temporal-holdout-v0-1">B33 数值门</Link><a href="#chain">证据链</a><a href="#carrier">载体</a><a href="#blind">盲法</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Human Review 0.1</span></header>

    <section className="contact-hero human-q-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B34 · PUBLIC BLINDING COUNTEREXAMPLE</p><h1>载体准备好了。<br/><span>公开哈希击穿盲法。</span></h1><p>13 个真实 Blender PID 与三条 lossless carrier 全部过工程门；但 public manifest 和 observer HTML 可以按 carrier SHA 关联，18/18 session 无需 sealed mapping 即被解盲。因此正式人类收集在开始前停止。</p></div><aside className="contact-gate human-q-gate"><b>SUPERSEDING STATUS</b><strong>DO NOT<br/>COLLECT</strong><code>PUBLIC SHA JOIN · 18 / 18</code><code>SEALED MAPPING NOT USED</code><small>ENGINEERING EVIDENCE RETAINED</small></aside><div className="contact-stats"><article><strong>432/432</strong><span>carrier RGB exact</span><small>engineering fact retained</small></article><article><strong>18/18</strong><span>sessions unblinded</span><small>public hash join</small></article><article><strong>0/18</strong><span>formal observers</span><small>collection stopped</small></article><article><strong>0.0</strong><span>composite float error</span><small>independent audit · 432</small></article></div></section>

    <section className="section human-q-chain" id="chain"><div className="section-index">00 / 从渲染到观察者，不跳步</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> IMMUTABLE EVIDENCE CHAIN</p><h2>每一层有自己的事实。<br/><span>盲法失败会阻断下一层。</span></h2></div><p>scene-linear exact、carrier exact、播放器可用、blinding integrity 和人类偏好是不同的事。前三层已经实测；public-hash attack 在观察者之前截断证据链，因此第五层保持空白。</p></div><div className="human-q-flow">{chain.map(([id,title,detail,count],index)=><article className={index===4?'pending':''} key={id}><span>{id}</span><b>{title}</b><p>{detail}</p><small>{index===4?'BLOCKED BY PUBLIC HASH JOIN':count}</small></article>)}</div><div className="human-q-separation"><div><b>FACT</b><span>载体逐帧无损</span><code>432 / 432 · RGB exact</code></div><i>≠</i><div><b>INVALID ROUTE</b><span>现有 session 可公开解盲</span><code>18 / 18 · do not collect</code></div></div></section>

    <section className="section human-q-render" id="render"><div className="section-index light">01 / 一条六秒序列，十三个真实进程</div><div className="contact-heading"><div><p className="eyebrow"><span/> BLENDER 5.2 · FRAME 1–144</p><h2>不是三次视频模型调用。<br/><span>是 1,872 次可追溯 render。</span></h2></div><p>每个 jitter component 在独立 Blender PID 中完成 144 帧；Q4 与 Q8 只在 ACEScg scene-linear float 中等权平均。motion blur 关闭，因此本轮不验证运动模糊。</p></div><div className="human-q-methods">{methods.map(item=><article className={item.color} key={item.id}><header><span>{item.id}</span><b>{item.ratio.toFixed(3)}× observed time</b></header><strong>{item.renders.toLocaleString()}</strong><p>render calls / EXR</p><div><i style={{width:`${item.renders/1152*100}%`}}/></div><footer><span>{item.seconds.toFixed(3)} s</span><small>{item.carrier} carrier</small></footer></article>)}</div><div className="contact-nonclaim"><b>COST BOUNDARY</b><p>这里的倍数来自这一台 M4 Max、这一场景和 Blender 自报源渲染时间。Q8 的数值 proxy 接近 NATURAL，不代表它免费；本轮实测仍接近八倍源 render。</p></div></section>

    <section className="section human-q-carrier" id="carrier"><div className="section-index">02 / “lossless”必须解码后再证明</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> VP9 PROFILE 1 · GBRP</p><h2>不相信编码参数。<br/><span>比较解码后的每个像素。</span></h2></div><p>三条 WebM 都重新解码为 144 张 RGB PNG，与固定 ACES 2 display PNG 逐帧比较。随后又 fresh decode 到第二个目录，三个 roundtrip report 全部 byte exact。</p></div><div className="human-q-carrier-grid"><article><span>NATURAL32</span><strong>7d09a539…071d8</strong><b>144 / 144 EXACT</b><small>27,491,693 bytes</small></article><article><span>Q4</span><strong>76c97538…2fed0</strong><b>144 / 144 EXACT</b><small>25,417,613 bytes</small></article><article><span>Q8</span><strong>919b8c3d…4149c</strong><b>144 / 144 EXACT</b><small>24,463,879 bytes</small></article></div><div className="human-q-display"><span>ACEScg FLOAT</span><i>→</i><span>ACES 2 SDR<br/><small>100 nits · Rec.709</small></span><i>→</i><span>PNG8 RGBA</span><i>→</i><span>VP9 GBRP</span><i>→</i><strong>RGB Δ = 0</strong></div></section>

    <section className="section human-q-blind" id="blind"><div className="section-index light">03 / 被新攻击击穿的盲法假设</div><div className="contact-heading"><div><p className="eyebrow"><span/> PUBLIC METHOD SHA + OBSERVER CLIP SHA</p><h2>页面没有写方法名。<br/><span>相同 SHA 仍能完成 join。</span></h2></div><p>salted mapping 与 response-first unblind 顺序本身没有泄漏；失败来自另一条公开路径。仓库 manifest 映射方法到 carrier SHA，observer HTML 映射 CLIP 到 carrier SHA。两表关联即可恢复方法。</p></div><div className="human-q-hash-attack"><article><span>PUBLIC MANIFEST</span><strong>METHOD → SHA</strong><small>tracked before collection</small></article><i>⋈</i><article><span>OBSERVER HTML</span><strong>CLIP → SHA</strong><small>distributed session data</small></article><i>→</i><article className="fail"><span>RECOVERED</span><strong>CLIP → METHOD</strong><small>18 / 18 sessions</small></article></div><div className="human-q-permutations">{permutations.map((item,index)=><article key={item}><span>ORDER {String(index+1).padStart(2,'0')}</span><strong>{item}</strong><small>RECOVERABLE · DO NOT DISTRIBUTE</small></article>)}</div></section>

    <section className="section human-q-audit"><div className="section-index">04 / 审计也允许失败</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> FAILURE RETAINED · CLEAN RERUN</p><h2>第一次 audit 没有被美化。<br/><span>它因一个变量名退出。</span></h2></div><p>首轮 package audit 在写报告前触发 `ReferenceError`：累计变量是 changedPixels，输出误写 changedRgbPixels。修复先提交，再净重跑；正式载体没有重算或替换。</p></div><div className="human-q-audit-grid"><article className="fail"><span>ATTEMPT 01</span><strong>REPORT BUG</strong><code>ReferenceError · no output</code><small>retained in journal</small></article><article><span>PACKAGE AUDIT</span><strong>PASS</strong><code>1,872 + 432 + 432 files</code><small>18 sessions · mapping sealed</small></article><article><span>FLOAT AUDIT × 2</span><strong>BYTE EXACT</strong><code>max error 0.0</code><small>432 / 432 composites</small></article></div></section>

    <section className="section contact-limits human-q-boundary" id="boundary"><div className="section-index">05 / 当前真正缺的是什么</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ENGINEERING READY ≠ STUDY READY</p><h2>现在不能收人。<br/><span>必须先生成新 realization。</span></h2></div><p>浏览器 pilot 仍证明 UI 可以工作，但已公开的三条 carrier identity 不能再进入严谨盲评。下一版必须在收满并锁定 18 份 response 前延迟披露所有 method-labelled hash。</p></div><div className="contact-checks"><article><span>SUPPORTED</span><h3>Source + composite</h3><p>13 PID、1,872 render；432 个 float composite 独立重算 exact。</p><b>RETAIN</b></article><article><span>SUPPORTED</span><h3>Carrier + interface</h3><p>三条 RGB exact；播放器实际 decoded 144 / dropped 0。</p><b>RETAIN</b></article><article><span>FALSIFIED</span><h3>Public blinding</h3><p>carrier SHA 跨 public manifest 与 observer HTML 关联，18/18 可恢复。</p><b>DO NOT COLLECT</b></article><article><span>OUT OF SCOPE</span><h3>Cinematic merit</h3><p>叙事、表演、4K、motion blur、跨镜头与整体电影感未验证。</p><b>NOT CLAIMED</b></article></div><div className="human-q-decision"><header><span>NEXT PROTOCOL · DELAYED DISCLOSURE</span><b>NEW VISUAL REALIZATION REQUIRED</b></header><div><article><strong>BEFORE</strong><p>公开 protocol、工具 identity、opaque package commitment</p><small>NO METHOD HASH</small></article><article><strong>COLLECT</strong><p>18 份 response 先 canonical hash-lock</p><small>MAPPING STAYS SEALED</small></article><article><strong>AFTER</strong><p>再公开 method outputs、hash 与 unblinded analysis</p><small>VERIFY COMMITMENT</small></article></div></div><div className="contact-artifacts"><a href={`${repo}experiments/human-quadrature-review-v0-1/evidence/public-hash-unblinding-audit.json`}><span>BLINDING FAILURE</span><b>18 / 18 recovered ↗</b></a><a href={`${repo}specs/human-quadrature-review-spec.v0.1.json`}><span>FROZEN SPEC</span><b>original boundary ↗</b></a><a href={`${repo}experiments/human-quadrature-review-v0-1/results.json`}><span>PACKAGE RESULT</span><b>engineering evidence ↗</b></a><a href={`${repo}experiments/human-quadrature-review-v0-1/evidence/independent-composite-audit.json`}><span>FLOAT AUDIT</span><b>432 / 432 exact ↗</b></a><a href={`${repo}research/2026-08-26-b34-human-quadrature-review-package-result.md`}><span>SUPERSEDING NOTE</span><b>failure · mitigation · limits ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B34 Public-blinding Counterexample</b></div><p>engineering evidence retained · formal collection stopped before observer 1</p><Link href="/delayed-disclosure-review-v0-2">进入 B35 delayed-disclosure 修订 →</Link></footer>
  </main>;
}
