import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const packageCommitment = '5ab10b6e97fa1fda1480b48582d7b723cce651aa8bf34f8d5e2e20365c8b5001';
const registryCommitment = 'c1ce83b0a168327b01738a3cd8db1074952cc0bd3804f43fec690ae85b9ea2e9';
const stages = [
  ['01','REAL BLENDER','13 fresh PIDs','1,872 source renders'],
  ['02','FLOAT PIPELINE','432 composites','432 ACES 2 display PNG'],
  ['03','PRIVATE CARRIER','3 lossless sequences','432 / 432 RGB exact'],
  ['04','PUBLIC GATE','3,226 sensitive IDs','0 public matches'],
  ['05','HUMAN','collection not open','0 / 18 responses'],
];

export const metadata: Metadata = {
  title: 'B35 延迟披露人类盲评｜Blender Film Studio',
  description: '真实 Blender 5.2 新 realization、3,226 项敏感身份零公开匹配；private package 已验证，但正式人类采集尚未开放。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/delayed-disclosure-review-v0-2/' },
};

export default function DelayedDisclosureReviewPage() {
  return <main className="contact-page factorial-page delayed-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B35 导航"><Link href="/journal">实验日志</Link><Link href="/human-quadrature-review-v0-1">B34 反例</Link><a href="#repair">盲法修复</a><a href="#evidence">证据</a><a href="#gate">采集门</a></nav><span className="edition contact-edition">Human Review 0.2</span></header>

    <section className="contact-hero delayed-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B35 · DELAYED DISCLOSURE</p><h1>包已经验证。<br/><span>身份仍然密封。</span></h1><p>新 52 mm realization 已由真实 Blender 5.2 完成，载体与独立审计全部过门；但方法、CLIP 与视觉 hash 的关联仍只存在 private work。公开面只有 salted commitments 与聚合计数，所以现在仍不是人类结论。</p></div><aside className="contact-gate delayed-gate"><b>CURRENT GATE</b><strong>COLLECTION<br/>NOT OPEN</strong><code>PUBLIC MATCHES · 0</code><code>HUMAN RESPONSES · 0 / 18</code><small>PRIVATE PACKAGE VALIDATED</small></aside><div className="contact-stats"><article><strong>13</strong><span>真实 Blender PID</span><small>all unique</small></article><article><strong>1,872</strong><span>source renders</span><small>fresh EXR32</small></article><article><strong>3,226</strong><span>sensitive identities</span><small>salted registry</small></article><article><strong>0</strong><span>public matches</span><small>exact head audit</small></article></div></section>

    <section className="section delayed-repair" id="repair"><div className="section-index">00 / 不是隐藏失败，而是从失败改设计</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> B34 COUNTEREXAMPLE → B35 CONTROL</p><h2>相同 SHA 能解盲。<br/><span>那就延迟公开可连接身份。</span></h2></div><p>B34 的 public method→carrier SHA 与 observer CLIP→SHA 可直接 join。B35 没有把 mapping 换一个目录就宣布安全；它把 disclosure order 写成正式实验变量，并让任何提前 join 使整项研究失效。</p></div><div className="delayed-join"><article className="old"><span>B34 · PUBLIC</span><strong>METHOD → SHA</strong><small>⋈ CLIP → SHA</small><b>18 / 18 UNBLINDED</b></article><i>→</i><article><span>B35 · BEFORE CLOSE</span><strong>SALTED COMMITMENT</strong><small>no method / CLIP identity</small><b>0 / 3,226 MATCHES</b></article><i>→</i><article className="future"><span>AFTER CLOSE ONLY</span><strong>OPEN + VERIFY</strong><small>mapping · salt · analysis</small><b>18 LOCKED OR ABORT</b></article></div></section>

    <section className="section delayed-realization"><div className="section-index light">01 / 新画面，不复用已经泄露的 carrier</div><div className="contact-heading"><div><p className="eyebrow"><span/> METHOD-SYMMETRIC INTERVENTION</p><h2>每个进程先验证 50 mm。<br/><span>再只在内存中设为 52 mm。</span></h2></div><p>源 `.blend`、camera transform 与 timeline 不变；lens 干预对 NATURAL、Q4、Q8 完全相同。它的目的不是声称画质更好，而是创建不能与 B34 公开 identity 相等的新视觉 realization。</p></div><div className="delayed-lens"><article><span>SOURCE</span><strong>50.0<small> mm</small></strong><p>required observed lens</p></article><i>+2.0 mm</i><article className="active"><span>IN-MEMORY</span><strong>52.0<small> mm</small></strong><p>all 13 fresh processes</p></article><article><span>SOURCE FILE</span><strong>BYTE<br/>UNCHANGED</strong><p>no saved intervention</p></article></div><div className="delayed-distinct"><span>NEW IDENTITY GATE</span><b>432 / 432 display frames distinct from B34</b><b>3 / 3 carriers distinct from B34</b></div></section>

    <section className="section delayed-evidence" id="evidence"><div className="section-index">02 / 私有证据照常严格，公开证据故意最小</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> TWO-SURFACE EVIDENCE MODEL</p><h2>不是少做审计。<br/><span>是把可解盲证据延迟披露。</span></h2></div><p>完整 EXR、composite、decoded frames、mapping 和 session 仍被逐项验证，只是不在 collection close 前进入公开树。公开 commitment 能事后证明这些私有字节没有被替换。</p></div><div className="delayed-flow">{stages.map(([id,title,detail,count],index)=><article className={index===4?'pending':''} key={id}><span>{id}</span><b>{title}</b><p>{detail}</p><small>{count}</small></article>)}</div><div className="delayed-surfaces"><article><header><span>PRIVATE · UNTIL CLOSE</span><b>FULL EVIDENCE</b></header><ul><li>method-labelled EXR / PNG / WebM identities</li><li>decoded frames and pixel bindings</li><li>mapping, salt and observer sessions</li><li>accepted responses during collection</li></ul></article><article className="public"><header><span>PUBLIC · NOW</span><b>NON-JOINABLE</b></header><ul><li>preregistered protocol and tool source</li><li>salted package commitment</li><li>salted registry commitment</li><li>aggregate counts and zero-match audit</li></ul></article></div></section>

    <section className="section delayed-audit"><div className="section-index light">03 / 先攻击，再允许页面说“通过”</div><div className="contact-heading"><div><p className="eyebrow"><span/> INDEPENDENT RECOMPUTATION</p><h2>注入一个敏感值，<br/><span>scanner 必须真的失败。</span></h2></div><p>攻击 surface 中放入一个 registry value 时，公开面审计返回 FAIL；干净 commit 则为 0 match。另有独立 Node audit 与两次 factory-startup Blender float 重算，避免 runner 只验证自己写出的摘要。</p></div><div className="delayed-audit-grid"><article className="attack"><span>INJECTION ATTACK</span><strong>DETECTED</strong><code>expected FAIL · observed FAIL</code><small>1 sensitive value on test surface</small></article><article><span>PRIVATE PACKAGE</span><strong>PASS</strong><code>1,872 + 432 + 432 + 432</code><small>18 sessions rebound</small></article><article><span>FLOAT AUDIT × 2</span><strong>BYTE EXACT</strong><code>max error 0.0</code><small>432 / 432 composites</small></article><article><span>PUBLIC TREE</span><strong>0 MATCH</strong><code>3,226 identities</code><small>0 tracked private paths</small></article></div></section>

    <section className="section contact-limits delayed-gate-section" id="gate"><div className="section-index">04 / 工程门可测，人类结论不可代填</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ENGINEERING READY ≠ HUMAN EVIDENCE</p><h2>现在仍是 0/18。<br/><span>不能把 developer pilot 算作 observer。</span></h2></div><p>真实浏览器 pilot 已让三条匿名 clip 各完成 2/2，汇总 dropped 0，画面实测 960×540，且没有原生 controls 或身份文字。最终公开 source 发布前仍须对精确状态复扫；正式采集继续锁定。</p></div><div className="delayed-gates"><article className="done"><span>PASS</span><b>PRIVATE PACKAGE</b><p>real Blender · exact carrier · independent audits</p></article><article><span>NEXT</span><b>FINAL PUBLIC HEAD</b><p>publish exact source, then rerun 3,226-value leak scan</p></article><article className="done"><span>PASS</span><b>INTERFACE PILOT</b><p>3 clips × 2 plays · dropped 0 · response unlocked</p></article><article className="locked"><span>LOCKED</span><b>FORMAL COLLECTION</b><p>18 independent observers; audit before every accept</p></article></div><div className="delayed-commitments"><article><span>PACKAGE COMMITMENT</span><code>{packageCommitment}</code></article><article><span>SENSITIVE REGISTRY COMMITMENT</span><code>{registryCommitment}</code></article></div><div className="contact-nonclaim"><b>NON-CLAIM</b><p>participant blind 不等于 operator double-blind。远程显示器不统一；motion blur、4K、跨镜头/机器、表演、叙事、photorealism 与整体电影感仍未由本实验验证。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/human-quadrature-review-v0-2/precollection-commitment.json`}><span>PUBLIC COMMITMENT</span><b>non-joinable evidence ↗</b></a><a href={`${repo}specs/human-quadrature-review-spec.v0.2.json`}><span>FROZEN SPEC</span><b>delayed disclosure v0.2 ↗</b></a><a href={`${repo}research/2026-08-26-b35-delayed-disclosure-human-review-protocol.md`}><span>PROTOCOL</span><b>falsification gates ↗</b></a><a href={`${repo}research/2026-08-26-b35-delayed-disclosure-package-result.md`}><span>PACKAGE RESULT</span><b>facts · unknowns · next ↗</b></a></div></section>

    <footer><div><span className="brand-mark">BFS</span><b>B35 Delayed Disclosure Review</b></div><p>private package validated · collection not open · human 0/18</p><Link href="/journal">继续看实验日志 →</Link></footer>
  </main>;
}
