import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = { title: 'B11 资产净化｜Data-only .blend｜Blender Film Studio', description: '对 hash-valid Blender 资产注入隐藏 driver、shape-key driver、constraint、rigid body、action、linked library 与 override，并验证 append 后净化。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/asset-security-v0-1/' } };
const attacks = [['N01','object driver'],['N02','shape-key driver'],['N03','object constraint'],['N04','rigid body'],['N05','pre-existing action'],['N06','linked library'],['N07','library override'],['N08','combined asset'],['N09','autoexec enabled']];

export default function AssetSecurityV01Page() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B11 导航"><Link href="/security-v0-1">B10 路径</Link><Link href="/trajectory-v0-2">B08 编译</Link><a href="#inventory">基线</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Asset Security 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B11 · APPENDED ASSET SANITIZATION</p><h1>哈希证明字节没变。<br /><span>不证明资产没有行为。</span></h1><p>首轮攻击把 driver、约束、刚体和 action 藏进一个 SHA 完全匹配的 SET 资产，编译器仍成功输出场景。B11 在 append 后、任何正式编译操作前检查资产的求值结构。</p></div><aside className="contact-gate"><b>CURRENT STATUS</b><strong>FORMAL B11<br />TRUE</strong><code>first run: compiled hidden behavior</code><code>after fix: 9 / 9 rejected</code><small>no malicious executable code used</small></aside><div className="contact-stats"><article><strong>9</strong><span>既有资产审计</span><small>B01–B08 pinned set</small></article><article><strong>6</strong><span>窄 rig 白名单</span><small>head + gaze only</small></article><article><strong>9 / 9</strong><span>攻击被拒绝</span><small>evaluation + library + autoexec</small></article><article><strong>0</strong><span>基线非法发现</span><small>after typed classification</small></article></div></section>
    <section className="section contact-verdict"><div className="section-index">00 / 两种完整性</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> BYTE INTEGRITY ≠ BEHAVIORAL INTEGRITY</p><h2>BuildPlan 锁文件，<br /><span>Blender 锁求值结构。</span></h2></div><p>SHA 能阻止换包，却不能判断包里本来就有什么。路径和哈希验证发生在 JavaScript；资产内部 driver、constraint、physics 和 library 依赖只能在 Blender append 后被检查。</p></div><div className="contact-flow"><article><span>01</span><b>PATH + SHA</b><p>exact declared bytes</p></article><i>→</i><article><span>02</span><b>APPEND</b><p>no compiler edits yet</p></article><i>→</i><article><span>03</span><b>SANITIZE</b><p>typed behavior allowlist</p></article></div></section>
    <section className="section contact-contract" id="inventory"><div className="section-index">01 / 已锁定资产基线</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> TYPE-SENSITIVE POLICY</p><h2>SET / PROP 必须纯净。<br /><span>CHARACTER 只开窄门。</span></h2></div><p>B03/B04 各有一个 `BFS_HEAD_LIMIT` 与两条 `BFS_GAZE_*`，目标仍在同一集合；角色 mesh 只允许指向内部 rig 的 ARMATURE modifier。其它 action、driver、constraint、physics、外链与 override 都停止。</p></div><div className="contact-boundary"><b>ALLOWED</b><span>mesh + materials</span><span>internal armature</span><span>head limit</span><span>internal gaze</span><strong>EVERYTHING ELSE DENY</strong></div><div className="contact-plan"><span>POSITIVE STRUCTURE</span><code>c699fc27230d…b7f0b</code><b>B01 UNCHANGED</b><b>B03 · B05 · B08 REGRESSED</b></div></section>
    <section className="section contact-diagnostic"><div className="section-index">02 / 反例</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> INSPECT BEFORE AUTHORING</p><h2>编译器自己还没加行为前，<br /><span>先确认资产没有偷带行为。</span></h2></div><p>每个反例都具有合法路径和精确文件哈希。linked-library 反例同时暴露未锁定依赖；autoexec 反例验证显式开启脚本会立即停止。</p></div><ol className="contact-negative-list">{attacks.map(([id,item]) => <li key={id}><span>{id}</span><b>{item}</b><small>REJECTED</small></li>)}</ol></section>
    <section className="section contact-limits" id="boundary"><div className="section-index">03 / 未关闭边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> PARSED IS NOT SANDBOXED</p><h2>B11 看见了行为结构，<br /><span>还没有隔离解析器。</span></h2></div><p>Blender 仍需先解析主 `.blend` 才能审计。资源耗尽、解析器漏洞、复杂 Geometry Nodes 语义、恶意包和 OS 权限必须在后续进程沙箱、预算与签名资产层继续处理。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/asset-security-v0-1/first-run-falsified.json`}><span>FIRST RUN</span><b>隐藏行为编译成功 ↗</b></a><a href={`${repo}experiments/asset-security-v0-1/results.json`}><span>RESULT</span><b>修复后 9/9 ↗</b></a><a href={`${repo}experiments/asset-security-v0-1/pinned-asset-inventory.json`}><span>INVENTORY</span><b>9 个资产白名单 ↗</b></a><a href={`${repo}research/2026-08-26-b11-asset-sanitization-result.md`}><span>RESULT NOTE</span><b>结论与边界 ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B11 Data-only Asset Sanitizer</b></div><p>First run falsified · typed sanitizer pass · parser sandbox still open</p><Link href="/security-v0-1">返回 B10 →</Link></footer>
  </main>;
}
