import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical='https://lovejzzz.github.io/BlenderFilmStudio/blender-static-interior-risk-localization-v0-1/';
const socialImage='https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-5/wedge-panel-beauty.png';
export const metadata:Metadata={title:'B52-D12.6 局部风险定位｜Blender Film Studio',description:'92,763 个真实 Blender 派生 RGB 样本：局部对比度风险界零低估，并以极低选择率覆盖全部半阈值尾部。',alternates:{canonical},openGraph:{title:'B52-D12.6 局部风险定位',description:'距离不是共同机制；Vector 权重 × 局部颜色梯度才是。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'B52-D12.6 局部风险定位',description:'零低估 · 18/18 attacks · adaptive holdout next',images:[socialImage]}};
const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const cells=[
  {id:'WEDGE / PANEL',image:'wedge-panel',r2:'5,986',r3:'5,350',max:'1.2517e−6',rho:'0.918–0.921',distance:'d17 + d11',selected:'5 / 5',actual:'4 / 4'},
  {id:'NESTED CURVES',image:'nested-curves',r2:'3,760',r3:'3,133',max:'4.7684e−7',rho:'0.922–0.928',distance:'d3 → d4/5/6',selected:'0 / 0',actual:'0 / 0'},
  {id:'CROSSING RODS',image:'crossing-rods',r2:'6,682',r3:'6,010',max:'1.1325e−6',rho:'0.894–0.901',distance:'d4',selected:'7 / 2',actual:'3 / 2'},
] as const;

export default function BlenderStaticInteriorRiskLocalizationPage(){return <main className="contact-page d126-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.6 导航"><Link href="/blender-static-radius-intervention-v0-1">D12.5</Link><a href="#verdict">结论</a><a href="#mechanism">算术</a><a href="#selectivity">选择率</a><a href="#boundary">边界</a><Link href="/blender-static-adaptive-risk-gate-v0-1">D12.7</Link><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Localization D12.6</span></header>
  <section className="contact-hero d126-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.6-C2 · ZERO-RENDER ARITHMETIC REPLAY</p><h1>距离不是共同机制。<br/><span>局部梯度才是。</span></h1><p>把 D12.5 的真实 scene-linear float32 数组逐像素重放：微小 Vector 权重乘上同主体颜色差，足以制造 d17、d11 与 d4 的内部尾部。</p></div><aside className="contact-gate d126-gate"><b>FORMAL VERDICT</b><strong>BOUND<br/>CONSERVATIVE</strong><code>actual error ≤ local risk</code><code>92,763 RGB samples</code><small>adaptive rule not yet validated</small></aside><div className="contact-stats"><article><strong>92,763</strong><span>内部 RGB 样本</span><small>3 fixtures × 2 radii</small></article><article><strong>0</strong><span>风险界低估</span><small>all registered samples</small></article><article><strong>18 / 18</strong><span>mutation attacks</span><small>independent audit</small></article><article><strong>0</strong><span>新 Blender render</span><small>read-only committed arrays</small></article></div></section>
  <section className="section d126-verdict" id="verdict"><div className="section-index">00 / WHAT CHANGED</div><div className="contact-heading"><div><p className="eyebrow"><span/> FROM GLOBAL DISTANCE TO LOCAL RISK</p><h2>半径 3 删除一整圈。<br/><span>风险界只标记真正危险的点。</span></h2></div><p>注册的通道风险是四个双线性 tap 相对当前中心的加权绝对差，再加 pre-cast 量级的一整 ULP。它在开发证据上是保守上界，同时与真实误差保持 0.894–0.928 的秩相关。</p></div><div className="d126-equation"><span>RISK<sub>c</sub>(p)</span><strong>Σ |wᵢ| · |tapᵢ,c − center<sub>c</sub>|</strong><i>+</i><b>1 float32 ULP</b><code>pixel risk = max(R, G, B)</code></div><div className="d126-claims"><article><span>SAFETY</span><strong>0 / 92,763</strong><b>underbounds</b><p>实际绝对误差从未超过注册风险界。</p></article><article><span>TIGHTNESS · MEDIAN</span><strong>1.60–1.69×</strong><b>bound / nonzero actual</b><p>p95 为 2.41–2.50×；极小误差会产生更大比例。</p></article><article><span>HALF-GATE RECALL</span><strong>100%</strong><b>13 / 13 actual positives</b><p>跨两种半径全部捕获，但这仍是开发集观察。</p></article></div></section>
  <section className="section d126-mechanism" id="mechanism"><div className="section-index">01 / PIXEL ARITHMETIC</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> TINY WEIGHT × LOCAL CONTRAST</p><h2>不是物体边缘漏进来。<br/><span>是同一物体内部的颜色斜率。</span></h2></div><p>下面两处 radius 3 仍保留的极值揭示同一个算术结构。轮廓距离分别是 17 和 4，却都由约 10⁻⁵ 的 Vector 权重乘以约 10⁻² 的局部颜色差主导。</p></div><div className="d126-arithmetic"><article><header><span>WEDGE / PANEL · BLUE</span><b>d17 · owner 11117</b></header><div><code>w(x+1) = 2.28881e−5</code><i>×</i><code>ΔB = +0.04794</code><i>≈</i><strong>+1.09719e−6</strong></div><p>再叠加上方 tap 的 +1.72309e−7，float32 cast 后得到 1.2516975e−6 的正式误差。</p></article><article><header><span>CROSSING RODS · GREEN</span><b>d4 · owner 11791</b></header><div><code>w(x+1) = 3.05175e−5</code><i>×</i><code>ΔG = −0.03036</code><i>≈</i><strong>−9.26417e−7</strong></div><p>再叠加上方 tap 的 −2.33714e−7，最终得到 1.1324883e−6；加大轮廓侵蚀不改变它。</p></article></div><div className="d126-distance-line"><span>SILHOUETTE DISTANCE</span>{['d3','d4','d5','d6','d11','d17'].map((d,index)=><i key={d} className={index===1||index>3?'hot':''}>{d}</i>)}<b>多个距离，同一种局部算术</b></div></section>
  <section className="section d126-cells"><div className="section-index">02 / SIX PRIMARY CELLS</div><div className="contact-heading"><div><p className="eyebrow"><span/> COMMITTED BEAUTY · READ-ONLY NUMBERS</p><h2>同一画面，两种资格域。<br/><span>每个极值都完整枚举。</span></h2></div><p>图像沿用 D12.5 的正式 EXR display proxy，仅帮助辨认几何；D12.6 的结论来自已提交数组。表中 selected / actual 按 radius 2 / radius 3 给出半阈值像素数。</p></div><div className="d126-cell-grid">{cells.map(cell=><article key={cell.id}><Image src={`${basePath}/evidence/b52-d12-5/${cell.image}-beauty.png`} width={596} height={388} unoptimized alt={`${cell.id} Blender display proxy`}/><header><strong>{cell.id}</strong><code>{cell.distance}</code></header><dl><div><dt>R2 / R3</dt><dd>{cell.r2} / {cell.r3}</dd></div><div><dt>MAX</dt><dd>{cell.max}</dd></div><div><dt>SPEARMAN</dt><dd>{cell.rho}</dd></div><div><dt>SELECT / ACTUAL</dt><dd>{cell.selected} / {cell.actual}</dd></div></dl></article>)}</div></section>
  <section className="section d126-selectivity" id="selectivity"><div className="section-index">03 / SAFETY VERSUS COST</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> HALF-GATE · 1 / 1,048,576</p><h2>全局再侵蚀一圈，<br/><span>还是只拒绝十几个像素？</span></h2></div><p>风险界给出一个可证伪的新方向：保留 radius 2 的覆盖，只拒绝 risk 超门的局部样本。在当前开发集，它以万分之一量级的选择率覆盖所有半阈值超标点。</p></div><div className="d126-select-table"><div className="head"><b>DOMAIN</b><b>INTERIOR</b><b>ACTUAL &gt; HALF</b><b>RISK SELECTED</b><b>RECALL</b><b>SELECTED FRACTION</b></div><div><strong>RADIUS 2</strong><code>16,428</code><code>7</code><code>12</code><b>100%</b><small>0.0730%</small></div><div><strong>RADIUS 3</strong><code>14,493</code><code>6</code><code>7</code><b>100%</b><small>0.0483%</small></div></div><div className="d126-choice"><article><span>GLOBAL RADIUS 3</span><strong>−1,935 px</strong><p>删除所有 ring-3 像素，仍无法处理 d17/d11/d4 内部尾部。</p></article><i>VS</i><article className="candidate"><span>R2 + LOCAL RISK</span><strong>−12 px</strong><p>开发集半阈值候选；必须在 unseen fixture 上重新验证。</p></article></div></section>
  <section className="section d126-boundary" id="boundary"><div className="section-index">04 / EVIDENCE BOUNDARY</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> DERIVED HERE · VALIDATE NEXT</p><h2>数学上安全，<br/><span>不等于生产上已验证。</span></h2></div><p>风险公式与阈值都在 D12.5-C2 开发证据上被看见。D12.6 只能批准下一次 holdout，不能把同一批像素循环包装成独立证明。</p></div><div className="d126-timeline"><article className="invalid"><span>D12.6</span><strong>INVALID</strong><p>边界 tap 顺序 bug；结果写出前退出，根目录永久保留。</p></article><i>→</i><article><span>D12.6-C2</span><strong>DERIVED</strong><p>唯一顺序修正；8/8 checks，18/18 attacks。</p></article><i>→</i><article className="next"><span>D12.7</span><strong>UNSEEN HOLDOUT</strong><p>新几何比较 radius 3 与冻结的 R2 + risk gate。</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-static-interior-risk-localization-c2-v0-1/results.json`}><span>MACHINE RESULT</span><b>92,763 samples ↗</b></a><a href={`${repo}experiments/blender-static-interior-risk-localization-c2-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>18 / 18 attacks ↗</b></a><a href={`${repo}experiments/blender-static-interior-risk-localization-c2-v0-1/receipt.json`}><span>FORMAL RECEIPT</span><b>two unique PIDs ↗</b></a><a href={`${repo}research/2026-08-27-b52-d12-6-c2-interior-risk-localization-result.md`}><span>RESULT NOTE</span><b>adaptive holdout next ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.6 Interior Risk Localization</b></div><p>local bound conservative on development evidence · fresh validation completed</p><Link href="/blender-static-adaptive-risk-gate-v0-1">查看 D12.7 fresh holdout →</Link></footer>
</main>}
