import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical='https://lovejzzz.github.io/BlenderFilmStudio/blender-motion-aware-curvature-risk-v0-1/';
const socialImage='https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-9-d1/camera-parallax-bounds-candidate.png';
export const metadata:Metadata={title:'B52-D12.9-D1 运动感知曲率风险｜Blender Film Studio',description:'从 D12.8 负结果派生 Q30 二阶差分风险：Python/Node 逐字节一致，运动覆盖恢复到 97.48–98.37%；明确标记为 post-hoc，等待新鲜 Blender 5.2 holdout。',alternates:{canonical},openGraph:{title:'B52-D12.9-D1 运动感知曲率风险',description:'静态对比度失败后，Q30 曲率候选恢复运动覆盖；派生成功但尚未盲测。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'B52-D12.9-D1 运动感知曲率风险',description:'10/10 derivation checks · 0 fresh renders · fresh holdout next',images:[socialImage]}};

const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const fixtures=[
  {id:'RIGID OWNER SWEEP',name:'rigid-sweep-disocclusion',raster:'149×97',old:'1,498',next:'8,646',gain:'+7,148',retention:'97.994%',ownerMin:'97.857%',rgb:'1.866657e−5',support:'177',risk:'0'},
  {id:'CAMERA DOLLY / PARALLAX',name:'camera-parallax-bounds',raster:'163×101',old:'0',next:'13,853',gain:'+13,853',retention:'98.374%',ownerMin:'98.156%',rgb:'1.793410e−5',support:'229',risk:'0'},
  {id:'SAME INDEX / DEPTH REVEAL',name:'same-index-depth-reveal',raster:'173×107',old:'1,560',next:'11,544',gain:'+9,984',retention:'97.475%',ownerMin:'97.092%',rgb:'1.465026e−5',support:'202',risk:'97'},
  {id:'STATIC MULTI-OWNER CONTROL',name:'multi-owner-static-control',raster:'127×83',old:'9,045',next:'9,045',gain:'0',retention:'100%',ownerMin:'100%',rgb:'6.610617e−8',support:'0',risk:'0'},
] as const;

export default function BlenderMotionAwareCurvatureRiskPage(){return <main className="contact-page d128-page d129-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.9-D1 导航"><Link href="/blender-projective-motion-disocclusion-adaptive-risk-v0-1">D12.8</Link><a href="#rewrite">公式</a><a href="#evidence">像素</a><a href="#matrix">测量</a><a href="#identity">整数合同</a><a href="#next">盲测</a><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Curvature Risk D12.9-D1</span></header>

  <section className="contact-hero d129-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.9-D1 · POST-HOC DERIVATION</p><h1>梯度不是风险。<br/><span>曲率才接近插值余项。</span></h1><p>D12.8 的真实失败数据被用作派生集：Q30 二阶差分候选把运动 history retention 恢复到 97.48–98.37%，同时保持零 measured risk underbound。它已经可复现，但还没有通过新鲜盲测。</p></div><aside className="contact-gate d129-gate"><b>SCIENTIFIC STATUS</b><strong>CANDIDATE<br/>DERIVED</strong><code>10 / 10 checks</code><code>0 fresh renders</code><small>not yet validated</small></aside><div className="contact-stats"><article><strong>BYTE EXACT</strong><span>Python ↔ Node</span><small>12 / 12 canonical payloads</small></article><article><strong>97.48–100%</strong><span>radius-2 retained</span><small>every owner ≥ 97.092%</small></article><article><strong>0</strong><span>risk underbound samples</span><small>all eligible RGB</small></article><article><strong>2⁻¹⁵</strong><span>quality ceiling</span><small>accepted max · 1.866657e−5</small></article></div></section>

  <section className="section d129-rewrite" id="rewrite"><div className="section-index">00 / CAUSAL REWRITE</div><div className="contact-heading"><div><p className="eyebrow"><span/> FIRST ORDER OUT · SECOND ORDER IN</p><h2>不再问“颜色变了多少”。<br/><span>改问“插值弯曲了多少”。</span></h2></div><p>旧规则把 four taps 到 current center 的绝对差全部相加；运动后的正确对应也会产生很大一阶变化。新候选只看 previous frame 的二阶差分，让线性颜色坡度不再自动成为拒绝理由。</p></div><div className="d129-equation"><article className="old"><span>D12.8 · REJECTED MODEL</span><strong>Σ |wᵢ| · |Pᵢ − C|</strong><code>gradient + transport + interpolation mixed</code><p>camera cell 接受 0 像素；安全来自空域，不具有生产意义。</p></article><i>→</i><article className="new"><span>D12.9-D1 · CANDIDATE</span><strong>4 × ½[fₓ(1−fₓ)Mₓ + fᵧ(1−fᵧ)Mᵧ]</strong><code>previous-frame curvature only</code><p>`Mₓ / Mᵧ` 是 4×4 support 上的最大二阶差分；current RGB 不参与决策。</p></article></div><div className="d129-thresholds"><article><span>RISK GATE</span><strong>2⁻¹³</strong><p>Q30 integer ≤ 131,072</p></article><article><span>QUALITY GATE</span><strong>2⁻¹⁵</strong><p>独立测量，不混入决策</p></article><article><span>CALIBRATION</span><strong>×4 + 512</strong><p>curvature factor + Q30 rounding allowance</p></article></div></section>

  <section className="section d129-evidence" id="evidence"><div className="section-index">01 / SAME PIXELS · DIFFERENT DECISION</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> D12.8 OLD MASK → D12.9-D1 Q30 MASK</p><h2>青色不是合成示意。<br/><span>是被新公式恢复的真实 history。</span></h2></div><p>左图为已冻结 D12.8 adaptive domain；右图由同一批真实 Blender EXR 与新 Q30 integer payload 生成。青色是新恢复、绿色是两者都接受、黄色是 support 不完整、洋红是 curvature-risk rejection。</p></div><div className="d129-gallery">{fixtures.map(f=><article key={f.id}><header><div><span>{f.id}</span><b>{f.raster}</b></div><code>{f.old} → {f.next}</code></header><div><figure><Image src={`${basePath}/evidence/b52-d12-8/${f.name}-adaptive.png`} width={519} height={321} alt={`${f.id} D12.8 旧 adaptive mask`} unoptimized/><figcaption>D12.8 · STATIC CONTRAST</figcaption></figure><figure><Image src={`${basePath}/evidence/b52-d12-9-d1/${f.name}-candidate.png`} width={519} height={321} alt={`${f.id} D12.9-D1 Q30 curvature mask`} unoptimized/><figcaption>D12.9-D1 · Q30 CURVATURE</figcaption></figure></div><footer><strong>{f.gain} recovered</strong><code>{f.retention} RETAINED</code></footer></article>)}</div></section>

  <section className="section d129-matrix" id="matrix"><div className="section-index">02 / DERIVATION MEASUREMENTS</div><div className="contact-heading"><div><p className="eyebrow"><span/> COVERAGE RECOVERED · QUALITY SEPARATE</p><h2>保留率不再靠放弃运动对象。<br/><span>每个 owner 都有样本。</span></h2></div><p>三个 moving cells 和所有有至少 100 个 radius-2 pixels 的 analytic owner 都越过冻结覆盖门。误差只在 analyzer 中测量；候选决策没有读取 current target RGB。</p></div><div className="d129-table"><div className="head"><b>FIXTURE</b><b>OLD</b><b>Q30</b><b>RETENTION</b><b>OWNER MIN</b><b>RGB MAX</b><b>SUPPORT REJECT</b><b>RISK REJECT</b></div>{fixtures.map(f=><div className="row" key={f.id}><strong>{f.id}<small>{f.raster}</small></strong><code>{f.old}</code><code>{f.next}</code><code>{f.retention}</code><code>{f.ownerMin}</code><code>{f.rgb}</code><code>{f.support}</code><code>{f.risk}</code></div>)}</div><div className="d129-caveat"><b>POST-HOC BOUNDARY</b><p>这些 threshold 看过 D12.8 后才被选择，所以 10/10 的含义只是“候选被完整派生并可复跑”，不是“已经泛化”。任何把这里改称 holdout 或 production support 的说法都是越界。</p></div></section>

  <section className="section d129-identity" id="identity"><div className="section-index">03 / CANONICAL CROSS-LANGUAGE CONTRACT</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> FLOAT INPUT · INTEGER DECISION</p><h2>把 1e−19 的语言差异，<br/><span>从合同里彻底移除。</span></h2></div><p>D12.8 的 binary64 risk 出现 300 个末位差异。新协议把 float32 RGB 精确提升为 Q30，把 motion fraction 精确提升为 Q24，所有乘法、ceil 与 saturation 都在整数域执行。</p></div><div className="d129-byte-grid"><article><span>COLOR</span><strong>Q30</strong><code>2³⁰ scale</code><p>声明 `[0,1]` 域内的 previous float32 RGB 必须精确可表示。</p></article><article><span>MOTION FRACTION</span><strong>Q24</strong><code>2²⁴ scale</code><p>`q=(x+Vector.X,y−Vector.Y)` 的小数部分变成精确整数。</p></article><article><span>OUTPUT</span><strong>U32 LE</strong><code>risk.q30.u32</code><p>超过范围 saturation；阈值以上仍然拒绝，不隐藏 overflow。</p></article><article><span>DUAL RESULT</span><strong>12 / 12</strong><code>BYTE IDENTICAL</code><p>四个 fixtures × eligible / accepted / risk 三类 payload。</p></article></div></section>

  <section className="section d129-next" id="next"><div className="section-index">04 / FRESH BLENDER 5.2 HOLDOUT</div><div className="contact-heading"><div><p className="eyebrow"><span/> B52-D12.9-H1 · FREEZE BEFORE RENDER</p><h2>候选已经选完。<br/><span>下一次才是真正的考试。</span></h2></div><p>下一批场景将更换 resolution、transform、material frequency 与 disocclusion geometry。Q30 公式、×4、512 allowance、2⁻¹³ risk gate 与 2⁻¹⁵ quality ceiling 不再调整。</p></div><div className="d128-next-grid"><article><span>01</span><strong>FRESH FIXTURES</strong><p>任何正式 render 前冻结全部场景参数、随机性、路径、工具与 verdict mapping。</p></article><article><span>02</span><strong>TYPED DEPTH</strong><p>valid-history depth accuracy 与 expected depth rejection 分开统计，不再污染同一 aggregate。</p></article><article><span>03</span><strong>OWNER COVERAGE</strong><p>每个 moving analytic owner 都必须跨过非空、有用覆盖门；空域直接失败。</p></article><article><span>04</span><strong>EXACT FALLBACK</strong><p>invalid、support reject 与 risk reject 必须逐字节复制 current float32 RGBA。</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-motion-aware-curvature-risk-derivation-v0-1/results.json`}><span>DERIVATION RESULT</span><b>10 / 10 checks ↗</b></a><a href={`${repo}specs/blender-motion-aware-curvature-risk-derivation.v0.1.json`}><span>MACHINE CONTRACT</span><b>Q30 / Q24 frozen ↗</b></a><a href={`${repo}scripts/derive-b52-d12-9-curvature-risk.py`}><span>PYTHON PRODUCER</span><b>integer algorithm ↗</b></a><a href={`${repo}research/2026-08-27-b52-d12-9-motion-aware-curvature-risk-derivation-result.md`}><span>RESEARCH NOTE</span><b>claims + non-claims ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.9-D1 Motion-Aware Risk</b></div><p>candidate derived · fresh Blender holdout required</p><Link href="/journal">继续看实验日志 →</Link></footer>
</main>}
