import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical='https://lovejzzz.github.io/BlenderFilmStudio/blender-projective-motion-disocclusion-adaptive-risk-v0-1/';
const socialImage='https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-8/rigid-sweep-disocclusion-beauty.png';
export const metadata:Metadata={title:'B52-D12.8 运动与反遮挡压力测试｜Blender Film Studio',description:'16 次真实 Blender 5.2 render：结构拒绝通过，但静态局部风险门在真实运动上仅保留 0–16.98% 历史；C2 独立审计通过，正式结论为不支持。',alternates:{canonical},openGraph:{title:'B52-D12.8 运动与反遮挡压力测试',description:'结构门通过；静态风险门无法泛化到真实运动。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'B52-D12.8 运动与反遮挡压力测试',description:'16 renders · 9/14 scientific checks · C2 audit 16/16',images:[socialImage]}};

const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const fixtures=[
  {id:'RIGID OWNER SWEEP / DISOCCLUSION',name:'rigid-sweep-disocclusion',raster:'149×97',structural:'2,332 owner · 2,400 bounds',r2:'8,823',adaptive:'1,498',retention:'16.978%',rejected:'7,325',vector:'8.3993e−5',depth:'4.1299e−7',rgb:'0',status:'LOW COVERAGE'},
  {id:'CAMERA DOLLY / YAW / PARALLAX',name:'camera-parallax-bounds',raster:'163×101',structural:'984 bounds · 84 owner',r2:'14,082',adaptive:'0',retention:'0%',rejected:'14,082',vector:'5.9024e−5',depth:'4.4263e−7',rgb:'EMPTY',status:'EMPTY DOMAIN'},
  {id:'SAME INDEX / DEPTH REVEAL',name:'same-index-depth-reveal',raster:'173×107',structural:'3,678 depth · 2,513 bounds',r2:'11,843',adaptive:'1,560',retention:'13.172%',rejected:'10,283',vector:'6.7498e−5',depth:'0.289271*',rgb:'2.9802e−8',status:'LOW COVERAGE'},
  {id:'MULTI-OWNER STATIC CONTROL',name:'multi-owner-static-control',raster:'127×83',structural:'207 bounds · 172 owner',r2:'9,045',adaptive:'9,045',retention:'100%',rejected:'0',vector:'2.2888e−5',depth:'2.0298e−7',rgb:'5.9605e−8',status:'CONTROL PASS'},
] as const;

export default function BlenderProjectiveMotionDisocclusionPage(){return <main className="contact-page d128-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.8 导航"><Link href="/blender-static-adaptive-risk-gate-v0-1">D12.7</Link><a href="#verdict">结论</a><a href="#fixtures">真实像素</a><a href="#matrix">测量</a><a href="#audit">审计</a><a href="#next">下一假设</a><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Motion Holdout D12.8</span></header>

  <section className="contact-hero d128-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.8-C1 · REAL PROJECTIVE MOTION</p><h1>结构拒绝有效。<br/><span>静态风险门不适合运动。</span></h1><p>四组未见透视场景、16 次真实 Blender 5.2 Cycles render。owner / bounds / depth 先剔除错误历史；但 D12.7 冻结的局部对比度阈值，在正确运动对应上拒绝了 83–100% 的 radius-2 历史。</p></div><aside className="contact-gate d128-gate"><b>FROZEN VERDICT</b><strong>NOT<br/>SUPPORTED</strong><code>scientific checks · 9 / 14</code><code>C2 audit · 16 / 16</code><small>negative result preserved</small></aside><div className="contact-stats"><article><strong>16</strong><span>fresh Blender renders</span><small>4 fixtures × 2 frames × 2 repeats</small></article><article><strong>0–16.98%</strong><span>moving-history retention</span><small>static control · 100%</small></article><article><strong>0</strong><span>false invalid accepts</span><small>fallback exact · every cell</small></article><article><strong>75</strong><span>recorded process identities</span><small>74 original + 1 C2 audit</small></article></div></section>

  <section className="section d128-verdict" id="verdict"><div className="section-index">00 / TWO GATES · TWO DIFFERENT QUESTIONS</div><div className="contact-heading"><div><p className="eyebrow"><span/> VALIDITY PASSED · USEFULNESS FAILED</p><h2>能识别错误历史，<br/><span>不等于能保留正确历史。</span></h2></div><p>结构门回答“这个 previous sample 是否来自同一个可见表面”；风险门回答“即使对应正确，插值误差是否足够小”。第一问通过，第二问使用了静态像素差模型，因此在运动中失去覆盖。</p></div><div className="d128-logic"><article className="pass"><span>01 · STRUCTURAL VALIDITY</span><strong>PASS</strong><code>owner · bounds · alpha · depth</code><p>同索引深度陷阱被拒绝 3,678 像素；所有 invalid history 与 risk rejection 都精确复制 current float32 RGBA。</p></article><i>→</i><article className="fail"><span>02 · STATIC LOCAL RISK</span><strong>FAIL</strong><code>tap-to-current contrast</code><p>正确运动也会改变 current pixel 的颜色；冻结阈值把真实 transported signal change 当成插值风险。</p></article><i>→</i><article className="reject"><span>FROZEN DECISION</span><strong>REJECTED</strong><code>coverage · quality · identity</code><p>camera cell 的 adaptive 域为空。低误差不能来自“拒绝一切”；这条规则不能进入生产 temporal policy。</p></article></div><div className="d128-contrast"><article><span>MOVING FIXTURES</span><strong>16.98 · 0 · 13.17%</strong><p>radius-2 history retained</p></article><article><span>STATIC CONTROL</span><strong>100%</strong><p>same rule, same threshold</p></article><article><span>INTERPRETATION</span><strong>DOMAIN SHIFT</strong><p>static contrast ≠ motion uncertainty</p></article></div></section>

  <section className="section d128-fixtures" id="fixtures"><div className="section-index">01 / FORMAL EXR · DIAGNOSTIC PROXIES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> BEAUTY · STRUCTURAL REASON · ADAPTIVE DOMAIN</p><h2>不是概念示意。<br/><span>是冻结结果里的真实像素。</span></h2></div><p>Beauty 来自 current-frame scene-linear ACEScg EXR；结构图显示每个 pixel 的拒绝原因；adaptive 图中绿色为接受、洋红为 radius-2 内的风险拒绝、蓝色为候选域。PNG 只用于导航，不参与判定。</p></div><div className="d128-gallery">{fixtures.map(f=><article key={f.id}><header><div><span>{f.id}</span><b>{f.raster}</b></div><code>{f.status} · {f.retention}</code></header><div>{[['beauty','BEAUTY · ACES DISPLAY'],['structural','STRUCTURE · GREEN VALID / REASON COLORS'],['adaptive','ADAPTIVE · GREEN ACCEPT / MAGENTA REJECT']].map(([suffix,label])=><figure key={suffix}><Image src={`${basePath}/evidence/b52-d12-8/${f.name}-${suffix}.png`} width={519} height={321} alt={`${f.id} ${label}`} unoptimized/><figcaption>{label}</figcaption></figure>)}</div><footer><span>{f.structural}</span><code>{f.rejected} RISK REJECTED</code></footer></article>)}</div></section>

  <section className="section d128-matrix" id="matrix"><div className="section-index">02 / PRIMARY CELL MEASUREMENTS</div><div className="contact-heading"><div><p className="eyebrow"><span/> REPEAT 1 · REPEAT 2 EXACT</p><h2>运动向量很准。<br/><span>覆盖仍然崩溃。</span></h2></div><p>Vector endpoint 误差全部低于 8.4e−5 px；零 risk underbound、零 false accept、exact fallback 全部通过。失败不是 correspondence 完全失控，而是静态风险公式对运动过度保守。</p></div><div className="d128-table"><div className="head"><b>FIXTURE</b><b>VECTOR MAX</b><b>DEPTH REL.</b><b>RADIUS 2</b><b>ADAPTIVE</b><b>RETENTION</b><b>REJECTED</b><b>RGB MAX</b><b>STATE</b></div>{fixtures.map(f=><div className="row" key={f.id}><strong>{f.id}<small>{f.raster}</small></strong><code>{f.vector}</code><code>{f.depth}</code><code>{f.r2}</code><code>{f.adaptive}</code><code>{f.retention}</code><code>{f.rejected}</code><code>{f.rgb}</code><b className={f.status==='CONTROL PASS'?'pass':'fail'}>{f.status}</b></div>)}</div><div className="d128-caveat"><b>* DEPTH DOMAIN DEFECT · PRESERVED</b><p>same-index cell 的 `0.289271` 包含了本来就应该被 `INVALID_DEPTH` 拒绝的像素。冻结 analyzer 在拒绝前把它们加入 aggregate。C2 没有事后修值；未来实验必须把 valid-history depth agreement 与 expected depth rejection 分成两个域。</p></div></section>

  <section className="section d128-audit" id="audit"><div className="section-index">03 / BYTE IDENTITY · NEGATIVE-RESULT AUDIT</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> FAILURE IS DATA</p><h2>300 个末位差异，<br/><span>0 个决策差异。</span></h2></div><p>Python 与 Node 的八个 decision/reconstruction payload 全部 exact；只有 moving cells 的 float64 risk bytes 在 1e−19 量级不同。科学 exact-identity gate 仍为 false，C2 只修正“如何审计一个 false”。</p></div><div className="d128-byte-grid"><article><span>NON-RISK PAYLOADS</span><strong>64 / 64</strong><code>BYTE EXACT</code><p>reconstruction、reason、owner、validity、radius 与 adaptive masks 全同。</p></article><article><span>RISK FLOAT64</span><strong>300</strong><code>DIFFERING SCALARS</code><p>最大绝对差 `4.336808689942018e−19`；repeat summaries 完全一致。</p></article><article><span>THRESHOLD DECISIONS</span><strong>0</strong><code>DIFFERENCES</code><p>微小 arithmetic divergence 没有改变任何 accept / reject bit。</p></article><article><span>C2 AUDIT</span><strong>16 / 16</strong><code>40 / 40 MUTATIONS</code><p>一条新 Python 进程；零科学重跑；原 verdict 与失败审计都被保留。</p></article></div><div className="d128-audit-chain"><article className="negative"><span>ANALYZER</span><strong>9 / 14</strong><code>NOT SUPPORTED</code><p>如实记录两个 identity/replay false，以及 depth、quality、coverage false。</p></article><i>→</i><article className="old"><span>ORIGINAL AUDIT</span><strong>9 / 10</strong><code>INFRASTRUCTURE FAIL</code><p>错误地要求已失败的 scientific dual-payload condition 必须为 true；runner 正确不写 receipt。</p></article><i>→</i><article className="corrected"><span>AUDIT-ONLY C2</span><strong>16 / 16</strong><code>NEGATIVE STATE VERIFIED</code><p>重新读取相同 bytes，验证“结果确实应当失败”；没有把任何 false 改成 true。</p></article></div></section>

  <section className="section d128-next" id="next"><div className="section-index">04 / NEXT FALSIFIABLE DESIGN</div><div className="contact-heading"><div><p className="eyebrow"><span/> D12.9 · FRESH FIXTURES REQUIRED</p><h2>下一步不是调大阈值。<br/><span>而是重写风险的物理含义。</span></h2></div><p>单纯放宽 1/1048576 会混合 transported signal change 与 interpolation error，无法说明为什么安全。新协议必须先定义 motion-aware uncertainty，再用全新场景检验覆盖与误差。</p></div><div className="d128-next-grid"><article><span>01</span><strong>MOTION-AWARE BOUND</strong><p>从 projective transport 的局部导数与插值余项估计不确定性，而不是比较 previous taps 与 current color 的绝对差。</p></article><article><span>02</span><strong>CANONICAL RISK FORMAT</strong><p>冻结 fixed-point 或精确 binary64 operation graph，先解决 Python/Node raw identity，再看阈值。</p></article><article><span>03</span><strong>TYPED DEPTH DOMAINS</strong><p>valid-history depth agreement 与 expected disocclusion rejection 分开计量，避免拒绝样本污染精度门。</p></article><article><span>04</span><strong>NON-EMPTY COVERAGE</strong><p>每个 moving owner 都必须保留有用样本；“误差很低但接受域为空”明确失败。</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-projective-motion-disocclusion-adaptive-risk-holdout-c1-v0-1/results.json`}><span>FORMAL RESULT</span><b>9 / 14 checks ↗</b></a><a href={`${repo}experiments/blender-projective-motion-disocclusion-adaptive-risk-holdout-c1-v0-1/audit.c2.json`}><span>C2 AUDIT</span><b>16 / 16 checks ↗</b></a><a href={`${repo}specs/blender-projective-motion-disocclusion-adaptive-risk-audit-c2.v0.1.json`}><span>CORRECTION PROTOCOL</span><b>frozen state replay ↗</b></a><a href={`${repo}research/2026-08-27-b52-d12-8-projective-motion-disocclusion-adaptive-risk-result.md`}><span>RESEARCH NOTE</span><b>limits + next hypothesis ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.8 Motion / Disocclusion Research</b></div><p>structural validity passes · static risk generalization rejected</p><Link href="/blender-motion-aware-curvature-risk-v0-1">查看 D12.9-D1 候选 →</Link></footer>
</main>}
