import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const mediaBase = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio/review-dailies-v0-1' : '/review-dailies-v0-1';
export const metadata: Metadata = { title: 'B14 完整审片样片｜真实 Blender 144 帧｜Blender Film Studio', description: 'receipt 绑定的 B02 场景经真实 Blender 5.2 输出完整 144 帧、6 秒 H.264 审片代理；10/10 攻击通过，人类电影感评审仍待完成。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/review-dailies-v0-1/' } };

const witnesses = [
  ['0001', 'Dolly 起点', '502–628 KB witness range'],
  ['0072', '时间轴中点', 'camera interpolation'],
  ['0144', 'Dolly 终点', 'exact final frame'],
];
const attacks = [
  ['N01','receipt 文件身份','RECEIPT_FILE_SHA'],['N02','receipt body','RECEIPT_BODY_HASH'],['N03','source .blend','SOURCE_BLEND_SHA'],['N04','scene plan marker','PLAN_MARKER_BINDING'],['N05','缺少 frame 0072','MISSING_FRAME'],['N06','多出 frame 0145','EXTRA_FRAME'],['N07','frame bytes','FRAME_SHA'],['N08','sequence manifest','SEQUENCE_SELF_HASH'],['N09','MP4 bytes','VIDEO_SHA'],['N10','ffprobe 声明','VIDEO_PROBE_BINDING'],
];

export default function ReviewDailiesPage() {
  return <main className="contact-page dailies-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B14 导航"><Link href="/journal">实验日志</Link><Link href="/compile-receipt-v0-1">B13 收据</Link><a href="#film">样片</a><a href="#evidence">证据</a></nav><span className="edition contact-edition">Review Dailies 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B14 · RECEIPT-BOUND COMPLETE SHOT</p><h1>不是三个代表帧。<br /><span>是完整的 1–144 帧。</span></h1><p>同一份 B02-A CompileReceipt 驱动真实 Blender 5.2，生成无缺口 PNG 序列，再由固定 FFmpeg 二进制封装为 6 秒审片样片。自动化门通过；这仍是低成本 Eevee 代理，不是影院母版。</p></div><aside className="contact-gate"><b>CURRENT STATUS</b><strong>FORMAL AUTOMATION<br />TRUE</strong><code>144 / 144 decoded frames</code><code>10 / 10 attacks rejected</code><small>HUMAN REVIEW · PENDING</small></aside><div className="contact-stats"><article><strong>144</strong><span>完整帧</span><small>1–144 · no gaps</small></article><article><strong>28.32s</strong><span>Blender 渲染</span><small>0.197 s / frame</small></article><article><strong>6.00s</strong><span>视频时长</span><small>24/1 fps</small></article><article><strong>10/10</strong><span>预注册攻击</span><small>stable reasons</small></article></div></section>

    <section className="section dailies-screen" id="film"><div className="section-index light">00 / 完整样片</div><div className="contact-heading"><div><p className="eyebrow"><span /> REVIEW_PROXY_NOT_MASTER</p><h2>让人真正看完整运动。<br /><span>但不偷换质量合同。</span></h2></div><p>960×540、Eevee 32 samples、关闭 motion blur、ACES 2 SDR review transform；H.264 CRF 18 只服务审片。4K/512 spp Cycles、multipart EXR 与交付元数据仍属于另一条母版合同。</p></div><div className="dailies-video"><video controls playsInline preload="metadata" poster={`${mediaBase}/B02-frame-0072.png`}><source src={`${mediaBase}/B02-review-proxy-v0.1.mp4`} type="video/mp4" />浏览器无法播放此 MP4。</video><div><span>AUTOMATED RESULT</span><b>PLAYABLE · COMPLETE · RECEIPT-BOUND</b><p>画面只是当前 B02 几何基准：一个简单室内 dolly。它证明流程完整，不证明场景精致、表演成立或具有电影感。</p></div></div></section>

    <section className="section contact-limits"><div className="section-index">01 / 三个视觉 witness</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> FRAME 1 · 72 · 144</p><h2>起点、中点、终点，<br /><span>都绑定到逐帧清单。</span></h2></div><p>本地完整 PNG 序列共 83,216,547 bytes；仓库保留全部 144 个哈希与三张 witness，不假装公开哈希能重建已丢弃的其余 PNG 原始字节。</p></div><div className="dailies-witnesses">{witnesses.map(([frame,title,note]) => <figure key={frame}><Image src={`${mediaBase}/B02-frame-${frame}.png`} alt={`B02 审片代理第 ${frame} 帧`} width={960} height={540} sizes="(max-width: 800px) 100vw, 33vw" /><figcaption><span>FRAME {frame}</span><b>{title}</b><small>{note}</small></figcaption></figure>)}</div></section>

    <section className="section contact-contract" id="evidence"><div className="section-index">02 / 完整性链</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> RECEIPT → FRAMES → CONTAINER</p><h2>视频不是孤立文件。<br /><span>每一层都有反向绑定。</span></h2></div><p>源 receipt 先通过 B13 的 19 项检查；Blender 再核对 scene 内嵌 plan/structure marker。sequence manifest 自哈希并列出每帧 SHA，最后 ffprobe 从 MP4 反读编码、尺寸、帧率、帧数、时长和音轨。</p></div><div className="contact-flow"><article><span>01</span><b>B02-A RECEIPT</b><p>plan · structure · .blend</p></article><i>→</i><article><span>02</span><b>144 PNG HASHES</b><p>a52903fc…d56e4</p></article><i>→</i><article><span>03</span><b>H.264 + FFPROBE</b><p>e9f52ad3…340b8</p></article></div><div className="contact-plan"><span>VIDEO PROFILE</span><code>h264 · yuv420p · 960×540 · 24/1 · 144 frames · 6.000s · audio 0</code><b>PASS</b></div></section>

    <section className="section contact-diagnostic"><div className="section-index">03 / 预注册攻击</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> TEN WAYS TO BREAK THE CLAIM</p><h2>换源、缺帧、多帧、改视频。<br /><span>都必须被准确拒绝。</span></h2></div><p>攻击只操作复制件和 disposable work 目录；每项都走到预注册的目标层，并返回稳定原因。正式 receipt、`.blend`、工具和证据文件未被攻击修改。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,result]) => <li key={id}><span>{id}</span><b>{item}</b><small>{result}</small></li>)}</ol></section>

    <section className="section dailies-cost"><div className="section-index light">04 / 成本边界</div><div className="contact-heading"><div><p className="eyebrow"><span /> REVIEW SPEED ≠ MASTER SPEED</p><h2>28 秒跑完整镜头。<br /><span>不是 28 秒完成母版。</span></h2></div><p>根据已测 B02 六个 4K/512 spp Cycles 样本，144 帧串行估计约 12.63 小时；本次代理快约 1,605×。差距来自分辨率、引擎、采样、输出格式与运动模糊选择，不能作为同质量成本对比。</p></div><div className="diagnostic-result"><article><span>REVIEW PNG</span><strong>83.2 MB</strong><b>144 files</b><small>local disposable sequence</small></article><article><span>REVIEW MP4</span><strong>438.6 kB</strong><b>lossy delivery</b><small>GitHub Pages playable</small></article><article><span>PROXY WALL</span><strong>28.32 s</strong><b>real Blender 5.2</b><small>M4 Max · Eevee</small></article><article className="fail"><span>HUMAN GATE</span><strong>PENDING</strong><b>cinematic quality</b><small>automation cannot pass it</small></article></div><div className="contact-artifacts"><a href={`${repo}experiments/review-dailies-v0-1/results.json`}><span>RESULT</span><b>metrics · 10 attacks ↗</b></a><a href={`${repo}experiments/review-dailies-v0-1/evidence/dailies.evidence.json`}><span>EVIDENCE</span><b>complete binding graph ↗</b></a><a href={`${repo}research/2026-08-26-b14-review-dailies-result.md`}><span>RESULT NOTE</span><b>结论与非结论 ↗</b></a><a href={`${repo}research/lab-journal.md`}><span>JOURNAL</span><b>首次实现缺陷 ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B14 Receipt-bound Review Dailies</b></div><p>Automation true · review proxy · human cinematic gate pending</p><Link href="/journal">返回实验日志 →</Link></footer>
  </main>;
}
