import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical='https://lovejzzz.github.io/BlenderFilmStudio/blender-owner-token-pass-v0-1/';
const socialImage='https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-10-p1-c1/material-index-discrete.png';
export const metadata:Metadata={title:'D12.10 Owner Token Pass｜Blender Film Studio',description:'8 次真实 Blender 5.2 Cycles render：Material Index 与 Value AOV 都能传递 compiler-assigned owner token，但两者边界语义不同。',alternates:{canonical},openGraph:{title:'D12.10 · Blender Owner Token Pass',description:'Object Index 7/7 无法区分 owner；Material Index 11/23 离散，Value AOV 0.25/0.75 在边缘混合。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'D12.10 · Blender Owner Token Pass',description:'8 real renders · corrected audit 14/14 · next: fresh Material Index integration',images:[socialImage]}};

const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const panels=[
  {src:'object-index-shared.png',label:'OBJECT INDEX · SHARED 7 / 7',title:'看不见 owner 边界',copy:'背景与前景同为 7。这个 pass 在数值上完全稳定，但没有 identity 信息。'},
  {src:'material-index-discrete.png',label:'MATERIAL INDEX · 11 / 23',title:'离散 owner 边界',copy:'全部 stable interiors exact；1,968 个 boundary pixels 也只出现 11 或 23。'},
  {src:'custom-aov-filtered.png',label:'VALUE AOV · 0.25 / 0.75',title:'采样混合边界',copy:'内域 exact，但边缘出现 20 个值；颜色仅是 source-bound 解释映射。'},
] as const;

export default function OwnerTokenPassPage(){return <main className="contact-page d128-page p1-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.10 owner token 导航"><Link href="/blender-motion-aware-curvature-risk-holdout-v0-1">D12.9-H1</Link><Link href="/blender-material-index-owner-integration-v0-1">D12.11 Result</Link><a href="#verdict">结论</a><a href="#passes">三种 Pass</a><a href="#boundary">边界</a><a href="#failure">失败链</a><a href="#next">下一干预</a><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Owner Token D12.10</span></header>

  <section className="contact-hero p1-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.10-P1-C1 · REAL BLENDER 5.2 PASS PROBE</p><h1>Object Index 不够。<br/><span>Blender 有两条可用通道。</span></h1><p>两个 analytic owners 故意共享 Object Index 7。真实 Cycles multilayer EXR 证明：Material Index 11/23 与 Value AOV 0.25/0.75 都能传 compiler-assigned owner token；但边缘一个离散，一个混合。</p></div><aside className="contact-gate p1-gate"><b>CORRECTED VERDICT</b><strong>TWO<br/>PASSES<br/>VIABLE</strong><code>post-hoc transport evidence</code><code>temporal safety · unproven</code><small>Material Index first</small></aside><div className="contact-stats"><article><strong>8</strong><span>real Cycles renders</span><small>2 frames × 2 displays × 2 repeats</small></article><article><strong>22,543</strong><span>stable pixels / cell</span><small>16,816 background + 5,727 foreground</small></article><article><strong>0</strong><span>interior token mismatch</span><small>Material Index + Value AOV</small></article><article><strong>14 / 14</strong><span>independent audit</span><small>raw EXR replay</small></article></div></section>

  <section className="section p1-verdict" id="verdict"><div className="section-index">00 / IDENTITY TRANSPORT</div><div className="contact-heading"><div><p className="eyebrow"><span/> SAME OBJECT INDEX · DISTINCT ANALYTIC OWNERS</p><h2>稳定不等于有用。<br/><span>身份必须由 compiler 分配。</span></h2></div><p>Object Index 的 7/7 在所有像素上都可复现，却无法区分背景与前景。Material Index 和 Value AOV 同时跨过 EXR availability、finite、stable-interior exact、display invariance 与 clean-process repeat gates。</p></div><div className="p1-logic"><article className="negative"><span>NEGATIVE CONTROL</span><strong>7 / 7</strong><code>OBJECT INDEX</code><p>两个 owner 共用一个 object pass index；数值 exact，identity 失败。</p></article><i>→</i><article className="selected"><span>CATEGORICAL CANDIDATE</span><strong>11 / 23</strong><code>MATERIAL INDEX</code><p>内域与边缘均保持离散；适合第一条 exact-equality integration。</p></article><i>+</i><article className="viable"><span>FILTERED CANDIDATE</span><strong>.25 / .75</strong><code>VALUE AOV</code><p>内域 exact、边缘混合；可作 coverage evidence，不能无条件当 categorical key。</p></article></div></section>

  <section className="section p1-passes" id="passes"><div className="section-index">01 / SOURCE-BOUND FLOAT32 VISUALIZATION</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> SAME FRAME · SAME CROP · THREE DATA PASSES</p><h2>同一个 owner 边界。<br/><span>三种完全不同的语义。</span></h2></div><p>下图从 F0 / ACES SDR / R1 的正式 float32 arrays 生成，并以 nearest-neighbor 放大。蓝橙只是解释映射，不是 Blender display transform，也不参与 verdict。</p></div><div className="p1-gallery">{panels.map(panel=><figure key={panel.src}><Image src={`${basePath}/evidence/b52-d12-10-p1-c1/${panel.src}`} width={456} height={396} alt={panel.label} unoptimized/><figcaption><span>{panel.label}</span><strong>{panel.title}</strong><p>{panel.copy}</p></figcaption></figure>)}</div><div className="p1-payload"><span>RAW → CORRECTED</span><strong>24 / 24 BYTE EXACT</strong><i>+</i><span>RAW → FAILED P1 ARRAYS</span><strong>24 / 24 BYTE EXACT</strong></div></section>

  <section className="section p1-boundary" id="boundary"><div className="section-index">02 / FROZEN THREE-PIXEL BOUNDARY BAND</div><div className="contact-heading"><div><p className="eyebrow"><span/> CATEGORICAL LABEL ≠ FILTERED COVERAGE</p><h2>Material Index 只给标签。<br/><span>AOV 给出了采样混合。</span></h2></div><p>两个机制都通过 stable-interior transport gate；这里的差异只决定下一候选如何 typed。不能把 0.25–0.75 之间的 AOV 数值偷偷 round 成 owner，也不能把 Material Index 的硬边缘解释成 antialiased coverage。</p></div><div className="p1-boundary-grid"><article className="material"><span>MATERIAL INDEX · F0 / F1</span><strong>0</strong><b>unregistered boundary values</b><div><code>11.0</code><i/><code>23.0</code></div><p>每个 boundary pixel 仍是一个离散 material token。</p></article><article className="aov"><span>VALUE AOV · F0</span><strong>658</strong><b>mixed boundary pixels</b><div><code>0.25</code><i/><code>0.75</code></div><p>20 个 unique values；相邻级差 0.015625。</p></article><article className="aov"><span>VALUE AOV · F1</span><strong>652</strong><b>mixed boundary pixels</b><div><code>0.25</code><i/><code>0.75</code></div><p>同样 20 个 unique values；payload 对 repeat/display byte exact。</p></article></div></section>

  <section className="section p1-failure" id="failure"><div className="section-index">03 / FAILURE WAS NOT ERASED</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> PREREGISTER → FAIL → LOCALIZE → CORRECT</p><h2>八次 render 没失败。<br/><span>我们的相机公式失败了。</span></h2></div><p>原 analyzer 把 landscape `ortho_scale=8` 当可见高度，错误 background mask 吞入真实前景；它还把“双候选都通过”写进 projection validator。失败 result、root 与 receipt 保留，C1 才以新工具和新 root 做只读修正。</p></div><div className="p1-timeline"><article><span>01 · PREREG</span><strong>7eb7…d4be</strong><p>五个工具与两个 roots 在 spec 冻结时不存在。</p></article><i>→</i><article><span>02 · REAL RENDERS</span><strong>8 / 8</strong><p>四个 pass 全存在；display 与 repeat arrays byte exact。</p></article><i>→</i><article className="failed"><span>03 · ANALYZER</span><strong>INVALID</strong><p>8/9 checks；横纵 extent 转置，audit 未启动。</p></article><i>→</i><article className="corrected"><span>04 · C1</span><strong>12 / 12</strong><p>28/28 attacks；独立 audit 14/14。</p></article></div></section>

  <section className="section p1-audit"><div className="section-index">04 / CLAIM BOUNDARY</div><div className="contact-heading"><div><p className="eyebrow"><span/> PASS TRANSPORT ≠ TEMPORAL RECONSTRUCTION</p><h2>我们选中了运输层。<br/><span>还没有证明重建层。</span></h2></div><p>Material Index 当前更适合 exact identity，但它属于 material 而不是 object。compiler 必须统一一个 owner 的全部 material slots，并处理跨 owner 共享 material data-block；可用范围实测为 0–32767。</p></div><div className="p1-audit-grid"><article><span>ANALYZER</span><strong>12 / 12</strong><code>28 / 28 attacks</code><p>outcome-neutral verdict mapping。</p></article><article><span>RAW AUDIT</span><strong>14 / 14</strong><code>32 measurements</code><p>不 import corrected analyzer。</p></article><article><span>NEW RENDERS</span><strong>0</strong><code>2 correction PIDs</code><p>八份 source EXR 保持 immutable。</p></article><article><span>UNKNOWN</span><strong>BOUNDARY</strong><code>temporal safety</code><p>必须交给新的 fresh integration。</p></article></div></section>

  <section className="section p1-next" id="next"><div className="section-index">05 / NEXT FALSIFIABLE INTERVENTION</div><div className="contact-heading"><div><p className="eyebrow"><span/> CHANGE ONE VARIABLE</p><h2>下一步只换 owner token。<br/><span>其余 H1 规则全部不动。</span></h2></div><p>fresh candidate 将用 compiler-assigned Material Index 替换 Object Index ownership；depth、alpha、Vector、Q30 risk、coverage denominator 与质量门保持原样。目标不是提高所有 coverage，而是先消除已经定位的 15 个 accepted owner aliases，且不新增 false accepts。</p></div><div className="p1-next-grid"><article><span>01</span><strong>MATERIAL TOKEN</strong><p>同 owner 全部 materials 使用同一个整数 token。</p></article><article><span>02</span><strong>ALIAS GATE</strong><p>原 15 个 accepted aliases 必须归零。</p></article><article><span>03</span><strong>NO NEW FALSE ACCEPT</strong><p>边缘硬标签不能绕过 typed depth 与 support validity。</p></article><article><span>04</span><strong>STENCIL LATER</strong><p>one-sided curvature support 保持另一条独立干预。</p></article></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-owner-token-pass-probe-c1-v0-1/results.json`}><span>CORRECTED RESULT</span><b>12 / 12 · 28 / 28 ↗</b></a><a href={`${repo}experiments/blender-owner-token-pass-probe-c1-v0-1/audit.json`}><span>RAW AUDIT</span><b>14 / 14 checks ↗</b></a><a href={`${repo}research/2026-08-28-b52-d12-10-p1-formal-analysis-failure.md`}><span>RETAINED FAILURE</span><b>wrong ortho extent ↗</b></a><a href={`${repo}research/2026-08-28-b52-d12-10-p1-c1-owner-token-pass-result.md`}><span>RESEARCH NOTE</span><b>claims · limits · next ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.10 Owner Token Pass</b></div><p>two transports viable · Material Index selected for integration</p><Link href="/blender-material-index-owner-integration-v0-1">继续：D12.11 15→0 →</Link></footer>
</main>}
