import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const sequences = [
  ['P01','ARRRRRRARRRA'], ['P02','RRRRRRRRARRR'], ['P03','RRRRARRRRARA'],
  ['P04','RRRRARAARRRR'], ['P05','RRRRRARRARAA'], ['P06','RRRRARRRARRR'],
  ['P07','RRRRRARRRRAR'], ['P08','RRRRRRRRAARA'], ['P09','ARRRARRARRRR'],
  ['P10','RRRRRRRRAARR'], ['P11','RARRRRRRRRRR'], ['P12','RRRARRRRRRRR'],
];
const ordinals = [2,1,0,1,4,2,2,2,5,3,2,4];

export const metadata: Metadata = {
  title: 'B28 同 PID 模式切换｜Blender Film Studio',
  description: '12 个真实 Blender 5.2 PID、144 次同帧 render：12/12 PID 内发生 REFERENCE/ALTERNATE 双模式切换，42/132 个相邻调用转换。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/repeated-frame-mode-switch-v0-1/' },
};

export default function RepeatedFrameModeSwitchPage(){return <main className="contact-page factorial-page repeated-mode-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B28 导航"><Link href="/journal">实验日志</Link><Link href="/frame-history-isolation-v0-1">B27</Link><a href="#design">设计</a><a href="#result">结果</a><a href="#sequences">序列</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Mode Switch 0.1</span></header>

  <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B28 · REAL BLENDER SAME-PID INTERVENTION</p><h1>同一个进程，<br/><span>输出仍会切换。</span></h1><p>frame 38 只设置一次；随后不改 frame、不改 scene、不重载 `.blend`，连续 render 12 次。12/12 个独立 Blender PID 都在两个冻结像素模式之间切换，把异常边界从“进程初始化”推进到每次 render invocation 或更底层。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>WITHIN-PID<br/>SWITCH SUPPORT</strong><code>SWITCHING PID · 12 / 12</code><code>TRANSITIONS · 42 / 132</code><small>NOVEL MODES · ZERO</small></aside><div className="contact-stats"><article><strong>12/12</strong><span>PID 内双模式</span><small>threshold was ≥2</small></article><article><strong>144</strong><span>真实 render calls</span><small>12 calls × 12 PID</small></article><article><strong>23/23</strong><span>攻击测试</span><small>all intended reasons</small></article><article><strong>2</strong><span>冻结模式</span><small>no third decoded SHA</small></article></div></section>

  <section className="section contact-verdict" id="design"><div className="section-index">00 / 只重复调用</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> FROZEN BEFORE B28 OUTPUT</p><h2>一次 frame_set。<br/><span>十二次 render。</span></h2></div><p>固定 scene、BuildPlan、structure、OCIO、32 samples、dither 0、Fast GI、TAA reprojection、FIXED/8 threads 和 PNG8。每个 replicate 是一个 fresh PID，但十二次调用都在同一持久进程里完成。</p></div><div className="blind-flow repeated-flow"><article><span>FRESH PROCESS</span><b>P01 … P12</b><small>12 unique observed PID</small></article><i>→</i><article><span>SET ONCE</span><b>frame 38</b><small>frameSetCount = 1</small></article><i>→</i><article><span>REPEAT</span><b>render × 12</b><small>no reload · no frame change</small></article><i>→</i><article><span>CLASSIFY</span><b>R / A / novel</b><small>decoded RGB SHA</small></article></div><div className="contact-nonclaim"><b>PRIMARY UNIT · ONE PID</b><p>支持阈值预先冻结为至少两个独立 PID 内出现两个 known mode。相邻 pair 是相关观察，不被伪装成 132 个独立 process samples；任何第三种 SHA 都必须触发 MODE_SPACE_EXPANDED。</p></div></section>

  <section className="section contact-evidence" id="result"><div className="section-index light">01 / 主终点</div><div className="contact-heading"><div><p className="eyebrow"><span/> EVERY PROCESS SWITCHED</p><h2>不是某个 PID 的偶然。<br/><span>十二个 PID 全部复现。</span></h2></div><p>REFERENCE 出现 116 次，ALTERNATE 出现 28 次。所有 PID 至少出现一次 ALTERNATE，并且都返回过 REFERENCE；42 次相邻转换几乎对称分布于两个方向。</p></div><div className="history-outcomes repeated-outcomes"><article><span>REFERENCE</span><strong>116</strong><b>of 144 renders</b><code>80.56%</code><small>decoded c1363822…bf308</small></article><article><span>ALTERNATE</span><strong>28</strong><b>of 144 renders</b><code>19.44%</code><small>decoded 6e9685c1…0feaf</small></article><article className="history-pvalue"><span>ADJACENT SWITCH</span><strong>42</strong><b>of 132 comparisons</b><code>R→A 22 · A→R 20</code><small>descriptive · dependent pairs</small></article></div><div className="diagnostic-verdict"><b>FROZEN DECISION</b><code>WITHIN_PID_MODE_SWITCH_SUPPORT</code><p>阈值 ≥2 switching PID；观察值 12。进程初始化不是充分的 mode-locking boundary。</p></div></section>

  <section className="section contact-diagnostic" id="sequences"><div className="section-index">02 / 原始模式序列</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> R = REFERENCE · A = ALTERNATE</p><h2>每一行都是一个 Blender。<br/><span>每一格都是一次真实 render。</span></h2></div><p>序列保留实际执行顺序。即使只有 12 次调用，每个进程都暴露至少一次双模式；没有插值，没有按视觉相似度归类，也没有丢弃异常帧。</p></div><div className="mode-sequences">{sequences.map(([pid,sequence])=><article key={pid}><b>{pid}</b><div>{[...sequence].map((mode,index)=><span className={mode==='A'?'alternate':''} key={`${pid}-${index}`} title={`call ${index+1}: ${mode==='A'?'ALTERNATE':'REFERENCE'}`}>{mode}</span>)}</div><small>{[...sequence].filter(mode=>mode==='A').length} alternate</small></article>)}</div><div className="ordinal-bars"><header><b>ALTERNATE BY CALL ORDINAL</b><span>描述性次终点 · 未预注册趋势检验</span></header>{ordinals.map((count,index)=><div key={index}><small>{String(index+1).padStart(2,'0')}</small><i style={{width:`${count/12*100}%`}}/><b>{count}/12</b></div>)}</div></section>

  <section className="section contact-limits" id="boundary"><div className="section-index">03 / 现在能说与不能说</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> INVOCATION BOUNDARY OR BELOW</p><h2>定位更窄，<br/><span>机制仍未被命名。</span></h2></div><p>B28 排除了“进程初始化永久锁定 mode”这一充分解释，但不能凭结果给 Metal、Eevee、TAA、rasterization 或 GPU scheduling 中任何一个定罪。下一实验必须先冻结更低层干预，再用新样本确认。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/repeated-frame-mode-switch-v0-1/results.json`}><span>RESULT</span><b>144 renders · 23 attacks ↗</b></a><a href={`${repo}experiments/repeated-frame-mode-switch-v0-1/evidence/mode-classification.json`}><span>CLASSIFICATION</span><b>all sequences · hashes ↗</b></a><a href={`${repo}experiments/repeated-frame-mode-switch-v0-1/evidence/classification-binding.json`}><span>BINDING</span><b>tools · manifests · contract ↗</b></a><a href={`${repo}research/2026-08-26-b28-repeated-frame-mode-switch-protocol.md`}><span>PREREGISTRATION</span><b>frozen before output ↗</b></a><a href={`${repo}research/2026-08-26-b28-repeated-frame-mode-switch-result.md`}><span>RESULT NOTE</span><b>claims · non-claims ↗</b></a></div></section>

  <footer><div><span className="brand-mark">BFS</span><b>B28 Repeated-Frame Mode Switch</b></div><p>12/12 PID switched · process initialization boundary rejected</p><Link href="/research-agenda">进入下一机制边界 →</Link></footer>
</main>}
