import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B49 运动模糊 Holdout｜Blender Film Studio',
  description: '八个真实 Blender 5.2 worker、三参考重复、三指标质量门与 19/19 对抗审计，验证 128 spp、CENTER 0.5 shutter 工作点。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/motion-blur-holdout-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath = process.env.GITHUB_PAGES === 'true' ? '/BlenderFilmStudio' : '';
const metrics = [
  ['LINEAR NRMSE','2.390795×','2.399813×','0.376%'],
  ['LOG-Y RMSE','2.435634×','2.443907×','0.339%'],
  ['EDGE RMSE','2.266177×','2.276491×','0.453%'],
] as const;
const passes = [
  ['Combined','EXACT','EXACT'],['Depth','EXACT','EXACT'],['Normal','EXACT','EXACT'],
  ['Crypto ×3','EXACT','EXACT'],['Vector','33,190 Δ','36,348 Δ'],
] as const;

export default function MotionBlurHoldoutPage(){return <main className="contact-page b49mb-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B49 运动模糊导航"><Link href="/journal">实验日志</Link><Link href="/resolution-holdout-v0-1">分辨率</Link><a href="#evidence">图像证据</a><a href="#boundary">结论边界</a></nav><span className="edition contact-edition">Motion Blur B49-MB</span></header>

  <section className="contact-hero b49mb-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> PREREGISTERED · THREE-REFERENCE HOLDOUT</p><h1>动态门通过。<br/><span>但提升很小。</span></h1><p>128 spp raw、CENTER 位置、0.5 frame shutter 在三项冻结误差指标上都小于三倍独立参考噪声地板，并且比关闭运动模糊更接近参考；相对优势只有 0.34–0.45%，不能冒充“肉眼电影感已经证明”。</p></div><aside className="contact-gate b49mb-gate"><b>FORMAL VERDICT</b><strong>SUPPORTED</strong><code>3 / 3 metrics pass</code><code>3 / 3 closer than OFF</code><small>19/19 ATTACKS · BYTE-EXACT AUDIT</small></aside><div className="contact-stats"><article><strong>8</strong><span>fresh workers</span><small>moving + static control</small></article><article><strong>3</strong><span>reference repeats</span><small>512 spp · distinct seeds</small></article><article><strong>0.5</strong><span>frame shutter</span><small>CENTER · 128 spp</small></article><article><strong>1.26%</strong><span>render delta</span><small>ON 9.981 s · OFF 9.857 s</small></article></div></section>

  <section className="section b49mb-design"><div className="section-index">00 / FROZEN INTERVENTION</div><div className="contact-heading"><div><p className="eyebrow"><span/> CHANGE ONE CAMERA-TIME VARIABLE</p><h2>同一帧、同一场景、同一采样。<br/><span>只开关有限快门。</span></h2></div><p>TABLETOP frame 37 是运动测试；INTERIOR frame 19 是静态负对照。候选与负对照都为 128 spp，三条 512 spp、不同 seed 的 blur-on 重复构成参考 ensemble。零快门 cell 用来隔离“开关状态”与“有限曝光窗口”。</p></div><div className="b49mb-flow"><article><span>NEGATIVE</span><strong>OFF</strong><small>128 spp · moving</small></article><i>↔</i><article className="selected"><span>CANDIDATE</span><strong>ON · 0.5</strong><small>CENTER · 128 spp</small></article><i>→</i><article><span>REFERENCE</span><strong>3 × 512</strong><small>independent seed ensemble</small></article></div></section>

  <section className="section b49mb-evidence" id="evidence"><div className="section-index">01 / ACES 2 DISPLAY PROXIES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> HUMAN NAVIGATION ONLY</p><h2>看得到差异在哪里。<br/><span>判决仍来自线性 EXR。</span></h2></div><p>网页图使用固定 OCIO 的 ACES 2 SDR 代理，仅帮助定位；正式门读取 scene-linear float32 EXR。差分热图以 moving on/off 的 99th percentile 共用标尺着色，静态对照因此保持全黑。</p></div><div className="b49mb-image-grid"><figure><Image src={`${basePath}/evidence/b49-mb/moving-off.png`} unoptimized alt="运动场景关闭运动模糊" width={128} height={72}/><figcaption>OFF · 128 SPP</figcaption></figure><figure className="selected"><Image src={`${basePath}/evidence/b49-mb/moving-on.png`} unoptimized alt="运动场景开启 0.5 帧运动模糊" width={128} height={72}/><figcaption>ON · CENTER 0.5</figcaption></figure><figure><Image src={`${basePath}/evidence/b49-mb/moving-reference-ensemble.png`} unoptimized alt="三次 512 采样参考的均值" width={128} height={72}/><figcaption>3 × 512 REFERENCE MEAN</figcaption></figure><figure className="heat"><Image src={`${basePath}/evidence/b49-mb/moving-difference.png`} unoptimized alt="运动场景开关运动模糊的线性绝对差分热图" width={128} height={72}/><figcaption>ON/OFF Δ · SHARED SCALE</figcaption></figure></div><div className="b49mb-static"><figure><Image src={`${basePath}/evidence/b49-mb/static-off.png`} unoptimized alt="静态场景关闭运动模糊" width={128} height={72}/><figcaption>STATIC OFF</figcaption></figure><figure><Image src={`${basePath}/evidence/b49-mb/static-on.png`} unoptimized alt="静态场景开启运动模糊" width={128} height={72}/><figcaption>STATIC ON · PIXEL EXACT</figcaption></figure><figure className="heat"><Image src={`${basePath}/evidence/b49-mb/static-difference.png`} unoptimized alt="静态场景差分为全黑" width={128} height={72}/><figcaption>STATIC Δ · 0 NONZERO PIXELS</figcaption></figure></div></section>

  <section className="section b49mb-metrics"><div className="section-index">02 / NUMERICAL GATE</div><div className="contact-heading"><div><p className="eyebrow"><span/> ERROR ÷ REFERENCE FLOOR</p><h2>候选通过三项门。<br/><span>关闭版本其实也会通过。</span></h2></div><p>预注册要求候选小于 3× 参考地板，且在三项指标上都比 OFF 更接近参考。两者差距很窄，所以结论是“工作点可用且方向一致”，不是感知显著性。</p></div><ol className="b49mb-table"><li className="head"><span>METRIC</span><b>ON / FLOOR</b><code>OFF / FLOOR</code><small>ON IMPROVEMENT</small></li>{metrics.map(row=><li key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><code>{row[2]}</code><small>{row[3]}</small></li>)}</ol><div className="b49mb-disclosure"><strong>0.34–0.45%</strong><p>这是数值方向，不是盲评效应量。下一道人工门仍不可省略。</p></div></section>

  <section className="section b49mb-domain"><div className="section-index">03 / PASS-DOMAIN CAUSAL CHECK</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ZERO-SHUTTER + STATIC CONTROLS</p><h2>像素变化来自曝光窗口。<br/><span>Vector 有独立语义。</span></h2></div><p>moving zero-shutter 与 OFF 的图像/几何/ID 通道逐字节一致；静态 ON/OFF 同样一致。Vector 在两种比较中均改变，证明它不能被当作 Combined 是否模糊的替身。</p></div><ol className="b49mb-pass-table"><li className="head"><span>PASS</span><b>MOVING ZERO ↔ OFF</b><code>STATIC ON ↔ OFF</code></li>{passes.map(row=><li key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><code>{row[2]}</code></li>)}</ol></section>

  <section className="section b49mb-audit"><div className="section-index">04 / EVIDENCE INTEGRITY</div><div className="contact-heading"><div><p className="eyebrow"><span/> REAL BLENDER 5.2 · ADVERSARIAL REPLAY</p><h2>十九种篡改都被拒绝。<br/><span>结果可独立重算。</span></h2></div><p>攻击覆盖父证据、源文件、worker image、隔离边界、磁盘准入、cell roster、采样/seed/blur 设置、pass、finite pixels、参考独立性、质量地板、指标、域检查、判决、操作、清理与 self-hash。</p></div><div className="b49mb-audit-grid"><article><strong>19 / 19</strong><span>frozen attacks rejected</span></article><article><strong>BYTE EXACT</strong><span>independent results replay</span></article><article><strong>0</strong><span>containers left running</span></article><article><strong>2b1d351…a8524</strong><span>evidence-core hash</span></article></div></section>

  <section className="section contact-limits" id="boundary"><div className="section-index">05 / CLAIM BOUNDARY</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> MACHINE GATE CLOSED · HUMAN GATE OPEN</p><h2>运动模糊工作点已选。<br/><span>景深与电影感尚未证明。</span></h2></div><p>本实验不覆盖长镜头时序稳定、变形/粒子模糊、rolling shutter、景深、GPU、2K/4K 成本，也没有证明人类偏好。下一步冻结并实测 DOF，再把候选交给匿名审片。</p></div><div className="b49-next"><span>THREE GATES</span><strong>RESOLUTION ✓</strong><i>→</i><strong>MOTION BLUR ✓</strong><i>→</i><strong>DOF + HUMAN OPEN</strong></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-worker-motion-blur-holdout-v0-1/results.json`}><span>MACHINE RESULT</span><b>8 workers · 19/19 ↗</b></a><a href={`${repo}experiments/codex-worker-motion-blur-holdout-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>byte-exact replay ↗</b></a><a href={`${repo}research/2026-08-27-b49-mb-codex-worker-motion-blur-holdout-result.md`}><span>RESULT NOTE</span><b>claims · limits · next ↗</b></a><a href={`${repo}research/2026-08-27-b49-mb-codex-worker-motion-blur-holdout-protocol.md`}><span>PREREGISTRATION</span><b>frozen before run ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B49 Motion Blur Holdout</b></div><p>machine support · small numerical advantage · human preference open</p><Link href="/journal">回到实验日志 →</Link></footer>
</main>}
