import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = { title: 'B15 Eevee 全序列复现边界｜Blender Film Studio', description: '同源 144 帧 A/B：0/144 PNG 字节相同，127/144 解码像素完全相同，精确确定性正式被证伪。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/review-proxy-repro-v0-1/' } };
const attacks = [['N01','A manifest identity','A_MANIFEST_SHA'],['N02','renderer identity','RENDERER_SHA'],['N03','A missing frame','A_MISSING_FRAME'],['N04','B missing frame','B_MISSING_FRAME'],['N05','B extra frame','B_EXTRA_FRAME'],['N06','A frame bytes','A_FRAME_SHA'],['N07','B frame bytes','B_FRAME_SHA'],['N08','A/B alias','ALIAS_RUNS']];

export default function ReviewProxyReproPage() {
  return <main className="contact-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav><Link href="/journal">实验日志</Link><Link href="/review-dailies-v0-1">B14 样片</Link><a href="#result">结果</a><a href="#boundary">边界</a></nav><span className="edition contact-edition">Proxy Repro 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B15 · SAME SOURCE · FULL SEQUENCE A/B</p><h1>差异很小。<br /><span>但“严格相同”已经被证伪。</span></h1><p>同一机器、Blender、`.blend`、OCIO 和 renderer 字节，完整渲染两次 144 帧。OpenImageIO 解码逐帧比较，不用 PNG 文件 SHA 代替像素结论。</p></div><aside className="contact-gate"><b>CURRENT STATUS</b><strong>FORMAL EXACT<br />FALSIFIED</strong><code>127 / 144 pixel-exact</code><code>114 failed pixels total</code><small>NO POST-HOC TOLERANCE</small></aside><div className="contact-stats"><article><strong>0/144</strong><span>PNG 字节一致</span><small>container exact</small></article><article><strong>127/144</strong><span>解码像素一致</span><small>17 frames differ</small></article><article><strong>114</strong><span>差异像素</span><small>of 74,649,600</small></article><article><strong>1/255</strong><span>最大通道差</span><small>approximately</small></article></div></section>
    <section className="section contact-verdict" id="result"><div className="section-index">00 / 正式结论</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> EXACTNESS IS A CLAIM</p><h2>99.9998473% 像素相同，<br /><span>仍然不是 exact。</span></h2></div><p>B15 门槛预先冻结为 max error 0。最终 17 帧出现 114 个差异像素，最坏 frame 94 有 14 个；最大差约一个 8-bit code value。“不可见”需要另一个预注册感知实验。</p></div><div className="diagnostic-result"><article><span>RUN A</span><strong>a529…</strong><b>B14 formal sequence</b><small>144 frames verified</small></article><article><span>RUN B</span><strong>ad3b…</strong><b>same renderer bytes</b><small>144 frames verified</small></article><article><span>WORST</span><strong>0094</strong><b>14 pixels</b><small>max 0.0039215833</small></article><article className="fail"><span>HYPOTHESIS</span><strong>FALSE</strong><b>exact decoded equality</b><small>falsification is a result</small></article></div></section>
    <section className="section contact-diagnostic"><div className="section-index">01 / 预注册攻击</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> VALID EXPERIMENT · 8 / 8</p><h2>先证明 A/B 真是两次运行，<br /><span>再谈像素。</span></h2></div><p>缺帧、多帧、源帧被改、manifest/renderer 换字节，以及把 A/B 指到同一个目录，全部在比较前被拒绝。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,result])=><li key={id}><span>{id}</span><b>{item}</b><small>{result}</small></li>)}</ol></section>
    <section className="section contact-limits" id="boundary"><div className="section-index">02 / 失败也要分层</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> CONTAINER ≠ PIXEL ≠ PERCEPTION</p><h2>三个层面，<br /><span>不能互相冒充。</span></h2></div><p>0/144 文件 SHA 相同，不代表 0/144 像素相同；127 帧解码完全一致证明多数文件差来自容器。B15 不追认感知容差，也不把 Eevee 外推给 Cycles EXR。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/review-proxy-repro-v0-1/results.json`}><span>RESULT</span><b>classification · attacks ↗</b></a><a href={`${repo}experiments/review-proxy-repro-v0-1/evidence/sequence.comparison.json`}><span>144 PAIRS</span><b>OIIO metrics ↗</b></a><a href={`${repo}research/2026-08-26-b15-review-proxy-repro-result.md`}><span>RESULT NOTE</span><b>invalid attempts ↗</b></a><a href={`${repo}research/lab-journal.md`}><span>JOURNAL</span><b>continuous record ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B15 Same-source Proxy Reproducibility</b></div><p>Exactness falsified · tolerance not selected</p><Link href="/research-agenda">进入下一个缺口 →</Link></footer>
  </main>;
}
