import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata = {
  title: 'B24 生产复现容差 Holdout｜Blender Film Studio',
  description: '真实 Blender 24 个未见帧、72 个进程验证：EXR32 与 PNG8 均 72/72 通过预冻结数值 envelope，22/22 攻击通过。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/production-tolerance-holdout-v0-1/' },
};
const holdout = [4,10,16,22,28,34,40,46,52,58,64,70,76,82,88,94,100,106,112,118,124,130,136,142];

export default function ProductionToleranceHoldoutPage() {
  return <main className="contact-page factorial-page">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B24 导航"><Link href="/journal">实验日志</Link><Link href="/eevee-repeated-render-boundary-v0-1">B23</Link><a href="#split">derivation / holdout</a><a href="#result">结果</a><a href="#failure">失败候选</a><a href="#next">下一边界</a></nav><span className="edition contact-edition">Holdout Envelope 0.1</span></header>
    <section className="contact-hero"><div className="contact-grid" aria-hidden="true" /><div className="contact-hero-copy"><p className="eyebrow"><span /> B24 · INDEPENDENT STATIC-FRAME HOLDOUT</p><h1>不要求每个像素相同。<br /><span>要求每个差异都在合同内。</span></h1><p>先用 B21/B23 的 288 个 EXR pair 与 36 个 PNG pair 推导 envelope，再冻结 24 个从未参与阈值选择的帧。72 个新进程的所有 pair 均通过，没有事后放宽阈值。</p></div><aside className="contact-gate"><b>PRE-REGISTERED DECISION</b><strong>ENVELOPE<br />SUPPORT</strong><code>EXR32 · 72 / 72</code><code>PNG8 · 72 / 72</code><small>22 / 22 ATTACKS PASS</small></aside><div className="contact-stats"><article><strong>24</strong><span>未见 holdout 帧</span><small>frame mod 6 = 4</small></article><article><strong>72/72</strong><span>唯一 PID</span><small>A / B / C</small></article><article><strong>144</strong><span>双格式保存</span><small>same Render Result</small></article><article><strong>0</strong><span>Yee failed pixels</span><small>nominal viewing inputs</small></article></div></section>

    <section className="section contact-verdict" id="split"><div className="section-index">00 / 先推导，再验证</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> DERIVATION ≠ VALIDATION</p><h2>旧差异只负责定门。<br /><span>新帧负责判生死。</span></h2></div><p>Holdout 由纯算术规则选择：1–144 中 `frame mod 6 = 4`。它与 B20–B23 的 12 个 sentinel 零重叠，且在任何 B24 render 之前写进预注册。</p></div><ol className="contact-negative-list">{holdout.map((frame,index)=><li key={frame}><span>{String(index+1).padStart(2,'0')}</span><b>frame {frame}</b><code>A · B · C</code><small>3 fresh pairs</small></li>)}</ol></section>

    <section className="section contact-evidence" id="result"><div className="section-index light">01 / Holdout 结果</div><div className="contact-heading"><div><p className="eyebrow"><span /> ALL PAIRS · ALL CEILINGS</p><h2>Strict exact 仍会失败。<br /><span>生产 envelope 全部通过。</span></h2></div><p>两种格式都只有 frame 10 的 A-B / A-C 非 exact，B-C exact。四个非 exact 格式-pair 仍满足各自 max、RMS、空间稀疏度与 Yee 门。</p></div><div className="factorial-matrix"><article className="factorial-exact"><span>EXR32 ENVELOPE</span><strong>72/72</strong><b>70/72 strict exact</b><small>max 0.0068359375</small></article><article className="factorial-exact"><span>PNG8 ENVELOPE</span><strong>72/72</strong><b>70/72 strict exact</b><small>max ≈ 1/255</small></article><article className="factorial-exact"><span>PROVENANCE</span><strong>72/72</strong><b>source · plan · structure</b><small>runtime/tool hashes exact</small></article><article className="factorial-exact"><span>ATTACKS</span><strong>22/22</strong><b>stable rejection reasons</b><small>threshold mutation included</small></article></div><div className="diagnostic-verdict"><b>DECISION</b><code>PRODUCTION_REPEATABILITY_ENVELOPE_SUPPORT</code><p>这是一个静态数值稳定合同，不是 bitwise determinism，也不是“观众绝对看不见”的声明。</p></div></section>

    <section className="section contact-limits" id="failure"><div className="section-index">02 / 失败候选仍然公开</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> CANDIDATE 0a69c1c · INVALID</p><h2>画面先通过了。<br /><span>实验合同没有通过。</span></h2></div><p>第一候选误实现 23 个攻击，而预注册明确要求 22 个，所以即使两种格式都是 72/72，runner 仍判 INVALID。修正后更换工具哈希并完整重跑，而不是复用有利结果。</p></div><div className="contact-nonclaim"><b>EXPERIMENTAL SPIRIT</b><p>门禁保护的不是“结果看起来好”，而是结论确实来自运行前承诺。实现偏离协议时，好结果也必须拒绝。</p></div></section>

    <section className="section contact-diagnostic"><div className="section-index">03 / 两套合同</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> EXACT PROVENANCE × BOUNDED PIXELS</p><h2>世界身份必须 exact。<br /><span>最终像素必须 bounded。</span></h2></div><p>SceneSpec、BuildPlan、资产、结构、Blender、OCIO 与工具身份仍执行严格哈希门；只有 GPU 渲染像素进入独立验证过的 envelope。两者不能混成一句“可复现”。</p></div></section>

    <section className="section contact-limits" id="next"><div className="section-index">04 / 下一影视边界</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span /> TEMPORAL PLAYBACK × BLIND REVIEW</p><h2>静帧稳定已支持。<br /><span>下一步看运动中是否闪烁。</span></h2></div><p>连续序列需要冻结 temporal-difference 指标和盲评协议。静态 Yee 的 nominal 100 cd/m²、45° 输入不能替代校准显示、播放节奏、观看距离和真实审片者。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/production-tolerance-holdout-v0-1/results.json`}><span>RESULT</span><b>144 holdout comparisons ↗</b></a><a href={`${repo}experiments/production-tolerance-derivation-v0-1/results.json`}><span>DERIVATION</span><b>threshold provenance ↗</b></a><a href={`${repo}research/2026-08-26-b24-production-tolerance-holdout-result.md`}><span>RESULT NOTE</span><b>invalid candidate retained ↗</b></a><a href="https://openimageio.readthedocs.io/en/latest/imagebufalgo.html"><span>OIIO</span><b>compare metric contract ↗</b></a><a href="https://docs.blender.org/manual/en/5.2/render/color_management/displays_views.html"><span>BLENDER 5.2</span><b>linear × display boundary ↗</b></a></div></section>
    <footer><div><span className="brand-mark">BFS</span><b>B24 Production Tolerance Holdout</b></div><p>Exact provenance · bounded pixels · independent holdout</p><Link href="/research-agenda">继续 temporal 验证 →</Link></footer>
  </main>;
}
