#!/usr/bin/env python3
"""C3 runner: materialize staged Data after all reset-triggering configuration."""

import hashlib
from pathlib import Path

BASE=Path(__file__).resolve().with_name("run-rc6-liquid-final-effector-mesh-c1.py")
EXPECTED_BASE_SHA256="58562de9fe0a24e3e9c9a2cbc39b64fc56be1624bb8b43b81080af883d541f0b"
if hashlib.sha256(BASE.read_bytes()).hexdigest()!=EXPECTED_BASE_SHA256:raise RuntimeError("C3 runner base identity mismatch")
source=BASE.read_text()
replacements=(
    ('"""Persist verified Data state, reopen it, and run one Mesh-only reconstruction."""','"""C3: materialize staged Data after configuration, persist, reopen and Mesh."""',"docstring"),
    ('FAILURE_EVIDENCE = RESEARCH / "experiments/physical-richness/RC6-2026-09-02-final-effector-mesh-attempt-44"\nFAILURE_WORK = Path("/Users/mengyingli/Documents/ChatGPT/BlenderFilmStudio-PostPB7-workspace/RC6-2026-09-02-final-effector-mesh-attempt-44")\nWORK = Path("/Users/mengyingli/Documents/ChatGPT/BlenderFilmStudio-PostPB7-workspace/RC6-2026-09-02-final-effector-mesh-c1-attempt-45")\nEVIDENCE = RESEARCH / "experiments/physical-richness/RC6-2026-09-02-final-effector-mesh-c1-attempt-45"','FAILURE_EVIDENCE = RESEARCH / "experiments/physical-richness/RC6-2026-09-02-final-effector-mesh-c1-attempt-45"\nFAILURE_WORK = Path("/Users/mengyingli/Documents/ChatGPT/BlenderFilmStudio-PostPB7-workspace/RC6-2026-09-02-final-effector-mesh-c1-attempt-45")\nWORK = Path("/Users/mengyingli/Documents/ChatGPT/BlenderFilmStudio-PostPB7-workspace/RC6-2026-09-02-final-effector-mesh-c3-attempt-46")\nEVIDENCE = RESEARCH / "experiments/physical-richness/RC6-2026-09-02-final-effector-mesh-c3-attempt-46"',"roots"),
    ('ADOPT_TOOL = RESEARCH / "scripts/run-rc6-liquid-final-effector-mesh-c1-adopt-scene.py"\nMESH_TOOL = RESEARCH / "scripts/run-rc6-liquid-final-effector-mesh-c1-scene.py"\nRUNNER = Path(__file__).resolve(); AUDITOR = RESEARCH / "scripts/audit-rc6-liquid-final-effector-mesh-c1.py"; SPEC = RESEARCH / "specs/ai-native-studio-rc6-liquid-final-effector-mesh-c1-tool-freeze.v0.50.json"\nCELL_ID = "final-effector-mesh-c1"','ADOPT_TOOL = RESEARCH / "scripts/run-rc6-liquid-final-effector-mesh-c3-adopt-scene.py"\nMESH_TOOL = RESEARCH / "scripts/run-rc6-liquid-final-effector-mesh-c3-scene.py"\nRUNNER = Path(__file__).resolve(); AUDITOR = RESEARCH / "scripts/audit-rc6-liquid-final-effector-mesh-c3.py"; SPEC = RESEARCH / "specs/ai-native-studio-rc6-liquid-final-effector-mesh-c3-tool-freeze.v0.54.json"\nCELL_ID = "final-effector-mesh-c3"',"tools and cell"),
    ('def argv(tool, blend): return [str(BINARY),"--background","--factory-startup","--disable-autoexec","--offline-mode",str(blend),"--python",str(tool),"--","--cell-id",CELL_ID,"--work-root",str(WORK),"--evidence-root",str(EVIDENCE),"--retained-data-manifest-hash",RETAINED_DATA_HASH] + ([] if tool==ADOPT_TOOL else ["--mesh-particle-radius","9.0"])','def argv(tool, blend): return [str(BINARY),"--background","--factory-startup","--disable-autoexec","--offline-mode",str(blend),"--python",str(tool),"--","--cell-id",CELL_ID,"--work-root",str(WORK),"--evidence-root",str(EVIDENCE),"--retained-data-manifest-hash",RETAINED_DATA_HASH] + (["--staged-data-root",str(WORK/"staged-data")] if tool==ADOPT_TOOL else ["--mesh-particle-radius","9.0"])',"argv"),
    ('    if manifest(FAILURE_EVIDENCE)["manifestHash"]!=spec["retainedFailure"]["evidenceRootManifestHash"] or manifest(FAILURE_WORK)["manifestHash"]!=spec["retainedFailure"]["workRootManifestHash"] or read_json(FAILURE_EVIDENCE/"processes/01-final-effector-mesh.json")["processHash"]!=spec["retainedFailure"]["processHash"]: raise RuntimeError("C1 retained failure drift")','    failure_evidence_manifest=manifest(FAILURE_EVIDENCE)\n    failure_evidence_manifest["root"]="experiments/physical-richness/RC6-2026-09-02-final-effector-mesh-c1-attempt-45"\n    failure_evidence_manifest["manifestHash"]=self_hash(failure_evidence_manifest,"manifestHash")\n    if failure_evidence_manifest["manifestHash"]!=spec["retainedFailure"]["evidenceRootManifestHash"] or manifest(FAILURE_WORK)["manifestHash"]!=spec["retainedFailure"]["workRootManifestHash"] or read_json(FAILURE_EVIDENCE/"processes/01.json")["processHash"]!=spec["retainedFailure"]["processHash"]: raise RuntimeError("C3 retained failure drift")',"failure binding"),
    ('    cell=WORK/CELL_ID; cell.mkdir(parents=True,exist_ok=False); shutil.copy2(SOURCE_BLEND,cell/"source-state.blend"); shutil.copytree(RETAINED_CACHE,cell/"mantaflow-cache",symlinks=False)\n    if data_manifest(cell/"mantaflow-cache")!=retained_data: raise RuntimeError("C1 copied Data drift")','    cell=WORK/CELL_ID; cell.mkdir(parents=True,exist_ok=False); shutil.copy2(SOURCE_BLEND,cell/"source-state.blend"); shutil.copytree(RETAINED_CACHE,WORK/"staged-data",symlinks=False)\n    if data_manifest(WORK/"staged-data")!=retained_data or (cell/"mantaflow-cache").exists(): raise RuntimeError("C3 staged Data or empty final cache mismatch")',"staging"),
    ('(MESH_TOOL,cell/"data-adopted-state.blend","RC6_FINAL_EFFECTOR_MESH_C1=")','(MESH_TOOL,cell/"data-adopted-state.blend","RC6_FINAL_EFFECTOR_MESH_C3=")',"marker"),
    ('result.get("schemaVersion")!="bfs.rc6LiquidFinalEffectorMeshC1Cell.v0.1"','result.get("schemaVersion")!="bfs.rc6LiquidFinalEffectorMeshC3Cell.v0.1"',"result schema"),
    ('status="PASS_FINAL_EFFECTOR_MESH_C1_STATIC" if scientific_pass(result,t) else "FAIL_FINAL_EFFECTOR_MESH_C1_STATIC"','status="PASS_FINAL_EFFECTOR_MESH_C3_STATIC" if scientific_pass(result,t) else "FAIL_FINAL_EFFECTOR_MESH_C3_STATIC"',"status"),
    ('"slowTipUnlocked":status=="PASS_FINAL_EFFECTOR_MESH_C1_STATIC"','"slowTipUnlocked":status=="PASS_FINAL_EFFECTOR_MESH_C3_STATIC"',"unlock"),
    ('"counts":{"blenderStarts":2,"cacheStateAdoptions":1,','"counts":{"blenderStarts":2,"stagedDataMaterializations":1,"cacheStateAdoptions":1,',"counts"),
    ('bfs.rc6LiquidFinalEffectorMeshC1Receipt.v0.1','bfs.rc6LiquidFinalEffectorMeshC3Receipt.v0.1',"receipt schema"),
    ('RC6_FINAL_EFFECTOR_MESH_C1_RECEIPT=','RC6_FINAL_EFFECTOR_MESH_C3_RECEIPT=',"receipt marker"),
)
for before,after,label in replacements:
    if source.count(before)!=1:raise RuntimeError(f"C3 runner {label} target mismatch")
    source=source.replace(before,after)
exec(compile(source,str(BASE)+"#MESH_C3_RUNNER_V01","exec"),globals(),globals())
