import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = { title: 'B49 景深 Holdout｜Blender Film Studio', description: '十个真实 Blender 5.2 worker、两场景、六个参考地板指标与 21/21 对抗审计，验证编译场景的 DOF 数值工作点。', alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/depth-of-field-holdout-v0-1/' } };
const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const shots=[
  {id:'TABLETOP',frame:43,camera:'58 mm · f/4 · focus 8.2 m',floor:['2.785777×','2.496550×','2.856265×'],gain:['0.529%','0.570%','0.465%'],cost:'1.0095×',files:['tabletop-off.png','tabletop-on.png','tabletop-reference.png','tabletop-difference.png']},
  {id:'INTERIOR',frame:23,camera:'70 mm · f/4 · focus 3.2 m',floor:['1.789957×','1.798302×','2.186421×'],gain:['45.264%','48.518%','64.131%'],cost:'1.0298×',files:['interior-off.png','interior-on.png','interior-reference.png','interior-difference.png']},
] as const;
const labels=['DOF OFF · 128 SPP','DOF ON · 128 SPP','3 × 512 REFERENCE','ON/OFF Δ · LOCAL SCALE'] as const;

export default function DepthOfFieldHoldoutPage(){return <main className="contact-page b49mb-page dof-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B49 景深导航"><Link href="/journal">实验日志</Link><Link href="/motion-blur-holdout-v0-1">运动模糊</Link><a href="#evidence">图像证据</a><a href="#human">人工门</a></nav><span className="edition contact-edition">Depth of Field B49-DOF</span></header>
  <section className="contact-hero b49mb-hero dof-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> TWO-SCENE · THREE-REFERENCE HOLDOUT</p><h1>景深机器门通过。<br/><span>焦点意图仍归人。</span></h1><p>两套真实编译场景都在三项冻结指标上保持 128-spp 数值充分性，并且 DOF-on 全部比同 seed 的 off 更接近高采样参考。但“更接近配置”不等于“配置选对了主体”。</p></div><aside className="contact-gate b49mb-gate"><b>FORMAL VERDICT</b><strong>SUPPORTED</strong><code>2 / 2 shots pass</code><code>6 / 6 metrics closer</code><small>21/21 ATTACKS · BYTE-EXACT AUDIT</small></aside><div className="contact-stats"><article><strong>10</strong><span>fresh workers</span><small>6 reference · 4 paired</small></article><article><strong>2</strong><span>real scenes</span><small>moving tabletop + static interior</small></article><article><strong>0.5</strong><span>frame shutter</span><small>held on in every cell</small></article><article><strong>1–3%</strong><span>DOF render cost</span><small>bounded 128×72 cells</small></article></div></section>

  <section className="section b49mb-design"><div className="section-index">00 / SINGLE-VARIABLE STACK TEST</div><div className="contact-heading"><div><p className="eyebrow"><span/> MOTION BLUR HELD ON · DOF TOGGLED</p><h2>不是孤立镜头玩具。<br/><span>是在已晋级特征栈里加景深。</span></h2></div><p>每个场景先用三次独立 512-spp DOF-on 建立本地噪声地板，再比较同 seed 的 128-spp on/off。分辨率、采样、快门、帧、场景、色彩和生产通道全部固定。</p></div><div className="b49mb-flow"><article><span>NEGATIVE</span><strong>DOF OFF</strong><small>128 spp · blur on</small></article><i>↔</i><article className="selected"><span>CANDIDATE</span><strong>DOF ON</strong><small>compiled focus · f/4</small></article><i>→</i><article><span>REFERENCE</span><strong>3 × 512</strong><small>independent seed ensemble</small></article></div></section>

  <section className="section b49mb-evidence" id="evidence"><div className="section-index">01 / REAL EXR DISPLAY PROXIES</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ACES 2 · HUMAN NAVIGATION ONLY</p><h2>TABLETOP 的差异很小。<br/><span>INTERIOR 的焦平面影响很大。</span></h2></div><p>代理图只用于定位；判决读取 scene-linear float32 EXR。每个差分热图使用自己的 99th-percentile 标尺，不能跨场景比较亮度。</p></div>{shots.map(shot=><article className="dof-shot" key={shot.id}><header><span>{shot.id} · FRAME {shot.frame}</span><b>{shot.camera}</b></header><div className="b49mb-image-grid">{shot.files.map((file,index)=><figure key={file} className={index===1?'selected':index===3?'heat':''}><Image src={`${basePath}/evidence/b49-dof/${file}`} width={128} height={72} unoptimized alt={`${shot.id} ${labels[index]} real Blender depth-of-field evidence`}/><figcaption>{labels[index]}</figcaption></figure>)}</div></article>)}</section>

  <section className="section b49mb-metrics"><div className="section-index">02 / REFERENCE-FLOOR GATE</div><div className="contact-heading"><div><p className="eyebrow"><span/> ALL VALUES MUST BE ≤ 3.000×</p><h2>六项全部过门。<br/><span>但两个场景效应量不同。</span></h2></div><p>TABLETOP 的 on/off 方向一致但优势不到 0.6%；INTERIOR 的 DOF 对高对比边缘与整体误差都产生显著更大影响。机器门只判断数值充分性与方向。</p></div>{shots.map(shot=><div className="dof-metric-block" key={shot.id}><header><strong>{shot.id}</strong><span>DOF COST {shot.cost}</span></header><ol className="b49mb-table"><li className="head"><span>METRIC</span><b>ON / FLOOR</b><code>ON IMPROVEMENT</code><small>GATE</small></li>{['LINEAR NRMSE','LOG-Y RMSE','EDGE RMSE'].map((metric,index)=><li key={metric}><span>{metric}</span><b>{shot.floor[index]}</b><code>{shot.gain[index]}</code><small>PASS</small></li>)}</ol></div>)}</section>

  <section className="section b49mb-domain"><div className="section-index">03 / PASS-DOMAIN CONSEQUENCE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> AUXILIARY PASSES ARE MODE-BOUND</p><h2>景深不只模糊 Combined。<br/><span>它也改变边界真值。</span></h2></div><p>两个真实场景的 Depth、Normal 和活动 Cryptomatte 层都随 DOF 改变；Vector 因 motion-blur 模式固定而 exact。下游合成必须知道生成 pass 时的镜头模式。</p></div><ol className="b49mb-pass-table"><li className="head"><span>PASS</span><b>TABLETOP ON ↔ OFF</b><code>INTERIOR ON ↔ OFF</code></li><li><span>Combined</span><b>22,427 Δ</b><code>27,637 Δ</code></li><li><span>Depth</span><b>7,065 Δ</b><code>9,216 Δ</code></li><li><span>Normal</span><b>2,909 Δ</b><code>2,568 Δ</code></li><li><span>Crypto active</span><b>373 Δ</b><code>2,074 Δ</code></li><li><span>Vector</span><b>EXACT</b><code>EXACT</code></li></ol></section>

  <section className="section b49mb-audit"><div className="section-index">04 / EVIDENCE INTEGRITY</div><div className="contact-heading"><div><p className="eyebrow"><span/> REAL BLENDER 5.2 · INDEPENDENT REPLAY</p><h2>二十一种篡改被拒绝。<br/><span>结果逐字节可重算。</span></h2></div><p>审计覆盖父证据、源 `.blend`、worker image、隔离、磁盘、cell、采样、seed、快门、DOF、焦点、pass、finite、参考独立性、地板、指标、pass 域、判决、操作、清理和 self-hash。</p></div><div className="b49mb-audit-grid"><article><strong>21 / 21</strong><span>frozen attacks rejected</span></article><article><strong>BYTE EXACT</strong><span>independent replay</span></article><article><strong>0</strong><span>containers left running</span></article><article><strong>6d40b92…6d2e0</strong><span>evidence-core hash</span></article></div></section>

  <section className="section contact-limits" id="human"><div className="section-index">05 / FINAL OPEN GATE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> MACHINE GATES CLOSED · HUMAN GATE OPEN</p><h2>数值证明已经够了。<br/><span>现在必须让人判断焦点。</span></h2></div><p>INTERIOR 的 3.2 m 焦点落在窗区，椅子在约 5.7–7.0 m。机器结果证明 Blender 忠实执行了设置，却不能证明导演应该把观众注意力放在那里。下一步必须用 viewable-resolution、延迟披露、匿名平衡审片比较焦点意图和电影感。</p></div><div className="b49-next"><span>THREE MACHINE GATES</span><strong>RESOLUTION ✓</strong><i>→</i><strong>MOTION BLUR ✓</strong><i>→</i><strong>DOF ✓</strong><i>→</i><strong>HUMAN OPEN</strong></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-worker-depth-of-field-holdout-v0-1/results.json`}><span>MACHINE RESULT</span><b>two scenes · 21/21 ↗</b></a><a href={`${repo}experiments/codex-worker-depth-of-field-holdout-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>byte-exact replay ↗</b></a><a href={`${repo}research/2026-08-27-b49-dof-codex-worker-depth-of-field-holdout-result.md`}><span>RESULT NOTE</span><b>effect · cost · limits ↗</b></a><a href={`${repo}research/2026-08-27-b49-dof-codex-worker-depth-of-field-holdout-protocol.md`}><span>PREREGISTRATION</span><b>frozen before run ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B49 Depth of Field Holdout</b></div><p>machine gates closed · focus intent remains human</p><Link href="/journal">回到实验日志 →</Link></footer>
</main>}
