import type { Metadata } from 'next';
import Link from 'next/link';

const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
export const metadata: Metadata={title:'B16 Blender Dither 因果隔离｜Blender Film Studio',description:'关闭 Blender 输出 dither 后，全序列仍只有 130/144 帧 exact：dither 不是充分原因。',alternates:{canonical:'https://lovejzzz.github.io/BlenderFilmStudio/dither-isolation-v0-1/'}};
const attacks=[['N01','configurator bytes','CONFIGURATOR_SHA'],['N02','intervention value','INTERVENTION_VALUE'],['N03','starting dither','STARTING_DITHER'],['N04','run alias','ALIAS_RUNS'],['N05','A missing frame','D0-A_MISSING_FRAME'],['N06','B missing frame','D0-B_MISSING_FRAME'],['N07','B extra frame','D0-B_EXTRA_FRAME'],['N08','B frame bytes','D0-B_FRAME_SHA']];
export default function DitherIsolationPage(){return <main className="contact-page"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav><Link href="/journal">实验日志</Link><Link href="/review-proxy-repro-v0-1">B15</Link><a href="#result">结果</a><a href="#next">下一变量</a></nav><span className="edition contact-edition">Dither Isolation 0.1</span></header>
<section className="contact-hero"><div className="contact-grid"/><div className="contact-hero-copy"><p className="eyebrow"><span/>B16 · ONE-VARIABLE CAUSAL ISOLATION</p><h1>关掉 dither。<br/><span>微小漂移仍然存在。</span></h1><p>真实 Blender 查询确认源场景 dither=1.0。两个新净运行只把它改成 0.0，其余 renderer、场景、ACES 2 与 144 帧合同不变。</p></div><aside className="contact-gate"><b>DECISION</b><strong>DITHER NOT<br/>SUFFICIENT</strong><code>130 / 144 pixel-exact</code><code>69 failed pixels</code><small>8 / 8 ATTACKS PASS</small></aside><div className="contact-stats"><article><strong>1→0</strong><span>唯一干预</span><small>dither intensity</small></article><article><strong>130/144</strong><span>解码 exact</span><small>14 frames differ</small></article><article><strong>69</strong><span>差异像素</span><small>of 74.65M</small></article><article><strong>1/255</strong><span>最大差</span><small>approximately</small></article></div></section>
<section className="section contact-verdict" id="result"><div className="section-index">00 / 因果判定</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/>NECESSARY QUESTION · NEGATIVE ANSWER</p><h2>dither 不是，<br/><span>完整解释。</span></h2></div><p>如果输出抖动是充分原因，D0-A/B 应达到 144/144、max error 0。实际仍有 69 个差异像素，因此按预注册规则判为 DITHER_NOT_SUFFICIENT。不能因差异很小而改门槛。</p></div><div className="diagnostic-result"><article><span>B15 · DITHER 1</span><strong>127</strong><b>exact frames</b><small>114 pixels differ</small></article><article><span>B16 · DITHER 0</span><strong>130</strong><b>exact frames</b><small>69 pixels differ</small></article><article><span>CONTAINER</span><strong>0/144</strong><b>byte exact</b><small>separate claim</small></article><article className="fail"><span>HYPOTHESIS</span><strong>FALSE</strong><b>dither sufficient</b><small>valid negative result</small></article></div></section>
<section className="section contact-diagnostic"><div className="section-index">01 / 对抗门</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/>8 / 8 STABLE REASONS</p><h2>先证明干预真的只改一项。</h2></div><p>配置器字节、before/after、目录独立性、缺帧、多帧和帧字节都被验证；源 `.blend` 没有保存。</p></div><ol className="contact-negative-list">{attacks.map(([id,item,result])=><li key={id}><span>{id}</span><b>{item}</b><small>{result}</small></li>)}</ol></section>
<section className="section contact-limits" id="next"><div className="section-index">02 / 下一候选</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/>REPEATED FRAMES · NEARBY COORDINATES</p><h2>下一步看采样与求值顺序。</h2></div><p>43、91、93、110、111、114 在 B15/B16 都出现微差，坐标也相近。下一实验应控制 Eevee sample count 或执行并行度，而不是继续猜 PNG metadata。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/dither-isolation-v0-1/results.json`}><span>RESULT</span><b>decision · 8 attacks ↗</b></a><a href={`${repo}experiments/dither-isolation-v0-1/evidence/D0.sequence.comparison.json`}><span>144 PAIRS</span><b>OIIO comparison ↗</b></a><a href={`${repo}research/2026-08-26-b16-dither-isolation-result.md`}><span>RESULT NOTE</span><b>causal boundary ↗</b></a><a href={`${repo}research/lab-journal.md`}><span>JOURNAL</span><b>continuous record ↗</b></a></div></section><footer><div><span className="brand-mark">BFS</span><b>B16 Dither Isolation</b></div><p>One variable changed · exactness still false</p><Link href="/research-agenda">继续隔离 →</Link></footer></main>}
