import type { Metadata } from 'next';
import Link from 'next/link';

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const carriers = [
  ['A','27,496,119','0fc70ebc…e077b'],['B','27,510,630','5d21be2f…e8688c'],['C','27,492,939','538ebb58…3b95c1'],
];
const fields = ['anonymous observer ID','expertise','development involvement','acuity / colour screening','display model','resolution / refresh','scaling / brightness','browser / OS','viewing distance','ambient lighting','timestamps','carrier hashes'];

export const metadata: Metadata = {
  title: 'B26 匿名时间稳定性审片协议｜Blender Film Studio',
  description: '三条 lossless VP9 carrier 均 144/144 RGB exact，18 个平衡匿名 session 已就绪；正式人类结果仍为 PENDING。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/blind-temporal-review-v0-1/' },
};

export default function BlindTemporalReviewPage(){return <main className="contact-page factorial-page blind-review-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B26 导航"><Link href="/journal">实验日志</Link><Link href="/temporal-residual-holdout-v0-1">B25</Link><a href="#carrier">载体</a><a href="#blind">匿名化</a><a href="#people">人数门</a><a href="#status">状态</a></nav><span className="edition contact-edition">Blind Review 0.1</span></header>
  <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B26 · CARRIER READY · HUMAN PENDING</p><h1>载体 432/432。<br/><span>人类结论尚未发生。</span></h1><p>普通 MP4 会引入比 Blender 微差更大的编码变量。B26 把 A/B/C 独立编码为 lossless VP9，再逐帧解码回 RGB：三条均 144/144 exact。机器只证明载体没有改像素，不替观察者判断“看不看得见”。</p></div><aside className="contact-gate"><b>REVIEW STATUS</b><strong>HUMAN<br/>PENDING</strong><code>CARRIERS · 3 / 3 EXACT</code><code>ATTACKS · 20 / 20</code><small>FORMAL RESPONSES · 0 / 18</small></aside><div className="contact-stats"><article><strong>432/432</strong><span>roundtrip RGB 帧</span><small>maximum error 0</small></article><article><strong>82.5 MB</strong><span>三条 lossless carrier</span><small>VP9 Profile 1 · gbrp</small></article><article><strong>18</strong><span>匿名 session</span><small>6 orders × 3</small></article><article><strong>0</strong><span>有效观察者</span><small>no inferred result</small></article></div></section>

  <section className="section contact-verdict" id="carrier"><div className="section-index">00 / 先证明播放器没有改题</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> LOSSLESS CARRIER GATE</p><h2>先把 PNG 序列装进视频。<br/><span>再完整拆回来逐帧验算。</span></h2></div><p>FFmpeg 8.1.2 把每条 960×540、24 fps、6 秒序列编码为 VP9 Profile 1 `gbrp`。解码后必须 144/144 RGB exact、max=0、changed pixels=0；alpha 只有在源序列全部精确等于 1 时才可省略。</p></div><div className="blind-carrier-grid">{carriers.map(([label,bytes,sha])=><article key={label}><span>CARRIER {label}</span><strong>144/144</strong><b>RGB exact</b><code>{bytes} bytes</code><small>SHA {sha}</small></article>)}</div><div className="contact-nonclaim"><b>CARRIER PASS ≠ HUMAN PASS</b><p>这里证明的只是播放材料忠实承载 PNG8 RGB；它不证明 VP9 在所有浏览器/显示器拥有相同色彩管理，也不证明观察者看不到时间差异。</p></div></section>

  <section className="section contact-evidence" id="blind"><div className="section-index light">01 / 匿名化与 response lock</div><div className="contact-heading"><div><p className="eyebrow"><span/> SIX ORDERS · SEALED MAPPING</p><h2>观察者只见 CLIP-01/02/03。<br/><span>A/B/C 在锁定前不公开。</span></h2></div><p>六种顺序各分配给三位观察者。每个 session 用 32-byte salt 提交 SHA-256 commitment；公开证据保存 commitment，真实映射留在 git-ignore 本地目录，等 primary responses 全部锁定后才可解盲。</p></div><div className="blind-flow"><article><span>01 · SOURCE</span><b>A / B / C</b><small>verified carrier hashes</small></article><i>→</i><article><span>02 · SEALED</span><b>salt + mapping</b><small>commitment only is public</small></article><i>→</i><article><span>03 · OBSERVER</span><b>CLIP-01 / 02 / 03</b><small>no pause · seek · loop</small></article><i>→</i><article><span>04 · LOCK</span><b>responseHash</b><small>unblind only afterward</small></article></div><div className="diagnostic-verdict"><b>MAPPING COMMITMENT</b><code>540cc4c76193fc460945968e6919e5684d8a45fee58c5f8dcbcdfdee15a4379b</code><p>18 个 session commitment 均唯一；observer HTML 中未出现 sourceLabel、underlyingLabel 或 permutation。</p></div></section>

  <section className="section contact-diagnostic" id="people"><div className="section-index">02 / 人数不是装饰</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> ITU-R BT.500-15 BOUNDARY</p><h2>项目参与者只能 pilot。<br/><span>正式目标是 18 位独立观察者。</span></h2></div><p>现行 BT.500 通常要求至少 15 位观察者；更少必须标为 informal，直接参与系统开发的人不应进入正式样本。B26 用 18 人让六种顺序各重复三次；15–17 人仍记作 formal incomplete。</p></div><div className="factorial-matrix"><article className="factorial-nonexact"><span>OWNER / DEVELOPER</span><strong>PILOT</strong><b>interface only</b><small>never enters formal N</small></article><article className="factorial-nonexact"><span>1–14 INDEPENDENT</span><strong>INFORMAL</strong><b>descriptive only</b><small>no formal visibility claim</small></article><article className="factorial-nonexact"><span>15–17 VALID</span><strong>INCOMPLETE</strong><b>preserve and recruit</b><small>target balance not reached</small></article><article className="factorial-exact"><span>18 VALID</span><strong>FORMAL</strong><b>apply frozen decision</b><small>6 permutations × 3</small></article></div><div className="blind-field-grid">{fields.map((field,index)=><span key={field}><b>{String(index+1).padStart(2,'0')}</b>{field}</span>)}</div></section>

  <section className="section contact-limits" id="status"><div className="section-index">03 / 当前能说与不能说</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> PACKAGE READY · ZERO RESPONSES</p><h2>可以开始招募和 pilot。<br/><span>现在不能写“没有可见差异”。</span></h2></div><p>本机浏览器已验证三条视频 readyState 4、960×540、6 秒、无 controls；一次自动界面播放只验证计数从 0/2→1/2，并立即 reload，没有生成 response。正式与 pilot response count 均为 0。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/blind-temporal-review-v0-1/results.json`}><span>PACKAGE RESULT</span><b>20 attacks · human pending ↗</b></a><a href={`${repo}experiments/blind-temporal-review-v0-1/evidence/package.manifest.json`}><span>MANIFEST</span><b>carriers · sessions · hashes ↗</b></a><a href={`${repo}experiments/blind-temporal-review-v0-1/evidence/mapping.commitment.json`}><span>COMMITMENT</span><b>18 sealed sessions ↗</b></a><a href={`${repo}research/2026-08-26-b26-blind-temporal-review-protocol.md`}><span>PREREGISTRATION</span><b>people · decision gates ↗</b></a><a href="https://www.itu.int/rec/R-REC-BT.500-15-202305-I/en"><span>ITU-R BT.500-15</span><b>observer boundary ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B26 Blinded Temporal Review</b></div><p>Lossless carriers exact · mapping sealed · human result pending</p><Link href="/research-agenda">继续招募与 frame 38 隔离 →</Link></footer>
</main>}
