import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'B49 分辨率缩放 Holdout｜Blender Film Studio',
  description: '两个真实 Blender 5.2 worker 在未见 512×288 点验证跨场景近线性像素成本；15/15 攻击与独立字节重放通过。',
  alternates: { canonical: 'https://lovejzzz.github.io/BlenderFilmStudio/resolution-holdout-v0-1/' },
};

const repo = 'https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const shots = [
  { id:'TABLETOP', frame:37, baseline:'9.876 s', measured:'151.992 s', wall:'161.733 s', ratio:'15.390×', exponent:'0.985980', exr:'3.54 MB', exrExponent:'0.917547', rss:'541,200 KiB', point:'36%' },
  { id:'INTERIOR', frame:19, baseline:'12.119 s', measured:'191.877 s', wall:'201.652 s', ratio:'15.833×', exponent:'0.996206', exr:'3.36 MB', exrExponent:'0.955367', rss:'541,336 KiB', point:'46%' },
] as const;
const projections = [
  ['TABLETOP','28.25–48.55 min','113.0–194.2 h','1.76–3.47 h','421.7–832.6 h'],
  ['INTERIOR','34.67–59.58 min','138.7–238.3 h','2.16–4.26 h','517.5–1,021.7 h'],
] as const;

export default function ResolutionHoldoutPage(){return <main className="contact-page b49-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="B49 导航"><Link href="/journal">实验日志</Link><Link href="/quality-cost-holdout-v0-1">B48 工作点</Link><a href="#measured">实测</a><a href="#projection">外推边界</a></nav><span className="edition contact-edition">Resolution B49-R</span></header>

  <section className="contact-hero b49-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> PREREGISTERED · UNSEEN 16× PIXEL HOLDOUT</p><h1>像素扩大十六倍。<br/><span>时间仍接近线性。</span></h1><p>不是从已有曲线挑一个好看的点。我们先冻结 `[0.95,1.05]` 指数门，再让 TABLETOP 与 INTERIOR 两个真实 Blender 5.2 worker 各自渲染未见的 512×288 帧。</p></div><aside className="contact-gate b49-gate"><b>FORMAL VERDICT</b><strong>SUPPORTED</strong><code>p = 0.985980</code><code>p = 0.996206</code><small>15/15 ATTACKS · BYTE-EXACT AUDIT</small></aside><div className="contact-stats"><article><strong>2</strong><span>新鲜 worker</span><small>two scenes · one cell each</small></article><article><strong>16×</strong><span>像素干预</span><small>128×72 → 512×288</small></article><article><strong>128</strong><span>samples · raw</span><small>B48 selected point</small></article><article><strong>7</strong><span>EXR subimages</span><small>finite float32 Combined</small></article></div></section>

  <section className="section b49-design"><div className="section-index">00 / PRECOMMITTED DESIGN</div><div className="contact-heading"><div><p className="eyebrow"><span/> CHANGE ONE SPATIAL VARIABLE</p><h2>固定场景、采样和种子。<br/><span>只扩大输出网格。</span></h2></div><p>两帧沿用 B48 的场景、帧号、128-spp raw、seed offset、四线程、ACES 2 与生产通道。关闭 denoise、motion blur 和 persistent data。如此测到的是空间分辨率缩放，不是混合干预。</p></div><div className="b49-flow"><article><span>BASELINE</span><strong>128 × 72</strong><b>9,216 PIXELS</b><small>committed B48 timing</small></article><i>×16</i><article><span>UNSEEN HOLDOUT</span><strong>512 × 288</strong><b>147,456 PIXELS</b><small>two real workers</small></article><i>→</i><article><span>FROZEN GATE</span><strong>0.95 ≤ p ≤ 1.05</strong><b>BOTH SCENES REQUIRED</b><small>no post-hoc widening</small></article></div></section>

  <section className="section b49-measured" id="measured"><div className="section-index">01 / MEASURED BLENDER OUTPUT</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> OPERATOR TIME ≠ CONTAINER WALL</p><h2>两种场景，<br/><span>两次真实 512×288 渲染。</span></h2></div><p>Blender render operator 时间是缩放判据；fresh-worker wall 另行保留，包含约十秒的容器、Blender 与场景启动开销。EXR 是原始证据，不是网页截图。</p></div><div className="b49-shot-grid">{shots.map(shot=><article key={shot.id}><header><span>{shot.id} · FRAME {shot.frame}</span><b>PASS</b></header><div className="b49-time"><small>128×72 BASELINE</small><code>{shot.baseline}</code><i>→</i><small>512×288 MEASURED</small><strong>{shot.measured}</strong></div><dl><div><dt>TIME RATIO</dt><dd>{shot.ratio}</dd></div><div><dt>FRESH WALL</dt><dd>{shot.wall}</dd></div><div><dt>EXR / p</dt><dd>{shot.exr} / {shot.exrExponent}</dd></div><div><dt>PEAK SELF RSS</dt><dd>{shot.rss}</dd></div></dl></article>)}</div></section>

  <section className="section b49-gates"><div className="section-index">02 / EXPONENT GATE</div><div className="contact-heading"><div><p className="eyebrow"><span/> LOG(TIME RATIO) ÷ LOG(PIXEL RATIO)</p><h2>不是“看起来差不多”。<br/><span>两个点都必须进门。</span></h2></div><p>若渲染时间严格正比于像素数，指数 p=1。预注册容许 ±0.05；任一场景越界都会拒绝跨场景假设。</p></div><div className="b49-gauge"><header><span>0.95 · LOWER GATE</span><b>1.00 · LINEAR</b><span>1.05 · UPPER GATE</span></header>{shots.map(shot=><div className="b49-gauge-row" key={shot.id}><b>{shot.id}</b><div><i style={{left:shot.point}}/><span style={{width:shot.point}}/></div><strong>{shot.exponent}</strong></div>)}</div><div className="b49-gate-result"><span>HYPOTHESIS</span><b>near-linear through 512×288 on both frozen scenes</b><strong>SUPPORTED</strong></div></section>

  <section className="section b49-projection" id="projection"><div className="section-index">03 / MODEL PROJECTION · NOT MEASURED</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> CURRENT QEMU CPU WORKER ONLY</p><h2>2K / 4K 数字可以算。<br/><span>不能冒充跑过。</span></h2></div><p>下面从两个已提交 128×72 基线与冻结指数带 `[0.95,1.05]` 外推。宽区间是诚实的不确定性；它同时说明当前四 vCPU、amd64 emulation worker 不适合高分辨率生产。</p></div><ol className="b49-projection-table"><li className="head"><span>SHOT</span><b>2K / FRAME</b><code>2K × 240</code><b>4K / FRAME</b><code>4K × 240</code></li>{projections.map(row=><li key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><code>{row[2]}</code><b>{row[3]}</b><code>{row[4]}</code></li>)}</ol><div className="b49-labels"><b>MODEL_PROJECTION_NOT_MEASURED</b><b>CURRENT_QEMU_CPU_WORKER_ONLY</b><span>NO DOLLAR COST · NO COMPLETE SHOT · NO GPU CLAIM</span></div></section>

  <section className="section b49-audit"><div className="section-index">04 / EVIDENCE INTEGRITY</div><div className="contact-heading"><div><p className="eyebrow"><span/> REAL EXR · ADVERSARIAL REPLAY</p><h2>绿灯必须能被攻击。<br/><span>也必须能被独立重算。</span></h2></div><p>分析器验证父证据、源文件、worker image、隔离边界、磁盘准入、分辨率、渲染设置、pass roster、finite pixels、指数、RSS、操作计数、清理与 self-hash。</p></div><div className="b49-audit-grid"><article><strong>15 / 15</strong><span>frozen attacks rejected</span></article><article><strong>BYTE EXACT</strong><span>independent results replay</span></article><article><strong>0</strong><span>containers left running</span></article><article><strong>0b8199…2c9e</strong><span>evidence-core hash</span></article></div></section>

  <section className="section contact-limits"><div className="section-index">05 / CLAIM BOUNDARY</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> RESOLUTION CLOSED · CINEMA FEATURES OPEN</p><h2>空间成本门已过。<br/><span>运动与镜头光学仍未过。</span></h2></div><p>这个结论不证明 motion blur、depth of field、角色毛发、复杂纹理、GPU 吞吐或电影感。下一步必须保持分辨率与采样固定，分别介入运动模糊和景深，再进入匿名人类审片。</p></div><div className="b49-next"><span>NEXT B49 INTERVENTIONS</span><strong>MOTION BLUR</strong><i>→</i><strong>DEPTH OF FIELD</strong><i>→</i><strong>HUMAN REVIEW</strong></div><div className="contact-artifacts"><a href={`${repo}experiments/codex-worker-resolution-holdout-v0-1/results.json`}><span>MACHINE RESULT</span><b>two scenes · 15/15 ↗</b></a><a href={`${repo}experiments/codex-worker-resolution-holdout-v0-1/audit.json`}><span>INDEPENDENT AUDIT</span><b>byte-exact replay ↗</b></a><a href={`${repo}research/2026-08-27-b49-r-codex-worker-resolution-holdout-result.md`}><span>RESULT NOTE</span><b>claims · projections · limits ↗</b></a><a href={`${repo}research/2026-08-27-b49-r-codex-worker-resolution-holdout-protocol.md`}><span>PREREGISTRATION</span><b>frozen before tools ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B49 Resolution Holdout</b></div><p>two unseen cells · measured through 512×288 · projections labelled</p><Link href="/journal">回到实验日志 →</Link></footer>
</main>}
