import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const canonical='https://lovejzzz.github.io/BlenderFilmStudio/blender-static-adaptive-risk-gate-v0-1/';
const socialImage='https://lovejzzz.github.io/BlenderFilmStudio/evidence/b52-d12-7/frustum-crossbar-sphere-beauty.png';
export const metadata:Metadata={title:'B52-D12.7 自适应局部风险门｜Blender Film Studio',description:'12 次 fresh Blender render：冻结的局部风险门保留 99.60–99.86% radius-2 域，同时把 RGB 极值压到半门以下；正式结论因 comparator 合同保持 bounded。',alternates:{canonical},openGraph:{title:'B52-D12.7 自适应局部风险门',description:'候选本身通过；预注册 comparator 失败，结论不追改。',url:canonical,images:[{url:socialImage}]},twitter:{card:'summary_large_image',title:'B52-D12.7 自适应局部风险门',description:'12 renders · 20/21 checks · corrected audit 30/30',images:[socialImage]}};
const repo='https://github.com/lovejzzz/BlenderFilmStudio/blob/main/';
const basePath=process.env.GITHUB_PAGES==='true'?'/BlenderFilmStudio':'';
const fixtures=[
  {id:'RIPPLE / ROUNDED BOX',name:'ripple-rounded-box',raster:'117×79',registered:'9,164',r2:'7,661',adaptive:'7,650',rejected:'11',r3:'6,925',r2keep:'99.856%',r3gain:'+10.469%',adaptiveMax:'8.34465e−7',r3Max:'1.25170e−6',owner:'99.831%'},
  {id:'SUPERELLIPSE / TORUS',name:'superellipse-torus',raster:'139×91',registered:'6,334',r2:'4,325',adaptive:'4,318',rejected:'7',r3:'3,408',r2keep:'99.838%',r3gain:'+26.702%',adaptiveMax:'8.34465e−7',r3Max:'1.60933e−6',owner:'99.191%'},
  {id:'SPHERE / FRUSTUM / CROSSBAR',name:'frustum-crossbar-sphere',raster:'157×103',registered:'8,160',r2:'6,472',adaptive:'6,446',rejected:'26',r3:'5,736',r2keep:'99.598%',r3gain:'+12.378%',adaptiveMax:'8.94070e−7',r3Max:'2.14577e−6',owner:'95.963%'},
] as const;

export default function BlenderStaticAdaptiveRiskGatePage(){return <main className="contact-page d127-page">
  <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">BFS</span><span>Blender Film Studio</span></Link><nav aria-label="D12.7 导航"><Link href="/blender-static-interior-risk-localization-v0-1">D12.6</Link><a href="#verdict">判定</a><a href="#fixtures">真实场景</a><a href="#matrix">测量</a><a href="#audit">审计</a><Link href="/journal">日志</Link></nav><span className="edition contact-edition">Holdout D12.7</span></header>
  <section className="contact-hero d127-hero"><div className="contact-grid" aria-hidden="true"/><div className="contact-hero-copy"><p className="eyebrow"><span/> B52-D12.7 · FRESH REAL-BLENDER HOLDOUT</p><h1>局部风险门通过。<br/><span>正式结论仍有边界。</span></h1><p>冻结公式第一次面对三组未见几何：只从 radius 2 拒绝 44 个高风险像素，却比 radius 3 多保留 10.47–26.70% 的域。候选全部过门；预注册 comparator 自己越界，因此不追改总 verdict。</p></div><aside className="contact-gate d127-gate"><b>FROZEN VERDICT</b><strong>BOUNDED<br/>NOT PROMOTED</strong><code>candidate gates · pass</code><code>radius-3 comparator · fail</code><small>scientific label unchanged</small></aside><div className="contact-stats"><article><strong>12</strong><span>fresh Blender renders</span><small>3 fixtures × 2 frames × 2 repeats</small></article><article><strong>44</strong><span>radius-2 pixels rejected</span><small>non-empty tail in every fixture</small></article><article><strong>99.60–99.86%</strong><span>radius-2 coverage retained</span><small>all owners ≥95%</small></article><article><strong>30 / 30</strong><span>corrected audit attacks</span><small>zero scientific rerender</small></article></div></section>
  <section className="section d127-verdict" id="verdict"><div className="section-index">00 / READ THE LOGIC LITERALLY</div><div className="contact-heading"><div><p className="eyebrow"><span/> CANDIDATE ≠ OVERALL LABEL</p><h2>新规则完成了任务。<br/><span>旧比较器让总判定停在 bounded。</span></h2></div><p>冻结 analyzer 要求 21 项全部为真才能写 supported。局部风险候选的容差、stress、覆盖与 owner 公平性全部通过；唯一失败项是 radius 3 comparator 在第三场景越过原 production max。</p></div><div className="d127-logic"><article className="pass"><span>ADAPTIVE TOLERANCE</span><strong>PASS</strong><code>max ≤ 9.53674e−7</code><p>三组 primary cell 的最大值为 8.34465e−7、8.34465e−7、8.94070e−7。</p></article><i>+</i><article className="pass"><span>COVERAGE / STRESS</span><strong>PASS</strong><code>rejected &gt; 0 · owners ≥95%</code><p>每组都拒绝非空尾部；最低 owner retention 是 crossbar 的 95.963%。</p></article><i>+</i><article className="fail"><span>RADIUS-3 COMPARATOR</span><strong>FAIL</strong><code>2.14577e−6 &gt; 1.90735e−6</code><p>比较器不满足冻结 production gate，所以总 verdict 不能写 supported。</p></article><i>=</i><article className="bounded"><span>FROZEN VERDICT</span><strong>BOUNDED</strong><code>20 / 21 checks</code><p>结果支持继续验证候选，不构成生产 temporal policy 晋级。</p></article></div></section>
  <section className="section d127-fixtures" id="fixtures"><div className="section-index">01 / UNSEEN GEOMETRY · SAME FROZEN RULE</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> BEAUTY · ADAPTIVE · RADIUS 3</p><h2>不是示意图。<br/><span>是正式 EXR 的真实像素域。</span></h2></div><p>左侧是 ACES display proxy；中间绿色是 adaptive interior、橙色是边界、洋红是被风险门拒绝的 radius-2 像素；右侧青色是 radius 3 comparator。PNG 仅用于阅读，所有判定仍来自 scene-linear float arrays。</p></div><div className="d127-gallery">{fixtures.map(f=><article key={f.id}><header><div><span>{f.id}</span><b>{f.raster}</b></div><code>{f.rejected} REJECTED · {f.r3gain} VS R3</code></header><div>{[['beauty','BEAUTY'],['adaptive','ADAPTIVE · GREEN / REJECTED · MAGENTA'],['radius3','RADIUS 3 · CYAN']].map(([suffix,label])=><figure key={suffix}><Image src={`${basePath}/evidence/b52-d12-7/${f.name}-${suffix}.png`} width={628} height={412} unoptimized alt={`${f.id} ${label} proxy`}/><figcaption>{label}</figcaption></figure>)}</div></article>)}</div><div className="contact-nonclaim"><b>DISPLAY PROXY ≠ DECISION SURFACE</b><p>九份 PNG 在实验和审计结束后导出；manifest 绑定每份源 EXR、binary mask、OCIO、formal result 与 corrected audit 的 SHA-256。</p></div></section>
  <section className="section d127-matrix" id="matrix"><div className="section-index">02 / PRIMARY REPEAT MEASUREMENTS</div><div className="contact-heading"><div><p className="eyebrow"><span/> SAFETY WITHOUT GLOBAL OVER-EROSION</p><h2>保留几乎全部 radius 2。<br/><span>同时守住更严格的半门。</span></h2></div><p>adaptive 不是对 radius 3 的轻微修补：它从更宽的 radius-2 域出发，只拒绝局部风险高的像素。三组里，adaptive 都至少保留对应 radius-3 owner count。</p></div><div className="d127-table"><div className="head"><b>FIXTURE</b><b>REGISTERED</b><b>RADIUS 2</b><b>ADAPTIVE</b><b>REJECT</b><b>RADIUS 3</b><b>R2 KEEP</b><b>GAIN / R3</b><b>ADAPTIVE MAX</b><b>R3 MAX</b></div>{fixtures.map(f=><div className="row" key={f.id}><strong>{f.id}<small>lowest owner {f.owner}</small></strong><code>{f.registered}</code><code>{f.r2}</code><code>{f.adaptive}</code><code>{f.rejected}</code><code>{f.r3}</code><code>{f.r2keep}</code><b>{f.r3gain}</b><code>{f.adaptiveMax}</code><code className={f.id.startsWith('SPHERE')?'warn':''}>{f.r3Max}</code></div>)}</div><div className="d127-bounds"><article><span>ADAPTIVE RGB MAX</span><strong>≤ 8.94070e−7</strong><p>低于冻结 half-gate 9.53674e−7。</p></article><article><span>RISK UNDERBOUNDS</span><strong>0</strong><p>六个 repeat cell 的 RGB 样本全部满足 actual ≤ bound。</p></article><article><span>RADIUS-3 EXTRA LOSS</span><strong>725–910 px</strong><p>相对 adaptive，每个 primary fixture 额外删除的安全域。</p></article></div></section>
  <section className="section d127-audit" id="audit"><div className="section-index">03 / FAILURE PRESERVED · CORRECTION BOUNDED</div><div className="contact-heading dark-heading"><div><p className="eyebrow dark"><span/> AUDIT IS PART OF THE EXPERIMENT</p><h2>第一次审计失败。<br/><span>所以我们没有把它藏起来。</span></h2></div><p>原 audit 重建了 payload、process totality、21 项 checks 与 bounded verdict，却只拒绝 28/30 个 repaired-self-hash mutations。两个逃逸都改写了 result 内已检查但未进入 protected projection 的 mutation roster。</p></div><div className="d127-audit-chain"><article className="failed"><span>ORIGINAL AUDIT</span><strong>28 / 30</strong><code>FAIL · two roster mutations escaped</code><p>失败 audit、缺失原 receipt 与 run.failure.json 永久保留。</p></article><i>→</i><article><span>C1 SCOPE</span><strong>2 fields</strong><code>mutationAttacks + analyzerPid</code><p>绑定 immutable parents 与原 tool Git blob；禁止重跑科学过程。</p></article><i>→</i><article className="passed"><span>CORRECTED AUDIT</span><strong>30 / 30</strong><code>PASS · verdict unchanged</code><p>只启动一个新 Python audit process；Blender renders 为零。</p></article></div><div className="d127-next"><span>NEXT DEFENSIBLE GAP</span><strong>从静态刚体，进入真实运动与 disocclusion。</strong><p>D12.7 不覆盖 object/camera motion、deformation、遮挡揭露、透明、毛发、粒子、体积、motion blur 或人类时间质量。下一项必须在看见新输出前重新冻结 comparator 的角色，并用新刚性运动与遮挡场景做 fresh holdout。</p></div><div className="contact-artifacts"><a href={`${repo}experiments/blender-static-adaptive-risk-gate-holdout-v0-1/results.json`}><span>MACHINE RESULT</span><b>20 / 21 checks ↗</b></a><a href={`${repo}experiments/blender-static-adaptive-risk-gate-holdout-v0-1/audit.c1.json`}><span>CORRECTED AUDIT</span><b>30 / 30 attacks ↗</b></a><a href={`${repo}research/2026-08-27-b52-d12-7-adaptive-risk-gate-holdout-result.md`}><span>RESULT NOTE</span><b>bounded, not relabeled ↗</b></a><a href={`${repo}public/evidence/b52-d12-7/manifest.json`}><span>PROXY MANIFEST</span><b>source-bound ↗</b></a></div></section>
  <footer><div><span className="brand-mark">BFS</span><b>B52-D12.7 Adaptive Local-Risk Gate</b></div><p>candidate passed on fresh static geometry · temporal production claim remains open</p><Link href="/journal">继续看实验日志 →</Link></footer>
</main>}
